### ISSUE TITLE
Caught exception from CraftPresence [Unable to load library 'discord-rpc']

### ISSUE THREAD

**Issue by vertex101** [Sunekaer/stoneBlock#101]
## Bug Report

Pack crashing on loading
I have tested this with fresh installs of the pack of the Twitch APP and MultiMC and get the same crash on both
## Steps to Reproduce (for bugs)

1. download & install
2. loading up

## Logs

* Client/Server Log: https://pastebin.com/icK6d89G
* Crash Log: https://pastebin.com/k6UM5MXH

## Client Information

* Modpack Version: latest 1.0.14
* Server/LAN/Single Player: with it being client i am gonna call it Single Player
* Optifine Installed: Nope
* Shaders Enabled: Nope

**Comment by vertex101** [comment]
okay after doing some more digging around with this issue i have found that this has been fixed in the latest version u can read up on it here https://gitlab.com/CDAGaming/CraftPresence/issues/1 so for it all to be fixed the needs to be updated to the latest version

**Comment by Sunekaer** [comment]
1.0.15
