### ISSUE TITLE
World Generated Stone Doesn't Drop Pebbles

### ISSUE THREAD

**Issue by Super-miner1** [Sunekaer/stoneBlock#103]
I generated my first world and when I broke it with my empty hand it didn't drop any pebbles. I placed a stone block in creative and broke it in survival and I got 4 pebbles. 

I'm using the twitch launcher, version 1.0.14

Thank you

**Comment by Super-miner1** [comment]
Nope, this didn't work

**Comment by Sunekaer** [comment]
I can’t recreate your problem, I need some logs

**Comment by Super-miner1** [comment]
Oh, wait I fixed it. Thank you

**Comment by paulstelian97** [comment]
I have seen the bug in a video series. Inventory slots where reward chests placed their contents into (or where the reward chest which was opened) apparently aren't considered an empty hand and pebbles don't drop. Changing the active hotbar slot is an annoying workaround. Hypnotizd (youtuber) has shown that issue.
