### ISSUE TITLE
AE2 Crafting CPU's not working properly

### ISSUE THREAD

**Issue by BCI1999** [Sunekaer/stoneBlock#104]
## Bug Report
Why you try to use more than 1 crafting CPU's in an ME system from "**Applied Energistics 2**" you cannot autocraft anything in the system. (see attached screenshots below)
![2018-09-12_16 01 55](https://user-images.githubusercontent.com/40671831/45442289-e7480400-b6c1-11e8-9dfb-bf9aa41ba3e8.png)
![2018-09-12_16 02 59](https://user-images.githubusercontent.com/40671831/45442290-e7480400-b6c1-11e8-9cff-682cd3118076.png)

## Steps to Reproduce (for bugs)

1. Make an ME system with autocrafting
2. Place at least 2 crafting CPU's in the system
3. Try to autocraft something in the ME system

## Client Information

* Modpack Version: 1.0.14
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Solution
Downloading the most recent **stable** build from the AE2's website fixes this issue, so please change the current alpha AE2 version in the modpack to stable

**Comment by Sunekaer** [comment]
1.0.15
