### ISSUE TITLE
Better Questing not completing for Refined Storage 1K Disk and Philosopher's Stone

### ISSUE THREAD

**Issue by SpeedSlider** [Sunekaer/stoneBlock#105]
## Bug Report
I do not have a log of the issue as one isn't generated; therefore, I understand and accept this issue will likely be ignored. If this is an incorrect understanding of the note then consider rewording it as I have previously not submitted this issue because of the note.

Better Questing will not complete for Refined Storage 1K disk (Original issue not reported due to note).
Better Questing will not complete for Philosopher's Stone.

## Steps to Reproduce (for bugs)
1. Craft either the 1k storage disk for Refined Storage or the Philosopher's Stone
2. Have them in your inventory and try completing the quest.
3. Does not work if you exit quest and go back in.
4. I have been able to complete and select rewards for many storage quests and am roughly 50% of the way through the quests in general.

## Logs
* Client/Server Log: N/A
* Crash Log: N/A

## Client Information
* Modpack Version: 1.0.14
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

![2018-09-14_10 09 39](https://user-images.githubusercontent.com/25437944/45556050-53348480-b808-11e8-8c0f-44f9b22abd38.png)
![2018-09-14_10 10 17](https://user-images.githubusercontent.com/25437944/45556053-53cd1b00-b808-11e8-958c-378104dbcf5d.png)
![2018-09-14_10 10 34](https://user-images.githubusercontent.com/25437944/45556056-5465b180-b808-11e8-87c3-225e01dae9e4.png)

**Comment by SpeedSlider** [comment]
Better Questing for all the Refined Storage Disk 1K, 4K, 16K, and 64K are broken.

**Comment by Sunekaer** [comment]
1.0.15

**Comment by moimemepl** [comment]
the quest for the 1k storage still buggy in 1.0.15

**Comment by Darkmift** [comment]
+1 on this issue
