### ISSUE TITLE
Some mod suggestions

### ISSUE THREAD

**Issue by MSandro** [Sunekaer/stoneBlock#107]
## Context
Hi, I realy like this modpack and it would bei realy nice if you could add the following mods. Most of the mods are addons for Avaritia or ProjectE. In the Modpack I realy like to use those mods but it would be realy nice to be able to do a bit more with those. The other Mod "Advanced Rocketary" would be nice because we would be able to escape the threatening stone planet and travel to other worlds with space ships. I realy love this mod.

## Mod Details
> * Name: Advanced Rocketry
> * CurseForge Link: https://minecraft.curseforge.com/projects/advanced-rocketry
> * Description: As I saied, it is a realy cool mod simular to Galacticraft but much better. It would be realy nice to be able to escape the stone world and travel to other planets in the pack. I think it would give the progression line in the modpack an realy nice touch. Maybe the mod should be tweaked a bit to only get acces to it in a bit later game.

> * Name: Refined Exchange
> * CurseForge Link: https://minecraft.curseforge.com/projects/refined-exchange
> * Description: This is an realy cool addon for Refined Storage and ProjectE. Because I've head about that much troubles and issues with AE2 in 1.12 I've switched to RefinedStore. I like the mod. It has some touch of AE1 in MC 1.6. Also I realy like to use ProjectE in mid-game. This Mod would make it posible to allow autocrafting through an RS-System.

> * Name: Equivalent Integrations
> * CurseForge Link: https://minecraft.curseforge.com/projects/equivalent-integrations
> * That would be a mod to AE2 users not to disadvantage. It would allow to automate EMC Crafting throgh AE2, I've not tested it yet but it seems to be usefull.

> * Name: Expanded Equivalence
> * CurseForge Link: https://minecraft.curseforge.com/projects/expanded-equivalence
> * Description: This mod is realy handy becuase it adds several EMC values to mod items without the need to do this manually. It would allow the players to do much more with EMC.

> * Name: Avaritia Tweaks
> * CurseForge Link: https://minecraft.curseforge.com/projects/avaritia-tweaks
> * Description: A nice Avaritia addon which doen't add that much. It enchances Avaritia with some small tweaks and configuration posibilities.

> * Name: Refined Avaritia
> * CurseForge Link: https://minecraft.curseforge.com/projects/refined-avaritia
> * Description: The last mod in my list. It is also and addon for RefinedStroage and for Avarita. It makes it posible to autcraft Avaritia stuff with an RS System. Realy nice feeling in late-game.

**Comment by Sunekaer** [comment]
Explain to your hearts content about why you would like the change/addition

**Comment by MSandro** [comment]
I've edited my post.

**Comment by MSandro** [comment]
I've edited my post and tested alll those mod in the pack. With some LibVulpe, updated HammerCore and JustEnoughIDs everything works fine.

**Comment by nytstar** [comment]
Equivalent Integrations I like this idea.. AE2 Builds are an obsession and adding more to them would be dreamy <3

**Comment by Sunekaer** [comment]
at this point of the pack im not gonna add these mods, currently concentrating on cleanup and polishing the pack
