### ISSUE TITLE
Aluminium Ore Chunk not working in Mekanism Enrichment Chamber

### ISSUE THREAD

**Issue by Wacko71** [Sunekaer/stoneBlock#108]
## Bug Report
Using Mekanism Enrichment chamber to convert Ore Chunks into Ore Grit for doubling, all work as expected except Aluminium chunks from Ex Nihilo.

## Steps to Reproduce (for bugs)
Test Iron, Silver, Gold all work. Aluminium chunks won't right click in, but if you drag and drop they go in and sit there without processing.

## Client Information

* Modpack Version: 1.0.14
* Server/LAN/Single Player: SP
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
1.0.15
