### ISSUE TITLE
Thermal Foundation Fluid Exception

### ISSUE THREAD

**Issue by Jacka5597** [Sunekaer/stoneBlock#109]
Bug Report

Updated the Pack to the new version 1.0.15, since updating the game will not load. 
I have been playing fine on the previous version for the last week since downloading. I have made no changes to any configs or removed any mods, I have added a two mod to allow me to rebind the narrator and magical psi as i prefer the look of it over the tech psi which I have disabled both and tried launching with no effect.

Crash report can be uploaded if needed but there seems to be an error with thermal foundation,  and the fluidblockcore which was not there before.

Steps to Reproduce

No clue but when downgraded to 1.0.14 in a new profile there is no issue, also downgrading in the same profile is no issue.

Replacing the new reborn storage config with the previous version does not effect. (The new update changed the config, wondered if anything would affect it)

Comparing the configs of Thermal Foundation they are the same. 

Completely removing the mods folder of the new version 1.0.15 and replacing with the old version of 1.0.14 without the two extra mods has no effect.

Thermal foundation has not been updated between the two versions.

Client Information

    Modpack Version: 1.0.15
    Server/LAN/Single Player: SP
    Optifine Installed: No
    Shaders Enabled: No

**Comment by thevipe** [comment]
I also did the update and I could not even use my own world even brand new it just kept crashing so i reinstalled stoneblock and everything starting new went fine except trying to host a local server. did what was mentioned here before installation to no effect so as I said I just reinstalled everything

**Comment by Sunekaer** [comment]
No crash or log files... closing issue

**Comment by Jacka5597** [comment]
Sorry, when creating this issue last night it didnt show me the template, currently uploading the crashlogs
