### ISSUE TITLE
Bonsai Pots Disabled?

### ISSUE THREAD

**Issue by darkequine** [Sunekaer/stoneBlock#11]
Neither the regular or hopping bonsai pot will accept trees. I've tried all 6 vanilla saplings and the Apple Sapling from Pam's and they won't go in. Tried left click, right click and shift+right click.

Version 1.0.3

**Comment by Sunekaer** [comment]
Ill look in to that

**Comment by darkequine** [comment]
I don't know what changed, but I tried the bonsai pots again out of curiosity, and they worked. I've booted up the pack for the first time since last night, so maybe it needed a relog?
