### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by SirioIlBe** [Sunekaer/stoneBlock#111]
## Bug Report

My game crashes, but i can't provide any crash logs because it does not produce any. i have to manually kill the process. i can still move in my world, but i cannot open any chest/machine and if i try to save and quit the game just then the game actually freeze.
## Steps to Reproduce (for bugs)

there is no step to reproduce this (as far as i know). i just play the game and it happens after some time (no more than 10-15 minutes of gameplay)

## Logs

* Client/Server Log:
* Crash Log:i don't have a crash log, but i can give you what the console was writing when the crash was happening: https://pastebin.com/13gTdKE3

## Client Information

* Modpack Version:1.0.15 (i had this problem with 1.0.14 too)
* Server/LAN/Single Player:Singleplayer
* Optifine Installed:no
* Shaders Enabled:no

**Comment by Lost-Ninja** [comment]
Literally came here to post the same thing, though for me I'm 99% sure it's the mob masher thing from MobUtilities wasn't happening before I placed it, is now...

**Comment by Sunekaer** [comment]
cant use that log to anything

**Comment by Sunekaer** [comment]
crash log, or the full log

**Comment by SirioIlBe** [comment]
i manage to load the world and remove the mob masher and switched to some diamond spikes. i will play now for some time and see if it will still crash/freeze.

**Comment by SirioIlBe** [comment]
ok, so i played for like 1 and a half hours and the game never crashed. the problem was the mob masher from mob_grinding_utils
