### ISSUE TITLE
Mekanism Paxels Not Craftable

### ISSUE THREAD

**Issue by iceboundglaceon** [Sunekaer/stoneBlock#115]
## Bug Report

Can't craft tools from different mods that have the same recipe using the same materials
## Steps to Reproduce (for bugs)

1. you can't craft the right versions of the tools required to make a paxel since they're from the wrong mod

Add the mod NoMoreRecipeConflict by stimmedcow

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 10.0.15
* Server/LAN/Single Player: Single Player
* Optifine Installed: Optifine_1.12.2_HD_U_E2
* Shaders Enabled:

**Comment by Sunekaer** [comment]
which once are you talking about? the once i just tested works fine

**Comment by Sunekaer** [comment]
I know and no 
If there is items like pixels where there is a recipe conflict, they should be reported with which specific items that has conflicting recipe, so I can change them

**Comment by Sunekaer** [comment]
no answer from creator closing
