### ISSUE TITLE
No Pebbles after placing Stone Crafting Bench

### ISSUE THREAD

**Issue by urikkiru** [Sunekaer/stoneBlock#119]
When starting a fresh game, you can break stone to get pebbles with your empty hand. Once you get to the point where you place the Stone Crafting Bench, you suddenly get no pebbles from break stone with an empty hand. This stops you from progressing in the pack at all. 

Reproduction
1. Start new game
2. Break enough stone with an empty hand, until you have 16 pebbles
3. Make 4 cobblestone out of the 16 pebbles.
4. Make the stone crafting bench from the 4 cobblestone.
5. Place the stone crafting bench on the floor, in the center of the room(position may not matter)
6. You now will get no pebbles when breaking stone with an empty hand.

Workaround:
Close the game, and restart. This works until you break and place the stone crafting bench again.

## Client Information
Pack version 1.0.15
Single player
No resource packs, optifine, or alterations to the pack.

**Comment by Sunekaer** [comment]
I can’t recreate the issue, you sure your hand is empty? What if you use another slot?

**Comment by urikkiru** [comment]
Definitely was using an empty hand. Discovered the culprit though. If I place the stone crafting bench, my hand is now empty, but I still have the same slot on the bar selected that used to contain the now placed crafting bench. If I change slots to a different empty slot, then pebbles will drop as normal. Changing back to the previous slot will once again cause no pebbles to be dropped.

**Comment by urikkiru** [comment]
Additionally, if I place something back into that slot on the bar, and then remove it, pebbles drop once more.

**Comment by urikkiru** [comment]
https://youtu.be/3DDlPz5OsOQ?t=502

That's Direwolf20 playing the pack, if you go to 8:22, you'll see him attempting to break a stone block with an empty hand that had just previously contained the stone crafting bench. No pebbles drop. He then changes slots on the bar, and his next stone block drops pebbles.

**Comment by Sunekaer** [comment]
was finally able to create it, I'm talking with the mod dev about finding a fix

**Comment by Sunekaer** [comment]
1.0.16
