### ISSUE TITLE
Savegame crashes and don't restart

### ISSUE THREAD

**Issue by PresaMan** [Sunekaer/stoneBlock#121]
The modpack crashes and I can't reload a saved game:

Error:

The game crashed whilst exception in server tick loop
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EnderStorage (enderstorage)

Full Report: https://pastebin.com/raw/XSr1SW85

**Comment by Sunekaer** [comment]
Use the template for creating an issue
