### ISSUE TITLE
Save from previous version not showing in the single player menu

### ISSUE THREAD

**Issue by Super-miner1** [Sunekaer/stoneBlock#122]
## Bug Report
I just updated the pack and started it using the twitch launcher. When I clicked singleplayer my save from the previous version did not show up

## Steps to Reproduce (for bugs)

1. Create a save in version 1.0.14 then update to 1.0.15
2. Go to the singleplayer menu and the save doesn't show up

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.15
* Server/LAN/Single Player: SP
* Optifine Installed: NO
* Shaders Enabled: NO

**Comment by Sunekaer** [comment]
Check the instance folder that it didn’t create new instance after the update and check the save folder if the save is there

**Comment by Super-miner1** [comment]
Nope, I updated to the same profile, no new instance

**Comment by Sunekaer** [comment]
well this didnt happen to me when i updated, is the save folder empty?
you did use twitch launcher before update right?

**Comment by Super-miner1** [comment]
The save is still in the folder and I was was using twitch before

**Comment by Sunekaer** [comment]
Try and copy the save out on your desktop and delete the pack and install it again

**Comment by Sunekaer** [comment]
No answer for 2 days, please reopen with an answer

**Comment by Super-miner1** [comment]
Sorry for not replying,
 but I just went on holiday. anyway, I tryed this, but it didnt work
[Caveman.zip](https://github.com/Sunekaer/stoneBlock/files/2409270/Caveman.zip)
