### ISSUE TITLE
items in inventory disappear and appear 

### ISSUE THREAD

**Issue by mine3500** [Sunekaer/stoneBlock#124]
## Bug Report

i check my chests and other inventories and the items are gone but appear after closing the chest and opening even if you break the chest and place the contends back again it does the same  
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:1.0.15
* Server/LAN/Single Player:single player
* Optifine Installed:no
* Shaders Enabled:no

**Comment by Sunekaer** [comment]
I can’t not recreate this problem, is it just Minecraft chest it happens with for you, or what chest?

**Comment by mine3500** [comment]
iron chest,roost breeder and vanilla chest but i found that crates from immersive doesn't  do that

**Comment by Sunekaer** [comment]
hmm just tested again with those mods/items, I still can't recreate the problem
how much ram do you have assigned?

**Comment by mine3500** [comment]
5gb maybe one of the inventory mods is making that but if this is happening to me alone i will try to disable both inventory mods and see if there are giving me problems

**Comment by mine3500** [comment]
still does the same

**Comment by Sunekaer** [comment]
just uploaded 1.0.16, try and see if you also have the problem there

**Comment by Sunekaer** [comment]
no answer for 3 days

**Comment by Sunlis** [comment]
I was having this happen constantly. Chest items would disappear, but would reappear if their stack is modified (ie. an item being piped in/out). Leaving the chest screen open for 20 seconds was enough to reproduce 100% of the time for me.

F3 screen: https://i.imgur.com/VzwEa1w.png
Repro video: https://youtu.be/e4hc3DYIOGo

I had a 5x5x4 smeltery in the same chunk as the chests that were doing this. Removing the smeltery controller completely resolved the issue. My workaround is to keep the output chest of my smeltery on the other side of a chunk boundary: https://i.imgur.com/4F3XPnn.png
