### ISSUE TITLE
Everything freezes after 10 seconds of play game

### ISSUE THREAD

**Issue by miguellahoz** [Sunekaer/stoneBlock#125]
## Bug Report
After like 10 seconds of entering my old world, that has been working fune until now, everything freezes.
I can no longer click on any interactable block, can't damage entities, can't use portals, break blocks, etc.

## Steps to Reproduce (for bugs)
Simply enter into the world.

## Logs
Can't post the log because of it's size

## Client Information
* Modpack Version: 1.0.15
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
upload the log to https://gist.github.com and link it

**Comment by miguellahoz** [comment]
Here is the log: https://gist.github.com/miguellahoz/dd167122a10323179b99878926d5b801

**Comment by Sunekaer** [comment]
Hmm old journeymap bug, havent found anything that i can do about it
https://github.com/TeamJM/journeymap/issues/56

**Comment by miguellahoz** [comment]
Any hint on how to play again the pack without deleting the map data?

**Comment by miguellahoz** [comment]
It's not JourneyMap, I just removed ir from the mods folder and it keeps freexing

**Comment by Sunekaer** [comment]
Hmm then I’m not sure what the problem is, because that’s all I get from the log

**Comment by miguellahoz** [comment]
Is there something I can do to get more info about the error? When everything freezes I need to force exit because the Save and Exit button doesn't work, maybe because of that the log isn't updating

**Comment by Sunekaer** [comment]
log updates realtime, and the only in the log is that JourneyMap

**Comment by miguellahoz** [comment]
Here's the log without JourneysMap: https://gist.github.com/miguellahoz/2ef0841731aa8aac7207cbe5d12f31ab

**Comment by Sunekaer** [comment]
yeah the log doesnt saying
could you try disabling foamfix?

**Comment by miguellahoz** [comment]
Still freezes

**Comment by Sunekaer** [comment]
then i dont know what the problem is

**Comment by SirioIlBe** [comment]
do you use a mob grinder from mob grinding utils? it may be that,,,

**Comment by miguellahoz** [comment]
Yes, I use it, is there a way that I can delete it from the world without entering it?

**Comment by Sunekaer** [comment]
could also be Refined storage controller if your using that

**Comment by Sunekaer** [comment]
you could use something like MC Edit to remove it, lots of youtube videos on how to do that

**Comment by miguellahoz** [comment]
It worked just removing the mob grinder, any hint on what could cause that and if i can use it again?

**Comment by Sunekaer** [comment]
i dont know why it happens, but if it happens again i would recommend reporting to the mod author
