### ISSUE TITLE
trying to create a Creeperhost multiplayer server, but ...

### ISSUE THREAD

**Issue by Thosam** [Sunekaer/stoneBlock#127]
Hello all.
I'm trying to install this modpack on CreeperHost as a multiplayer server, sofar sadly without luck.
I and my Minecraft buddy start in a normal overworld, even with Generator set to voidworld etc.

CreeperHosts support offered some advice, and in the server.properties document the first lines are this: 
spawn-protection=16
memory=adaptive
max-tick-time=60000
query.port=25565
generator-settings=voidworld
force-gamemode=false
allow-nether=true
gamemode=0
enable-query=false

Anyone who can help?

**Comment by Sunekaer** [comment]
generator-settings should just be empty

**Comment by Sunekaer** [comment]
level-type should be voidworld
