### ISSUE TITLE
server won't do anything after players attempt to connect

### ISSUE THREAD

**Issue by iDarper** [Sunekaer/stoneBlock#128]
## Bug Report

The last few days, my players on the server get an instant timeout. The server isn't doing anyting beyond the initial connect function leaving the following message in console: [13:04:52] [User Authenticator #3/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: UUID of player iDarper is *******
## Steps to Reproduce (for bugs)

1. load pack
2.Attempt to connect to the server.

## Logs

* Client/Server Log:
* Crash Log:
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2402379/latest.log)

## Client Information

* Modpack Version: 1.0.14 & 1.0.15
* Server/LAN/Single Player: server
* Optifine Installed: no, it's a server =)
* Shaders Enabled: ^^

**Comment by Sunekaer** [comment]
paste the log in gist or pastebin..
