### ISSUE TITLE
Suggestion: Nuclearcraft?

### ISSUE THREAD

**Issue by GeevanNMan** [Sunekaer/stoneBlock#129]
## Context

Hey there - I've been playing this pack for a while now (really enjoying it - love the uniqueness!), and was wondering whether you had considered adding Nuclearcraft as another option for nulcear power, or even a replacement for Extreme reactors. As well as thinking it's just a better mod and is not so widely used, I also think it combos better with other tech mods, especially Mekanism.

## Mod Details
* Name: Nuclearcraft
* CurseForge Link: https://minecraft.curseforge.com/projects/nuclearcraft-mod

**Comment by Sunekaer** [comment]
at this point of the pack im not gonna add this mods, currently concentrating on cleanup and polishing the pack
