### ISSUE TITLE
Save Game won't load unless full restart

### ISSUE THREAD

**Issue by vcnickels** [Sunekaer/stoneBlock#13]
If I save my game (Save and Exit to Main Menu) I can't load my save unless I fully restart Minecraft.

**Comment by Sunekaer** [comment]
Doesnt happen to me, try reinstalling the pack, or a new save

**Comment by gaminggirl** [comment]
Happened here to on version 1.0.4

**Comment by Sunekaer** [comment]
try with 1.0.5
