### ISSUE TITLE
Welcome to StoneBlock! Let's SPAM YOUR CHAT on dimension change!

### ISSUE THREAD

**Issue by SephirothWS** [Sunekaer/stoneBlock#132]
## Bug Report

Let's SPAM YOUR CHAT with a Welcome to the mod pack and discord spam-vertisement on dimension change! I would prefer it if this spam-vertisement happens either ONCE per world load or not at all.

![Image](https://i.imgur.com/6mFZ8WP.png)

## Steps to Reproduce (for bugs)

1. Launch the modpack.
2. Join a single-player world.
3. Observe as the "Welcome to StoneBlock" message exists in chat.
4. Change dimensions (In my case, Overworld <-> Nether)
5. Observe as a SECOND "Welcome to StoneBlock" message spams chat.
6. Change dimensions again.
7. Observe as a THIRD "Welcome to StoneBlock" message spams chat.
8. Rinse and repeat.
9. ???
10. Profit.

## Logs

* Client/Server Log: [Latest.log](https://gist.github.com/SephirothWS/91a6bb5c8e2708748ab4041057922d77)
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.15
* Server/LAN/Single Player: Single Player
* Optifine Installed: Nope
* Shaders Enabled: Nope

**Comment by knoxhack** [comment]
Yeah, I didn't know it gives that on dimension change too

**Comment by Sunekaer** [comment]
Hmm I haven’t had that happen to me when changing dim, but I’ll look at it

**Comment by SephirothWS** [comment]
I'll like to add a bit of additional information. I know it's got the Fixed in dev label, but I got murdered by an Evolved Enderman in my base while I was afk. Came back, respawned and got the Welcome to StoneBlock message again, even without transferring dimensions.

**Comment by Sunekaer** [comment]
removed in 1.0.16
