### ISSUE TITLE
Game Crashes on World Creation/Loading

### ISSUE THREAD

**Issue by Koyoss** [Sunekaer/stoneBlock#133]
[CRASH REPORT](https://pastebin.com/DVD1cEuy)

I'd really like to play this modpack- I've been watching a few videos of it on youtube and it seems pretty fun, but after downloading it and launching it, my game crashes upon creating and loading a world and I'm not sure why.

I've removed the mod Chisels and Bits, but it was crashing long before I removed that. I can't even get into a world..

**Comment by Sunekaer** [comment]
Use the template then creating an issue
