### ISSUE TITLE
Client rendering bug?

### ISSUE THREAD

**Issue by zerogott** [Sunekaer/stoneBlock#134]
## Bug Report

After some random time/sometimes after walking near a wall i get insane movement speed and the rendering for breaking blocks seems to be completly offcenter.

Captured 2 Videos of the problem.
Rendering offcenter: https://www.youtube.com/watch?v=nnn2jX33WSQ
Movement speed broken: https://www.youtube.com/watch?v=qjh6YfWwnMA
## Steps to Reproduce (for bugs)

1. Play the modpack(started multiple worls to test it) 
2.

## Logs

* Client/Server Log: https://gist.github.com/zerogott/fc337b971615822e232669dc9a570d27
* Crash Log: No crash log cause no crash.

## Client Information

* Modpack Version: StoneBlock-1.0.15
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
did you change settings on betterFPS?

**Comment by zerogott** [comment]
> 
> 
> did you change settings on betterFPS?

Yeah changed the algorhyme on first start because i forgot to change my ram settings before,let me reset that fast and i will edit the post
