### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by RealGamer2018** [Sunekaer/stoneBlock#135]
## Bug Report

When I try to load the game it crash almost instantly
## Steps to Reproduce (for bugs)

1. Try and load the game

## Logs

* Client/Server Log: https://pastebin.com/0K8KPYLd
* Crash Log: https://pastebin.com/ciHV5a3b

## Client Information

* Modpack Version:1.10.14
* Server/LAN/Single Player:Single Player
* Optifine Installed:No
* Shaders Enabled:No

**Comment by Sunekaer** [comment]
1.0.16
