### ISSUE TITLE
Suggestion; Add the NoMoreRecipeConflict mod

### ISSUE THREAD

**Issue by Chaogomu** [Sunekaer/stoneBlock#137]
## Context

I've been playing this pack for a while and have noticed at least a dozen small recipe conflicts. The NoMoreRecipeConflict mod would solve this issue without requiring any changes to existing recipes. It adds a cycle button to crafting tables that lets you select the recipe that you want out of all the conflicting ones. It also tells you how many conflicts each recipe has.

## Mod Details
* Name: NoMoreRecipeConflict
* CurseForge Link: https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict

**Comment by Sunekaer** [comment]
As said many time.. no
when you find conflicting items recipes create an issue for it
