### ISSUE TITLE
Duplication Recipe Conflict

### ISSUE THREAD

**Issue by Nazta** [Sunekaer/stoneBlock#138]
## Bug Report
You can duplicate soul sand.

## Steps to Reproduce (for bugs)
1.  Turn 4 Soul Sand into Tin Progression Soul Sandstone
2.  Turn 1 Soul Sandtsone back into 9 soul sand. 
3. Rinse and repeat

**Comment by Nazta** [comment]
I don't want to open another issue, since it's just small recipe changes. But the diamond furnace gives ex nihiolo aluminium ingots from the ex nihiolo ore chunks, while most other furnaces give thermal ingots.

**Comment by Nazta** [comment]
Normal, but it's annoying to get differing versions of the same item, when it can be fixed.

Tinkers is one of the mods giving the thermal ingots when you smelt chunks.

**Comment by SirioIlBe** [comment]
usually you could use a drawer with the ingot that you want and when you pump in the other ingots (same type but from different mod) it converts it in the ingot that you first put in the drawer.i don't know if this is an old thing or the mod autor didn't put the right mod to do this

**Comment by Ravalli03** [comment]
SiriollBe, you still can, but you have to have the drawer conversion upgrade , it's the blue one.

**Comment by Sunekaer** [comment]
https://github.com/Kashdeya/Tiny-Progressions/issues/111

**Comment by Sunekaer** [comment]
well that perm fix now, as they havent answered for 5days

**Comment by Sunekaer** [comment]
1.0.17
