### ISSUE TITLE
Problems installing from Server

### ISSUE THREAD

**Issue by floepker** [Sunekaer/stoneBlock#139]
Hello Mods,

My friend and I really like your server, but we seem to be having problems installing the server on our Host. Would it be possible for you to help us install the modpack?

Any response would be greatly appreciated!

Best Regards,

Felix

**Comment by Sunekaer** [comment]
what the problem?? whos your host?

**Comment by floepker** [comment]
I use the hosting Service Bisecthosting

**Comment by Sunekaer** [comment]
what instructions?

**Comment by floepker** [comment]
The instructions at the front page.

This modpack is kinda like SkyBlock, except you don't start with a tree and you're surrounded by stone It´s a kitchen-sink modpack with lots of quests to help guide you in the start and to give the players goals to reach

This is not a lightweight pack Requirements: The Twitch App to download it At least 4-6GB of RAM allocated to the pack. A decent CPU.

Note: Choose the world type "Void? World" in single-player, or "voidworld" on servers. If something regarding quests or quests rewards is mentiond in the update log, do "/bq_admin default load" and "/bqs_loot default load" to update your questbook.

These. Unless you have actual instructions which i didnt seem to have found, that's what I tried to work with.

**Comment by Sunekaer** [comment]
the only part of this that is instructions is:
Note: Choose the world type "Void? World" in single-player, or "voidworld" on servers. If something regarding quests or quests rewards is mentiond in the update log, do "/bq_admin default load" and "/bqs_loot default load" to update your questbook.

**Comment by floepker** [comment]
I agree. I am trying to install this on an actual Server though and I am having trouble using those instructions to set up the server. Could you create instructions that explain how to set this up on a host server? Otherwise, I would be happy to give you access to my host server and we could work on figuring out how to set this up? 

Please let me know, but either would work for me.

**Comment by Sunekaer** [comment]
did you google how to or ask your host who your paying?

**Comment by floepker** [comment]
Yes, I did google. I have also set up plenty of servers myself, but it seems that once you involve the void world mod it becomes a little trickier. The Host/Vendor for my Host Server was having trouble themselves which is when they asked me to see if I can gather some instructions, which is why I opened this threat.

**Comment by Sunekaer** [comment]
its like making any other modded server, except you change the world type(level-type) to voidworld
