### ISSUE TITLE
No recipe or source for sky stone?

### ISSUE THREAD

**Issue by remclave** [Sunekaer/stoneBlock#14]
I've been searching through the dimensions and the files for the last three days and can find no way to acquire sky stone. Without it no advancement. There is sky stone dust in my inventory but there are NO recipes assigned. It's currently a useless item in my inventory. Did I just miss the sky stone somewhere? 

I've updated from 1.0.2 to 1.0.4 and the same problem appears to be following the updates.

I do not know if this qualifies as an issue but I can find no other way to get an answer

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/42796091-0fbd6cca-8988-11e8-9222-a7082491ecdc.png)
this was broken in 1.0.2 and 1.0.4 but did work in 1.0.3 and also works in 1.0.5
