### ISSUE TITLE
Trouble opening modpack

### ISSUE THREAD

**Issue by GCPleb** [Sunekaer/stoneBlock#143]
**Bug Report**
Steps to Reproduce (for bugs):
Open the modpack and run the modpack as it is loading it crashes around 4/7 loading

**Logs**
Client/Server Log:
Crash Log:[crash-2018-09-22_10.34.15-client.txt](https://github.com/Sunekaer/stoneBlock/files/2407862/crash-2018-09-22_10.34.15-client.txt)
**Client Information**
Modpack Version:1.0.15
Server/LAN/Single Player: Single Player
Optifine Installed: N
Shaders Enabled: N

**Comment by Sunekaer** [comment]
....
upload the logto gist or pastebin

**Comment by GCPleb** [comment]
Wait how can I do that im kinda new to this so sorry if im being a bit of a pain

**Comment by Sunekaer** [comment]
https://gist.github.com

**Comment by GCPleb** [comment]
Thank you uploaded with the link this time
