### ISSUE TITLE
This item is disabled

### ISSUE THREAD

**Issue by Walhfort** [Sunekaer/stoneBlock#145]
## Bug Report

When opening uncommon loot-bags, I obtained a "This Item Is Disabled." item from Applied Energetics 2. It has no sprite (it's transparent). It doesn't seems to crash the game.

## Steps to Reproduce (for bugs)

1. Open Uncommon loot-bags from "lootbags" mod.
2. ???
3. Profit

## Logs

* Client/Server Log:
* Crash Log: No crash = no log

## Client Information

* Modpack Version: StoneBlock 1.0.15
* Server/LAN/Single Player: 1.0.15 Server on remote Windows Server 2016 VM
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
theres no applied energetics items in lootbags, did you mean loot chest?

**Comment by Sunekaer** [comment]
could you post a image of the item?

**Comment by Walhfort** [comment]
No it's really the green lootbag, and when i search the disables item's
recipes, it's only obtainable through green lootbag opening. I can't post a
pic right now, but it shows only "This Item Is Disabled.", With no sprite
at all, like if the slot was empty.

**Comment by Ravalli03** [comment]
@Walhfort, do you have your AE2 config set to not have channels? If so, AE2 disables the dense, smart, etc. cables.

**Comment by Walhfort** [comment]
I haven't changed any settings, so I should have the same config as
everyone. I'll update you when I will get back.

**Comment by swoolcock** [comment]
It's usually the AE2 silicon, which gets disabled if Ender IO is also in the pack:
https://ae-mod.info/Silicon/

**Comment by zCodeg** [comment]
![screenshot_1](https://user-images.githubusercontent.com/5285811/45928689-681fbf00-bf50-11e8-97f1-04b3e0b89e1c.png)
Pack version: 1.0.16

**Comment by Sunekaer** [comment]
1.0.17
