### ISSUE TITLE
Graphical glitch

### ISSUE THREAD

**Issue by Walhfort** [Sunekaer/stoneBlock#146]
## Bug Report

When crafting in your inventory grid, opening JEI and closing it makes the crafted item visualisation disappear, the item can still be crafted.

## Steps to Reproduce (for bugs)

1. Open your inventory and place any valid recipe in the 2x2 grid
2. Open and close JEI
3. The crafted item visualisation should have disappeared, but should still be craftable by clicking the now empty slot.

## Logs

* Client/Server Log:
* Crash Log: No crash

## Client Information

* Modpack Version: 1.0.15
* Server/LAN/Single Player: 1.0.15 server on remote Win server 2016 VM
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Just tested in Single player and dont have this issue

**Comment by Sunekaer** [comment]
might be a TPS/lag issue?

**Comment by Walhfort** [comment]
I don't have in-game lag (144fps more or less constant ), I will check TPS
as soon as i can come back (in 5-12 hours).
I should add that it happened when using the R key ( show recipe) on any
item. I might post a video of it if i have some time.

**Comment by jellonek** [comment]
It's for sure not TPS/lag - i've seen that in probably all packs based on 1.12.x. That can be connected probably with some inventory tweaking mod.

Similarly there is issue that sometimes when you will try to use recipe from JEI - there can land on crafting grid of any kind/size not only things needed by recipe, but also some additional item from inventory, which will land in an empty place in recipe.

Idk if it's a JEI bug or something on connection between it and inventory sorter, but i assume the first one.

**Comment by Sunekaer** [comment]
Walhfort if you still have the problem in 1.0.16 try disabling some of those mods jellonek is talking about
