### ISSUE TITLE
Add a mod to sort items in inventory / chests

### ISSUE THREAD

**Issue by Insane-96** [Sunekaer/stoneBlock#147]
## Context

A mod like Inventory Tweaks should be added. This adds just a small quality of life in early game by not having messy chests. Adds even a faster way to get small items quantities from / to chests.

## Mod Details
[Inventory Tweaks](https://minecraft.curseforge.com/projects/inventory-tweaks)
> Replaces your tools as they break (maybe should be disabled? But not that unbalancement)
> Sorts your inventory and your chests in a single click/keystroke
> Provides lots of powerful shortcuts to move items around

**Comment by Walhfort** [comment]
A sorting mod shpuld already be installed, try R or middle mouse click to
sort the inventory.

**Comment by Insane-96** [comment]
Can confirm, never tried Middle Click, always tried only 'R'
