### ISSUE TITLE
Server stops loading

### ISSUE THREAD

**Issue by Asocan** [Sunekaer/stoneBlock#149]
## Bug Report

I cant see any crush but server stops loading
## Steps to Reproduce (for bugs)

1. https://imgur.com/a/6qFsIIY stops loading like this
2.

## Logs

* Client/Server Log: server
* Crash Log: https://paste.ubuntu.com/p/dpyvRXyxY3/ heres log

## Client Information

* Modpack Version:latest version
* Server/LAN/Single Player:server
* Optifine Installed:no
* Shaders Enabled:no

**Comment by Asocan** [comment]
ram?

**Comment by Sunekaer** [comment]
yea

**Comment by Walhfort** [comment]
You might try what they said in the crash log : Remove FoamFixAPI (or
replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.1-1.12.2.jar)

**Comment by Asocan** [comment]
https://imgur.com/a/vlJdOqJ have 2 gb ram in server files i think hand have 6 gb in client

**Comment by Walhfort** [comment]
Foamfix API link :
https://minecraft.curseforge.com/projects/foamfix-for-minecraft/files/2545217

Le sam. 22 sept. 2018 à 22:33, Séguenot Maël <mael.seguenot@gmail.com> a
écrit :

> You might try what they said in the crash log : Remove FoamFixAPI (or
> replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.1-1.12.2.jar)
>

**Comment by Sunekaer** [comment]
no dont remove that

**Comment by Sunekaer** [comment]
foamfix has nothing to do with the problem

**Comment by Sunekaer** [comment]
okay assign at least 4gb of ram to the server

**Comment by Asocan** [comment]
okay opened the server waiting

**Comment by Walhfort** [comment]
I meant replacing foamfix with the lawful version like they said.
Otherwise the issue seams to have been raised by Draconic evolution. You
might try to remove it for debug purposes.

**Comment by Sunekaer** [comment]
no need to do so walhfort

**Comment by Asocan** [comment]
https://paste.ubuntu.com/p/TPT5xGB2m9/ same thing happens when i give 4 gb ram stops loading

**Comment by Sunekaer** [comment]
You ether have a corrupt jar or another mod (most likely a coremod) is breaking something. but as i have tested it before uploading it, i know its not another mod, so its a corrupt jar file, so redownloading the mods should fix, and by updating to 0.16 your redownloading the mod and that should hopefully fix it

**Comment by Asocan** [comment]
okey gonna download again and update the pack

**Comment by Walhfort** [comment]
Once again it seems to crash because of Draconic evolution, try
redownloading the mod to see whether or not it boots.

**Comment by Sunekaer** [comment]
walhfort..... i looked up the error, thats where i have my answer from...

**Comment by knoxhack** [comment]
Does this keeps happening after updating to versiom 1.0.16?

**Comment by Asocan** [comment]
i dont know if its about the 1.0.16. didnt know there is 1.0.16 like 5 min ago. Im updating now and going to try it again

**Comment by knoxhack** [comment]
Make sure to update forge too

**Comment by Asocan** [comment]
Updated pack and server and same thing happening again. https://paste.ubuntu.com/p/nZRR5ZGX4X/ smh

**Comment by Sunekaer** [comment]
weird, let me try and download it from curse and test, might have gotten corrupted in upload or something

**Comment by Asocan** [comment]
singleplayer works fine but cant say the same thing for server. Just wanted to play this modpack with friends guess we are not going to. Btw thanks for your help

**Comment by Sunekaer** [comment]
all i can say is referring to what the dev says "corrupt jar or another mod (most likely a coremod) is breaking something."
maybe one of your friends can try
https://github.com/brandon3055/BrandonsCore/issues/57

**Comment by Asocan** [comment]
same thing happens for my friends guess not gonna play. Sad, it was a really nice mod pack

**Comment by Walhfort** [comment]
Are you on the same OS / Java version than your friend ?

**Comment by Asocan** [comment]
nope
