### ISSUE TITLE
Issue visiting another friends Base on server

### ISSUE THREAD

**Issue by KeepoMC** [Sunekaer/stoneBlock#15]
When I try to do /island visit [Name] I get spammed with "You can't be away from your island or spawn that far away!". Also I start taking damage because I'm stuck in some block so I have to /island home and when the tp goes through some blocks don't load and you need to reconnect to the server.

**Comment by Sunekaer** [comment]
What version of the pack?

**Comment by KeepoMC** [comment]
1.03

**Comment by Sunekaer** [comment]
update to 1.0.5, it has the newest version of Void Island that fixes this problem
