### ISSUE TITLE
Game Crashing on World Load

### ISSUE THREAD

**Issue by Koyoss** [Sunekaer/stoneBlock#150]
## Bug Report

Whenever I load and create a new world, the game crashes. I can't even play the game because it crashes 100% of the time.

## Steps to Reproduce (for bugs)

1. Launch game
2. Create new world, or load already created world
3. Game crashes

## Logs

* Client/Server Log: https://gist.github.com/Koyoss/9865195e02eebe7bc8b69d24cdfc7b0e
* Crash Log: https://pastebin.com/YaSZK2FD

## Client Information

* Modpack Version: 1.0.16
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
looks like some files is missing in the folder "\Install\libraries\org\scala-lang"
i would recommend trying to reinstall the pack

**Comment by Koyoss** [comment]
Sorry for the wait on the reply; I did a full reinstall of the pack, but it's still crashing the same way with what looks like the same crash log.

**Comment by Sunekaer** [comment]
do you have a folder in Install\libraries\org\scala-lang\scala-reflect? mine is called 2.11.1 and in that folder there is a file called scala-reflect-2.11.1.jar

**Comment by Koyoss** [comment]
I do, yeah!

**Comment by Sunekaer** [comment]
weird cause it says it cant find a class from that file "Unknown Source"
maybe delete that file and reinstall the problem hopefully that would redownload it and fix it

**Comment by Koyoss** [comment]
Yes! Deleting scala-reflect and letting it reinstall fixed the problem! Thank you!!
