### ISSUE TITLE
Home made server issue

### ISSUE THREAD

**Issue by Amnic0re** [Sunekaer/stoneBlock#151]
Bug Report
Now i created this server earlier and have made 0 changes to it i load it up and boom it spawns me in lava i try to create an island and it says that its not a void world but according to the server file it says it is not a voidworld

Steps to Reproduce (for bugs)

Logs:

Client/Server Log:
[2018-09-23-5.log](https://github.com/Sunekaer/stoneBlock/files/2408521/2018-09-23-5.log)

Crash Log: 

Client Information
Modpack Version: 1.0.16
Server/LAN/Single Player: server
Optifine Installed: not sure
Shaders Enabled: not sure

**Comment by Sunekaer** [comment]
did you set the level-type to voidworld in server.properties? then you need to delete the old world after that so it can create a new one
