### ISSUE TITLE
SoulBound and Shimmer enchantments can go on Ex Nihilo Meshes.

### ISSUE THREAD

**Issue by Insane-96** [Sunekaer/stoneBlock#153]
## Bug Report

When looking up JEI or enchanting a mesh for Sieves, you can see that it can be enchanted with Soulbound or Shimmer which are two useless enchantments, and removes chance to other enchantments to pop out.

EDIT: The same should apply to ex nihilo hammers.

## Steps to Reproduce (for bugs)

1. Look up JEI or Enchant some meshes to level 30 in enchanting table.
2. It may need a few enchantments but you may get Soulbound or Shimmer
3. You got Soulbound and/or Shimmer and nothing else? Nice, you now have an almost useless diamond mesh.

## Client Information

* Modpack Version: 1.0.15
* Server/LAN/Single Player: SinglePlayer
* Optifine Installed: ❌
* Shaders Enabled: ❌

**Comment by Sunekaer** [comment]
No a bug, and not something im gonna do anything about, thats just the RNG of the enchanting table

**Comment by Insane-96** [comment]
Any plan the adding Sieve Efficiency / Fortune / Luck of the Sea to the Ender IO Enchanter?
