### ISSUE TITLE
Crash forge version 1.0.16

### ISSUE THREAD

**Issue by Nicocraft05** [Sunekaer/stoneBlock#155]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: serveur crash
* Crash Log:
[crash-2018-09-23_13.13.43-server.txt](https://github.com/Sunekaer/stoneBlock/files/2408675/crash-2018-09-23_13.13.43-server.txt)

## Client Information= Server

* Modpack Version:1.0.16
* Server/LAN/Single Player: server
* Optifine Installed:lol in 1.12 no version for modpack
* Shaders Enabled: no shader no time

**Comment by Sunekaer** [comment]
upload the log to gist or pastebin....

**Comment by Nicocraft05** [comment]
links or?

**Comment by Sunekaer** [comment]
..... gist.github.com or pastebin.com ...

**Comment by Nicocraft05** [comment]
https://pastebin.com/XY2wdnM0

**Comment by Sunekaer** [comment]
Please post the latest log (logs/latest.log)

**Comment by Nicocraft05** [comment]
the version server is tested for you or not?

**Comment by Sunekaer** [comment]
do you mean if i have tested the server files?

**Comment by Nicocraft05** [comment]
yes?

**Comment by Sunekaer** [comment]
yes of course i test it before i upload it

**Comment by Nicocraft05** [comment]
for windows?

**Comment by Sunekaer** [comment]
yes...

**Comment by Sunekaer** [comment]
now post the log or close the issue

**Comment by Nicocraft05** [comment]
The LaunchServer.sh no function

**Comment by Nicocraft05** [comment]
yes 2 minutes please

**Comment by Sunekaer** [comment]
Because thats for linux...

**Comment by Nicocraft05** [comment]
yes

**Comment by Nicocraft05** [comment]
I already report x problem on your modpack

**Comment by Sunekaer** [comment]
what

**Comment by Nicocraft05** [comment]
xnet and wireless crafting terminal and ...

**Comment by Sunekaer** [comment]
that has nothing to do with this crash....

**Comment by Nicocraft05** [comment]
yes sorry but i love the modpack and I'm not alone waiting for the server launch

**Comment by Sunekaer** [comment]
and but mods has been updated

**Comment by Nicocraft05** [comment]
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2408695/latest.log)

**Comment by Sunekaer** [comment]
.... gist or pastebin

**Comment by Nicocraft05** [comment]
https://pastebin.com/dRcnsFZs

Sorry

**Comment by Sunekaer** [comment]
"Unable to read the jar file Draconic-Evolution-1.12.2-2.3.14.308-universal.jar - ignoring
java.util.zip.ZipException: error in opening zip file"
this happens for many mods, looks like a permission issue or corrupt jars

**Comment by Nicocraft05** [comment]
I tested 2 times the installation of the pack and tested the version 1.0.15 and as said no problem for the version 1.0.15.

Java: build 1.8.0_181-8u181-b13-1 ~ deb9u1-b13)

**Comment by Nicocraft05** [comment]
one bug:
./LaunchServer.sh
-bash: ./LaunchServer.sh: /bin/bash^M: bad interpreter: No such file or directory

**Comment by Sunekaer** [comment]
try redownloading the mods or check permission or update java

**Comment by Sunekaer** [comment]
Thats not a bug....

**Comment by Nicocraft05** [comment]
I just did it

**Comment by Nicocraft05** [comment]
for version linux no problem for windows?

**Comment by Sunekaer** [comment]
LaunchServer.sh is for starting the server on linux NOT WINDOWS

**Comment by Nicocraft05** [comment]
yes but my is linux

**Comment by Nicocraft05** [comment]
I just did the version of windows I just tested and has no problem

**Comment by Sunekaer** [comment]
did you update the LaunchServer.sh to the new one from the new files

**Comment by Nicocraft05** [comment]
i have del your modpack simply and tried the command for the start.sh

**Comment by Sunekaer** [comment]
start.sh?

**Comment by Nicocraft05** [comment]
LaunchServer.sh

**Comment by Sunekaer** [comment]
and what happened.......

**Comment by Nicocraft05** [comment]
but you're crazy about me, the same problem since earlier just listen to me I do not have it to do I go because you soul me serious good holiday ever I hope

**Comment by Sunekaer** [comment]
I have no clue what you are trying to say
