### ISSUE TITLE
Movement key lock-up.

### ISSUE THREAD

**Issue by derpendary** [Sunekaer/stoneBlock#156]
## Bug Report
Whenever I move around, the game randomly decides to act like I'm still holding a button and keeps making me walk until I press the button again. I have a high FPS of between 40 and 50, so I don't believe it is game lag. And this is the only pack in which this has happened. I've played other packs with a peak of 5FPS and have not experienced this.

## Steps to Reproduce bug
1. Hold any button for movement for more than 1 second, and it is likely to happen.

## Client Information
* Modpack Version: Latest; 1.0.15
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: false (to my knowledge)
* Shaders Enabled: false

**Comment by Sunekaer** [comment]
did you change BetterFPS or FoamFix settings?

**Comment by derpendary** [comment]
Not at all; I left BetterFPS as it is because there was hardly any lag. As for FoamFix, I hardly know what that is. Is there some sort of fix for this in there?

All in all, the most I did in the settings was check for vein miner in the controls, and make sure Vsync was on.

**Comment by Sunekaer** [comment]
is this in a new world or an old one?

**Comment by derpendary** [comment]
I've only made one world for the game. If you want me to make a new world and test it in that, I will be more than happy to.

**Comment by Sunekaer** [comment]
yeah that would be nice and if you also could try with version 1.0.16 of the pack

**Comment by knoxhack** [comment]
Are you sure your isn't your keyboard that is broken?

**Comment by derpendary** [comment]
Sunekaer: I did download the newest update you rolled out a day or two ago. It still occurs. Personally, I don't think starting a new world would fix the problem, but whatever you need.

knoxhack: I'm sure it isn't my keyboard. The keys don't physically get stuck, nor in the BIOS. Just in StoneBlock.

**Comment by Sunekaer** [comment]
sorry the late reply, whats your cpu usages at then this happens, and how much ram do you have assigned to minecraft?
