### ISSUE TITLE
Placeholder Rewards

### ISSUE THREAD

**Issue by Vaporous** [Sunekaer/stoneBlock#159]
## Bug Report
One of the loot chest rewards seems to have a typo or something in the list of items that it is supposed to give.

Reward gives 9 each of: Mirror, Photovoltaic Cell I, Photovoltaic Cell II, Photovoltaic Cell III, and Item Placeholder. The first 4 items are from Solar Flux Reborn, the last from Better Questing; according to the item placeholder, the original ID it was supposed to give was " solarflux:photovoltaic_cell_/0 ". I'm going to guess, as there is a Photovoltaic Cell IV in the mod pack, that that was the last item it was supposed to be given.

## Client Information
* Modpack Version: 1.0.16
* Server/LAN/Single Player: Single Player
* Optifine Installed: Not unless it came bundled with it

**Comment by jellonek** [comment]
The correct id for the item should be `solarflux:mirror` instead of `solarflux:photovoltiac_cell_/0`.

**Comment by Sunekaer** [comment]
no it should be `solarflux:photovoltaic_cell_4`

**Comment by Sunekaer** [comment]
1.0.17

**Comment by jellonek** [comment]
Was it new world on 1.0.17 or it was after upgrade to 1.0.17?
If later - have you executed `/bqs_loot default load` after pack upgrade?

**Comment by faminecode** [comment]
Existing world, after upgrade to 1.0.17.  I had run "/bq_admin default
load" as instructed by the release notes on first load of the world, but
not a loot command.

**Comment by jellonek** [comment]
@Sunekaer so looks like there is a need to add also an info (or autocmd as a renewable reward) for both bq_admin and bqs_loot default load after pack upgrade.

I can confirm that on plain new world on 1.0.17 this solar panels reward works perfectly ok (as iv'e received it just seconds ago).
