### ISSUE TITLE
End Rod recipe not working

### ISSUE THREAD

**Issue by kagejohn** [Sunekaer/stoneBlock#16]
JEI shows that i need 2 Ender Tether and 2 Lavender Quartz.
but when i put that in a crafting grid nothing happens, i have even tried using the Move Items button and it didn't work either.
![jei](https://user-images.githubusercontent.com/9349493/42896549-938ffda2-8abd-11e8-9bb9-f6f8fd31f3b1.png)
![crafting grid](https://user-images.githubusercontent.com/9349493/42896550-93ad4fd8-8abd-11e8-91b7-5345ea4190bc.png)

**Comment by Sunekaer** [comment]
fixed in dev.

Quick fix go to Instances\StoneBlock\scripts and delete shapedrecipes.zs and put in the one from this zip file
[shapedrecipes.zip](https://github.com/Sunekaer/stoneBlock/files/2206743/shapedrecipes.zip)
