### ISSUE TITLE
Disappearing mobs

### ISSUE THREAD

**Issue by IamStig** [Sunekaer/stoneBlock#160]
## Bug Report
Invisible mobs after visiting mining dimension, tags can be visible, but not always.

## Steps to Reproduce (for bugs)

1. Go to Aroma mining dimension
2. Return to overworld (stoneblock)
3. Reload and mobs are visible

## Logs
NA

* Client/Server Log:NA
* Crash Log:NA

## Client Information

* Modpack Version:1.0.16
* Server/LAN/Single Player:single
* Optifine Installed:Not added
* Shaders Enabled:Not added

**Comment by Sunekaer** [comment]
sounds like an Aroma bug, works fine with nether portal, but ill have to do some testing

**Comment by IamStig** [comment]
All good, not a huge issue just annoying. I'll Try the nether portal fix. 
BTW just had a thought, I'm not playing atm but I THINK when I used the teleporter (enderIO) to get back from mining world today the animals MAY not have disappeared.

Also, thanks for the work you put in, I'm really enjoying the pack

**Comment by Sunekaer** [comment]
from my testing is only with Aroma portal, ill create an issue on his github and ask him if he has seen this before

**Comment by Danklor** [comment]
The problem exists upon returning from the Deep Dark dimension as well.  It's not just Aroma after all.

**Comment by knoxhack** [comment]
Still happening in version 1.0.17?

**Comment by Danklor** [comment]
I just retested with 1.0.17, but the problem persists.
![invisible_mobs](https://user-images.githubusercontent.com/9893553/46239639-e9b88800-c368-11e8-8ba7-dd4d0e22a4ac.png)

**Comment by Sunekaer** [comment]
Okay, ill have to go through and remove mods one by one to try and find the one causing this issue, gonna take some time

**Comment by knoxhack** [comment]
Can you verify this is still a problem is version 1.0.19?

**Comment by Danklor** [comment]
I've just retested with pack version 1.0.19 and the problem persists.  It still affects both mobs and item frames and still occurs when returning from the mining dimension or the Deep Dark with those mods' portals.  However I've found that the problem does not occur when using the Advanced Dislocator from Draconic Evolution.

**Comment by IamStig** [comment]
I'm still using 1.0.18 (I like to have a week between spending 20 minutes redoing keybinds).
Can confirm still occurs

**Comment by IamStig** [comment]
Did a bit of further testing which provided interesting results.
Went to Aroma came back through portal - animals became invisible (6 pigs and a cow)
Went back to aroma and used charged porter to return - 2 of the pigs became visible
Went to nether and used charged porter to return - remainder of animals reappeared
At least there is an alternative to restarting. But why would 2/6 pigs reappear?

**Comment by Danklor** [comment]
I found a possible culprit: iChunUtil
With this mod (and its dependents) disabled I do not have any issues with invisible mobs / entities.
I'm not sure if the bug is actually in iChunUtil or if it triggers the bug in another mod, but I'm leaving it disabled until another fix is found.
Also, only disabling all of iChunUtil's dependents without disabling iChunUtil did not fix the problem.  These are GooglyEyes, Hats, BetterThanBunnies, and BetterThanLlamas.

**Comment by Danklor** [comment]
> I'm still using 1.0.18 (I like to have a week between spending 20 minutes redoing keybinds).
> Can confirm still occurs

A bit off-topic, but you can save your keybinds if you back up the file minecraft/options.txt.  I also back up my Journeymap folder when applying updates.  If you've modified any configs then you can back those up as well, but I use the pack default configs.

**Comment by Danklor** [comment]
It took quite a while trying different combinations of mods, but I found the trouble to be some kind of conflict between iChunUtil and CodeChickenLib.  With just those two plus the Aroma mods for testing I was able to duplicate the problem. I could also duplicate with iChunUtil and CodeChickenLib and Extra Utilities 2 (Deep Dark portal) for testing. I started with using the configs and mod files in pack v1.0.21 and disabled everything but the above. Many many mods in the pack depend on CodeChickenLib so disabling that really isn't an option.

**Comment by Sunekaer** [comment]
just loaded those 2 libs and aroma alone, i cant recreate the problem with only those 3 mods

**Comment by Sunekaer** [comment]
This is the list of mods im currently down to 
•Aroma1997Core (by Aroma1997)
•Aroma1997s Dimensional World (by Aroma1997)
•iChunUtil (by iChun)
•CodeChicken Lib 1.8.+ (by covers1624)
•Void Island Control (by Bartz24)
•Avaritia 1.1x (by brandon3055)
•Redstone Flux (by TeamCoFH)
•Brandon's Core (by brandon3055)
•p455w0rd's Library (by TheRealp455w0rd)
•/dank/null (by TheRealp455w0rd)
•Enderman Evolution (by TheRealp455w0rd)
•Ender Storage 1.8.+ (by covers1624)
•Forge MultiPart CBE (by covers1624)
•CoFH Core (by TeamCoFH)
•CoFH World (by TeamCoFH)
•Thermal Foundation (by TeamCoFH)
•Thermal Expansion (by TeamCoFH)
•Thermal Dynamics (by TeamCoFH)
•Translocators 1.8.+ (by covers1624)

**Comment by Danklor** [comment]
Here's a short video demo of the problem. Sorry for the bad video quality. It's my first Minecraft recording.
[invis-entities.mp4.zip](https://github.com/Sunekaer/stoneBlock/files/2479323/invis-entities.mp4.zip)

**Comment by Sunekaer** [comment]
hmm didnt do it for me, ill try a few time more

**Comment by Sunekaer** [comment]
Ty danklor ill talk with covers and ichun to find an solution

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
