### ISSUE TITLE
File LaunchServer.sh not formatted properly for linux.

### ISSUE THREAD

**Issue by tlemaillet** [Sunekaer/stoneBlock#161]
## Bug Report
The `LaunchServer.sh` file is in DOS format and therefore gives the following message while trying to execute it on linux: 
`bash: ./LaunchServer.sh: /bin/bash^M: bad interpreter: No such file or directory`

## Steps to Reproduce (for bugs)

1. Boot up a linux machine
2. Download fresh server files
3. Change permissions of `LaunchServer.sh` to be executable
4. Execute `LaunchServer.sh`
5. Get mentioned error message

## Logs
Irrelevant

## Client Information

* Modpack Version: 1.0.16
* Server/LAN/Single Player: Server Files on Linux
* Optifine Installed: irrelevant
* Shaders Enabled: irrelevant

This is due to Windows using a different file format than Unix. Notably using `\r\n` (or CR/LF) for line return while Unix only uses `\n`.
The first line is therefore: `#!/bin/bash\r` and `bash\r` indeed doesn't exists in the `/bin` directory.
You can use notepad++ to change EOL formatting:
https://stackoverflow.com/questions/16239551/eol-conversion-in-notepad

**Comment by jellonek** [comment]
`/usr/bin/bash` is also quite strange location (even on macos it's `/bin/bash`). If you are unsure where is the correct location of binary - use `!/usr/bin/env bash`.

**Comment by tlemaillet** [comment]
@jellonek That's my bad, i changed it after my tests and posted the error with it. In the actual server archive, it is indeed `/bin/bash`.
On my distro `/bin` is a symlink to `/usr/bin`.
Same problem even without the change of course =)

**Comment by Sunekaer** [comment]
[LaunchServer.zip](https://github.com/Sunekaer/stoneBlock/files/2411396/LaunchServer.zip)
could you test this one for me to check EOL

**Comment by tlemaillet** [comment]
This one works perfectly =)

**Comment by Sunekaer** [comment]
Thanks :)
