### ISSUE TITLE
Ingot/Block conflicts

### ISSUE THREAD

**Issue by Grynder01** [Sunekaer/stoneBlock#162]
Crafting Copper ingots into blocks makes the mekanism block instead of the thermal foundation block
but pouring blocks from the smelter makes thermal foundation block
this means they cant be stored in a compacting drawer together

More chickens mod Lead chicken drop item is IC2 lead instead of thermal foundation ingot
But crafting the IC2 ingot yields thermal foundation block
Edit:
It seams there are alot of chickens droping IC2 ingots instead of the TF ones
Silver
Lead 
Tin 
Bronze
Steel
 I may have have missed some
Also I haven't yet gotten to the uranium chicken but it looks like some possible conflicts there as well 
there is a uranium chicken that drops Immersive engineering uranium but that ingot is not listed by JEI

Again causing problems with compacting drawer storage systems

Not sure if these are intended or not but since the pack is showing Thermal foundation ingots in JEI
And the Mekanism blocks and ic2 ingots cant even be seen in JEI I thought it may just be an oversight

Logs: N/A

* Modpack Version: 1.0.16
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
they are just on default

**Comment by Grynder01** [comment]
I would go change them myself and I could upload the changes to you to update the pack but I cant find the Thermal foundation items to list correctly 
For instance the Invar chicken is like this
"Lay Item": "thermalfoundation:material:162",
    "Drop Item": "thermalfoundation:material:162",

But the Bronze chicken is this
"Lay Item": "ic2:ingot:1",
    "Drop Item": "ic2:ingot:1"

If I could find a list of the Thermal foundation material Numbers I would change it

**Comment by Aracos80** [comment]
i ran into the same problem like you, Grynder01.
if you'd like i could share my config file for more chickens which is edited so that the chickens lay/drop the thermal ingots instead of the ic2 stuff
