### ISSUE TITLE
EnderIO recipes

### ISSUE THREAD

**Issue by zCodeg** [Sunekaer/stoneBlock#164]
## Bug Report

Industrial Machine Chassis (used to make Alloy Smelter, SAG Mill and some other machines) is not craftable
## Steps to Reproduce (for bugs)

1.  Recipes for Alloy Smelter (requires the chassis)
![image](https://user-images.githubusercontent.com/5285811/45966830-e9e91880-c034-11e8-9452-05a0f64c2a5c.png)
2. Industrial Machine Chassis (dust item is Industrial Dye Blend)
![image](https://user-images.githubusercontent.com/5285811/45966996-53692700-c035-11e8-8221-2800c8611a78.png)
3.To make Dye Blend you need Organic Dye
![image](https://user-images.githubusercontent.com/5285811/45967062-84e1f280-c035-11e8-8495-7b8075841f84.png)
4.To make any of the organic dyes you need Alloy Smelter
![image](https://user-images.githubusercontent.com/5285811/45967145-bbb80880-c035-11e8-9045-cd7793b9eaa1.png)

## Logs

* Client/Server Log: -
* Crash Log: -

## Client Information

* Modpack Version: 1.0.16
* Server/LAN/Single Player: Server, but same on client
* Optifine Installed: No
* Shaders Enabled: No

**Comment by BushTrocity** [comment]
I thought i was going crazy. I noticed this as well. modpack 1.0.16

**Comment by mine3500** [comment]
dude simple alloy and simple sag to start then u can upgrade ur machines

**Comment by Sunekaer** [comment]
not a bug
