### ISSUE TITLE
Compressed mobs drop name tag

### ISSUE THREAD

**Issue by GaboonViper** [Sunekaer/stoneBlock#165]
## Steps to Reproduce (for bugs)

1. Create a mobfarm with a 3x3 shaft 22 blocks high
2. Stone spikes at the bottom
3. Wait for a compressed mob to fall down into the spikes
4. Collector collects name tag with "Compressed [MobName]" text on it

![2018-09-24_19 40 05](https://user-images.githubusercontent.com/6190802/45968954-a8f00480-c032-11e8-87a2-d47cc5058412.png)
![2018-09-24_19 40 47](https://user-images.githubusercontent.com/6190802/45968955-a8f00480-c032-11e8-9c87-083669174e5e.png)
![2018-09-24_19 40 54](https://user-images.githubusercontent.com/6190802/45968956-a8f00480-c032-11e8-9a93-65f9d687f164.png)
![2018-09-24_19 41 05](https://user-images.githubusercontent.com/6190802/45968957-a9889b00-c032-11e8-9a07-f232122aa3d9.png)

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.16
* Server/LAN/Single Player: Single Player
* Optifine Installed: OptiFine_1.12.2_HD_U_E2
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
sounds like an Ex Compressum bug, but ill have to do some testing

**Comment by Walhfort** [comment]
It drops even with punji sticks or manual killing with swords

**Comment by Sunekaer** [comment]
Ty seph, I didn’t know about those, which was why I said had more testing to do :)

**Comment by Sunekaer** [comment]
1.0.17
