### ISSUE TITLE
Advance Dislocator Quest won't complete

### ISSUE THREAD

**Issue by SpeedSlider** [Sunekaer/stoneBlock#168]
## Bug Report
Advance Dislocator Quest doesn't complete.

## Steps to Reproduce (for bugs)
1. Craft Advance Dislocator
2. Try to complete Quest

## Logs
N/A

## Client Information

* Modpack Version: 1.0.16
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by SpeedSlider** [comment]
Draconic Armor Quest is blank for items needed and can be completed without having the armor.

**Comment by Sunekaer** [comment]
1.0.17
