### ISSUE TITLE
Crashes due to Induction Smelter from TF (and other random crashes)

### ISSUE THREAD

**Issue by ThePlantPrince** [Sunekaer/stoneBlock#170]
Pastebins of the crashes:
https://pastebin.com/LnKmFnpr
https://pastebin.com/QfcHcUJX
https://pastebin.com/NSKAewt5
https://pastebin.com/PN0rUehk
https://pastebin.com/dH1GxNpm

These all happened within an hour of each other, all while I was doing either autocrafting with Refined Storage and/or using the Induction Smelter's UI (like clicking the "Lock Flux Slot" button or taking items out of it).

**Comment by Sunekaer** [comment]
Use the template
