### ISSUE TITLE
world corrupted?

### ISSUE THREAD

**Issue by Sir-hundred** [Sunekaer/stoneBlock#171]
so i had recently automated my mob farm and like  20 mins later the game had like corrupted ,
i am allowing 5 gigs of ram but it seems to only use 4.7
now , i cant interact with any block whatsoever(other than liquids...(with buckets)), bonsai pots are stuck at 100% even though a chest with free slots is under em.
cobblestone generators no longer respond with cobblestone x (number) when shift clicked cant sift , block wont drop anymore and i cant open my project e backpack bags thingys
No my mob farms drops are definetly not lagging out the world, 
when i close the world the game goes not responding but manages to save everything and does not give a crash log(i force close it by the way bcs it takes forever and dosent respond) this bug is consistent with 1.0.14 1.0.15

**Comment by Sunekaer** [comment]
use the template
