### ISSUE TITLE
Redwood saplings disappear when placed down

### ISSUE THREAD

**Issue by Whoevers** [Sunekaer/stoneBlock#173]
## Bug Report
Some Redwood Saplings from the mod Natura will disappear when placed in a 7x7 area, the size required for the Redwood tree to grow.

## Steps to Reproduce (for bugs)

1. Place down Redwood Saplings in a 7x7 area.
2. Wait, bonemeal or use Twerk-Sim 2K16

## Logs

* Client/Server Log: https://gist.github.com/Whoevers/1964f8464ac4e3a953a93234425c0493
* Crash Log:

## Client Information

* Modpack Version: 1.0.14
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
