### ISSUE TITLE
Lead Ore Piece chance seems low with Diamond Stiffened Mesh

### ISSUE THREAD

**Issue by retep998** [Sunekaer/stoneBlock#174]
## Bug Report
The chance for obtaining Lead Ore Piece is 3% with the String Mesh, 6% with the Flint Stiffened Mesh, 9% with the Iron Stiffened Mesh, but only 1% with the Diamond Stiffened Mesh. This *seems* like an oversight and since there was no existing issue I just wanted to check whether this was intentional or is indeed a bug.

## Steps to Reproduce (for bugs)
1. Check Drop Chance for Lead Ore Piece from Sieve in JEI

## Logs
N/A

## Client Information
* Modpack Version: 1.0.16
* Server/LAN/Single Player: Server
* Optifine Installed: N/A
* Shaders Enabled: N/A

**Comment by Sunekaer** [comment]
1.0.17
