### ISSUE TITLE
Tin Gear: Stone Gear OreDictionary fail - Please add

### ISSUE THREAD

**Issue by xILikepuddingx** [Sunekaer/stoneBlock#175]
## Context

Currently there is a small problem with the Tin Gear. Normally, it should be so that the Tin Gear accepts all kinds of Stone Gears. It does not do it. It only accepts the one from Tesla Lib. Here's a little fix for the problem. Would be glad if it came in.

## Config/Script Details
* Link: https://paste.myftb.de/galenohete.xml

https://files.ilikepudding.de/vsjb9cnhs7.mp4
First: Old Recipe
Second: New Recipe

Unfortunately there is a small problem here. recipe.remove do not remove the old recipe. There you should look again. But is better than nothing ^^

**Comment by Sunekaer** [comment]
1.0.17
