### ISSUE TITLE
Crash on entry of a new world 1.0.16

### ISSUE THREAD

**Issue by Zaronon** [Sunekaer/stoneBlock#176]
## Steps to Reproduce (for bugs)

1. 
2.

## Logs

* Client/Server Log: https://gist.github.com/Zaronon/1ec5581fa5e6c3cd6efbb6386ef14fbc
* Crash Log:
## Client Information

* Modpack Version: 1.0.16
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
crash log?

**Comment by Zaronon** [comment]
Pardon my ignorance but where would it be located?

**Comment by Sunekaer** [comment]
in the folder called crash-report in the minecraft instance folder

**Comment by Zaronon** [comment]
It doesn't exist for me the only additional information I can provide is from the output log which says "Process crashed with exit code 255"

**Comment by davidthesquid** [comment]
I also had the same problem, but not with a new world. It was an old world that I had used previously with no issues. When it updated, the game crashed as soon as it loaded. I did manage to get the crash report and it is attached. For server and optifine and all, it's the same as Zaronon's. Also, it tells you that there are missing items from the world, and that they will be removed, if that is of any importance.
[crash-2018-09-26_22.33.12-client.txt]
(https://github.com/Sunekaer/stoneBlock/files/2422261/crash-2018-09-26_22.33.12-client.txt)

**Comment by Zaronon** [comment]
I would love to be able to play the modpack but at this point it looks like I might just have to give up.

**Comment by knoxhack** [comment]
Try creating a new world using version 1.0.17 to see if this is still happening

**Comment by Zaronon** [comment]
The problem persisted. However, after messing with some stuff I did get a crash report: https://gist.github.com/Zaronon/44349d23d834d47184f9084c0895ae9d

**Comment by Zaronon** [comment]
I resolved it can't run it in fullscreen mode
