### ISSUE TITLE
Refined storeage Items disapeared

### ISSUE THREAD

**Issue by BushTrocity** [Sunekaer/stoneBlock#177]
## Bug Report
No items show up in my crafting grid. It has power and the controller sees the grid and the drive. the drives show they are holding stuff.

## Steps to Reproduce (for bugs)

1. Idk how this happened so i can't say how to recreate it but i crafted a importer and left the grid to place it came back and everything was gone.

## Logs
* Client/Server Log: https://gist.github.com/BushTrocity/c8bc8b4a19896fab98fc70ff80561c83

## Client Information

* Modpack Version:1.0.16
* Server/LAN/Single Player:Server
* Optifine Installed:No
* Shaders Enabled:No

![grid](https://user-images.githubusercontent.com/3528732/46063633-636b2e80-c13b-11e8-8230-1f3efc092c55.JPG)

**Comment by Sunekaer** [comment]
Try and break the controller and place it again

**Comment by BushTrocity** [comment]
I broke it all and replaced and nothing. I restarted the server and my client still nothing.

**Comment by BushTrocity** [comment]
After restarting the server and client a few times seemd to fix it. everything is back,
