### ISSUE TITLE
Beacon Effect Application Range is Incorrect & Inconsistent (1.0.15)

### ISSUE THREAD

**Issue by TheExtraChromosome** [Sunekaer/stoneBlock#178]
## Bug Report
Max tier beacon built underground with tunnel to sky activates correctly. Selecting effect and giving sacrificial item also works correctly. However, beacon effect area is incorrect and inconsistent, depending on it's location. The few tests I ran were similar in that the beacon didn't seem to extend downwards correctly, and the range was often very small horizontally.

The only config I changed was the tinker's leveling config, to cap leveling to 10.

## Steps to Reproduce
1. build beacon
2. tunnel to surface above beacon
3. stem the flow of lava and return to beacon
4. activate beacon effect
5. enjoy trying to figure out where the beacon wants to give you the effect, and where it doesn't

## Client Information
* Modpack Version: 1.0.15
* Experiencing issue in Single Player
* Running with java jre1.8.0_171
* Moved instance to MultiMC launcher due to annoyances that created deep-rooted hatred with twitch launcher

**Comment by TheExtraChromosome** [comment]
Further tested and removed potential factors:
1. Bug present regardless of dimension or height in the world
2. Launched with default settings and config (excluding changing Xmx to 8192mb) from twitch launcher, bug persisted
3. Updated to current latest modpack version, 1.0.16, bug persisted

**Comment by TheExtraChromosome** [comment]
I don't think location matters, it just seems completely random. 95% of the time, it only gives you the effect if you're directly above the beacon (not below), but sometimes you can get the effect in other places near the beacon as well. I have no idea what could be causing the issue, or if anyone else is able to reproduce it.

**Comment by TheExtraChromosome** [comment]
I set up roughly 20 beacons between the overworld, the nether, and the end, and all of them acted the same.

**Comment by Sunekaer** [comment]
Okay, ill have to do some testing to try and find the mod messing with it, its gonna take some time  tho

**Comment by knoxhack** [comment]
Can you verify this is still a problem is version 1.0.19?

**Comment by knoxhack** [comment]
Can you verify this is still a problem is version 1.0.20?

**Comment by TheExtraChromosome** [comment]
Sorry for the long response time, I've had painfully bad internet. I am still experiencing the bug on a fresh install of version 1.0.20, gonna try a binary elimination check turning mods on and off to see if I can find the culprit.

**Comment by knoxhack** [comment]
Probably cyclic :/

**Comment by TheExtraChromosome** [comment]
I believe the problem is being caused by Better Fps. This makes sense as better fps edits beacon code

**Comment by Sunekaer** [comment]
So turning Fast Beacon off should fix it, that we can change in an update

**Comment by TheExtraChromosome** [comment]
Turning off fast beacon from Better Fps' options menu does seem to solve the issue in 1.0.15 and 1.0.20 (the versions I have installed), should this issue be closed?

**Comment by Sunekaer** [comment]
we´ll close it when we push it out with an update

**Comment by knoxhack** [comment]
Fixed in 1.0.21
