### ISSUE TITLE
Game froze (could still move, but everything was frozen) (1.0.15)

### ISSUE THREAD

**Issue by Insane-96** [Sunekaer/stoneBlock#179]
## Bug Report
Was normally playing, after creating a mobspawner with Extra Utilities cursed dirt and mob_grinder_utils mob fan and smasher, after a while that I'd started the farm, the world froze.

## Steps to Reproduce (for bugs)

Really don't know

## Logs

* Client/Server Log: https://gist.github.com/Insane-96/72cdb48385e069381f7c2bac65f14bee
* Crash Log: No Crash log

## Client Information

* Modpack Version: 1.0.15
* Server/LAN/Single Player: Single Player
* Optifine Installed: ❌
* Shaders Enabled: ❌

**Comment by TheExtraChromosome** [comment]
There's alerts in your log for having inadequate memory, and dropped game-ticks as a result. I would recommend increasing your allocated ram to the recommended 6 GB (6144mb), minimum, instead of the current 4484mb you have allocated.

**Comment by Insane-96** [comment]
Tried putting 6144 MB of ram via Twitch, but the game seems to not use over 3.5GB, tried reopening the world, after a few seconds the world stops responding again.

**Comment by TheExtraChromosome** [comment]
When in the debug screen (F3), your memory usage should appear at the top right. Is 3.5GB roughly around the 100% mark? Or does it simply not pass 3.5gb usage? I've had many, many horrible issues with the twitch launcher in the past (I would recommend looking into using MultiMC launcher and manually patching your game) when trying to change any launch settings off default.

If your memory isn't bumping around 100%, your log shows some exnihilo related blocks bugging out at  BlockPos{x=-1008, y=90, z=-998}, BlockPos{x=-1008, y=90, z=-1000}, and BlockPos{x=-1012, y=90, z=-1006}. While it's unlikely, they could be causing issues. If there isn't anything wrong with these blocks, I would recommend backing up your save and removing your mob farm- if the issue persists, it's unlikely to be the cause, and something else is happening.

**Comment by Insane-96** [comment]
![2018-09-26_14 58 48](https://user-images.githubusercontent.com/7185104/46081786-af4ebf80-c19d-11e8-893a-cb3425891c39.png)
That's my F3 screen, seems ram is not a problem here.

Plus seems like the log wasn't fully copied, that's the right log before crashing as soon as I re-open the world: https://gist.github.com/Insane-96/b8d65e506a1efdff0525e940ef40051f

I'll now try to destroy the blocks at the positions, but don't think is the problem

**Comment by Insane-96** [comment]
Tried destroying and place back the auto sieve and hammers, for a while the world worked properly, BUT sadly after about 15 minutes the world stopped again. I did an F3 screenshot after the world stopped.
![2018-09-26_15 24 24](https://user-images.githubusercontent.com/7185104/46082920-8a0f8080-c1a0-11e8-84f7-af2f23d72f59.png)

I'll now try to remove the mob_grinder_utils smasher.
That's the latest log: https://gist.github.com/Insane-96/1d4662e24d5ab496651831eb4c7e1550

**Comment by OfficialStamper** [comment]
Just an observation, forge ver 2707, current is 2760. Not sure what the recommended ver is for 1.0.15, but 1.0.16 is forge 2760.......

**Comment by Insane-96** [comment]
I see Java too is outdated. I'll try to update both modpack and use the right java later, but right now I removed the smasher and set difficulty to peaceful for a while, had no problems. Now I've replaced the smasher with some simple stone spikes, if the game no longer freezes then might be that the smasher has some problems (maybe with a mob spawned from cursed earth), if not, then the problem might be the cursed earth.

**Comment by TheExtraChromosome** [comment]
Wow, the entity UUID bug is still cropping up 7-8 years later, I didn't know that STILL wasn't fixed (thanks mojang). That would make sense as being your potential culprit (the UUID bug will bog down servers, in this case, your internal server, explaining why the game freezes but your "client" doesn't). I've never found a solution for it, and it is one of the most infuriating world-killing bugs, because all the "solutions" that are posted are temporary fixes. There might be something in the modpack causing it to flare up though, so I would keep the issue open.

**Comment by TheExtraChromosome** [comment]
Makes even more sense considering you said your game is fine in peaceful, all of your "ghost" entities are hostiles
[15:14:49] [Server thread/WARN]: Keeping entity minecraft:skeleton that already exists with UUID 1808f199-decc-4091-b4e8-89b1b07bc5be
[14:58:21] [Server thread/WARN]: Keeping entity minecraft:skeleton that already exists with UUID 1c17fcef-28fc-4551-9731-f31be1efda18
[14:59:53] [Server thread/WARN]: Keeping entity minecraft:skeleton that already exists with UUID cefa5ec2-c49e-4fe4-90b9-8371c808ec14

**Comment by Insane-96** [comment]
I was AFK for a while now


```
[16:54:46] [Server thread/WARN]: Keeping entity minecraft:skeleton that already exists with UUID 87fc7ad1-3cd8-480a-8845-ea48b6e387e0
[16:54:57] [Server thread/WARN]: Keeping entity minecraft:skeleton that already exists with UUID 2019c23f-71fe-4264-8578-06568eb90e4f
[16:59:19] [Server thread/WARN]: Keeping entity minecraft:skeleton that already exists with UUID ff71ae28-db93-4f38-b974-593da05ae7ca
[17:02:05] [Server thread/WARN]: Keeping entity minecraft:skeleton that already exists with UUID 55c78eef-b073-4f9b-8e35-b76c11a652ba
[17:04:44] [Server thread/WARN]: Keeping entity minecraft:skeleton that already exists with UUID d3626c78-388c-4649-900a-a1841b8c71df
[17:18:18] [Server thread/WARN]: Keeping entity minecraft:skeleton that already exists with UUID e95db006-7280-45ce-96a9-257ba7c4888b
```
Those were still in the log, but the world had no problem with stone spikes. I'll try changing to different killing methods (because I need xp and killed-by-player loot too). So the smasher seems to kill mobs in a strange way.
Maybe Cursed Earth spawns entities in a strange way too since I've never seen this happen with vanilla spawns

**Comment by Insane-96** [comment]
Yep, removing the Smasher (and replacing it with some simple stone spikes) did the trick. I'm thinking that maybe the internal server crashes due to compressed mobs killed by the smasher. I'll test this out later
