### ISSUE TITLE
Lava spawn

### ISSUE THREAD

**Issue by esben1** [Sunekaer/stoneBlock#181]
When i spawn in i spawn in lava but dont take damage and got 0 fps pls help

**Comment by Denslat** [comment]
the world is spawned with lava at the very top of the map.
The world can also take a while to load (usually after which you will be placed in the correct location) should that fail and you happen to die or get stuck somewhere, either recreate the world with cheats enabled and do /spawn (if it happens again) 
you may also not have enough memory and as such the game is struggling to load correctly.

**Comment by esben1** [comment]
The modpack says that you can configure Builders to make it esayier for your pc to run it, but where can i find it??

**Comment by esben1** [comment]
and if you mean Ram i got like 12 GB left to use

**Comment by Sunekaer** [comment]
what where does it say that?

**Comment by esben1** [comment]
You can see it where you can type commands by pressing T i think

**Comment by Sunekaer** [comment]
that is buildCraft... but your not using buildcraft on an new world so that wrong change anything.
How ram do you have assigned to minecrafT?

**Comment by esben1** [comment]
Where can i see that?

**Comment by esben1** [comment]
Where can i check that ??

**Comment by knoxhack** [comment]
If you don't know how much RAM you have allocated then you have the default that the Twich launcher gives 3GBs I think, then you need to allocate more RAM. Here is how:
https://youtu.be/R3_sCJWZKp8

**Comment by knoxhack** [comment]
Make sure to allocate at least 6GB of RAM
