### ISSUE TITLE
Yellorium duplication due to uneven math

### ISSUE THREAD

**Issue by Denslat** [Sunekaer/stoneBlock#183]
## Bug Report

Yellorium duplication possible.
## Steps to Reproduce (for bugs)

https://www.youtube.com/watch?v=f1KrijKAMnk&t

Video has all the details. I'm reporting this but I won't say people shouldn't take advantage of it until you resolve it.
## Logs
unecessary

## Client Information

* Modpack Version:10.0.16
* Server/LAN/Single Player: Doesn't matter
* Optifine Installed: Doesn't matter
* Shaders Enabled: Doesn't matter

**Comment by mine3500** [comment]
well then i dont know if is a bug or just mekanism but the amount of resources u need to get started far outweighs the benefits

**Comment by Sunekaer** [comment]
1.0.17
