### ISSUE TITLE
Fluxed Electrum Block (EMC)

### ISSUE THREAD

**Issue by Strezzed** [Sunekaer/stoneBlock#184]
## Context

Add EMC to Fluxed Electrum Block

**Comment by Sunekaer** [comment]
why

**Comment by Strezzed** [comment]
For getting the Fluxed Singularity

**Comment by SirioIlBe** [comment]
yes...i second this. its so hard to create the fluxed elextrum blocks. well not hard.it just takes a lot of time.i actually think the recipe is wrong.maybe it was suposed to be just one block like the enderium and the steel blocks

**Comment by Sunekaer** [comment]
1.0.17
