### ISSUE TITLE
draconic armor quest

### ISSUE THREAD

**Issue by Bass2style** [Sunekaer/stoneBlock#186]
## Bug Report
issue in the Draconic Evolution Branch,
Draconic Armor have no quest, quest auto-completes when Wyvern Armor is crafted.

## Steps to Reproduce (for bugs)
simply finish the Wyvern Armor quest, and see the Draconic Armor quest : https://prnt.sc/kz5ccn

## Logs
no logs to provide.

## Client Information

* Modpack Version: 1.0.16
* Server/LAN/Single Player:single player
* Optifine Installed:nope
* Shaders Enabled:nope

**Comment by Sunekaer** [comment]
#168
