### ISSUE TITLE
Make Grinding less Grindy?

### ISSUE THREAD

**Issue by Mukkod** [Sunekaer/stoneBlock#187]
I was playing the pack and my love of mekanism immediately took over
Config/Script Details
Add ability to grind cobble down to dust with various machines from various mods; Thermal Expansion/Mekanism/IC2 ect.
    Link: None

Mod Details

    Name: Mekanism and other mods that add grinders
    CurseForge Link:

**Comment by Sunekaer** [comment]
1.0.17
