### ISSUE TITLE
Shift+right click water upgrade on quantum tank does not work

### ISSUE THREAD

**Issue by Runisco** [Sunekaer/stoneBlock#188]
## Bug Report
Attempting to shift+right click an infinite water upgrade on a quantum tank does not work. Nothing happens.

## Steps to Reproduce (for bugs)
1. Make a quantum tank and infinite water upgrade, try to shift+right click.

## Client Information

* Modpack Version: 1.0.16
* Server/LAN/Single Player: Single
* Optifine Installed: NO
* Shaders Enabled: NO

**Comment by Sunekaer** [comment]
you need one bucket of water in it to work
