### ISSUE TITLE
IC2 Progression

### ISSUE THREAD

**Issue by KeepoMC** [Sunekaer/stoneBlock#19]
I'm unsure of how to progress with IC2 in this pack. ImEng cables no longer convert so I had to make a basic solar panel just to run the only machine I wanted, the compressor. Also I'm working on Wyvern Armor and you need the Quantum armor which requires iridum shards which are normally found in chests in the overworld. I tried to breed iridium chickens but that's not the right type of iridium so I guess I'm unsure of where to go from here.

**Comment by Sunekaer** [comment]
Added recipe with 9 Iridium nugget for 1 Iridium Ore in the Compressor

Quick fix go to Instances\StoneBlock\config and paste the folder from this ZIP file
[ic2.zip](https://github.com/Sunekaer/stoneBlock/files/2210238/ic2.zip)
