### ISSUE TITLE
Quantum Tank Duplication with Flat Transfer Node (Fluid)

### ISSUE THREAD

**Issue by pleggins** [Sunekaer/stoneBlock#190]
## Bug Report
Quantum Tank is duplicated under specific behavior.

## Steps to Reproduce (for bugs)
(please see screenshot 1 for setup. I have a basic tiny progressions cobblestone generator feeding a crucible over a superheating element. There is a fluid flat transfer node on the side of the crucible.)
1. place empty quantum tank where shown in screenshot
2. shift + right click on fluid transfer node with empty hand creates a duplicate empty quantum tank
3. Does not work with other tanks. I have tried a tank from open blocks and also a basic ender io tank. Also tried with a wooden barrel and water. This does not work.
4. Issue persists after game and client restarts

![screenshot_1](https://user-images.githubusercontent.com/10521475/46114758-aa980480-c1b9-11e8-9d45-70a40a5cc47c.png)
![screenshot_2](https://user-images.githubusercontent.com/10521475/46114768-aff54f00-c1b9-11e8-8654-845bfd1d3687.png)

## Logs

* Client/Server Log: 
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2421924/latest.log)

* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.16
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
could you make a video of this? because either i cant recreate or then i dont understand your steps
