### ISSUE TITLE
Multiple ore type spawn

### ISSUE THREAD

**Issue by Nazta** [Sunekaer/stoneBlock#191]
## Bug Report
Both thermal and immersive engineers ores  spawn in the mining dimension.  Things like aluminium/bauxite, copper, lead, etc. 

## Fix
Add the mining dimension id to the immersive engineering ore spawn blacklist. 
Potentially add thermalfoundation to the top of the "preferred ores" listing in the the same config flie.

**Comment by Sunekaer** [comment]
I know both spawn there, I made them do that, I don’t see how that is a problem

**Comment by Nazta** [comment]
Usually I would say it's not normal. Since most packs tend to unify ore spawn as long as the end result is the same.

**Comment by Sunekaer** [comment]
Well yes some new packs are doing it, but I don’t see it, to be a problem, so I won’t be changing it
