### ISSUE TITLE
Fluxbore uncraftable in .16

### ISSUE THREAD

**Issue by cpypcy** [Sunekaer/stoneBlock#192]
Fluxbore is uncraftable and i think few more thermal mod recipes too.

1. None needed

## Client Information

* Modpack Version: StoneBlock-1.0.16

* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No
* Inventory Tweaks: Yes

**Comment by Sunekaer** [comment]
The mod adding that is not in this pack
