### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Pm0001** [Sunekaer/stoneBlock#193]
Crash while playing. See report attached.

Using latest version.

[crash-2018-09-27_12.36.17-client.txt](https://github.com/Sunekaer/stoneBlock/files/2423721/crash-2018-09-27_12.36.17-client.txt)

**Comment by Pm0001** [comment]
I noticed it crashes when I wanna put sth in the jungle shelf...

**Comment by Sunekaer** [comment]
Use the template and upload the log to gist.github.com or pastebin
