### ISSUE TITLE
Fluxbore is uncraftable in 0.16

### ISSUE THREAD

**Issue by cpypcy** [Sunekaer/stoneBlock#194]
Fluxbore is uncraftable and i think few more thermal mod recipes too.

    None needed

Client Information

    Modpack Version: StoneBlock-1.0.16

    Server/LAN/Single Player: Server
Server files untouched, client files only keybinds changed.
    Optifine Installed: No

    Shaders Enabled: No

**Comment by Sunekaer** [comment]
ill say it again the mod that adds Fluxbore is not in the pack
