### ISSUE TITLE
Terrible FPS and load speeds.

### ISSUE THREAD

**Issue by Tanman706** [Sunekaer/stoneBlock#195]
## Bug Report

I have attempted to load the modpack multiple times now, at least 15 times or so, redownloaded it twice as well, and no matter what I try, the world takes an ungodly amount of time to load, and the game crashes two to three times before the world will finally load in. I've been able to play for a little bit, but ever time i move, i go from 120FPS, to 0. All of my graphics settings are at the bare minimum, Here are my specs
GPU: Geforce GTX 1080
CPU:  AMD Ryzen 5 1600X Six-Core Processor, 3600 Mhz, 6 Core(s), 12 Logical Processor(s)
Ram: 2 8GB sticks of TeamGroup
I don't know the motherboard, but I know that this computer can run PUBG at the highest graphics settings, and get 60FPS without dropping, and i'm looking for a solution to this problem. This modpack seems like a ton of fun, and it would be a shame if I couldn't play it.
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.16
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by knoxhack** [comment]
This normally happens when you don't allocate enough RAM to Minecraft, how much are you allocating?

**Comment by Tanman706** [comment]
> This normally happens when you don't allocate enough RAM to Minecraft, how much are you allocating?
I'm not sure actually, how do I allocate my ram to the game?

**Comment by knoxhack** [comment]
https://youtu.be/R3_sCJWZKp8

**Comment by Tanman706** [comment]
Knoxhack

So that worked and fixed that problem, but now i'm having a new problem. Whenever I load the modpack, my headset stops working. I restarted my PC, and then it was working fine, and now as soon as the pack loaded, the audio cut out entirely. My headset is a Corsair Void Pro USB headset

**Comment by Tanman706** [comment]
UPDATE:
It's fine, I just had to reload resource packs with F3 + T.
Thank you for your help!
