### ISSUE TITLE
Make default load for quests and loot button in GUI (Re-asking)

### ISSUE THREAD

**Issue by alpal01** [Sunekaer/stoneBlock#200]
Please make it so in the next update that you can refresh the quests and loot without having OP permissions, thanks!
Because you said that you can't do that (in #167), packs like FTB Continuum and Modern Skyblock 3 do it with same questing mod

**Comment by knoxhack** [comment]
I got the go ahead from Sunakaer to add this, I'll be working on adding them probably for next update

**Comment by Sunekaer** [comment]
1.0.18
