### ISSUE TITLE
Visual glitch with Fluid Cow cool-down

### ISSUE THREAD

**Issue by Whoevers** [Sunekaer/stoneBlock#201]
## Bug Report
When milking Fluid Cows using the Animal Rancher from Industrial Foregoing, Waila will continuously display "Next usable: Now". The cool down is actually reset; the Animal Rancher will keep milking the cow approximately every 3 minutes.  Right clicking on the cow resets the cool down. Right clicking on the cow with an empty bucket will make it look like the cow has been milked again. Clicking on the bucket with the liquid in it will make the bucket disappear.

## Steps to Reproduce (for bugs)

1. Milk MooFluids Cow with the Animal Rancher.
2. Right click cow with a bucket/empty hand.

## Logs

* Client/Server Log: https://gist.github.com/Whoevers/12eef890b977624ad6e091ea0e357fdf
* Crash Log:

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
removed Moo FLuids in 1.0.24
