### ISSUE TITLE
Aroma's mining dimension DimID config issue

### ISSUE THREAD

**Issue by GuntherDW** [Sunekaer/stoneBlock#203]
## Bug Report
Currently the aroma's mining dimension config has an issue regarding the DimID.
The config string/key for the DimID has changed and thus is pointing towards an other DimID, while the oregen configs and other mods still referr to the old DimID.

https://github.com/Sunekaer/stoneBlock/blob/9d5745b62458f59fabe159a5841edf0fb3424d6c/config/aroma1997/aroma1997sdimension.cfg#L3-L8

The correct one is the one with the comment leading it, thus "I:dimensionID". That value for that key should be changed accordingly and the other one removed for clarity.

We have changed this on our server after we noticed the quest book talking about stuff that should generate in the mining DIM and not doing so.
After changing the value to the correct one (6) stuff did generate accordingly.
This also does leave a dangling DIM-6 folder in the world folder, which can be removed cleanly (or renamed if you want to keep the "old" chunks).

## Logs

No logs required because it's not a crash but a config issue?

## Client Information
* Modpack Version: 1.0.17 (but affects older versions as well since we started the pack, on 1.0.15)
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

**Comment by GuntherDW** [comment]
The supplied fix could use some work though. It's best to remove the other line as well so somewhere down the line you (or other people) don't get confused as to which one the "correct" one is.

Cleaning up should be part of the process.

**Comment by OfficialStamper** [comment]
Players on my server have already built in -6, and that is lost now. Before they rebuild, can we agree if mining dim is going to be 6 or -6?
Thanks

**Comment by Sunekaer** [comment]
-6

**Comment by OfficialStamper** [comment]
@Sunekaer thanks for the reply.  So all the other mod configs, will be changed to -6, rather than the Aroma config being changed to 6 as suggested above.  Just trying to clarify your answer.

**Comment by Sunekaer** [comment]
1.0.18
