### ISSUE TITLE
Infinite use of items on stone barrel with automated user from cyclic

### ISSUE THREAD

**Issue by Midlog** [Sunekaer/stoneBlock#207]
## Bug Report

Automated user attached to a surival generator and a stone barrel uses blocks from its inventory but they are still there. Use it to produce for example clay using only water or endstone using only lava.

## Steps to Reproduce (for bugs)

1. Place a stone barrel
2. Attach  automated user from cyclic to 1.
3. Power 2. with survival generator
4. Put more than 1 block of for example dust into 2.
5. Fill the 1. with water
6. See how it makes an item but doesnt take the dust from the automated user.

## Logs

* Client/Server Log: none
* Crash Log: none

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: SinglePlayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
i can not recreate this in my testing world, could you sent me an screenshot of the setup
