### ISSUE TITLE
Diamond Duping

### ISSUE THREAD

**Issue by ariosos** [Sunekaer/stoneBlock#208]
Bug - It is possible to duplicate diamonds via different crafting and machines.

Steps to reproduce -

1. Craft diamond horse armor. (4 diamonds, 1 wood, 2 leather).
2. Put the horse armor into an AA Crusher (gives 6 diamond dust - pulverizer gives 2).
3. Smelt the dust in a redstone furnace. (1:1 ratio of dust to diamond).

Result - You get a net gain of 2 diamonds. Sure, you need the wool and leather, but these are pretty easy to automate with a mob farm.

Using 1.0.17 (removed Evilcraft and Evolved Endermen)

**Comment by GithubDuke** [comment]
2 diamonds is nothing in a pack like this. You can easily get 20.000 diamonds using chickens without too much work.

**Comment by Spyrox17** [comment]
Not really a bug since you can dupe other ores easily as a feature.

**Comment by Sunekaer** [comment]
1.0.18
