### ISSUE TITLE
End Game EMC production

### ISSUE THREAD

**Issue by KeepoMC** [Sunekaer/stoneBlock#21]
Do you have an idea for end game EMC production because all the EMC farms I've looked up requires blocks that aren't in this pack. Things I've tried: 

Mystical Aggraditions Nether Star Farms with max amount of Tier 3 Growth Crystals
Extra Utilities Cobblestone Generator
Tiny Progressions Cobblestone Generator
Enchanted Books with automated essence berry generation but the farming station no longer farms just the concentrated essence berries

none of these seems to produce a adequate source of EMC for endgame duping

**Comment by KeepoMC** [comment]
The enchanted books might work if there's a way to farm just the concentrated essence berries but I haven't found one that doesn't destroy the actual bush

**Comment by KeepoMC** [comment]
I think the solution is a buttload of emerald chickens producing emerald blocks but if you have a more optimal way I'd love to hear it.   

Also I started this pack on a server 7 days ago and here's my time played https://puu.sh/AZJxO/7dcd67bb62.png  

I think you have a really good pack

**Comment by Sunekaer** [comment]
there is no specific end game farms added.. its all up to the player to find a way to farm EMC that make sense to them

**Comment by iSnuup** [comment]
Personally, on Stoneblock 2, I have many terrasteel chickens pumping into my mk2 condenser. Mk1 couldn't keep up with the input.
