### ISSUE TITLE
Local server crash on update to 1.0.17

### ISSUE THREAD

**Issue by dlswimmer** [Sunekaer/stoneBlock#211]
## Steps to Reproduce (for bugs)

1. Cleaned folders and files copied from updated server zip (config, mods, scripts, etc.)
2. Local server updated to 1.0.17 from 1.0.16 (copied from server download).
3. Start server and crash

## Logs

* Client/Server Log: https://pastebin.com/vpRVpp4M

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Local Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Could you try redownloading the mod files?

**Comment by dlswimmer** [comment]
I re-downloaded the files, and tried the update again. I get the same crash.
https://pastebin.com/sa9rvvf0

**Comment by knoxhack** [comment]
That's a corrupted block at: -43,89,6
Delete that block using the mod World Utils or use World Edit to edit it out

**Comment by Sunekaer** [comment]
Could you try and go into the config folder. Locate the file "Forge.cfg" there is a line for removing erroring tile entities. turn this from false to true. Restart the server and load the chunks the crash is happening at. Afterwards turn the config back to false and restart the server.

**Comment by Sunekaer** [comment]
weird

**Comment by knoxhack** [comment]
This still happening in 1.0.20? 🍶

**Comment by knoxhack** [comment]
Thats a totally different crash if you are not getting the crash on the report Im considering this fixed
