### ISSUE TITLE
Issue when updating from 1.0.16 - 1.0.17

### ISSUE THREAD

**Issue by tjd46** [Sunekaer/stoneBlock#212]
Bug Report
Steps to Reproduce (for bugs)

update from 1.0.16 to 1.0.17 with this world file

Logs

    Client/Server Log: https://pastebin.com/MMn1Nr2s
    Img berfore - https://i.imgur.com/i9pdh5E.png
    Img after - https://i.imgur.com/CRwpeAi.png (little further away but those were
 the roosts)
    world dl - https://drive.google.com/open?id=18IZ8BMdJavHzewSSLxv-Y2xrj-wuWVS_
Client Information

    Modpack Version: 1.0.17 & 1.0.16
    Server/LAN/Single Player: Single player
    Optifine Installed: No
    Shaders Enabled: No

**Comment by tjd46** [comment]
also note that the log says something about an auto sieve I currently don't have an auto I do have 1 normal and 1 heavy sieve.

**Comment by Sunekaer** [comment]
do you have backup of the world from before it got messed up?

**Comment by tjd46** [comment]
that was the latest before updating I shall try some of the others.

**Comment by tjd46** [comment]
oldest backup did not work still had the corruption. I did find a way for now to get my stuff over when updating, I stored my whole base into vanilla chests(had to be vanilla otherwise it got corrupted/swapped)
this probably wont work for everyone though......

**Comment by tjd46** [comment]
world without the wooden crucible turning into a ticking crash - https://drive.google.com/open?id=1S2Q7YhKuwr6Kp8tX85P942m2mSo_vYI_
and album of before and after the update https://imgur.com/a/QjCXzs7

**Comment by Sunekaer** [comment]
Okay so this issue gets fixed by adding https://minecraft.curseforge.com/projects/notenoughids
From looking at the issues you wrote in there

**Comment by Sunekaer** [comment]
Okay thanks, im gonna add JustEnoughIDs in the next update, does the same thing just updated

**Comment by Sunekaer** [comment]
1.0.18
