### ISSUE TITLE
Compacting drawers from the storage drawers do not work with exnihilocreatio ore chunks.

### ISSUE THREAD

**Issue by egold555** [Sunekaer/stoneBlock#213]
## Bug Report
Compacting drawers from the storage drawers do not work with exnihilocreatio ore chunks.

## Steps to Reproduce (for bugs)
1. Craft a compacting drawer
2. Place in 4+ ore chunks
3. Watch as the storage drawer locks out the bottom two slots.

## Logs
* Client/Server Log: https://gist.github.com/egold555/61ca0b1832722918d73ffde7a405222f
* Crash Log: No Crash Log because the game didn't crash.

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## Fix
I have a fix  for my installation but I feel like this should be fixed on every version. To fix this, open the storage drawers config and add these lines in the registry aspect of the config

exnihilocreatio:item_ore_iron:1, exnihilocreatio:item_ore_iron, 4
exnihilocreatio:item_ore_gold:1, exnihilocreatio:item_ore_gold, 4
exnihilocreatio:item_ore_copper:1, exnihilocreatio:item_ore_copper, 4
exnihilocreatio:item_ore_tin:1, exnihilocreatio:item_ore_tin, 4
exnihilocreatio:item_ore_aluminium:1, exnihilocreatio:item_ore_aluminium, 4
exnihilocreatio:item_ore_lead:1, exnihilocreatio:item_ore_lead, 4
exnihilocreatio:item_ore_silver:1, exnihilocreatio:item_ore_silver, 4
exnihilocreatio:item_ore_nickel:1, exnihilocreatio:item_ore_nickel, 4
exnihilocreatio:item_ore_ardite:1, exnihilocreatio:item_ore_ardite, 4
exnihilocreatio:item_ore_cobalt:1, exnihilocreatio:item_ore_cobalt, 4
exnihilocreatio:item_ore_apatite:1, exnihilocreatio:item_ore_apatite, 4
exnihilocreatio:item_ore_osmium:1, exnihilocreatio:item_ore_osmium, 4

**Comment by Revvilo** [comment]
I'm pretty sure that happens because the iron can't be changed back into pieces again once the chunk is crafted.
As far as I know, the compacting drawer works both ways and stores the items in the most compact form, so it doesn't allow one-way compacting.

**Comment by Sunekaer** [comment]
1.0.18
