### ISSUE TITLE
Grains of Infinity Seeds & Phytogenic Insolator

### ISSUE THREAD

**Issue by Flatts3000** [Sunekaer/stoneBlock#214]
## Bug Report
Grains of Infinity Seeds from Mystical Agriculture cannot be placed in a Phytogenic Insolator from Thermal Expansion.

## Client Information
* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server
* Optifine Installed: False
* Shaders Enabled: False

**Comment by Sunekaer** [comment]
1.0.18
