### ISSUE TITLE
Item Duping

### ISSUE THREAD

**Issue by OverloadedWolf** [Sunekaer/stoneBlock#217]
## Bug Report
Items can dupe when grabbing a recipe in the refined storage wireless crafting grid.

## Steps to Reproduce (for bugs)
1. Open Wireless Crafting Grid
2. Shift-Click Recipe from JEI
3. Click X to send back to inventory
4. Notice Item is duped

## Client Information
* Modpack Version: 1.0.17
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by xILikepuddingx** [comment]
Its an issue of  Refined Storage Addon.But it is already known and has already been communicated to the mod creator. Its just in SP. MP works fine

**Comment by Sunekaer** [comment]
https://github.com/raoulvdberge/refinedstorageaddons/issues/38

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
