### ISSUE TITLE
Question: Should slimes spawn in slime chunks in Overworld

### ISSUE THREAD

**Issue by OfficialStamper** [Sunekaer/stoneBlock#218]
Having found a slime chunk, I am not experiencing any slimes spawning at level 40 or below.  Should slimes spawn or has this been disabled by the pack?

* Modpack Version:  1.0.16
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled:

**Comment by Sunekaer** [comment]
ill have to do some testing, but i haven't disabled it, but you can slime by other means

**Comment by OfficialStamper** [comment]
wanted to generate Botania Mana from slimes, which only works with natural spawned slimes, it will not work with other spawned means. That was the reason for my question.  Thanks for looking into it :)

**Comment by xILikepuddingx** [comment]
slimes are spawning https://screen.ilikepudding.de/4updn7bsqy.png

**Comment by OfficialStamper** [comment]
@xILikepuddingx that link does not work for me.  I have found a slime chunk in my world (server), but I am not getting any slimes spawning.  Can you explain how you are locating slimes please?  Thanks

**Comment by Sunekaer** [comment]
link works for me, and show that he has slime that has spawned

**Comment by OfficialStamper** [comment]
@Sunekaer yes, link works for me now too, thanks.

I see he is in an Ocean biome, and I assume its the overworld and not another dimension.  Can you confirm its server and not SSP?  

I have located slime chunks using the Botania 'Slime in a Bottle', but I am not getting slimes to spawn under normal MC mechanics (i.e below level 50)

**Comment by OfficialStamper** [comment]
My thanks to both of you @Sunekaer @xILikepuddingx , user error on my part, I had a Mega Torch in range of the chunks, doh.  I have closed the issue.
