### ISSUE TITLE
player dead when join server

### ISSUE THREAD

**Issue by Leaveleaf** [Sunekaer/stoneBlock#219]
player dead when join server. can remove the lava , Sorry, my English is very bad.
![tim 20180930201948](https://user-images.githubusercontent.com/19620848/46257545-442f2100-c4ee-11e8-82d0-b7e6ce79a182.png)

**Comment by Sunekaer** [comment]
Hey

Nothing i can do about this problem, its sadly happens sometimes on a server due to latency and lag, which is why you have the buffs
