### ISSUE TITLE
mob_grinding_utils Cause World Disconnect

### ISSUE THREAD

**Issue by joebb3** [Sunekaer/stoneBlock#22]
After placing the Mob Masher (10 each Sharpness, Luck and Beheading upgrades) and 2 Mob Fans (2 Range and 1 width upgrade), after a few minutes mobs freeze, interfaces are disabled and you cannot interact with mobs.  You can navigate the world and break blocks, but the blocks disappear.  Tried reloading the mod pack, using a backed up world, no joy.  Used MC Edit to remove the Masher and Fans and the world worked normally.  (Windows 10 Java Edition, Forge 14.23.4.2729, MCP 9,42, Latest Update to pack)

**Comment by Sunekaer** [comment]
tried to reproduce, and wasnt able to, sound like a mod bug, if you can get the log file and sent it to the mod owner
