### ISSUE TITLE
Crash Upon Loading New World

### ISSUE THREAD

**Issue by DarthSpaceLord** [Sunekaer/stoneBlock#220]
## Bug Report
Just downloaded StoneBlock, and it crashes the instant a world loads.

## Steps to Reproduce (for bugs)
1. Download Stoneblock. (I tried downloading again multiple times to no avail.)
2. Attempt to join a world.

## Logs
*Twitch Log: https://pastebin.com/p327MSAA

## Client Information
* Modpack Version: Latest, 1.0.17
* Server/LAN/Single Player: Single player, no LAN
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Delete scala-reflect in minecraft/install/libraries/org/scala-lang/scala-reflect/2.11.1

**Comment by DarthSpaceLord** [comment]
Delete the whole folder?

**Comment by DarthSpaceLord** [comment]
Whenever I delete it, it reappears when I try to open Twitch or StoneBlock from Twitch.

**Comment by Sunekaer** [comment]
yes delete and a new one will be create and that should fix the problem
