### ISSUE TITLE
Crashing after update

### ISSUE THREAD

**Issue by Skyburns** [Sunekaer/stoneBlock#222]
## Steps to Reproduce (for bugs)

1. updated to latest version through twitch
2.Crashes after selected the world from single player

## Logs

* Client/Server Log: 
* Crash Log: https://pastebin.com/48FygYSz

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: single player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by chajo10** [comment]
I had a very similar incident.  I updated to the most recent version on Twitch and now my game crashes each time I try to load.  Rolling back does not help either.

**Comment by Sunekaer** [comment]
i have heard that adding this mod https://minecraft.curseforge.com/projects/notenoughids might resolve your problem could you test that?
