### ISSUE TITLE
Angel ring and dragon armor by

### ISSUE THREAD

**Issue by Darkmift** [Sunekaer/stoneBlock#225]
The tiny progression dragon  armor does not provide night vision....so I rather use the Vision helmet by cyclic...however this breaks the full set so I cannot fly.
I figured I use the angel ring...but there seems to be a conflict preventing flight in such a manner. :(

I am not saying its a bug but if someone could address that I would be one happy camper :)

P.s. Love the mod! <3

**Comment by Revvilo** [comment]
It seems a bit odd to me that the angel ring wouldn't work... do you have enough of the Extra Utilities "Network Power" to support the ring?

**Comment by Sunekaer** [comment]
do you have grid power enough? are they loaded when you try to fly ?

**Comment by Denslat** [comment]
> 
> 
> do you have grid power enough? are they loaded when you try to fly ?

Can confirm issue, when only part of armor is equipped, angel ring will not work even with enough GP

**Comment by Sunekaer** [comment]
https://github.com/Kashdeya/Tiny-Progressions/issues/112

**Comment by Darkmift** [comment]
Got a ''few'' dragon eggs 😃

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
