### ISSUE TITLE
Players dcing after the server is running for a little bit and can't get back in

### ISSUE THREAD

**Issue by Magesw** [Sunekaer/stoneBlock#226]
## Bug Report
We have noticed that after the server has been up for a couple hours players start getting dced and can't log back in because it says their char is still in the game. I can use a /kick command on them but it seems to do nothing.

## Steps to Reproduce (for bugs)

1. We have a 30 slot server with 30 players connected just let it run and it happens. Running version 1.0.17
2. Not much else to reproduce this

## Logs

* Don't really have crash logs because it's not crashing.

## Client Information

* Modpack Version:1.0.17
* Server/LAN/Single Player:Dedicated server
* Optifine Installed:only if it came with the modpack
* Shaders Enabled:no

**Comment by Magesw** [comment]
To add to this, they are being disconnected but still show up as being in game using the /kick or /ban command seems to do nothing. It says it kicked or banned them but hitting tab still shows them in game and they still can't connect.

**Comment by xILikepuddingx** [comment]
Not a Problem of the Pack. The Problem comes with ur Server

**Comment by Magesw** [comment]
> Not a Problem of the Pack. The Problem comes with ur Server

What do you think that problem is? This server is an OC i7 7700K 64GB of RAM on 2x NVMe SSD's 1GB port guaranteed 500 up and down bandwidth and has ran  other MC servers, REND, ARK, Conan and Space Engineers without issues.

I even turned the firewall off to see if that was causing it and still same problem, so what do you think it is?

**Comment by Sunekaer** [comment]
what does it say in the console when they cant join, hows the TPS and the lag when it happens?

**Comment by Magesw** [comment]
![tps2](https://user-images.githubusercontent.com/13952888/46305724-1cc86a80-c567-11e8-8300-15998c95ad46.PNG)
![tps](https://user-images.githubusercontent.com/13952888/46305733-1fc35b00-c567-11e8-85f2-ae02272bd941.PNG)

**Comment by Magesw** [comment]
I will have to get the log sometime today when it happens to someone again.

**Comment by Magesw** [comment]
This is still an issue for us, player characters are not leaving the server when players get disconnected from it. Using /kick on them or /ban nothing works they are ghosts until server restarts.
