### ISSUE TITLE
Pack won't load

### ISSUE THREAD

**Issue by BrycethePsycho** [Sunekaer/stoneBlock#227]
I am unable to load the pack and thus unable to post a log for it. Whenever I go to launch it, i get the launcher up. but once I hit play, it says that it requires elements from an unsupported version.

Edit- I have tried using both types of the mc launcher and they both say the same thing for me.

**Comment by Sunekaer** [comment]
Use the template and add logs

**Comment by BrycethePsycho** [comment]
dude, how am i supposed to add logs when there are none to even add?
