### ISSUE TITLE
Unlimited lootbags

### ISSUE THREAD

**Issue by DeciTM** [Sunekaer/stoneBlock#228]
## Bug Report
You can take unlimited lootbags from the Bag Storage block.

## Steps to Reproduce (for bugs)

1. Right click the block to open its GUI.
2. Click the Cycle Bag button until an Epic Lootbag is displayed.
3. Instead of clicking the bag to remove it, hover over it with the mouse pointer and tap an open hotbar key slot. You'll notice the "Stored" value doesn't change.

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
https://github.com/Malorolam/LootBags/issues/155

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
