### ISSUE TITLE
Add more mid-game quests

### ISSUE THREAD

**Issue by Spyrox17** [Sunekaer/stoneBlock#229]
## Context

I'm at the point where I've completed practically everything but draconic and project E as per the quest book.
I'm suggesting to start on a new section for Immersive Engineering and possibly EnderIO, among other large mods without a part in the quests.

It just feels odd to be at this mid-point and still feel very far awar from ever even starting tasks like project E which requires an insane amount of materials. Perhaps, some quests that lead up to Project E or Draconic instead of just like "hey, make a transmutation table with just a few quests proceeding it".

It would be more immersive(haha, get it) if there were more quests for each required item for those extremely complicated items in draconic and Project E and elsewhere.

## Config/Script Details
Better Questing

**Comment by Sunekaer** [comment]
Mid game is blank for an reason, The quest in this pack is to help you get started, show you an little of what you can do, and what the end game items is, not to hold your happen through the game, the mid is completely up to how you want to play it
