### ISSUE TITLE
Create an Island Banner

### ISSUE THREAD

**Issue by joebb3** [Sunekaer/stoneBlock#23]
The "Create an island! /island for help" banner is persistent.  It won't go away.  I didn't "Create an island" because I spawned into the world ready to play (Single Player).  Now the banner just sits up at the top right of the screen and there's nothing I can do to get rid of it.  It blocks part of JEI and is a bother.

**Comment by Sunekaer** [comment]
main/pause menu->mod options->void island control->config->othersettings->hideToasts

**Comment by joebb3** [comment]
You are the best!  Thanks!
