### ISSUE TITLE
Game Crashed Everytime

### ISSUE THREAD

**Issue by Eziair** [Sunekaer/stoneBlock#236]
I hope I have all you need and are asking for.

StoneBlock via Twitch launcher
StoneBlock version: 1.0.17

I have tried to download the pack 10 times now, 5 times today alone. Each time the game installs fine and clicking the 'PLAY' button is ok but after the game loads and I create a new world all I get every time is - 

"GAME CRASH. It looks like you are using an unsupported modified version of the game. The game crashed whilst exception in server tick loop".

Each time I have installed/uninstalled before trying again but still the same comes up on my screen.

https://pastebin.com/0U4fGgvT
(hope I did that right)

* Modpack Version: StoneBlock version: 1.0.17
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

I have no extra mods in the pack.
I have other packs via the Twitch launcher and all work

**Comment by Sunekaer** [comment]
Delete scala-reflect in minecraft/install/libraries/org/scala-lang/scala-reflect/2.11.1 and try again

**Comment by Eziair** [comment]
That worked.

Thank you
