### ISSUE TITLE
Spawning issues on 1.0.17 Server

### ISSUE THREAD

**Issue by Y0ungSandwich** [Sunekaer/stoneBlock#237]
We started the server on 1.0.16 the other day with no spawning issues. We updated to 1.0.17 today and I was told that several new players were not generating their own "island" areas and a player had spawned at 0,0 and started his play-through before he realized new players were just spawning in his base and branching away to build. 

We DO run spongeforge, nucleus, and a permission plugin but even once I disabled all of these and deleted  player data people still continued to freshly spawn at the base at 0,0. I download a clean install locally and ran it with the same plugins above and tested with a few people and we all spawned at 1000 block increments as we are suppose to. So I have gathered that the spawn isn't some plugin spawn over ride. 

Generating new worlds fixes the issue but I rather not make everyone restart. Is this anything that you have seen yet? Could the base at 0,0 be throwing off the island generation?

**Comment by knoxhack** [comment]
To "fix" this change the config file voidislandcontrol.cfg and enable auto create islands.
The server files are set so new players first go to spawn and then from there they do /island create after reading the rules or whatever you have at spawn

**Comment by Y0ungSandwich** [comment]
`   # Automatically give new players islands
        B:autoCreate=true`

That one? Already true.

**Comment by Y0ungSandwich** [comment]
Alright so I loaded up the old world and tried /island create and it tells me Im not in a void world. 
yet server.properties: `level-type=voidworld`

**Comment by Y0ungSandwich** [comment]
Looks like it was a result of a server crash early this morning. Couldn't quite repair it fully so we rolled from a backup. Ill go through the crash report and see if its anything to report. Thanks.
