### ISSUE TITLE
item placeholder in better questing chest

### ISSUE THREAD

**Issue by Denslat** [Sunekaer/stoneBlock#238]
## Steps to Reproduce (for bugs)

1.Open better questing chest
2. get item https://imgur.com/a/SslII5U

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: single player
* Optifine Installed: 
* Shaders Enabled:

**Comment by xILikepuddingx** [comment]
if u had version 1.0.17 u need to type /bqs_loot default load
