### ISSUE TITLE
Lonsdaleite

### ISSUE THREAD

**Issue by hfreakmatze** [Sunekaer/stoneBlock#24]
there's no recipe to become lonsdaleite shards... have to make speed upgrades for the void ore miner that requires londaleite shards

**Comment by hfreakmatze** [comment]
thanks does it works for server too?

**Comment by Sunekaer** [comment]
it would have to be done server side too

**Comment by hfreakmatze** [comment]
ok i'll try it now

**Comment by hfreakmatze** [comment]
so it works now...thank you
