### ISSUE TITLE
Lag Spikes when opening inventories

### ISSUE THREAD

**Issue by Sekwah** [Sunekaer/stoneBlock#240]
## Bug Report
Lag Spikes (1-2s) when opening inventories. Not really a CPU/Memory limitation (don't see anything strange on Windows' task manager tracker nor MSI Afterburner). 

## Steps to Reproduce (for bugs)
1. Just open any inventory. 
[Video Link](https://youtu.be/f21uwABA3nU) (you can use Torch's animation to notice the spike)

## Client Information
* Modpack Version: 1.0.17
* Server/LAN/Single Player: SP
* Optifine Installed: No
* Shaders Enabled: No

No changes done to the pack, nothing strange in configuration (just a few rebinds and disabled auto-jump).

PC Specs:
I5 6600k @3.6Ghz
16Gb RAM (8Gb for Minecraft allocated using Twitch's Launcher, no Java parameters)
MSI GTX 970 (not really related)
Windows 10

I've found other packs saying that it's probably a NEI problem, but this pack doesn't have NEI so it seems to be another thing.

**Comment by Sunekaer** [comment]
weird, not an thing i can recreate, if you close JEI open your inventory and click ctrl + o, does it then also happens when opening inven?

**Comment by Sekwah** [comment]
I posted it in [reddit](https://www.reddit.com/r/feedthebeast/comments/9kuvng/several_packs_inventories_freezing_for_a_few_secs/) too, and an user told me that it was caused by Mouse Tweaks. Indeed, MT was the problem (also happens with Crafting Tweaks but only in crafting tables).

Disabled both and both problems were fixed, it has nothing to do with JEI. I really hope you can look for alternatives to change both mods so we can update the pack freely without needing to disable+reinstall other mods every time, since it seems i'm not the only one suffering from these specific mods.

The guy in the reddit thread suggested [Item Scroller](https://minecraft.curseforge.com/projects/item-scroller) as an alternative and it seems to be pretty much the same mod without the lag spikes.

**Comment by LemADEC** [comment]
As this been reported to MouseTweak already?

**Comment by Sekwah** [comment]
Reported it to MouseTweaks' Git yesterday, also has been reported in the past when using both Forge and LiteLoader, but since this pack isn't using liteloader i'm just trying different combinations of mods to see if i can find the one causing the problem

**Comment by Sunekaer** [comment]
https://github.com/YaLTeR/MouseTweaks/issues/12

**Comment by Sekwah** [comment]
Seems like indeed it was either a mod problem or a windows/forge config problem. The creator is going to release a new version which doesn't write back info to the disk which may solve the problem.
