### ISSUE TITLE
Freeze when placing compressed cobblestone

### ISSUE THREAD

**Issue by mtjohnson47** [Sunekaer/stoneBlock#241]
## Bug Report
Placing a compressed cobblestone with Fancy Block Animations enabled results in a frozen client.  And it seems sometimes even if it's not enabled if it previously was.

## Steps to Reproduce (for bugs)
1. Enable Fancy Block Animations
2. Place a Compressed Cobblestone block in the world

## Logs
* Client/Server Log: https://drive.google.com/file/d/1-anQaiEsczdXmFSWjxNJsMbSM6NxqCOU/view?usp=sharing (Log files are 70 MB)
* Crash Log: Crashes while generating crash log.

## Client Information
* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: Yes

**Comment by Sunekaer** [comment]
upload log to gist.github.com

**Comment by mtjohnson47** [comment]
I can't, Chrome crashes.

Latest.log is 29 MB, debug.log is 41 MB

**Comment by mtjohnson47** [comment]
I did find an exceptions menu, but it requires that the block be placed in the world to use.

**Comment by Sunekaer** [comment]
Sorry but I’m not downloading logs..
How much ram do you have assigned, and what’s your cpu usages at when you have this problem

**Comment by mtjohnson47** [comment]
5GB and normal 60-100%

**Comment by Enteerman** [comment]
Same Issue

**Comment by Sunekaer** [comment]
1.0.18
