### ISSUE TITLE
Game fails to load

### ISSUE THREAD

**Issue by JetFusion444** [Sunekaer/stoneBlock#242]
## Bug Report
I launch the modpack, it starts to load and will get about 15 seconds in and tell me im using an unsupported version of the game

## Steps to Reproduce (for bugs)

1.launch with twitch
2.

## Logs

* Client/Server Log:
* Crash Log:https://pastebin.com/GNqfLY7f

## Client Information

* Modpack Version:1.0.17
* Server/LAN/Single Player: single
* Optifine Installed:no
* Shaders Enabled:no

**Comment by Sunekaer** [comment]
try and go to Minecraft\Install\libraries\org and delete the folder called scala-lang and reinstall the pack
