### ISSUE TITLE
Game crash with Chickens/Hatchery

### ISSUE THREAD

**Issue by Jani442** [Sunekaer/stoneBlock#243]
## Bug Report
Game crashed giving a render error when trying to place a Red Chicken egg into a Nest from Hatchery.

## Steps to Reproduce (for bugs)
Placing a Red Chicken Egg (Chickens) into the Egg Nest (Hatchery) ends up in crashing the game and making the save unable to load.

## Logs
https://pastebin.com/8DgHi4eA

## Client Information
This happened while playing the Stoneblock 1.0.17 in single player. Unedited

**Comment by Jani442** [comment]
Well after sleeping over it and doing more research, this problem was caused by having too new versio of Forge installed. Problem came from the Chickens mod renders going bonkers with latest Forge

**Comment by dingsbums** [comment]
Same Problem here. 

How did you fix it? I tried downgrading forge but then ftblib wants version 2765.
