### ISSUE TITLE
Cannot craft BuildCraftBuilders:Builder

### ISSUE THREAD

**Issue by OfficialStamper** [Sunekaer/stoneBlock#245]
## Bug Report
The Builder for BuildCraft shows in JEI but there is no recipe for crafting

## Steps to Reproduce (for bugs)

1.  Open JEI, search Builder
2.  Click BC Builders: Builder and no recipe is displayed

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server
* Optifine Installed: N/A
* Shaders Enabled: N/A

**Comment by knoxhack** [comment]
When updating the server, did you updated the /scripts folder also?

**Comment by OfficialStamper** [comment]
Yes I did. Deleted old folder and unzipped the new

Which script could be the issue and I can check its contents are same as here on GitHub

**Comment by Sunekaer** [comment]
Hmm weird I’ll have to check when I get home if I have the same issue.. but we haven’t change nor removed the recipe and the mod wasn’t updated in last update

**Comment by Sunekaer** [comment]
so i just made an new modpack with only JEI and Buildcraft and there is no recipe for the builder

**Comment by Sunekaer** [comment]
"As shown by the builders recipe being removed in 7.99.15, the builder is not ready for survival (along with a few other things). The builder currently only 'properly' supports vanilla blocks and doesn't even support BC blocks themselves so don't expect it to work correctly."
