### ISSUE TITLE
Ftbu Chunk loading

### ISSUE THREAD

**Issue by Grynder01** [Sunekaer/stoneBlock#247]
Just wondering how I might increase the chunk load limit in Ftbu

All the documentation I have found seems to reference files that either I cant find or the info is out of date and the files dont exist in that form anymore

**Comment by Sunekaer** [comment]
https://github.com/LatvianModder/FTBUtilities/blob/master/guide/ranks/config/README.md

**Comment by Szmjuly** [comment]
https://github.com/LatvianModder/FTBUtilities/blob/master/guide/ranks/config/README.md

It says that the page cannot be found, is there anyway that I can see how to do this still? I am having an identical issue.
