### ISSUE TITLE
Recipes requiring specific potions such as growth crystal are not reading the potion metadata accepting any bottle of water/potion

### ISSUE THREAD

**Issue by Denslat** [Sunekaer/stoneBlock#248]
## Bug Report

First issue noticed: ender io conduits pulling all potion types out of brewery even with filter.
Second issue noticed: growth crystal tier 2 accepting potion of swiftness 2 (recipe needs Potion of swiftness 1) 
Tested to see if it would accept just awkward potion, it did.
 
## Steps to Reproduce (for bugs)

1. Bug report contains details.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: single player
* Optifine Installed:
* Shaders Enabled:

**Comment by Sunekaer** [comment]
First issue works fine for me with an basic item filter
Second issue fixed in dev

**Comment by Sunekaer** [comment]
1.0.18
