### ISSUE TITLE
Crash while crafting, extremly slow 'recipe lookups'

### ISSUE THREAD

**Issue by neoc666** [Sunekaer/stoneBlock#249]
## Bug Report
Game randomly crashed while I was crafting in a Tinker's Crafting Station. Also while using the station the game feels very laggy. In the logs you can see many instances of "Recipe registry plugin is slow" which probably has something to do with this. I changed some config settings, but I didn't add or remove any mods.

EDIT: Also quests weren't working anymore after the crash. I did "/bq_admin default load" as described on the curseforge page. Now they're working again, but progress is lost. Maybe you should warn about progress being lost with these commands.

## Steps to Reproduce (for bugs)
The crash is not reproducible (for now).

## Logs
The uncompressed log is >5MB. I won't paste that in plain text into a pastebin or gist (is that even possible?). I attached the ZIP. I don't see why this shouldn't work, apart from having to unzip a file it's no difference.

## Client Information
* Modpack Version: 1.0.17
* Server/LAN/Single Player: only single
* Optifine Installed: no
* Shaders Enabled: no
[2018-10-02-4.log.gz](https://github.com/Sunekaer/stoneBlock/files/2440655/2018-10-02-4.log.gz)

**Comment by Sunekaer** [comment]
That command doesn’t reset progress, as the quests was gone after your crash, the crash had corrupted something, and that’s why you lost the quest progress..
Please upload the log to Gist.github.com and link it

**Comment by neoc666** [comment]
As I said, the plain text of the log is >5MB. I didn't see an option to upload a binary to gist, and don't know if it's even possible to paste a file that big as plain text. It is attached here, above: https://github.com/Sunekaer/stoneBlock/files/2440655/2018-10-02-4.log.gz

I downloaded it and compared files, I can't see what's the problem with having it as an attachment here, apart from not being able to view the text in the browser.

**Comment by Sunekaer** [comment]
you can copy paste it to gist

**Comment by neoc666** [comment]
You can click the link above.

**Comment by neoc666** [comment]
Wow, you're a true professional. Releasing this alpha trash as "R", then bitching about people who file bug reports.

**Comment by Sunekaer** [comment]
it said when you created the issue "No logs, not in Pastebin/ gist = Closing, and Ignoring the issue!" and i asked you to do it 2 times

**Comment by neoc666** [comment]
And I called this bitching. You didn't explain why this is essential - I would have done this if I knew why. Without a reason it's just an arbitrary barrier.
