### ISSUE TITLE
[1.0.17] Old Dank Mod causes Crash when Player stores non-placeable items in it

### ISSUE THREAD

**Issue by kreezxil** [Sunekaer/stoneBlock#250]
## Bug Report

Players that are using /dank/null to store massive quantities of material experience a can't log on bug when they store non-placeable items in the device.

## Steps to Reproduce (for bugs)

1. get /dank/null
2. put items in it that can't placed into the world like a pick axe for instance
3. quit and try to relog

## Logs

We're running version 1.0.17 of the server pack and client. We've reported already to the dev of /dank/null and he responded with that he thinks the mod is running on old code. https://github.com/p455w0rd/DankNull/issues/134#issuecomment-426316995

* Modpack Version: 1.0.17

According to the version for this device you are indeed running old code. 
![screenshot_1](https://user-images.githubusercontent.com/3880072/46408152-c843fd00-c6d6-11e8-8879-67d603081ef4.png)

**Comment by Sunekaer** [comment]
old and old, the two newer versions has been release within the last 5 days...

**Comment by xILikepuddingx** [comment]
no words....
1.0.17 came on the 21st sep ....
the 2 new version of Dank / null came on 29.09.2018 and 01.10.2018

**Comment by Sunekaer** [comment]
1.0.18
