### ISSUE TITLE
Potion Wand doesn't function.

### ISSUE THREAD

**Issue by xkatsuro** [Sunekaer/stoneBlock#251]
## Bug Report

When crafting a potion wand with a potion, it won't let apply the potion's effect on it. Any potion, that is.

## Steps to Reproduce (for bugs)

1. Simply try crafting a potion wand in a crafting bench with a desired potion. Either empty or charged.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: SP
* Optifine Installed: yes
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
https://github.com/romelo333/notenoughwands/issues/83

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
