### ISSUE TITLE
Spectre Trees and  IFG's plant gatherer don't get along.

### ISSUE THREAD

**Issue by xkatsuro** [Sunekaer/stoneBlock#252]
## Bug Report

Plant Gatherer from Industrial Foregoing won't gather any ectoplasm from spectre trees.
## Steps to Reproduce (for bugs)

1. Harvest a spectre tree with IFG's plant gatherer.
2.

 It is weird, that spectre trees are the only one's that aren't working with any kind of automation. Neither with Thermal Expansion nor with Bonsai Pots. Even semi-manual means of harvesting are not an option, like letting IFG's machine harvest and replanting sapling yourself without any dramatic loss.
## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: SP
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by mine3500** [comment]
well i use a custom file that let bonsai work with spectre trees it takes awhile to get spectre but not as much as letting it grow manually

**Comment by xkatsuro** [comment]
> well i use a custom file that let bonsai work with spectre trees it takes awhile to get ectoplams but not as much as letting it grow manually

can you point me in a direction of that file? I'd like to have that option as well and thank you in advance!

**Comment by mine3500** [comment]
Here is the link of the Bonsai Github Scroll down until you see Xemnes-Keyethkateth comment i would put a link to the file but it automatically download its
https://github.com/thraaawn/BonsaiTrees/issues/22

**Comment by Sunekaer** [comment]
Adding spectra tree for bonsai

**Comment by mine3500** [comment]
ty

**Comment by Sunekaer** [comment]
1.0.18
