### ISSUE TITLE
Crafting bug: Magma suit requires, unable to craft, mod specific emerald suit

### ISSUE THREAD

**Issue by TheFlie01** [Sunekaer/stoneBlock#253]
When crafting the magma suit (Helmet, Chestplate, Legging and Boots), you need the emerald suit first. the problem is that when you craft the emerald suit, it belongs to the mod 'Actually additions'. The recipes for the magma suit require you to have the emerald suit made from 'Tiny Progressions'.

Please add the emerald suit of 'Actually additions' to the magma suit recipes.

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by xILikepuddingx** [comment]
Use the forestry worktable. https://screen.ilikepudding.de/edau2ehpq0.png

**Comment by Sunekaer** [comment]
1.0.18
