### ISSUE TITLE
Dupe glitch any item!!

### ISSUE THREAD

**Issue by misshaptat** [Sunekaer/stoneBlock#255]
so this works on any version of the pack, you take the butter fingers potion, either from the a chance from the giant chance cube or make it your self!!  clear out your hot bar place the one item of any kinda in your hot bar use potion of butter fingers walk or run around while pressing either 1 and 2 on short cut of key board or use the scroll mouse!!

**Comment by xILikepuddingx** [comment]
i removed the potion. i hope @Sunekaer add it

**Comment by Sunekaer** [comment]
1.0.18
