### ISSUE TITLE
Refined Storage Duplication glitch

### ISSUE THREAD

**Issue by tootiecornet4** [Sunekaer/stoneBlock#256]
## Bug Report
When using the Wireless Crafting Grid, then placing an item in to the crafting grid and pressing the "clear" button to remove the item from the grid, it will duplicate that item, then place both the duped item and the original in the storage system.

## Steps to Reproduce (for bugs)
1. Empty Crafting Grid is here as you can see.
![crafting grid empty](https://user-images.githubusercontent.com/24525585/46508478-a0b77680-c835-11e8-82f2-93d33d366f47.jpg)
2. I place One Red Matter into the crafting grid, note that there are none in the system.
![red matter dupe start](https://user-images.githubusercontent.com/24525585/46508614-26d3bd00-c836-11e8-8729-0d79ef908e9e.jpg)
3. I click on the "clear" button and it will duplicate that item. I have tested with multiple items and it can work for any item, stackable, non-stackable, if has item with a retainable inventory can be duped, and if it still retains its inventory after the dupe, such as a draconic fusion crafting injector and it does. 
![red matter dupe end](https://user-images.githubusercontent.com/24525585/46508618-29cead80-c836-11e8-9cd0-2dce9fdd91ae.jpg)

## Logs
* Client/Server Log:
* Crash Log: N/A
* Optifine Installed: None
* Shaders Enabled: None

## Client Information
* Modpack Version: 1.017
* Server/LAN/Single Player: Singleplayer/LAN - tested LAN also and it does work consistantly.

**Comment by Sunekaer** [comment]
https://github.com/raoulvdberge/refinedstorageaddons/issues/38

**Comment by krisavi** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/2024

**Comment by krisavi** [comment]
Tested with minimal setup
Refined Storage 1.6.5
Refined Storage Addons 0.4.2
Forge 14.23.5.2768
FML 8.0.99.99
MCP 9.42
MC 1.12.2

Issue seems to be only with wireless terminal so in Refined Storage Addons issue actually

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
