### ISSUE TITLE
Server Files Incorrect

### ISSUE THREAD

**Issue by BrandonGamesYT** [Sunekaer/stoneBlock#257]
## Server Report
After Downloading server files from GitHub, The server opens up as a normal world instead of the stone world

Steps to Reproduce 
1. Download Sever files (Posted on the GitHub page "https://minecraft.curseforge.com/projects/stoneblock"
2.

Logs
* Client/Server Log: 
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2448674/latest.log)

* Crash Log:

Client Information
* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server
* Optifine Installed:
* Shaders Enabled:

Thanks for any help.

**Comment by Sunekaer** [comment]
Did you read that curse page? It also says to change your world type(level-type) to voidworld

**Comment by BrandonGamesYT** [comment]
@Sunekaer Thats not exactly easy to do when its a server, and from what i could find, nothing online tells you how.

**Comment by Sunekaer** [comment]
server.properties
