### ISSUE TITLE
Game Crash on World Gen 

### ISSUE THREAD

**Issue by Cori1989** [Sunekaer/stoneBlock#258]
## Steps to Reproduce (for bugs)

1. Load up Game
2. Start New World
3. Wait for World Load up (Then it crashes)

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/tLtYbqWk

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Delete scala-reflect in minecraft/install/libraries/org/scala-lang/scala-reflect/2.11.1
