### ISSUE TITLE
EvilCraft progress blocked by Environmental Accumulation Core

### ISSUE THREAD

**Issue by wcdanh2** [Sunekaer/stoneBlock#259]
The "Evilcraft" Sanguinary Environmental accumulator requires an Environmental Accumulation Core.  The core is normally obtained by breaking an Environmental Accumulator found via world gen.

So far I have not found a way to obtain the Core.

Suggestion: add a crafting recipe for the Environmental Accumulation core, or add it to a loot-bag.

Thanks.

**Comment by Sunekaer** [comment]
reipce added

**Comment by Sunekaer** [comment]
1.0.18
