### ISSUE TITLE
Infinite Loot

### ISSUE THREAD

**Issue by NinjaTroiiX** [Sunekaer/stoneBlock#26]
Using the loot bag storage block, you can open a loot bag and pull loot you want out, and leave at least 1 item in it, put it in the storage, and pull back out a brand new loot bag with new loot without using up any additional loot bag points. This can be used to get infinite of many items.  

Edit: appears this simple just requires a config change. "Prevent Merging Opened Bags"=false Needs to be changed to "Prevent Merging Opened Bags"=true unless this was left enabled on purpose

**Comment by Sunekaer** [comment]
ty
