### ISSUE TITLE
Flux point/plug duplication

### ISSUE THREAD

**Issue by SirPeugas** [Sunekaer/stoneBlock#265]
## Bug Report
Flux point/plug duplication

## Steps to Reproduce (for bugs)

1. if you use a moving wand in a flux point or a flux plug it will drop the item and still store the "real one". so if you spam right click it keeps duplicating the plugs/points
2.

## Logs
i attached the log folder

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no
[2018-10-05-1.log.gz](https://github.com/Sunekaer/stoneBlock/files/2451916/2018-10-05-1.log.gz)

**Comment by Sunekaer** [comment]
1.0.18
