### ISSUE TITLE
Enchantment Table clear Bag Inventory

### ISSUE THREAD

**Issue by Kratzwurst** [Sunekaer/stoneBlock#266]
Hello all

I Crafting the Bag Pouch (Tiny Progressions) and i want it to Soulbound Entchantment on this Bag. 
After this attempt, i show in the Bag and i lost the Bag Invetory directly.

## Steps to Reproduce (for bugs)

1. Creating the Bag Pouch
2. Fill up with Items
3. All Items to see
3. Want it to Enchantment Soulbound
4. See it does not work
5. Look in the Bag and lost all Items in this Bag Pouch
## Logs
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2452647/latest.log)

## Client Information

* Modpack Version: 1.0.17
* Mod Version:  tinyprogressions-1.12.2.-.3.3.3.1
* Server/LAN/Single Player: SP
* Optifine Installed: YES OptiFine_1.12.2_HD_U_E2
* Shaders Enabled: NO

Greetings

**Comment by xILikepuddingx** [comment]
i dont think its a bug. u change the item. item change --> all saved items are gone its the same with, for example: u ugrade ur wyvern bow with enchants --> all enchants are gone

**Comment by Kratzwurst** [comment]
If I put the bag in the enchanting table without lapis, the parts still disappear in the bag, without trying to change it.

**Comment by Kratzwurst** [comment]
Okay can here be closed. Thanks.
