### ISSUE TITLE
Not Being able to join my own Server

### ISSUE THREAD

**Issue by BrandonGamesYT** [Sunekaer/stoneBlock#267]
Well, I started a server where my friends can join, the only problem is that I can't join my server.

## Steps to Reproduce (for bugs)
1. Load Server files 
2. Try joining through multiplayer (My Server)
![image](https://user-images.githubusercontent.com/26289988/46567808-982b7280-c8ff-11e8-9547-26352d5b72d2.png)
![image](https://user-images.githubusercontent.com/26289988/46567815-b8f3c800-c8ff-11e8-88db-101d9ad42afe.png)

## Logs
* Client/Server Log:
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2452769/latest.log)

* Crash Log:

## Client Information
* Modpack Version: 1.0.17
* Server/LAN/Single Player:  Server
* Optifine Installed: 
* Shaders Enabled:

**Comment by BrandonGamesYT** [comment]
Some new Error that came in, Soon after, The Server closed on itself.
[00:58:23] [VoiceServer Listen Thread/INFO] [Mekanism]: VoiceServer: Accepted new connection.
[00:58:28] [Thread-107/ERROR] [Mekanism]: VoiceServer: Unable to trace connection's IP address.

**Comment by Kratzwurst** [comment]
Check and Change: 

- Router and Firewall for Port (Server) is sharing, when not enabled
- Lock at your eula.txt and change it to true
- Lock it at server.properties  server-port= your port, server-ip=your IP or Network IP
- Forge it's the same Version at yout client
- Is the Server on Java 8 installed?

**Comment by BrandonGamesYT** [comment]
All good, i was able to join first time without a problem, then the server crashed and now i am no longer even able to load my server

**Comment by Kratzwurst** [comment]
You have it reinstalled ?

**Comment by BrandonGamesYT** [comment]
Yes, I've tried that also

**Comment by Kratzwurst** [comment]
Okay that here was my last Idea: https://www.minecraftforum.net/forums/support/server-support-and/2919008-solved-io-netty-channel-abstractchannel

**Comment by BrandonGamesYT** [comment]
Sadly also doesn't work, just tried and everything is fine, wouldn't think that would matter tho because others can connect to my server but i cant

**Comment by BrandonGamesYT** [comment]
Just did that, right now it is working for the first time so hoping it stays that way, thank you for the help!

**Comment by Kratzwurst** [comment]
no problem, you're welcome
