### ISSUE TITLE
Recipe for RS silicon in Mekanism Crusher is huge bait

### ISSUE THREAD

**Issue by DerpityDoo** [Sunekaer/stoneBlock#268]
I think all the info you need about this is in the title. I didn't bother testing the actual output of crushing sand, so I set up a handful of machines and was very surprised to receive dust instead. Seems like automated silicon is gated behind either chickens or mystical agriculture. Definitely gave me blue balls

**Comment by Sunekaer** [comment]
Mekanism Crusher is already reported as a bug, you can get silicon from clay, i am looking at other ways to make silicon
