### ISSUE TITLE
Double Compressed Diamond Hammer not working

### ISSUE THREAD

**Issue by 5hqdow** [Sunekaer/stoneBlock#269]
## Bug Report

the hammer is not at all working. It cannot mine anything. It is not even functioning as a tool to mine with, it cant even mine stone to get cobblestone. 
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player:Single Player
* Optifine Installed:no
* Shaders Enabled:no

**Comment by Sunekaer** [comment]
Did your read the tool tip? "Tinkers Construct Modifier" its an modifier you put on an tinkers tool and then it works like an hammer
