### ISSUE TITLE
Reactor parts not accepting yellorium, please fix :P

### ISSUE THREAD

**Issue by Darknesscafted** [Sunekaer/stoneBlock#27]
at the moment. i use yellorium seeds to get yellorium. however reactor parts are only accepting uranium/refined uranium. however yellorium does work as a fuel. it would be great if a config change could me made to either 
1. convert yellorium to uranium with a crafting recipe
2. modify recipies to have reactor parts accept yellorium
3. have yellorium and uranium have the same ore dictionary. which will also work for 2.^^
please fix/modify

**Comment by Sunekaer** [comment]
Convert recipe added
