### ISSUE TITLE
Unable to Join Servers

### ISSUE THREAD

**Issue by fishynuts** [Sunekaer/stoneBlock#270]
## Bug Report
Attempt to join servers shows "Disconnected" error message

## Steps to Reproduce (for bugs)
1. Try to join any server running Stoneblock
2. The screen looks as if it is loading the world and then you will able to see the server for a brief second before it shows an error. It is usually just "Disconnected " but there are been a wide range of others.

## Logs
This is what the logs shows from the second I click to join the server to the moment it shows me the error https://pastebin.com/JwR9pUJZ

## Client Information
* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled:No
I am using a MacOS running High Sierra

**Comment by Sunekaer** [comment]
The log doesnt say anything about why you get that
pretty hard to tell why happens, it can be the game, server, internet connection, router, it can be so many things causing it

**Comment by codydbgt** [comment]
this is a ram issue i had the same issue u need 5gb of ram :) min when u join a server it loads more things in to the ram

**Comment by fishynuts** [comment]
I have allocated 6gb of RAM do I need to lower it?

**Comment by PlacidK** [comment]
Ehrm..... how about this:
[15:56:21] [Netty Client IO #4/INFO] [FML]: Attempting connection with missing mods [foamfixcore, betterthanbunnies, betterthanllamas, clienttweaks, controlling, craftpresence, ctgui, ctm, custommainmenu, defaultoptions, fbp, foamfix, fw, googlyeyes, jehc, modnametooltip, moreoverlays, mousetweaks, neat, norecipebook, oldjava, resourceloader, toastcontrol, reauth] at SERVER

**Comment by Sunekaer** [comment]
thats not the problem PlacidK
From the log you linked if shows that you was connected to the server and this was sent to you in chat "You haven't joined or created a team yet! [Click Here] to open TeamsGUI or [Click Here] to hide this message." it doesnt say why you got disconnected, youll have to contact the server staff of the server your trying to connect to and get them to tell you, why you get disconnected it should say it in the server-console or log when you get disconnected

**Comment by fishynuts** [comment]
But it happens on all servers
