### ISSUE TITLE
Chance cube fluids cause lag and crash. Backup save required to work around.

### ISSUE THREAD

**Issue by CDArena** [Sunekaer/stoneBlock#273]
## Bug Report

Chance cube related crash: glass ball of various fluids was created by a chance cube. After cracking it open and bucketing out various liquids, some of the floating liquids came out and went skywards; unfortunately this happened in a dome with a large vent open to y=255. Lag ensued from the "floaty" liquids and the game crashed. I had to revert to an old backup save, which thankfully is running.

Chance cube events which can cause a fatal crash like that.. well they suck. If I can find a config for the chance cubes and figure out which one it is, I'll try to disable it myself. In the mean time, beware...  If I knew it was going to happen I would simply use a RF Tools builder to overwrite the glass ball with cobblestone and then mine it. But once it does happen you cant get back into the game without reverting to an earlier save.

## Steps to Reproduce (for bugs)

1. Kind of tricky: pop chance cubes until you get a glass ball of mixed fluids. create a 9x9 vent going all the way above it to y=255. Remove the top of it and bucket out fluids on top if necessary to allow the floaty liquids to flow upwards. 
2. Enjoy the lag.

## Logs

* Client/Server Log:
* Crash Log: (I'd paste a copy but its jsut a huge file full of "at net.minecraftforge.fluids.BlockFluidBase.getFogColor(BlockFluidBase.java:773)
", which is not in the least bit surprising, since it lagged then locked up after trying to float liquids for a few minutes

## Client Information

* Modpack Version: 1.0.17?
* Server/LAN/Single Player:  Single Player
* Optifine Installed: No?
* Shaders Enabled: No?

**Comment by Sunekaer** [comment]
i have disabled some chance cube rewards now, but im not sure if this one is one of them

**Comment by Sunekaer** [comment]
1.0.18
