### ISSUE TITLE
Duplicate recipes

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [Sunekaer/stoneBlock#275]
## Bug Report

Dupilcate recipes for dough and cow bait. Using 2 wheat, place them beside each other in a crafting table, you get cow bait. That recipe is also valid for dough, there is no option to get dough.
## Steps to Reproduce (for bugs)

1.Using 2 wheat, place them beside each other in a crafting table, you get cow bait. That recipe is also valid for dough, there is no option to get dough.

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Multiplayer Server
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
1.0.18
