### ISSUE TITLE
Game Crash when viewing Draconium info.

### ISSUE THREAD

**Issue by KusanagiRyu** [Sunekaer/stoneBlock#277]
## Bug Report
 Game Crash when viewing Draconium info in the Draconic Evolution Information Tablet. Game crash error message: Ingredient rendering issue.

## Steps to Reproduce (for bugs)

1. Open Draconic Evolution Information Tablet.
2. Click on Draconic Evolution
3. Click on Draconium (Crash immediately)

## Logs

* Client/Server Log: N/A
* Crash Log: https://pastebin.com/DCdezxKt

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
https://github.com/brandon3055/Draconic-Evolution/issues/1094

Optifine bug
