### ISSUE TITLE
game not launching

### ISSUE THREAD

**Issue by gtxjgk** [Sunekaer/stoneBlock#284]
**Bug Report**

**_Steps to Reproduce (for bugs)_**
1.try launching minecraft

**LOGS**

https://pastebin.com/h0HQwi3M

https://pastebin.com/HGVsiMvW

**Client Information**

Modpack Version: 1.0.17
Server/LAN/Single Player:
Optifine Installed:
Shaders Enabled:

**Comment by gtxjgk** [comment]
there were only

latest.log

debug.log  

which i posted

sorry for bad english

**Comment by gtxjgk** [comment]
https://pastebin.com/VSQTgXNm

**Comment by Sunekaer** [comment]
if the game crashed you should have a folder called crash-report (Minecraft\Instances\StoneBlock\crash-report)

**Comment by knoxhack** [comment]
Is this on a servee or client? That info could have helped a alot
