### ISSUE TITLE
Barley seed recipe - Pam's harvestCraft

### ISSUE THREAD

**Issue by Darkmift** [Sunekaer/stoneBlock#285]
## Bug Report
There seems to be a recipe conflict between barley seed(pamm's harvestcraft) and barley flour (natura)

## Steps to Reproduce (for bugs)
1.try crafting and only flour is possible not seed

## Client Information

* Modpack Version: 1.0.17
* Single Player.

**Comment by Sunekaer** [comment]
1.0.18
