### ISSUE TITLE
Mods not being downloaded in the mod pack.

### ISSUE THREAD

**Issue by Simones112** [Sunekaer/stoneBlock#287]
I downloaded the mod pack stoneblock from curse over **5** times but everytime I check to copy paste it in my minecraft folder, there are **no mods** in the mods folder from the mod pack. Help!

All I did was downloading the mod pack from curse but no **mods were downloaded**.

Modpack Version: stoneBlock-1.0.17.zip
Server/LAN/Single Player: Singleplayer
Optifine Installed: No.
Shaders Enabled: I don't have any.

**Comment by Sunekaer** [comment]
The zip file you download from curse you are supposed to import in the twitch launcher and then it will download the mods from curse it self
