### ISSUE TITLE
Server Spawning in overworld despite level-type=voidworld

### ISSUE THREAD

**Issue by SpoonsRattling** [Sunekaer/stoneBlock#288]
## Bug Report
despite switching level-type from DEFAULT to voidworld, it spawns me in the overworld for no reason.

## Steps to Reproduce (for bugs)
1. extract
2. accept eula (as usual)
3. start server (minecraft_server.1.12.2.jar)
4. switch level-type to voidworld
5. delete world
6. restart server, then join

spawns me in overworld.
## Logs

* Client/Server Log: https://pastebin.com/gfSK9NX1
* Crash Log:

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

**i'm sorry for being 234234234234 person to make an issue for this, but i've made the change and tried multiple things to no avail. 

thank you very much for your help.

**Comment by ArbitraryHubris** [comment]
can you pastebin your server.properties file here?

**Comment by ArbitraryHubris** [comment]
Your server.properties file looks right, but your log doesn't look right at all.  

Ah, now it makes sense.  you need to start the forge jar, not minecraft_server.  Are you using the LaunchServer.sh or LaunchServer.bat file to start it?  

You're starting vanilla minecraft

**Comment by SpoonsRattling** [comment]
i was using minecraft_server from all points. do i start forge for every part? even after a fresh extraction?

**Comment by ArbitraryHubris** [comment]
when running a server, you always start the forge jar and it sets things up and then it starts the minecraft server jar.  What do you mean, "from all points"?

**Comment by Sunekaer** [comment]
Did you delete your world after changing level-type?

**Comment by SpoonsRattling** [comment]
i did infact do that, tp which it said it started a "default world type", but still gave me mod related things in the chat (upon joining the server) then had WAILA working properly, so it wasn't loading a vanilla world.

**Comment by Sunekaer** [comment]
Could you try again, turn off the server, delete the world folder, make sure level type is correct and start the via the script 
Just to make sure your didn’t change the of name of the jar in the script correct?

**Comment by SpoonsRattling** [comment]
i did not change that. the only thing i changed was the level-type to voidworld, then deleted the world and restarted. i will do it via the script this time.
