### ISSUE TITLE
No recipes for fused quartz

### ISSUE THREAD

**Issue by Denubis** [Sunekaer/stoneBlock#289]
## Bug Report

There are no routes to getting normal fused quartz to build the pressurized fluid conduit. While the pressurised tank accepts hardened glass, the conduit does not. There are no recipes to build normal fused quartz. (The "expected" recipe creates silicon instead)

## Steps to Reproduce (for bugs)

1. Try to craft a pressurised fluid conduit. 
2. Try to craft fused quartz for the conduit.
3. No recipes exist to create normal fused quartz.

## Logs

* Client/Server Log: https://gist.github.com/Denubis/f9c3ff494f29cb30e9b809dcaa09fbc3
* Crash Log: Not a crash. Recipe issue

## Client Information

* Modpack Version: 1.0.017
* Server/LAN/Single Player: Single player
* Optifine Installed: Default (so probably not?)
* Shaders Enabled: No

**Comment by ArbitraryHubris** [comment]
You're right that it doesn't appear in JEI, but just plop 4 quartz in an alloy smelter and you get one fused quartz.

**Comment by Denubis** [comment]
Huh. I thought I tested that. Looks like there's an odd conflict with 1 quartz -> silicon, and 4 quartz -> fused. Just tested and you're right. 

Testing: 
4 -> fused quartz (Ah. I was looking on the wiki and putting in *3* not 4)
1-3 -> silicon
8 -> fused quartz
9 -> 8 -> fused quartz, 1-> silicon.

Ok, I think I see the logic it's using. Thanks for your help. (Is there an alternate silicon recipe to enable, since this *also* means that more than 3 silicon in a Ender smelter gets fused quartz? Or is this a "Don't use EnderIO for large silicon processing?)

**Comment by ArbitraryHubris** [comment]
I keep my alloy smelter on "furnace only" so this doesn't happen when I'm processing ores.  Then I switch it over to "alloy only" when I need to make vibrant alloy, or fused quartz, and then right back to "furnace only".

**Comment by Sunekaer** [comment]
could you try pack version 1.0.19 and test?

**Comment by Denubis** [comment]
![screenshot from 2018-10-10 17-42-16](https://user-images.githubusercontent.com/243503/46717504-f4054b00-ccb3-11e8-8a91-983188276428.png)

I confirm that the problem still persists in 1.0.19. 

In furnace mode, it makes only silicon. In others, with 4, it makes fused quartz. Recipe doesn't show (As well as the recipe for the reservoir, somehow).

**Comment by Sunekaer** [comment]
That is very weird because it show for me in single player and on my dev server

**Comment by Sunekaer** [comment]
"white" is original Fused Quartz if that what you mean

**Comment by Denubis** [comment]
... Oh. Ok, so it's just a user expectations problem. Any comments on the reservoir? https://ftb.gamepedia.com/Reservoir_(Ender_IO)

**Comment by Sunekaer** [comment]
Well the recipe still works, but why it isnt showing i do not know

**Comment by Sunekaer** [comment]
ah it have gotten a new name Endervoir
