### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by blumunch** [Sunekaer/stoneBlock#29]
I added Item conduits to a Solderer  (top and bottom) and attached chests and now my game will not load correctly. I can log in but cannot do anything. Mobs don't spawn, chests cannot open. If I destroy the Item Conduits and reload after the crash the game goes back to how it was before it crashed.

https://pastebin.com/PescfTrE

**Comment by Sunekaer** [comment]
full log please

**Comment by blumunch** [comment]
pastabin is the log when i crash
