### ISSUE TITLE
Why is forestry in the pack and so disabled?

### ISSUE THREAD

**Issue by ArbitraryHubris** [Sunekaer/stoneBlock#290]
I have a theory that forestry is included because it will someday be enabled and made part of the pack, and maybe the quests as well.  As it is now, bees and trees are disabled in the configs and could be whitelisted for the mining dimension.  Also, apatite doesn't appear as an ore and is not in the config so you can't even make good use of the farming system.  

If it is not disabled with an eye toward re-enabling later, it should probably be removed from the pack.   Personally, I would definitely be breeding bees and trees and making ethanol were it not so decisively unusable.  

Please don't take this as an upset complaint.  It's not.  There's plenty to do and I'm enjoying the pack.  Just looking for a little clarity.

**Comment by Valericoe** [comment]
It's enabled in 1.0.18. Not sure about earlier versions though.

**Comment by ArbitraryHubris** [comment]
good to know.  I'm using 1.0.17.  Thanks @Valericoe

**Comment by ArbitraryHubris** [comment]
It's still disabled in 1.0.18.  No generation of beehives, trees, villagers, etc.

**Comment by Sunekaer** [comment]
Sorry I forgot about those I’ll try and get that fix in the next version

**Comment by xILikepuddingx** [comment]
I can maybe help u Ive an idea

**Comment by Sunekaer** [comment]
2c050078edbe54d169bfe1ad56b57670a84a34ac

**Comment by ArbitraryHubris** [comment]
@Sunekaer please see the comment on your commit.  Apatite will still be unavailable

**Comment by Sunekaer** [comment]
my bad forgot that one

**Comment by Sunekaer** [comment]
there

**Comment by ArbitraryHubris** [comment]
it doesn't seem to work.  no trees, hives, villagers so far in a fresh mining world dimension.  In a couple of hours, I'll be home and will play with it.  I'm wondering if blacklist and whitelist conflict with each other.

**Comment by gwpantazes** [comment]
I'm not sure if this is directly related to this exact issue or only related because it's also Forestry, but I filed [Charcoal Pit causes increasing memory usage until the game freezes/crashes #2264](https://github.com/ForestryMC/ForestryMC/issues/2264) over in Forestry. I think that this ticket might be a possible cause for that ticket though.

Is the Forestry Charcoal pit crashing in Stoneblock a known issue? I can copy the issue from Forestry over to here, since I cross checked against FTB Revelation and it didn't crash (as mentioned in the issue comments).

**Comment by ArbitraryHubris** [comment]
update: I changed the aroma config to replace dirt filler with stone and grass top layer with stone so I could see oregen.  apatite is generated.  Also, villages sometimes have forestry houses with bee houses.  

There are no trees generated and no hives generated.  Somehow, all the mods 3 was able to get forestry trees to gen in the mining dimension. their forestry config doesn't explain this.  But, that pack does not have hives generated.  I'm pretty sure that's because forestry uses biomes to decide which type of hive to create and we only have the miningBiome biome in the mining dimension.

So, if someone really wants bees, they can travel finding villages and get some queen bees.  The only problem is that there are no drone bees.  I'm just not sure if we can make this work.  

Maybe we don't need to whitelist and blacklist dimensions - no hives will generate in the overworld, because there is no grass or generated trees for them to spawn on/under.  though, rocky bees might spawn in the stone, which doesn't seem so bad.  I'm bringing this up, because I think the solution is rftools dimensions.  If you make a dimension with vanilla biomes, I think you'll get beehive generation.

**Comment by Sunekaer** [comment]
oh right you have to sure the scoop for collecting the bees

**Comment by Sunekaer** [comment]
Okay i got the hives to kind spawn 
![2018-10-09_15 22 27](https://user-images.githubusercontent.com/18720460/46677089-30687680-cbe2-11e8-86dd-02c4168a6100.png)

**Comment by Sunekaer** [comment]
still trying to get the sapling to working sifting

**Comment by Sunekaer** [comment]
okay so i just uploaded version 1.0.19
with villagers, Apatite and Beehives in mining dim fix, im still working on getting the sapling to work as drop from sifting

**Comment by ArbitraryHubris** [comment]
The worldgen looks good!  We need one mod added: JEI Bees, by bdew.  It adds breeding info on trees, bees, and butterflies to JEI.  Crucial information.

**Comment by knoxhack** [comment]
Fixed in 1.0.21
