### ISSUE TITLE
Save file crashes with update 1.0.18

### ISSUE THREAD

**Issue by Ravalli03** [Sunekaer/stoneBlock#292]
## Bug Report

Downloaded new update, game runs for 2 sec and crashes.

## Steps to Reproduce (for bugs)

1. Updated game
2. Tried to run 3 times and crashes once in world for 2 sec. everytime 

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/gCPvG65u

## Client Information

* Modpack Version: 1.0.18
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Ravalli03** [comment]
I downgraded Iron Chest Mod, and save now runs without issue

**Comment by Sunekaer** [comment]
That’s interesting, i don’t have that problem on my dev server

**Comment by Ravalli03** [comment]
Is this something on my end? I don't know anything about crash logs and how to read them, I just took a guess as it said something about the iron chest mod causing an issue and I noticed the mod was updated in 1.0.18.

**Comment by Ravalli03** [comment]
I got another crash about 2 hours into playing, not sure if related, now world won't even load.

Crash log after a few hours of play>>>>https://pastebin.com/pUCNJkS7

Crash log after trying to reload>>>> https://pastebin.com/CUhdRH0b

**Comment by Sunekaer** [comment]
Spectre Coil at -981,81,-988 causing the crash on load

**Comment by Sunekaer** [comment]
try and go into the config folder. Locate the file "Forge.cfg" there is a line for removing erroring tile entities. turn this from false to true. start the game and load the world that is causing the crash. Afterwards turn the config back to false and restart the game.

**Comment by Ravalli03** [comment]
Set to true. Save still crashes ----https://pastebin.com/sRffYUz1

Set back to false. Still crashes----https://pastebin.com/bfHGKgUP (Still shows the coil being the issue.)

I may just remove Random Thing mod to remove them, and re-add it.

**Comment by Ravalli03** [comment]
So I remove Random Things Mod and re-added it. Save runs fine without issue. I can play again!!! The coil that caused the error has been there for a very long time and not sure why it caused a crash. I had it powering an auto sieve. Thanks for the help!!! I will leave this issue open as I'm not sure if the Iron chest mod is a issue caused by the pack update or not. Feel free to close it if it's not due to the pack update. I have not tried updating the Iron chest mod back.

Again thanks the help and great pack!!!!
