### ISSUE TITLE
[Bug] Angel Ring & Dragon Armor conflict

### ISSUE THREAD

**Issue by bloorocksDotD** [Sunekaer/stoneBlock#293]
Posting this here just because I wasn't sure if it should be posted to Tiny Progressions, Extra Utilities 2, or Angel Ring to Baubles, and I figured you would know and be able to do your fancy cross-post-link-thing.

## Bug Report

If you have an incomplete set of Dragon Armor from the Tiny Progressions and an Angel Ring(using the toBaubles version) you cannot use the Angel Ring to fly. It appears that once you have a single piece of the Dragon Armor set equipped, but not the entire set, the game sets you to be completely unable to get creative fly.

(Also I did see the other open issue for this, but it seemed rather non-specific)

## Steps to Reproduce (for bugs)

1. Equip 1-3 pieces of the Dragon Armor set.
2. Equip an Angel Ring
3. Try to fly
4. Be a little sad

## Logs

* Client/Server Log: N/A(Nothing involving this bug gets logged)
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.17 (without hats or kleeslabs)
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
#225
