### ISSUE TITLE
Maybe add Universal Remote

### ISSUE THREAD

**Issue by RyyJustin** [Sunekaer/stoneBlock#294]
## Context

The pack doesn't currently have a infinite wireless booster for AE2 or RS which is annoying to constantly be in 254 blocks of your base to access it with a remote where as this mod fixes that and works with any inventory, AE2 and RS across dimensions.

## Mod Details
* Name: Universal Remote
* CurseForge Link:https://minecraft.curseforge.com/projects/universal-remote

**Comment by xILikepuddingx** [comment]
wireless crafting terminal?

**Comment by Sunekaer** [comment]
wont be added, if your playing SP your welcome to add it yourself
