### ISSUE TITLE
Forestry Charcoal Pit gradually maxes out memory until OutOfMemoryError crash

### ISSUE THREAD

**Issue by gwpantazes** [Sunekaer/stoneBlock#296]
## Bug Report

The Forestry Charcoal pit, once it has burned for a while and starts turning to ash, will start allocating more and more memory until the game starts lagging, freezing, and will eventually crash due to an OutOfMemoryError. 

Note: Is this bug related to #290?

## Steps to Reproduce (for bugs)

1. Boot up a new Stoneblock world with cheats/creative
2. Make a 2 width, 3 long, 1 tall charcoal pit out of clay
3. Put in the woodpiles, light the corner woodpile with a flint and steel, and seal up the charcoal pit
4. Let it burn / wait. (5 minutes? 10? However long you have to wait for the charcoal pit).
5. Observe that after a while (it's been enough time for the charcoal pit to start converting to ash blocks) the game will start to stagger / slow, and eventually will freeze and crash due to an OutOfMemoryError.
    * You can visibly notice if you have debug info displaying during the course of the crash that the game will start allocating up to 100% of memory, while during the main course of the burning the memory allotment looks alot more normal. See the attached time lapse video of the memory going out of control in the zip file. [Charcoal.Pit.Memory.Crash.Timelapse.zip](https://github.com/Sunekaer/stoneBlock/files/2458698/Charcoal.Pit.Memory.Crash.Timelapse.zip)

 

## Logs

* Client/Server Log: https://gist.github.com/gwpantazes/7e7cab12c7d4281e4fe1a6912d0422d1
* Crash Log: Also in the same gist https://gist.github.com/gwpantazes/7e7cab12c7d4281e4fe1a6912d0422d1

## Client Information

* Modpack Version: 1.0.17 (Minecraft 1.12.2 (modded) forge-13.23.4.2760)
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No
* 5493 MB memory allocated

**Comment by gwpantazes** [comment]
This was originally filed over at https://github.com/ForestryMC/ForestryMC/issues/2264, should I close that one for the Forestry people if this issue belongs here in Stoneblock?

**Comment by Sunekaer** [comment]
not related to 290

**Comment by Sunekaer** [comment]
have to do some testing before i can say if its an stoneblock only error

**Comment by Sunekaer** [comment]
@gwpantazes could you try version 1.0.19 

https://minecraft.curseforge.com/projects/stoneblock/files/2626239

**Comment by gwpantazes** [comment]
Sorry I've been a bit busy @Sunekaer. I'll just comment here if it's not fixed in 1.0.19, I think I can try this weekend.

**Comment by gwpantazes** [comment]
@Sunekaer we might want to reopen this issue to keep an eye on it, because I tried reproducing this bug with only Vanilla, Forge, and Forestry to help narrow it down and I couldn't get it to crash, so the only pack where this is happening is Stoneblock. I'm not sure what else to do to help out, but it seems like a bug that affects just this pack. I made those attempts in a comment in https://github.com/ForestryMC/ForestryMC/issues/2264
