### ISSUE TITLE
Crash when trying to launch 1.0.18 server

### ISSUE THREAD

**Issue by coetyler** [Sunekaer/stoneBlock#297]
## Bug Report

Server crashing while trying to start it
## Steps to Reproduce (for bugs)

1. Download server and then upload to server host
2. Start server
3. Crash

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/Db7Cfjrw

## Client Information

* Modpack Version: 1.0.18
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
hmm weird issue, havent seen that one before, could you try with Modpack Version: 1.0.19?

**Comment by coetyler** [comment]
I will try this and update this with the results later tonight.

**Comment by coetyler** [comment]
still getting the same crash report even with the version 1.0.19

**Comment by coetyler** [comment]
now i get a different crash resulting from aroma this is the log for it https://pastebin.com/cY5Aarv0

**Comment by knoxhack** [comment]
@coetyler Thats a totally different crash, can you post it as a new issue so we start working on it? I will consider this one fixed if you don't get the first crash-report anymore
