### ISSUE TITLE
Problem with placing eggs into nests

### ISSUE THREAD

**Issue by SynapticStatic** [Sunekaer/stoneBlock#299]
Looks like there might be an[ issue in hatchery after the pack has updated forge from 2760 to 2765](https://github.com/GenDeathrow/Hatchery/issues/168)

Basically if you put an egg into a nest (Haven't tried even placing the nests), you get a crash:

https://pastebin.com/4jcB5Dwu

Just an FYI

**Comment by dingsbums** [comment]
Hatchery v2.1.4  did fix it (at least for me).

**Comment by Sunekaer** [comment]
ty dings

**Comment by Sunekaer** [comment]
1.0.19
