### ISSUE TITLE
Bread Slice crafting conflict

### ISSUE THREAD

**Issue by uglyduck2k4** [Sunekaer/stoneBlock#3]
JEI has bread slice being made by bread.
![bread1](https://user-images.githubusercontent.com/34759595/39223803-ccf0441a-47f8-11e8-9891-0a914720c96d.png)

Instead, I get this
![bread2](https://user-images.githubusercontent.com/34759595/39223835-f511a9e8-47f8-11e8-8dba-3adddb3b4ac3.png)

**Comment by Sunekaer** [comment]
fixed in dev
