### ISSUE TITLE
Server problem

### ISSUE THREAD

**Issue by JackMeds** [Sunekaer/stoneBlock#301]
Can I use your modpack on my Chinese server?
And Can I modify some craftings?

**Comment by JackMeds** [comment]
Can I modify some craftings? ,
Some cause the server to slow down and some too simple crafting

**Comment by Sunekaer** [comment]
Some cause the server to slow down? elaborate please
some too simple crafting, that's intended, only the endgame items is supposed to be harder

**Comment by JackMeds** [comment]
elaborate please
Something that doesn't affect the mission. Like boat 、Mine car。

**Comment by JackMeds** [comment]
that's intended, only the endgame items is supposed to be harder 
OK

**Comment by Sunekaer** [comment]
so you want to remove boats and minecarts on your server, for stability?

**Comment by JackMeds** [comment]
yeah

**Comment by Sunekaer** [comment]
then what about the items that use them for crafting recipes?

**Comment by JackMeds** [comment]
no way ，but I'm not going to make a big change.
