### ISSUE TITLE
Unable to craft Transmutation Table in 1.0.17

### ISSUE THREAD

**Issue by Riallyyy** [Sunekaer/stoneBlock#303]
## Bug Report

I cant craft the Transmutation Table, I tried Shift-Clicking the Recipe in with JEI and also placing everything manually and both times it wont let me craft the Table, even though JEI recognizes all items as correct and lets me Shift-Click them in the Crafting Table.

## Steps to Reproduce (for bugs)

1. Try to craft Transmutation Table
2. Unlucky

## Logs
![screenshot 2](https://user-images.githubusercontent.com/43991612/46667789-03f53000-cbcb-11e8-8bd8-de6936fdc26f.png)

Screenshot for reference since there are no Crash Logs.
* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by vertex101** [comment]
i seen the OP closed this what was the fix as i am having the same issue with v1.0.20
