### ISSUE TITLE
Game crashes after starting auto craft in refined storage.

### ISSUE THREAD

**Issue by devilishhero** [Sunekaer/stoneBlock#306]
## Bug Report
my game crashes after i start an auto craft in refined storage. start in version 1.0.17. still happening in 1.0.18

## Steps to Reproduce (for bugs)
1.start auto craft
2. game crashes

## Logs
* Client/Server Log:
* Crash Log: https://pastebin.com/UMYskaAV

## Client Information

* Modpack Version:1.0.18
* Server/LAN/Single Player: singleplayer
* Optifine Installed:no
* Shaders Enabled:no

**Comment by Sunekaer** [comment]
please report issue at https://github.com/raoulvdberge/refinedstorage/issues as i cant do anything about that
