### ISSUE TITLE
[Suggestion]Add Gendustry and CareerBees. Maybe, really maybe, MagicBees

### ISSUE THREAD

**Issue by xILikepuddingx** [Sunekaer/stoneBlock#308]
## Context

everybody knows. Making bees can be exhausting and boring. gendustry makes it all something more bearable.

careerbees adds some nice bees. such as. the temporal bee, which cuts down the tick times much like the acceleration wall.

If you maybe still want to add more bees possibilities, MagicBees would be great

## Mod Details
* Name: Gendustry
* CurseForge Link: https://minecraft.curseforge.com/projects/gendustry
* Name: Careerbees
* CurseForge Link: https://minecraft.curseforge.com/projects/career-bees

**Comment by Sunekaer** [comment]
At this point im not adding anymore mods unless i really really need too
