### ISSUE TITLE
Add ore pieces to ore chunk recipes to Cyclic packager

### ISSUE THREAD

**Issue by toastertim** [Sunekaer/stoneBlock#309]
**Suggestion** 
Add recipes to pack that allows Cyclic packager to execute the 2x2 recipe for ore pieces in ore chunks

**Comment by nzminecraftDOTcom** [comment]
Have you tried a compacter? Does the exact same thing! :+1:

**Comment by knoxhack** [comment]
Awesome, thanks. didnt know

**Comment by knoxhack** [comment]
Fixed in 1.0.21
