### ISSUE TITLE
Repeated Crashing

### ISSUE THREAD

**Issue by alio314** [Sunekaer/stoneBlock#311]
## Steps to Reproduce (for bugs)

1. This is my first crash report, but I've had crashes occur at several times, all while doing different things. For example, this last time I was in my Refined Storage crafting grid making Prudentium. I see the reference to Ender Storage and had just created an ender chest to collect ore from a void ore miner I had created in my mining world. But this is the first time I've used ender storage in the game, so not sure why I crashed the other times.
2. Several times, I have restarted the pack and come back to find myself in the original stone room from the beginning with all the inventory from my storage systems exploded all over the floor. I can hear my chickens, but can't see them.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/w2h7aSYA

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by alio314** [comment]
![2018-10-10 08 36 41](https://user-images.githubusercontent.com/39442868/46753807-d1ad0680-cc8e-11e8-9e73-88d578ce0281.jpg)

**Comment by knoxhack** [comment]
please delete the 'EnderStorage' folder Here: C:\Users\Alison\Documents\Curse\Minecraft\Instances\StoneBlock\saves\New World 1\EnderStorage and start the server again.

**Comment by knoxhack** [comment]
follow what it says to do, and try again, or try a fresh installation

**Comment by knoxhack** [comment]
let us know if it works

**Comment by alio314** [comment]
Thanks. It did work, but this is not the first crash I've had. Only the first that produced a crash report. Crossing my fingers.

**Comment by knoxhack** [comment]
@alio314 Thats a totally different crash, can you post it as a new issue so we start working on it? I will consider this one fixed
