### ISSUE TITLE
Stone Block modpack crashes during launch

### ISSUE THREAD

**Issue by phoenix13gaming** [Sunekaer/stoneBlock#312]
## Bug Report

I press the play button on the launcher and it loads for a few seconds and then crashes.

## Steps to Reproduce (for bugs)

1. I open Twitch go to my modpacks and press play on Stone Block.
2. Once the launcher opens I press play and it loads for a few seconds then crashes.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/8yEEPGW5

## Client Information

* Modpack Version: 1.0.19
* Server/LAN/Single Player: Single Player
* Optifine Installed: No 
* Shaders Enabled: No
![img_1909](https://user-images.githubusercontent.com/44037007/46759903-7daa1e00-cc9e-11e8-8739-3d2dc7569ba1.JPG)

**Comment by knoxhack** [comment]
Pls try a brand new installation, looks like your files got corrupted during download.

**Comment by knoxhack** [comment]
Any news?
