### ISSUE TITLE
Flux Network / Not Enough Wands - Moving Wand Duplication Bug

### ISSUE THREAD

**Issue by Armodakai** [Sunekaer/stoneBlock#313]
1. Make any item from flux networks IE(Plugs, Points, and Basic Storage) Did not try with controller as you only need one but i would assume it will work with controller as well.
2. Once you have any item made place it in the world 
3. now take a moving wand from the Not Enough Wands mod and make sure it is charged
4. Now grab the flux network item you placed in the world with the wand and it will pick it up if you then place it back in the world you will notice that you now have that item in your inventory and the wand still contains the original. This can be done with any of the flux network items

## Client Information
* Modpack Version: 1.0.17 and below
* Server/LAN/Single Player: Will work on server and single player worlds
* Optifine Installed: no 
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
already fixed in 1.0.18

**Comment by Armodakai** [comment]
Awesome thanks
