### ISSUE TITLE
Thermal Innovations

### ISSUE THREAD

**Issue by bloorocksDotD** [Sunekaer/stoneBlock#314]
## Context

Add Thermal Innovations to the modpack <3 Potion Injectors & Magnets & Drills oh my

## Mod Details
* Name: Thermal Innovations
* CurseForge Link: https://minecraft.curseforge.com/projects/thermal-innovation

**Comment by knoxhack** [comment]
Its been added in v.1.0.18

**https://minecraft.curseforge.com/projects/stoneblock/files/2625333**

**Comment by bloorocksDotD** [comment]
<3
