### ISSUE TITLE
Dupe Bug w/ Cyclic Automated User and Ex Nihilo Creatio Stone Barrel

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [Sunekaer/stoneBlock#316]
## Bug Report
Using a Automated User to apply redstone or glowstone to a lava filled Stone Barrel does not deplete the glowstone/redstone and yields the product as long as there are more than two of the item in the slot.
## Steps to Reproduce (for bugs)

1. Place a stone barrel in front of the operating end of an Automated User
2. Connect the stone barrel to a large source of lava
3. Place at least two redstone or glowstone in the UI for the Automated User
4. Power the Automated User
5. Turn on Automated User
## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

![2018-10-10_19 29 12](https://user-images.githubusercontent.com/9999849/46773442-0044d480-ccc3-11e8-8f30-2cdc518c7be2.png)
![2018-10-10_19 29 21](https://user-images.githubusercontent.com/9999849/46773445-063ab580-ccc3-11e8-802c-dee78850ed72.png)

**Comment by knoxhack** [comment]
Oh

**Comment by Rainee4563** [comment]
same for clay I think it works with anything with the barrels and the auto user

**Comment by Sunekaer** [comment]
from my testing this is fixed in 0.26
