### ISSUE TITLE
Constant server crashes

### ISSUE THREAD

**Issue by Magesw** [Sunekaer/stoneBlock#317]
## Bug Report

The server is constantly crashing

## Steps to Reproduce (for bugs)

1. I will provide logs below but it doesn't seem to be an overall single thing the players are doing but something to do with leaves.

## Logs

* https://pastebin.com/8G2tXSrD
* https://pastebin.com/3AsHSTc8
* https://pastebin.com/5Jrgaw5g
These are the last 3 crash logs so far all 15 or more have been the exact same thing.

## Client Information

* Modpack Version: 1.0.19
* Server/LAN/Single Player: Server
* Optifine Installed: Only if it is already in the pack
* Shaders Enabled: Only if it is already in the pack

**Comment by nzminecraftDOTcom** [comment]
Try 1.0.20, a non beta release.

**Comment by Magesw** [comment]
> Try 1.0.20, a non beta release.

You mean the version that was just added 7 hrs ago and only changed loot bags? I don't see a fix for leaves in the patch notes. 1.0.19 is the same version official is running as well.

**Comment by nzminecraftDOTcom** [comment]
Then go back to a version that works, clearly the answer here.

**Comment by Magesw** [comment]
> Then go back to a version that works, clearly the answer here.

Been running Stoneblock since 1.0.16, had some crashes there with it, same with 1.0.17 and 1.0.18 I feel it is better to bring it to the attention of the dev so it can be fixed and seeing as you have zero to do with that just walk away.

**Comment by nzminecraftDOTcom** [comment]
Hate to crawl up in your nose and lay the facts down but beta releases and even fresh full releases will have game breaking bugs. Any good server host knows to not update until bug reports have dropped right off. No point stressing your player base with constant crash loops causing them to lose valuable progress.

**Comment by yamy19** [comment]
As nzminecraft stated when updating to a newer version it is always better to wait at least a week because there maybe some bugs that can break the game that where not discovered in the beta realse

**Comment by Magesw** [comment]
and as I stated that same bug has been in RELEASED versions.

**Comment by nzminecraftDOTcom** [comment]
Perhaps there is something in your world causing it. Running 1.0.17 here and have had 0 crashes. Try loading a fresh world on a test server and see if you get the same problem.

**Comment by knoxhack** [comment]
Can you post your latest log file from "/logs" pls, thanks

**Comment by Magesw** [comment]
> Perhaps there is something in your world causing it. Running 1.0.17 here and have had 0 crashes. Try loading a fresh world on a test server and see if you get the same problem.

Fresh map as of 1.0.19

**Comment by Magesw** [comment]
> Can you post your latest log file from "/logs" pls, thanks

http://pasted.co/5f24e25a

**Comment by Sunekaer** [comment]
could you try and go In "Forge.cfg" there is a line for removing erroring tile entities. turn this from false to true. Restart the server and load the chunks the crash is happening at. Afterwards turn the config back to false and restart the server.

**Comment by Magesw** [comment]
> could you try and go In "Forge.cfg" there is a line for removing erroring tile entities. turn this from false to true. Restart the server and load the chunks the crash is happening at. Afterwards turn the config back to false and restart the server.

This line?
Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false

The one that can screw up everything? lol

**Comment by nzminecraftDOTcom** [comment]
Do a world backup first, I've had to use it and had no negative effects other than the console spamming whenever something went wrong. If all fails, the backup can be restored and other options can be looked into

**Comment by Magesw** [comment]
https://pastebin.com/MZKq0g8r

**Comment by Sunekaer** [comment]
Sorry i forgot about this issue, i been talking with some people and the issue is with some IC2 rubber trees trying to generate, and theres nothing i can do, i have to direct you to Industrial craft in hopes that they can help you
https://bt.industrial-craft.net/my_view_page.php
