### ISSUE TITLE
Add ME Capability Adapter

### ISSUE THREAD

**Issue by Arudarin** [Sunekaer/stoneBlock#318]
If you wish to use a Compact Machine at the moment, you cannot connect it to your AE2 network without quantum entanglement. This fixes that and allows for the containerization of various automation processes.
## Mod Details
* Name: ME Capability Adapter
* CurseForge Link: https://minecraft.curseforge.com/projects/capability-adapter

**Comment by Sunekaer** [comment]
Not adding anymore mods
