### ISSUE TITLE
Please add these mods

### ISSUE THREAD

**Issue by El-DoDo** [Sunekaer/stoneBlock#32]
- [Construct's Armory](https://minecraft.curseforge.com/projects/constructs-armory)
- [Baubley Heart Canisters](https://minecraft.curseforge.com/projects/baubley-heart-canisters)
- [Overpowered Armor Bar](https://minecraft.curseforge.com/projects/overpowered-armor-bar)

**Comment by Sunekaer** [comment]
not adding any mods atm.
