### ISSUE TITLE
Constant crashes after updating to 1.0.20

### ISSUE THREAD

**Issue by SayZer** [Sunekaer/stoneBlock#320]
## Bug Report

After updating to the latest 1.0.20, my client started crashing. The crash happens after few seconds to minutes of gameplay. After initial few crashes i did a clean install of mod pack but its still crashing.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/sWdvJ20m

## Client Information

* Modpack Version: 1.0.20
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

**Comment by wackoamd1** [comment]
u are lucky to even get in the game , mine crashes at startup . more specific its "craftpresence" that takes down the modpack

**Comment by xILikepuddingx** [comment]
ur lootbag opener crashes ur game

**Comment by SayZer** [comment]
any fix for that or just void the lootbags and trash the opener? Also was Patient Loot bag removed in 1.0.20 because its in my storage drawer but couldn't find it in JEI

**Comment by wackoamd1** [comment]
i fixed my game by removing craftpresence , not a crash in sight.

**Comment by shikyo13** [comment]
I'm having the exact same crash as OP. Seems some new item in the lootbags is causing a crash in the LootBag Opener.

**Comment by Steve59** [comment]
The problem seems to be changes to config\Lootbags_BagConfig.cfg
I restored this file from a backup and the crashing stopped.

**Comment by SayZer** [comment]
Removing the loot bag opener from the world fixed the problem, but now i can't open loot bags, so i will wait for the fix.

**Comment by knoxhack** [comment]
Could you try this pls and let me know
https://gist.github.com/knoxhack/a06fbd5fb4437a11a018a486659e4e12

**Comment by knoxhack** [comment]
try to so if it crash with this file, if so post the new crashlog pls thanks

**Comment by SayZer** [comment]
With that new file client crashed at the mod loading phase during start. 
https://pastebin.com/xQjz5J2C

**Comment by knoxhack** [comment]
Right, try this one:
https://gist.github.com/knoxhack/ba3c81a85172554c940b3629fc7419ee

**Comment by SayZer** [comment]
Crashed when i tried to load the save game.
https://pastebin.com/b3MH563K

**Comment by knoxhack** [comment]
could you provide the lates log file also "/logs"?

**Comment by knoxhack** [comment]
Oh, I think I found the problem

**Comment by knoxhack** [comment]
Try this :/
https://gist.github.com/knoxhack/cff37eec0eccd86a4581b14af1be069f

**Comment by SayZer** [comment]
https://gist.github.com/SayZer/fd81b25b678d6e2d6b5c8ac8342e62b3

**Comment by SayZer** [comment]
So i was successfully in the game this time, but it crashed after a minute or so.
https://pastebin.com/UtcDwQS4

**Comment by Grynder01** [comment]
Just breaking all the lootbag openers for right now will solve the problem...im just storing the bags in the storage block for now...im thinking it might be the Patient bag that is the problem because i noticed a few times that opening one of the other bags gives a Patient Bag when using the bag opener

**Comment by SayZer** [comment]
exactly, when i have bag opener in the world the game crashes but when i remove it, its fixed. i believe it has to be patient bag.

**Comment by kreezxil** [comment]
My dedicated server crashed after updating to 1.0.20 for the same reason these clients crashed.
Here are a list of the crashes which are all the same: http://paste.ubuntu.com/p/yhMhsTCY64/

And here is just one of them from that list: http://paste.ubuntu.com/p/S8C8hCQVSy/

And yes there is a bag opener in the world. I know for a fact there is one, i built one.

**Comment by Sunekaer** [comment]
could you try this one https://gist.github.com/Sunekaer/ab782b0c2fe996e9d424e4cb11fd1d4e

**Comment by kreezxil** [comment]
@Sunekaer that was causes a crash too: http://paste.ubuntu.com/p/VbDx4jTqvc/ and yet the config from 1.0.18 does not.

**Comment by TheUnbreakableBedrock** [comment]
I think I've got the same issue. Thank God I made a backup! I will try to downgrade, restore backup, remove the bag openers. I'll let y'all know if it worked.

**Comment by kreezxil** [comment]
don't downgrade just use the config from 1.0.18

**Comment by TheUnbreakableBedrock** [comment]
I was going to go back to 1.0.20 after that

**Comment by Malorolam** [comment]
Issue has been reported to me too, the problem I found was that there's whitelist entries with a minimum count larger than the maximum, these are the ones I saw in the config I was provided:
line 139: `minecraft:gunpowder:0:4:2:20`
line 146: `minecraft:fish:2:3:2:20`
The second number should be smaller or equal to the third number.
Fixing those should prevent the crash.  I'll add a catch to the code to stop similar problems in the future but it'll be a little while before I can make a proper release.

**Comment by Sunekaer** [comment]
https://gist.github.com/Sunekaer/5e3c89c19dbde16f09f21fe2976bb99a try this one

**Comment by SayZer** [comment]
@Sunekaer It seems like the crash has been fixed with the file you posted.

**Comment by 2J3P2001** [comment]
Where do I paste that file?
The one that @sunekaer lastly posted?

**Comment by 2J3P2001** [comment]
I always crash... Doesn't matter which lootbag config I use...
This is my Crash thingy
content://com.android.providers.downloads.documents/document/6884

**Comment by SayZer** [comment]
> 
> 
> Where do I paste that file?
> The one that @Sunekaer lastly posted?

"C:\Program Files (x86)\Minecraft\Instances\StoneBlock\config" Look for Lootbags_BagConfig.cfg open it and replace everything in it with what Sunekaer posted above. (Don't forget to make backup before changing the file.)

**Comment by 2J3P2001** [comment]
How do I do that backup?

**Comment by 2J3P2001** [comment]
@SayZer

**Comment by 2J3P2001** [comment]
Still not working...

**Comment by SayZer** [comment]
> 
> 
> Still not working...



> 
> 
> How do I do that backup?



> 
> 
> Still not working...

Backup = copy the original file store it in some other folder, and then make changes to the file in config folder.

2) Whats not working? game? backup? if you are still experiencing a crash than paste your most recent crash log in pastebin and post a link here.

You can find crash report at crash-reports folder

**Comment by MiistaK** [comment]
i keep getting a error whenever its halfway through the download, 

https://files.forgecdn.net/files 

does anyone know how to fix this? I was able to download it previously but after the update, i can't any more

**Comment by MiistaK** [comment]
https://pastebin.com/PqVSDdTX

im still getting crashes, its really frustrating because it was working and playing fine a few days ago.

**Comment by DDzwiedziu** [comment]
For reference: https://github.com/Malorolam/LootBags/issues/159

**Comment by MiistaK** [comment]
Okay, i'll try that, its just it'll quit loading halfway through the install so which why im having a hard time switching the two. (im using the twitch app)
    On Sunday, October 14, 2018, 2:52:01 PM GMT+4:30, kreezxil <notifications@github.com> wrote:  
 
 MiistaK just use the Lootbags_BagConfig.cfg from the version 1.0.19 pack on
your 1.0.20 pack, problem solved until they fix it. If running a server
make sure it is copied there too.

**Comment by kreezxil** [comment]
just kill the launch via task manager, remove the offending config from the
config folder and copy the old one in.

*If what you are saying* is that you have having issues with downloading,
here's the config as a paste http://paste.ubuntu.com/p/hSJbvkggNm/

**Comment by 2J3P2001** [comment]
Please help me!
I already used the config that @Sunekaer posted previously. Still, when I open my saved world, it loads until it says 0 percent and then it instantly crashes...
I don´t have any bag opener in the world, which, to some people, seems to be the problem...
I´m posting the crash report, hope someone can help me in this particular case.
https://pastebin.com/2RDiD6ak

**Comment by knoxhack** [comment]
@2J3P2001 please delete the 'EnderStorage' folder Here: G:\Minecraft Mods\Instances\StoneBlock (2)\saves\StoneBlock\EnderStorage and start the server again.

**Comment by knoxhack** [comment]
Fixed in 1.0.21
