### ISSUE TITLE
Potion generator does not accept potions

### ISSUE THREAD

**Issue by nguse** [Sunekaer/stoneBlock#324]
## Bug Report
I've tried just about every potion in the game, but I cannot get the potion generator from extra utilities 2 to accept any of them.

## Steps to Reproduce (for bugs)
Create potion generator
Try to give it some potions

## Client Information
* Modpack Version: 1.0.19 and 1.0.20

**Comment by xILikepuddingx** [comment]
fixed in a newer version of ExU2

**Comment by Rodedrengen** [comment]
So when is this going to be fixed in stoneblock?

**Comment by knoxhack** [comment]
Fixed in 1.0.21
