### ISSUE TITLE
Buildcraft Pump Depth.

### ISSUE THREAD

**Issue by Steve59** [Sunekaer/stoneBlock#325]
## Context

With the current settings the pump stops working just as it hits the main load of oil in the mining dimension. The default depth for the BC pump is 64, could you please raise that to 100 or 120. 

## Config/Script Details
* Link:
Config\Buildcraft\main.cfg

    # How far, in minecraft blocks, should pumps reach in fluids?
    I:pumpMaxDistance=64

To

    # How far, in minecraft blocks, should pumps reach in fluids?
    I:pumpMaxDistance=120

**Comment by knoxhack** [comment]
Can you explain more, why would you need it to be like that?

**Comment by knoxhack** [comment]
Good enough

**Comment by knoxhack** [comment]
I'll implement it

**Comment by knoxhack** [comment]
Fixed in 1.0.21
