### ISSUE TITLE
Version 1.0.17 Crashing when loading into any server

### ISSUE THREAD

**Issue by Spyrox17** [Sunekaer/stoneBlock#327]
## Bug Report
I've never had the problem before on 1.0.17 so I don't understand what the issue is. I checked my RAM associated with the modpack (I run it at a little over 4gb and it has run perfectly fine beforehand).

## Steps to Reproduce (for bugs)

1. Start in 1.0.17
2. Jump into a server running the same version.

## Logs

Client Log: "The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: net.minecraft.client.multiplayer.WorldClient.isPlayerUpdate()Z"

Latest Log:
Was too big for pastebin so I uploaded it to dropbox.
https://www.dropbox.com/s/qqsnoihu6cgp3fx/latest.log?dl=0

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server
* Optifine Installed: Yes, although it crashed even without optifine
* Shaders Enabled: No.

**Comment by Sunekaer** [comment]
Please upload the log to gist.github.com, we do not download files sorry

**Comment by Spyrox17** [comment]
Yeah I didn't upload it to gist at first cuz it was crashing my browser for some reason.
here you go now.
https://gist.github.com/Spyrox17/cd97ed5c56d21ce762ddfe252f0ca7ff

**Comment by Spyrox17** [comment]
I've since then reinstalled the modpack and it seems to be fixed. Although I'm still running 1.0.17 because that's the version the server I go to now runs on. They didn't update because of modpack crashes on the latest update.
