### ISSUE TITLE
Suggestion: Remove or change Steel ingot recipe in Ender IO alloy smelter

### ISSUE THREAD

**Issue by Hazmatik** [Sunekaer/stoneBlock#328]
The recipe for steel in an Ender IO alloy smelter can be conflicting and could cause issues with automation for making Electrical Steel. The problem is if iron and pulverized coal are put into the alloy smelter it starts smelting up steel before the silicon gets put in to make electrical steel.

**Comment by ArbitraryHubris** [comment]
it's a pain, but put a switch on your alloy smelter and set it to require signal.

**Comment by Sunekaer** [comment]
i wont be removing or changing  any of these recipes sorry
