### ISSUE TITLE
Server crash when starting a 1.0.20 

### ISSUE THREAD

**Issue by coetyler** [Sunekaer/stoneBlock#329]
## Bug Report

Server crashing while trying to start it
## Steps to Reproduce (for bugs)

1. Download server and then upload to server host
2. Start server
3. Crash

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/cY5Aarv0

## Client Information

* Modpack Version: 1.0.20
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Anoyomouse** [comment]
Go check your permissions on the file:
./config/aroma1997/aroma1997sdimension_gen.json (Permission denied)

Looks like the server is not able to access the file

**Comment by coetyler** [comment]
All I did was upload the files from my computer after downloading them off of course to the server host and I get this crash when starting it up. The server host uses minecraft panel for accessing the server.
