### ISSUE TITLE
Beet seeds give wrong output in Phytogenic Isolators

### ISSUE THREAD

**Issue by inofflinemode** [Sunekaer/stoneBlock#330]
## Bug Report

When inputting Pam's Harvest beet seed (required for Ultimate Stew) in the Phytogenic Isolators, it outputs beetroot from vanilla Minecraft. This beetroot is not accepted in the Ultimate Stew recipe.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.20

**Comment by xILikepuddingx** [comment]
u can buy the beet in the market

**Comment by inofflinemode** [comment]
I've checked both markets, there is not beet, just the seed that grows the wrong beets.

**Comment by Degenerecy** [comment]
The Farming for Blockheads Market npc sells Beetroot and Beet seeds(search bar, type beet) and the Beet seed is the right one(Pam's HarvestCraft)

**Comment by inofflinemode** [comment]
@Degenerecy The Pam's Harvest Beet seed is growing the wrong beet, that is the bug.

**Comment by Degenerecy** [comment]
Recently tried it out myself when I posted, bought from the market, and grew it in the garden cloche, grew the right one.

**Comment by inofflinemode** [comment]
Oh, you are right! It seems like it's just Phytogenic Insulators that give the wrong output then. Ill edit the original post to specify that. Thanks.

**Comment by knoxhack** [comment]
Fixed in 1.0.21
