### ISSUE TITLE
Incorrect forge referenced in LaunchServer.sh

### ISSUE THREAD

**Issue by Anoyomouse** [Sunekaer/stoneBlock#331]
## Bug Report
In LaunchServer.sh you are referring to:
`forge-1.12.2-14.23.4.2768-universal.jar`
instead of
`forge-1.12.2-14.23.5.2768-universal.jar`

## Steps to Reproduce (for bugs)
1. Download Server
2. Extract Server
3. Change LaunchServer.sh from a dos format to a unix format (else you get the GUI trying to appear)
4. run: `bash LaunchServer.sh`
5. Watch it not find the jar

## Logs
`user@server:~/StoneBlock$ bash LaunchServer.sh
Error: Unable to access jarfile forge-1.12.2-14.23.4.2768-universal.jar`

## Client Information
* Modpack Version: 1.0.20 (this was also an error in 1.0.18 and 1.0.19 BTW, since you updated forge)
* Server/LAN/Single Player: Server (Linux)
* Optifine Installed: Nope
* Shaders Enabled: Nope

**Comment by BrandonGamesYT** [comment]
Was just going to let them know

**Comment by Sunekaer** [comment]
#319
