### ISSUE TITLE
MooFluids Half Gone, Also Causing Crashes [1.0.20]

### ISSUE THREAD

**Issue by BrandonGamesYT** [Sunekaer/stoneBlock#332]
## Steps to Reproduce (for bugs)
1. Have moo fluid cows, try spawning the cows to get ones I had from before I updated.
2. Server Crashes when MooFluids come into play

## Logs
* Client/Server Log: 
[debug.log](https://github.com/Sunekaer/stoneBlock/files/2472234/debug.log)
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2472231/latest.log)
* Crash Log:
[crash-2018-10-12_02.27.33-server.txt](https://github.com/Sunekaer/stoneBlock/files/2472235/crash-2018-10-12_02.27.33-server.txt)
[crash-2018-10-12_03.18.53-server.txt](https://github.com/Sunekaer/stoneBlock/files/2472236/crash-2018-10-12_03.18.53-server.txt)

## Client Information
* Modpack Version: 1.0.20
* Server/LAN/Single Player: Server
* Optifine Installed:
* Shaders Enabled:

**Comment by Ravalli03** [comment]
Also having similar issue with Fluid Cows being invisible. Some fluid cows I had stored in soul vials when placed and invisible, you can still hear and kill them but not see nor milk them.

**Comment by BrandonGamesYT** [comment]
I looked through the cfg files and found that all the buildcraft cows were removed? or was that intentional? if not i can go about adding them back in and see of that fixes the problem?

**Comment by Zero-Angel** [comment]
We worked around this by removing moofluids, starting the server to purge any existing cows, and then readding the mod.

**Comment by Benedictum** [comment]
I have similar behavior in stoneblock. Missing about 40 types of fluid cows, the following were in animal nets and when i used them to put the cow back in the world they just emptied. I made a mob duplicator with a fluid cow in it and spat out 514 cows, none of the following types spawned.

dark steel
conductive iron
energetic alloy
gold
end steel
iron
soularium
steel
osmium
nickel
bronze
pulsating iron
copper
manasteel
elementium
terrasteel
osmiridium
redstone alloy
lead
brass
electrum
refined uranium
ardite
evil infused
manyullun
refined obsidian
pigiron
knightslime
demon metal
vibrant alloy

Many other fluids also did not spawn but those are the ones i am tracking. of the 514 i spawned, majority were of the following types:
constantin, invar, electrical steel, sap, resin, grassoline, essence of knowledge, primal mana, destabilized redstone, enderium, resonant ender, lava, crystalized oil, water, heavy water, energized glowstone, seed oil, platinum, tectonic petrotheum, mushroom stew, signalum, blazing pyrotheum, gelid cryotheum, potions, resin, tree oil, etc.

**Comment by Sunekaer** [comment]
removed Moo FLuids in 1.0.24
