### ISSUE TITLE
Suggestion: Equivalent Energistics and MystAgrad Cloche Compat.

### ISSUE THREAD

**Issue by Boyownik** [Sunekaer/stoneBlock#333]
Those mods would be nice to have, since ProjectE is endgame anyway it would be great to have autocrafting from EMC. And about Cloche, well all seeds to tier 6 works great so why can't we put tier 6 seeds there (like inferium seeds, with this mod they need insanium block underneath)?

## Mod Details
* Name: Equivalent Energistics and MystAgrad Cloche Compat
* CurseForge Link: 
https://minecraft.curseforge.com/projects/mystagrad-cloche-compat?gameCategorySlug=mc-mods&projectID=288959
https://minecraft.curseforge.com/projects/equivalent-energistics?gameCategorySlug=mc-mods&projectID=231853

**Comment by jk1895** [comment]
Or maybe he could add the new mod Equivalent Integrations:
https://www.curseforge.com/minecraft/mc-mods/equivalent-integrations
https://www.reddit.com/r/feedthebeast/comments/8zgzyl/1122_announcing_a_brand_new_mod_equivalent/

I never tried it but it looks very promising.

**Comment by Sunekaer** [comment]
not adding anymore mods
