### ISSUE TITLE
Server Crash on 1.0.20

### ISSUE THREAD

**Issue by cauliflower69** [Sunekaer/stoneBlock#337]
## Bug Report
Server Crash on 1.0.20

## Steps to Reproduce (for bugs)
Update server to 1.0.20

## Logs
https://pastebin.com/rajyqZ4Z

## Client Information
Version 1.0.20. - No client can connect as server crashes on startup

**Comment by budd308** [comment]
Try this: Take the new 1.0.20 server files, and put in a new folder. Take your world save file and your server.properties file from your current server and paste them into the new folder with the new 1.0.20 files in it. Rename the file called "forge-1.12.2-14.23.4.2768-universal" and change the 4 right before 2768 to a 5. Then try and launch the server. Hope this helps, it seems to have a conflict with updating an older server version to a newer one and this worked for me.

**Comment by cauliflower69** [comment]
We use McMyadmin to launch the servers which looks for a jar called ForgeMod.jar so I don't think that can work
