### ISSUE TITLE
Problem with creative.

### ISSUE THREAD

**Issue by Jacob-Suldaan** [Sunekaer/stoneBlock#340]
## Steps to Reproduce (for bugs)

1. Create a survival world and change to creative with top left buttons.
2. After a while try to switch back into survival.
3. Buttons are gone, gamemode, weather and cog icons are all gone.
4. I found that they was back this morning once i logged back in, is there a bug where they can disappear? 
5. Also there is a issue where if I use the commands to switch to creative and survival it stops me from placing, removing and interacting with blocks.

## Logs

* Client/Server Log: Don't know where to find this.
* Crash Log: Isn't a crash.

## Client Information

* Modpack Version: 1.0.20
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by nzminecraftDOTcom** [comment]
Can't switch. More details please? No buttons, no permission, button not working etc

Need to fill out the rest of the form or the Dev will shut this report as invalid

**Comment by Jacob-Suldaan** [comment]
The button to switch from creative and survival isn't there same as the
weather options and even the gear icons have gone?

Also there is a issue where if I use the commands it stops me from placing
and removing blocks and interacting with them

**Comment by Jacob-Suldaan** [comment]
Crashing and I don't know why?

Bug Report

Steps to Reproduce (for bugs)

I have no idea how to recreate this crash.

Logs

    Client/Server Log: I don't know where to find this one.
    Crash Log: [crash-2018-10-13_14.31.16-server.txt](https://github.com/Sunekaer/stoneBlock/files/2475504/crash-2018-10-13_14.31.16-server.txt)

I thought it would be better than creating a whole new issue, hope that was alright to do.

Client Information

    Modpack Version: 1.0.20
    Server/LAN/Single Player: Single Player
    Optifine Installed: Yes
    Shaders Enabled: No

**Comment by nzminecraftDOTcom** [comment]
A lootbag opener in your world has bugged out. 
It's co-ords are -930 90 -999 chunk coords -59 -63
You will either need to install world edit to remove this block or manually do it with an NBT editor
