### ISSUE TITLE
Suggestion:MordenConverter and maybe a chunk loader

### ISSUE THREAD

**Issue by TheMineKay** [Sunekaer/stoneBlock#341]
this mod would be great tp cpnvert the diffrent energy types: https://minecraft.curseforge.com/projects/modernconverter
and i would like a chunk loader to use with a quarry in the Aroma mining dimension

**Comment by Degenerecy** [comment]
To Chunkload, left click an area to claim, then shift+left click a claimed chunk to make it chunkload.  Right click to unclaim/remove chunkload.

**Comment by Sunekaer** [comment]
Not adding anymore mods to the pack, and you can chunkload via ftbu
