### ISSUE TITLE
Dark spots overlay not showing

### ISSUE THREAD

**Issue by Windstep** [Sunekaer/stoneBlock#343]
## Bug Report

Not showing f7 light overlay. No one of changes to default pack except of texture pack (soartex fanver modded). Not working even with default textures.

## Steps to Reproduce (for bugs)
I don't know) Really. Just started new world and overlay not working.

## Client Information

* Modpack Version: 1.0.20
* Server/LAN/Single Player: sp
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Windstep** [comment]
New worlds are good at this... So I'm currently trying to allocate problem.

**Comment by Windstep** [comment]
Problem is in one of this files. 
[region.zip](https://github.com/Sunekaer/stoneBlock/files/2475486/region.zip)

**Comment by Windstep** [comment]
As a side effect, mobs are not spawning even on hard difficulty and withing 24-32 radius

**Comment by knoxhack** [comment]
Does this still happens with 1.0.21?
