### ISSUE TITLE
loot bag opener issue causes crashing in 1.0.20

### ISSUE THREAD

**Issue by volicio** [Sunekaer/stoneBlock#345]
Since the latest update I've been having issues with where if a loot bag opener is running in my game at all it crashes and i have to go into MC edit and remove the bag opener just to load into the world.
[crash-2018-10-12_21.42.33-server.txt](https://github.com/Sunekaer/stoneBlock/files/2475438/crash-2018-10-12_21.42.33-server.txt) this is the crash report from my latest crash.

**Comment by Sunekaer** [comment]
#320
