### ISSUE TITLE
Potion generator not working

### ISSUE THREAD

**Issue by Albertaco** [Sunekaer/stoneBlock#347]
**Bug Report:**
The potion generator from Extra Utilities 2 doesn't accept any potions. Please add recipes for this as it makes it impossible to use the rainbow generator, which there is a quest for.

**Steps to Reproduce:**
Try to put some items into the potion generator and it wont accept them.

**Client Information:**
- Modpack Version: 1.0.20
- Single Player World
- Optifine Installed: No
- Shaders Enabled: No

**Comment by Sunekaer** [comment]
#324
