### ISSUE TITLE
[1.0.20]Loot Bags - Server Crash

### ISSUE THREAD

**Issue by Lost-Ninja** [Sunekaer/stoneBlock#348]
## Steps to Reproduce (for bugs)

1. Open Uncommon Lootbags (lootBags Mod) in the opener or by hand.
2. By hand gives a server error (but server stays up mostly), in the machine the server quits...

## Logs

* Client/Server Log: https://www.dropbox.com/s/hf6fji0k5l9jmx5/stoneblock.1.0.20-server.log (Too big for free pastebin sorry. I can upload it elsewhere if needed.)
Server is Win10 with 4Gb allocated to the server.
* Crash Log: https://pastebin.com/V2vQ6dPc

## Client Information

* Modpack Version: 1.0.20
* Server/LAN/Single Player: Server/Lan
* Optifine Installed: nope
* Shaders Enabled: nope

It should be a clean install as I was having the same issue when I'd disabled a bunch of mods (and added Quark) trying with the default didn't improve things. :(

Superb pack otherwise though, just have to manage without those green bags for now.

**Comment by Lost-Ninja** [comment]
Forgot to mention that when opening them by hand I'm seeing an awful lot of stacks of gold horse armour (JEI suggests only 1) but seeing 8-12 in a single bag.

**Comment by Sunekaer** [comment]
#320
