### ISSUE TITLE
Slime sapling and bonsai pot problem

### ISSUE THREAD

**Issue by Aranak** [Sunekaer/stoneBlock#349]
## Bug Report
"Bonzai Trees Mod" Bonsai pot and Bonzai pot hopper dosen't work with Magma Slime Sapling, Purple Slime Sapling and Blue Slime Sapling, The recipe is well done in NEI. Slime Sapling are from "Tinkers' Construct".

## Steps to Reproduce (for bugs)

1.Plant sapling in one of the 2 kind of Bonsai pot

## Client Information

* Modpack Version: 1.0.20(Release) (test on 1.0.19(Beta) too)
* Server/LAN/Single Player: Single Player
* Optifine Installed:No
* Shaders Enabled:No
![sapling](https://user-images.githubusercontent.com/44117604/46906460-d44b6e00-ced1-11e8-90d3-8ac85529acd6.png)

**Comment by Aranak** [comment]
It's work on another map your right. But something somewhere is able to conflict with it with old map.

**Comment by Nazta** [comment]
Make sure it has enough empty space above it, or it wont grow.

**Comment by Aranak** [comment]
> Make sure it has enough empty space above it, or it wont grow.
8 air space over it it's not that for this exemple. But i will remember that.

**Comment by Aranak** [comment]
It's was a torch who take a air block Nazta was right you can close the post thank you very much everyone it's my fault.
