### ISSUE TITLE
Game crashing 1.0.20

### ISSUE THREAD

**Issue by GrownUpBaby** [Sunekaer/stoneBlock#351]
## Bug Report
Game has started crashing as of today, not sure what is causing it since it has happened a few times.

## Steps to Reproduce (for bugs)
Not sure what is causing it since it doesn't always happen when doing the same thing

## Logs
https://gist.github.com/GrownUpBaby/bf3dd15b05eac9e5cc0e760d4f5d016e
https://gist.github.com/GrownUpBaby/3e76ace62e9fc70accef16e193834d71
https://gist.github.com/GrownUpBaby/2edfa40b37e89ec95f0dee5a325e0868

## Client Information

* Modpack Version: 1.0.20
* Server/LAN/Single Player: single player
* Optifine Installed no
* Shaders Enabled: no

**Comment by ixanza** [comment]
From what I've been reading and from some youtubers that have experienced crashes. iChun's Hats mod has been causing weird issues with mobs going transparent and some hats that spawn together with mobs will actually crash the game. You can try disabling that if you don't care about the hats at all and see if you experience crashes still.

**Comment by GrownUpBaby** [comment]
alright, i will give that a shot. I actually did have a problem with some soul chickens that came through my nether portal that had gone invivsible

**Comment by Batou222** [comment]
Mine is crashing every time after a few seconds in game, logs show the loot bag opener causing the issue:
mal.lootbags.tileentity.TileEntityOpener.func_73660_a(TileEntityOpener.java:72)

-- Block entity being ticked --
Details:
	Name: lootbags:tileentityopener // mal.lootbags.tileentity.TileEntityOpener
	Block type: ID #2601 (tile.lootbags_loot_opener // mal.lootbags.blocks.BlockOpener // lootbags:loot_opener)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-991,90,-961)

**Comment by jc2xs** [comment]
> Mine is crashing every time after a few seconds in game, logs show the loot bag opener causing the issue:
> mal.lootbags.tileentity.TileEntityOpener.func_73660_a(TileEntityOpener.java:72)
> 
> -- Block entity being ticked --
> Details:
> Name: lootbags:tileentityopener // mal.lootbags.tileentity.TileEntityOpener

Batou222 your issue isn't related to the crash reported in this thread.  You should do some research and actually compare the crash reports to make sure it is the same issue.  Then if no other reports are found open a new bug report.

**Comment by WRFleete** [comment]
remove or rename the lootbags.cfg and Lootbags_BagConfig.cfg to get the config files to re build, it seems to have fixed the crashing issue for me

**Comment by GrownUpBaby** [comment]
I tried disabling the hats mod and I also changed the lootbag configs but I had a few more crashes.
Latest crash
https://gist.github.com/GrownUpBaby/48460a878e186e01eb07b802ab32bcb1

**Comment by GrownUpBaby** [comment]
I am having more crashes, I can only play on my world for a seconds before it crashes
https://gist.github.com/GrownUpBaby/ce5142f1c3cf2c6f4edfbe8ca51a4371

**Comment by GrownUpBaby** [comment]
I think I figured it out. It seems that the wireless energy thing from extra utilities was what was causing my game to crash. I was able to get my game to not crash long enough to remove it and I haven't crashes since.
