### ISSUE TITLE
Update 1.0.20 - lootbag opener crashes game

### ISSUE THREAD

**Issue by HiFiSi** [Sunekaer/stoneBlock#353]
## Bug Report
When running the latest update (1.0.20) if you run lootbags through a lootbag opener the game crashes.

## Steps to Reproduce (for bugs)
1. Put lootbag in loot opener (not sure if it is all lootbags or only specific colors that cause the crashing, I had them all being piped in so I couldn't tell which was causing it)
2. Game crashes

## Logs
* Client/Server Log:
* Crash Log: https://gist.github.com/HiFiSi/bcd7c1fb04fae0e21b6db939b5622cd5

## Client Information
* Modpack Version: 1.0.20
* Server/LAN/Single Player: Single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by leonexis** [comment]
See #320
