### ISSUE TITLE
Buildcraft oil spawning inside Compact machine rooms

### ISSUE THREAD

**Issue by deadterran** [Sunekaer/stoneBlock#354]
## Bug Report

[https://imgur.com/a/XvGxPZu](url)

Should exclude dimension 144 in config

## Client Information

* Modpack Version: 1.0.20
* Server/LAN/Single Player: SP
* Optifine Installed: No
* Shaders Enabled: No

**Comment by knoxhack** [comment]
Fixed in 1.0.21
