### ISSUE TITLE
Re-add EMC to Project E items such as collectors and relays

### ISSUE THREAD

**Issue by cpw** [Sunekaer/stoneBlock#355]
## Bug Report

The core EMC generation mechanic in Project E revolves around flowers of relays and collectors. The goal of traditional EE play is to feed EMC to create EMC. That isn't how this pack plays. A key missing ingredient is the lack of EMC values for the core EE tools: collectors and relays.

I would advocate for adding reasonable EMC values for the three tiers of relays and collectors, in line with material crafting costs in the draconic setup.

Note that other EMC values are missing in ProjectE as well - the dusts for example.

**Comment by knoxhack** [comment]
Fixed in 1.0.21
