### ISSUE TITLE
Update ExtraUtilities2 (Fixes startup crash)

### ISSUE THREAD

**Issue by Developaws** [Sunekaer/stoneBlock#356]
Forge in the latest version reworked it's potion registry, causing XU2 to not work.
This in turn causes the potion generator to stop working, and causes a startup crash if using Item Conduits attempting to insert items in.

Also fixes #324 

This was patched in: https://github.com/rwtema/Extra-Utilities-2-Source/commit/a3a75e56f036619e301337c58d871e06b0ff4af0

**Comment by knoxhack** [comment]
Fixed in 1.0.21
