### ISSUE TITLE
Super cheap infinity catalysts emc value

### ISSUE THREAD

**Issue by Minyguy** [Sunekaer/stoneBlock#358]
The infinity catalysts seem to have a very low emc value compared to the ingredients.
The emc value of the catalyst is 7 482 318.
You need a lot of stuff to make the catalyst.
The total emc value of the ingredients are 7 731 170 989 emc. 
(calculation link: https://paste.ee/p/YfLXK )
Calculation paste expires in one year.

The emc of the ingredients are literally more than a thousand times the infinity catalyst.
The whole point of the emc value system is equivalent exchange.
1 one = 4 planks = 8 sticks = 1 log
But this one is off the charts.

**Comment by mtjohnson47** [comment]
Personally, I figured that it burns up most the ingredients in crafting.

**Comment by Minyguy** [comment]
You mean throw the ingedienta in the table and take a thousand out right?

**Comment by Minyguy** [comment]
To me, one part of the modded minecraft is building factories for stuff. And I feel like something being cheaper to make using emc puts players who make factories at a disadvantage, since you use a lot more space aswell as using a lot more resources.

**Comment by Minyguy** [comment]
Even if the extra stuff vanishes, the value is still there. You dont get the value back. If you got like an item worth the rest of the emc when you crafted it then fine, but its just lost, nowhere to be found.

**Comment by bloorocksDotD** [comment]
I mean, avaritia is more of a joke grind-fest mod anyways, and "legitimately" getting, let's say, 64 catalysts would take hours if not days even with factories. The mod isn't meant to be serious or balanced in the first place so IMO it's fine to have a way to bypass waiting additional hours/days after you've made a single catalyst and if you don't wish to do it this way then just don't :)

**Comment by Minyguy** [comment]
When you have the infinity armor you are literally unkillable, with the exception of the kill command and the hole from the endest pearl. That should be expensive as fuck.

**Comment by Minyguy** [comment]
The sword of the cosmos can oneshot kill anything that isnt immune to oneshots.
This stuff is insane.

**Comment by PlacidK** [comment]
> 
> 
> You mean throw the ingedients in the table and take a thousand out right?

ehrm.. yeah (math-derp) :P

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)

**Comment by oliverjanik** [comment]
This is insane. 7 billion emc for infinity catalyst??? that's 52k diamond blocks.

Even with hundreds of emerald chicken roosts it's still hours to get one infinity catalyst. And you need hundreds to finish the questline.

This is not grind, this AFK for few months.

**Comment by Minyguy** [comment]
Have you seen how you craft it?

**Comment by Minyguy** [comment]
You need 25k diamond blocks, and 25k emerald blocks. Its meant to be insane.

**Comment by oliverjanik** [comment]
Except you made the creator change the value for everyone ;-) Which pack had 7 billion for infinity catalyst? Not even project ozone.

Again, have you finished the pack with this ridiculous value?

Unless there's a quicker way to generate EMC besides emerald chickens this pack's balance is broken now.

**Comment by Minyguy** [comment]
Not the mod creator, just the pack creator.
Besides, i have math on my side. If you want it to be cheap, atleast make it cheap all ways, not just the emc way.
I found the true emc value.
If you want to change it back for everyone, atleast suggest a recipie that corresponds with its emc value.

**Comment by Minyguy** [comment]
And if 46 days is too much, just make more 100 chickens is just 7 (6.25 rounded up) roosts. Just make more. Getting materials for roosts is easy with emc, use from the chickens you have. And make breeders to make more chickens, and seeds with emerald-emc. If you make 100 roosts, (total 1600 chickens) youre down to 3 days.
Listen, we're talking abour armor that makes you immortal. You're not meant to get this in hours. This is the stuff that marks the point where you have done everything.

**Comment by oliverjanik** [comment]
You misreading my posts. 100 chicken *roosts* full of 16 10/10/10 emerald chickens.

**Comment by Minyguy** [comment]
Oh ok, yeah i misread, but still. Its the absolute endgame. Its meant to be insane.

**Comment by oliverjanik** [comment]
@knoxhack pls revert to something attainable. 25 mil or so? If @Minyguy 's idea of fun is AFKing for weeks or crashing his computer with thousands of chicken roosts he can keep his insane number in his config 👍

**Comment by Minyguy** [comment]
Thats fine by me, but change the actual recipie accordingly.

**Comment by Minyguy** [comment]
My problem here, is that emc is based around equivelent exchange. Turning something into something else should cost as much as making it normally.

**Comment by OfficialStamper** [comment]
I think the problem here is SMP vs MSP.  Server players have the luxury of Chunk Loading with machines/roosts still producing whilst the player is offline.  SMP players need to remain online afk to keep production running.

**Comment by bloorocksDotD** [comment]
Make an RFtools dimension of emerald blocks and you'll have trillions of EMC

**Comment by Sunekaer** [comment]
Stop talking in closed issues, you have a problem open an issue not spam closed one
