### ISSUE TITLE
No pebble after breaking torch

### ISSUE THREAD

**Issue by domosplace** [Sunekaer/stoneBlock#36]
Bug Report
No Pebbles after breaking torch

## Steps to Reproduce (for bugs)

1. Breaking stone with open gives pebbles
2.Breaks torch no more pebbles
3 slot in tool bar. Everywhere else works.

Modpack Version:1.0.8
Single Player

**Comment by Sunekaer** [comment]
I cannot reproduce this
are you sure your using a empty hand to break the stone?

**Comment by domosplace** [comment]
I can reproduce this every single time on server and single player.

**Comment by Sunekaer** [comment]
can you send a video of this? or at screenshot of your hot bar

**Comment by knoxhack** [comment]
Fixed in 1.0.9!
