### ISSUE TITLE
(Suggestion) Add EMC value for neutron collectors

### ISSUE THREAD

**Issue by mtjohnson47** [Sunekaer/stoneBlock#360]
All the ingredients for the neutron collector have EMC values, so it's a matter of pulling them out, crafting, storing in ME, pulling out, .... over and over.  I suggest adding a value for the collector itself.

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
