### ISSUE TITLE
Refined Storage disks disappear when moved using wand

### ISSUE THREAD

**Issue by krisavi** [Sunekaer/stoneBlock#363]
## Bug Report
Moving Disk drive with moving wand removes disks.

## Steps to Reproduce (for bugs)
1. Use moving wand on Refined Storage disk drive to move it to another location
2. Disks have disappeared

(Unless you are able to restore disk from backup, then disk and it's contents are gone. When you are able to restore that disk id, then you will get the items back that were stored before moving, a bit too technical to give steps for this)

## Client Information
* Modpack Version: 1.0.20
* Server/LAN/Single Player: SP

Easiest way to avoid it appearing would be to put RS in wand blacklist.

**Comment by Sunekaer** [comment]
blacklisted disk drive and disk manipulator

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
