### ISSUE TITLE
EMC for Extra utilities gen but not working in Table

### ISSUE THREAD

**Issue by Tuvermage** [Sunekaer/stoneBlock#365]
## Bug Report
EX2 gens have an EMC value but the tablet can't learn them.

## Steps to Reproduce (for bugs)

1. make a EX2 gen
2. burn it in tablet
3. can't find the item

## Logs
no logs

## Client Information

* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server specifically ShapeTheCube
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by mtjohnson47** [comment]
I was just coming by to report this.  It also applies to ALL EU2 machines crafted with a machine block.

It's because they're all the same block with different metadata, and the EMC stuff wipes metadata.  Solution: Remove EMC values from EU2 stuff.

**Comment by Sunekaer** [comment]
Removed EMC from all EU2 gens but this also removes EMV from Machine Block FYI

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
