### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by bloorocksDotD** [Sunekaer/stoneBlock#366]
https://minecraft.curseforge.com/projects/extra-bit-manipulation

Great fun mod :)

**Comment by Sunekaer** [comment]
Not adding any mods unless, needed to fix issues/bugs, your welcome to add it your own single player world

**Comment by bloorocksDotD** [comment]
So hats & googly eyes are fine, and the normal chisel & bits is fine, but you don't wanna add *better* chisel & bits wot

**Comment by knoxhack** [comment]
The modpack is in a state that we are only doing Tweaks and bugfixes, we aren't adding any new gameplay based mod. Maybe for Stoneblock 2? Maybe
