### ISSUE TITLE
Forge detecting missing registry entries in a save from 1.017 when trying to open in 1.0.21

### ISSUE THREAD

**Issue by THEJaxster** [Sunekaer/stoneBlock#367]
Hello, I get "Forge Mod Loader detected missing registry entries." when trying to load a world created in 1.0.17.  I got the same error when trying to load the save into 1.0.20 but I decided to pass on the update till a later update.  Now that I have the same issue but with more entries on a newer update, I thought it would be good to see what could be done about it.

## Steps to Reproduce (for bugs)

1. Create a save in 1.0.17
2. Load the save from 1.0.17 into 1.0.20 or 1.0.21.
3. I will attach my save for easy viewing.
4. I just want to say thanks for the modpack, it has been quite enjoyable.
## Client Information

* 1.0.21
* Single Player:
* Optifine Installed: None
* Shaders Enabled: None
[StoneBlock 1_12_2.zip](https://github.com/Sunekaer/stoneBlock/files/2477295/StoneBlock.1_12_2.zip)

**Comment by Danklor** [comment]
What you see is normal and expected.  Mods were updated and some conflicts were disabled in configuration.  If you have those specific variants of items (mentioned in the startup message) in your inventory/storage they will be deleted by the update, but it would be more likely that you have the intended variants provided by other mods.  You can always /give yourself the equivalent of any lost items after upgrading.  Be safe and make a backup first in case anything goes wrong.

**Comment by THEJaxster** [comment]
I'm playing as survival, but I did enable cheats for this very reason.  I suppose this is normal for every update?  If so, Sunekaer please close this issue.  Thanks for your reply Danklor.
