### ISSUE TITLE
Resonator not working as expected

### ISSUE THREAD

**Issue by xSixGhost** [Sunekaer/stoneBlock#368]
## Bug Report

- When crafting Stoneburnt in the Resonator, if there's more than one item, when the GP amount is met, all the polished stone inside the resonator is converted to only 1 Stoneburnt.

Edit: This is happening with every recipe of the resonator, if there's more than one recipe in the resonator, once it completes the first one, the other recipes dissapear.

## Steps to Reproduce (for bugs)

1. Place more than one polished stone on the resonator
2. Crank the manual mill or wait until the GP requirement is met.
3. Resonator will convert all the polished stone into only 1 stoneburnt.

## Logs

* Client/Server Log: No log
* Crash Log: No crash log

## Client Information

* Modpack Version: 1.0.21
* Server/LAN/Single Player: Server
* Server connection: localhost
* Optifine Installed: N/A
* Shaders Enabled: N/A

**Comment by Lowbobkee** [comment]
Got same issue, also if i place hopper to crucible it starts eat stone like crazy.

**Comment by mthomas768** [comment]
Experiencing the same issue in a single-player game. Inserting multiple polished stone or weight pressure plates (to make stoneburnt or upgrade bases), produces a single item of the expected type.

Also running pack version 1.0.21. I didn't notice this issue in previous versions (but haven't used the resonator in a while).

**Comment by Nightcaste** [comment]
Also having this issue in 1.0.21

**Comment by bthrom** [comment]
Yes just updated to 1.0.22r1 and it fixed the issues I was having before updating.
