### ISSUE TITLE
refined storage items stuck

### ISSUE THREAD

**Issue by joosthoi1** [Sunekaer/stoneBlock#369]
## Bug Report
for some items in my refined storage system the items get stuck and i cant get them out, i tried breaking the controller and placing it back, placing the disks in the disk manipulator to transfer it to another disk, through my testing though it seems that the disks dont have anything to do with it

## Steps to Reproduce (for bugs)

1. i honestly dont know how to reproduce, what i do know is that it happened when i autocrafted the items, the items right now are: 2 wyvern energy core, 2 wyvern core and about 100 draconium, these were all autocrafted, there might be more items under the affect that i dont know of

## Logs
https://pastebin.com/nGP7mWf0
i could only do 500kb so not everything is in there (the file was 800kb) i doubt it will be of much use though

## Client Information

* Modpack Version: stoneblock-1.0.21 but it has happened on older versions aswell
* Server/LAN/Single Player: single player
* Optifine Installed: yes, but it happened in the past aswell without optifine, that time it magically got fixed though
* shaders installed: no

**Comment by Sunekaer** [comment]
Please report this issue to refined storage
