### ISSUE TITLE
two bugs actually found

### ISSUE THREAD

**Issue by Bass2style** [Sunekaer/stoneBlock#37]
## Bug Report
- first bug : you loose XP levels when coming back to the Overwold when you're going in the end, and coming back to the OW, it seems also problematic with the nether, but in a different way.
nether : XP is set to 0, but when you get XP, the levels come back, i think it's a synch issue, also seen in vanilla maps.
END : XP is set to 0, but when coming back, and getting XP, you only get the "new XP", the already obtained XP stay definitively lost.

- second issue : same issue than the XP, but with the extra hearts from Cyclic, but it's only happening with the end (saturation give the hearts back.), Nether Portal doesn't reset hearts.

- i found another issue : when your'e getting back from the DeepDark to the OW, you are spawning at  hight 255, streigth in the lava, a chance that i found a Fire Charm in a loot chest in the nether few hours ago, because without it, i died and y loose my stuff. (because graves spawns a dirt block, then the grave over it, dirt block should spawn at 255, and i shoud not have my grave because it's on 256, and you cannot build on that heigt.)

## Steps to Reproduce (for bugs)
a quick vidéo, seems more easily than explaining, i've a bad english, so, a vidéo seems more clear.
vidéo link : https://youtu.be/BJoXSq_cly4

for the deep dark, simply go to the DD dimension, then go back to the overwold. need to test this on another map, see if apening everytime.
edit : it's apening everytime, seems to TP you on the X and Z from the portal, but at Y255. (i put the portal on X:2 Z:2 Y:81 on my test world, iv'e respawn at X:2 Z:2 Y:255 in the lava), tested on a third world, same issue)

## Logs
not a crash, only a bug, so no logs to provide.

## Client Information

* Modpack Version: 1.0.8, but whas already present since 1.0.3 and later. (not tested before.)
* Server/LAN/Single Player: single player.
* Optifine Installed: nope
* Shaders Enabled: nope, no optifine. xD

edit : added a bug to the list. (DD bug.)

**Comment by Sunekaer** [comment]
for the second bug you write about, how do you get back? do you use the /island home or the portal?

**Comment by Bass2style** [comment]
the deep dark bug ? i use the portals in the 3 cases.

**Comment by dlswimmer** [comment]
Is there a way to restore inventory if the grave bug happens? Happened to me and I had a whole lot of stuff on me.

**Comment by Bass2style** [comment]
the only way i found is setting the gamerule KeepInventory to true for the reste of my map, but lost stuff is lost. (behalve stuff that not burns in lava. like some TiC stuff and draconic stuff seems also not burning in lava.)

**Comment by RedBlockFilms** [comment]
To restore your inventory, you can type /ob_inventory restore <playername> , and then press tab twice to fill in the rest

**Comment by Bass2style** [comment]
must try, because the grave isn't made, because the grave spawns at y256, and you can't build there.

**Comment by SynexWolf** [comment]
Extra Utilities 2 Deep dark is known for that issue, but it was never fixed. Only thing I can suggest is to avoid using the portal when going back to the overworld. 
https://github.com/rwtema/Extra-Utilities-2-Source/issues/119

**Comment by Sunekaer** [comment]
just tested again, the XP bug seems to be fixed? doesn't happen in my SP Test world, only had the normal Minecraft bug where it doesn't show the level, until you gained XP again
