### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by LynicTaken** [Sunekaer/stoneBlock#372]
https://hastebin.com/iqohalazod.rb
Here my crash log.
Release: Stoneblock 1.0.21 here > https://minecraft.curseforge.com/projects/stoneblock/files/2627736
I try;
•Redownload
•Restart
•Fresh setup
•Restart PC
•Update PC

**Comment by Sunekaer** [comment]
brandonscore is crashing you please create an issue on brandonscore´s issue page
