### ISSUE TITLE
Suggestion: Diet Hoppers

### ISSUE THREAD

**Issue by DerpityDoo** [Sunekaer/stoneBlock#374]
QOL thing, very useful for early game automation of tinkers smeltery, being able to look into the smeltery controller without removing the hopper on the front of it

**Comment by ArbitraryHubris** [comment]
sounds interesting, but I do wonder why folks don't put their controller on a corner so it can be hoppered from the side.

**Comment by Sunekaer** [comment]
We are currently no adding anymore game changing mods
