### ISSUE TITLE
[Suggestion] FastFurnace and FastWorkbench

### ISSUE THREAD

**Issue by TheSnowyChickens** [Sunekaer/stoneBlock#375]
## (Suggestion) Report
How about to add the mods "FastFurnace" and "FastWorkbench" ?

https://minecraft.curseforge.com/projects/fastfurnace
https://minecraft.curseforge.com/projects/fastworkbench

They are performance mods and should be in every good modpack. :)=

**Comment by Sunekaer** [comment]
Already been said no to those
