### ISSUE TITLE
1.0.22 won't launch

### ISSUE THREAD

**Issue by Sabster** [Sunekaer/stoneBlock#377]
![image](https://user-images.githubusercontent.com/5185451/46991114-6497d780-d0b9-11e8-8a6b-7a41fc33a1e7.png)

**Comment by Sabster** [comment]
Ooops - sorry, this is the server files

**Comment by c0nnex** [comment]
Same problem here. (linux)

**Comment by c0nnex** [comment]
The libraries coming with 1.0.22 Server are corrupt/wrong.
Delete the libraries directory, get the forge-installer and install forge freshly.
"java -jar forge-1.12.2-14.23.5.2768-installer.jar --installServer nogui"

**Comment by saulrh** [comment]
It looks like you can also merge the libraries in from an installation of the minecraft client, if you can't figure out how to point the forge installer at the right directory:

`rsync -a ~/.minecraft/libraries/ libraries/`

**Comment by Sunekaer** [comment]
Could you test if it’s the same problem with 1.0.22r1?

**Comment by Sabster** [comment]
Looks like server files are missing for 1.0.22 and 1.0.22r1?

**Comment by knoxhack** [comment]
fixed in 1.0.22r1
