### ISSUE TITLE
OreExcavation Dupe Glitch

### ISSUE THREAD

**Issue by RandomlyGenName** [Sunekaer/stoneBlock#378]
## Bug Report
OreExcavating a block that is allowed to ore excavate will double the amount of blocks

## Steps to Reproduce (for bugs)
1. Make a stone hammer or  stone crook
2. OreExcavate cobble, gravel etc or crook dirt and notice you get twice the amount of items you placed.

## Client Information

* Modpack Version: 1,0.22
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by RandomlyGenName** [comment]
I should note you get 4 less then double, for example if you place 1 stack of cobble and ore excavate it you get 1 stack + 60 gravel back

**Comment by RandomlyGenName** [comment]
It may have something to do with the realistic item drops mod

**Comment by RandomlyGenName** [comment]
Downgrading Realistic item drops to 1.2.12 fixed the issue

**Comment by Sunekaer** [comment]
Fixed in 1.0.22r1

**Comment by Sunekaer** [comment]
https://github.com/Funwayguy/RealisticItemDrops/issues/21
