### ISSUE TITLE
Bug: Extra Utils 2 Resonator deleting excess stack after first process finishes.

### ISSUE THREAD

**Issue by Zutaradimus** [Sunekaer/stoneBlock#379]
## Bug Report
The resonator from extra utils 2 is deleting the extra items placed in it while processing. IE; I put in a stack of polished stone and get a single stone burnt out of it.

## Steps to Reproduce (for bugs)
1. Place more than 2+ of an item in resonator
2. Wait for resonator to finish
3. Only receive a single item despite putting in multiple.

## Logs

* Client/Server Log:
* Crash Log: https://gist.github.com/Zutaradimus/421cf6f2533df0c46542133a80112677

## Client Information

* Modpack Version: 1.0.21
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by phit** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/commit/29c635c9f6bef78098ed2242312c9c6e1fd8ddf7

was already fixed by the mod dev and is fixed in the latest pack versions 1.0.22+
