### ISSUE TITLE
Painted Blocks Crash From "Uses" of Some Blocks - EnderIO + JEI

### ISSUE THREAD

**Issue by BaalSalmon** [Sunekaer/stoneBlock#38]
## Bug Report

It seems to be a rendering/graphical issue, that crashes my client. The item that gets rendered in the JEI "uses", is the "enderio:block_painted_stone_slab" (log says this), it all starts at line 6653 "[15:50:41] ... Can't Keep Up!..."). Might be a corrupted file if you can't reproduce. I've narrowed it down to the painting mechanic of EnderIO and JEI showing the uses of blocks, with a tab being EnderIO painting.

## Steps to Reproduce (for bugs)

1. See the "uses" (JEI recipen't) for blocks, such as redstone block, stone slab. Didn't find more, because I got tired of waiting 5 minutes each time it crashes.
2. If those don't work to crash, then something's messed up with my EnderIO files.

## Logs

* Client/Server Log: [2018-08-02-4.log](https://github.com/Sunekaer/stoneBlock/files/2255732/2018-08-02-4.log) 
Just thought uploading the file would be easier. It all starts at line 6653 "[15:50:41] ... Can't Keep Up!...")
* Crash Log: Not quite sure what log of the crash. If LCL wasn't it, then ^this^ would be.
Launcher Crash Log: https://pastebin.com/v7vvCw8v Dunno how this relates

## Client Information

* Modpack Version: 1.0.8
* Server/LAN/Single Player: Single Player
* Optifine Installed: nope
* Shaders Enabled: nope
I mean I'm running on 4.5 gigs being allocated and a CPU of 3 GHz, but I doubt that would make that crash happen.

Hope this was sufficient, thanks for reading.

**Comment by knoxhack** [comment]
Do you have a crash report?

**Comment by knoxhack** [comment]
Fixed in 1.0.9!
