### ISSUE TITLE
Bug: Mekanism Cardboard box item dupe

### ISSUE THREAD

**Issue by Seivee** [Sunekaer/stoneBlock#380]
## Bug Report

Using a Mekanism Cardboard box on a container will "break" the inventory and the items will pop out but leaving the Cardboard box placed and the contents still contained.
## Steps to Reproduce (for bugs)

1. Use the Cardboard box on a container e.g. Storage drawer or Storage crate

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.22
* Server/LAN/Single Player: Single Player
* Optifine Installed:
* Shaders Enabled:

**Comment by knoxhack** [comment]
could you provide a log?

**Comment by knoxhack** [comment]
https://github.com/aidancbrady/Mekanism/issues/5183

**Comment by Sunekaer** [comment]
Blacklisted all Storage drawers, use Packing Tape or something else to move it

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
