### ISSUE TITLE
InGameInfo Crash. Causes all server players to disconnect.

### ISSUE THREAD

**Issue by brehmluke** [Sunekaer/stoneBlock#381]
## Bug Report

Random crashing, It happens regardless of what I'm doing. When it happens it causes the all players on the server to disconnect. I'm running just Stoneblock, no extra mods. 
The exact error is Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host.
The server side says: FMLIndexedMessageCodec exception caughtio.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type com.github.lunatrius.ingameinfo.network.message.MessageSeed in channel ingameinfoxml
And goes on for a while with that error.
## Steps to Reproduce (for bugs)

1. Log in
2. Play for ~30min (The most recent crash was while I was doing ProjectE crafting using Draconic Infusion.
3. At some point I get force disconnected.
4. After disconnect I can log back in but I have no connection to the server and get disconnected shortly after(30-60 seconds)
5. After enough attempts I'm able to get back in then the pattern repeats.

## Logs

* Client/Server Log: 
Client: [latest.log](https://github.com/Sunekaer/stoneBlock/files/2481690/latest.log)
Server: 
[Server-latest.log](https://github.com/Sunekaer/stoneBlock/files/2481693/Server-latest.log)
[Server-debug.log](https://github.com/Sunekaer/stoneBlock/files/2481694/Server-debug.log)

* Crash Log:
No Crash log in the root directory or the logs directory. If I missed it let me know and I'll find it.
## Client Information

* Modpack Version: 1.0.22 (Been happening for the last 2 versions but its much worse now)
* Server/LAN/Single Player: Server (Owned by me)
* Optifine Installed: None
* Shaders Enabled: None

**Comment by nzminecraftDOTcom** [comment]
This sounds a lot like an issue I'm having on my server. 2 or 3 players are constantly logging in/disconnecting. Complaining of high ping etc, they are fine when at the spawn however.

**Comment by brehmluke** [comment]
I could see it looking like high ping for sure. Prior to disconnecting I'm unable to access chests, etc.
Server has low load during that time but after disconnecting me the server gets overloaded and even crashes the TeamSpeak server.

**Comment by Sunekaer** [comment]
Please report the issue to the mod dev
