### ISSUE TITLE
Ore Dictionary Bug

### ISSUE THREAD

**Issue by intrepid249** [Sunekaer/stoneBlock#382]
## Bug Report
Upon interacting with a cartographer in the Mining Dimension, he requested 9 emeralds and a copper ingot from Immersive Engineering. Only an immersive engineering ingot is accepted, it doesn't cycle between different ingots. But because of other mods installed, immersive engineering copper ore gets smelted into thermal expansion/industrial craft copper ingots. There is no entry for Immersive Engineering copper ingots in JEI, or the creative menu item list.

## Steps to Reproduce (for bugs)

As this is a villager trade, results may vary, but I can upload a screenshot if required
1. Create a portal for, and travel to the mining dimension
2. Find a village with a cartographer and trade with the cartographer until he offers the map reward
3. Check the items required to complete the trade

## Client Information
* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server (hosted from local machine using server files)
* Optifine Installed: no
* Shaders Enabled: no

**Comment by xILikepuddingx** [comment]
U can change it with Forge Lexico. Press V to empowering then change it

**Comment by Sunekaer** [comment]
Thermal and immersive copper ingot has same oredict.. no way in immersive config to change what it accepts, use the Lexico as xILikepuddingx said
