### ISSUE TITLE
New 1.0.21 server over-world just standard minecraft world

### ISSUE THREAD

**Issue by dahlellama** [Sunekaer/stoneBlock#384]
## Bug Report

I downloaded and ran the latest server pack and instead of a dank and dark cave I am greeted by grassy plains and fluid cows.

## Steps to Reproduce (for bugs)

Server is on Debian Linux 9.5 running Oracle Java (1.8.0_181) and using "screen" virtual terminal to allow running of server when not connected.  Client is Windows 10 with fresh install of 1.0.21 from twitch client.
On Server:
1. mkdir StoneBlock
2. cd StoneBlock
3. wget https://minecraft.curseforge.com/projects/stoneblock/files/2627736/download (Linux will resolve the file and save it as the filename download... very annoying, but it works.)
4. unzip download
5. screen
6. sh ./LaunchServer.sh
7. nano eula.txt (Change eula file to allow running)
8. sh ./LaunchServer.sh

On client:
1. Launch game
2. Connect to server
3. Stare at a Creosote Fluid Cow and wonder...

## Logs

* Client/Server Log: https://gist.github.com/dahlellama/7f5ff832cd5692cad21d5297cf690b1f
* Crash Log: no crashes

## Client Information

* Modpack Version: 1.0.21
* Server/LAN/Single Player: Server
* Optifine Installed: Whatever is there by default.
* Shaders Enabled: Whatever is there by default.

**Comment by Sunekaer** [comment]
what toxic said remember to delete the world after changing the setting so it can generate an new world
