### ISSUE TITLE
1.0.22r1 Items get swallowed by extra util generators when piped or hoppered in

### ISSUE THREAD

**Issue by Bitesizeweezy** [Sunekaer/stoneBlock#386]
Tested on heated redstone generator and culinary generator. Had items piping in without appearing in the inventory aswell as with hoppers. Sadly this was kind of inconsistent, but enough to be a big issue.

**Comment by RussIT99** [comment]
I have the same issue on overclock generator and possibly other generators too

**Comment by Albertaco** [comment]
Happens with all of the generators I believe. It happened with my nether stars :(

**Comment by Sunekaer** [comment]
#387
