### ISSUE TITLE
Extra Utilities 2 machines still not working right

### ISSUE THREAD

**Issue by Nightcaste** [Sunekaer/stoneBlock#387]
This is a followup to issue #368 

## Bug Report
ExU2 Enchanter eats items

## Steps to Reproduce (for bugs)
Place Enchanter and 15 bookshelves
Provide power to enchanter
Put a stack of iron ingots and 8 nether stars into Enchanter to make Evil Infused Ingots
Iron Ingots vanish, no output item is produced.

## Client Information

* Modpack Version:   1.0.22r1
* Server/LAN/Single Player:  SSP
* Optifine Installed:  No
* Shaders Enabled:  No

**Comment by Sabster** [comment]
I ran into something similar with Refined Storage and the extra utilities 2 furnace.  I would request something be 'cooked up' (with a pattern) and it would do 2-3 of the item - and no further ones.  I finally built up an Ender IO Alloy Smelter - moved the pattern and would get every item I requested.  

It doesn't look like it's using the machine at all.  I requested (for example) 8 dark glass (there a 2x2 sand/glass combination - that gets cooked) and the crafting monitor would show 2 of 8 - but when I checked the furnace, it was empty.  I did craft 2 of the items however - it just then stopped afterward.

**Comment by Strange-Account** [comment]
Hi,

I also have the similar issue that Extra Utilities 2 generators "eat" the items even when they are not running.

**Steps to Reproduce (for bugs)**

- Place the generator
- Configure to run with redstone signal
- Piping in items

**Comment by Sunekaer** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/issues/204
https://github.com/rwtema/Extra-Utilities-2-Source/issues/205
https://github.com/rwtema/Extra-Utilities-2-Source/issues/206

**Comment by Nightcaste** [comment]
Soaryn was streaming Ultimate Alchemy last night, and both the ExU2 Furnace and Crusher also had this issue, so it is confirmed to not be a Stoneblock problem.

**Comment by Sunekaer** [comment]
did you see all the link i just commented? i know its not an stoneblock problem

**Comment by Nightcaste** [comment]
I'm just providing more information.  No reason to take it personally.

**Comment by SkonerJR** [comment]
*anxiously spams refresh for this fix*

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)

**Comment by Dragon911XX** [comment]
Installed 1.0.23 beta to try out the fix, and it seems to persist.

**Comment by loupduqc** [comment]
Based on the change log, it seems like EU2 have not been updated in the 1.0.23 version of the pack
