### ISSUE TITLE
Woot Factory Ender Dragon not dropping Dragon Scale

### ISSUE THREAD

**Issue by Silwyn** [Sunekaer/stoneBlock#388]
## Bug Report

An woot factory for ender dragon does not drop dragon scales. The expected behaviour would be to get dragon scales just like when killing the ender dragon.

## Steps to Reproduce (for bugs)

1. Build woot factory tier 4 that spawns ender dragons.
2. Supply end crystals and power.

## Solution
Edit the config of woot to contain dragon scales as a drop for ender dragon.
I have edited the config and tested it out in SSP to check that it works. Link to my updated custom_drops.json https://pastebin.com/ft5cm8Vv

What was added to the drop list of the ender dragon is the following entry:
        {
          "drop": {
            "item": "mysticalagradditions:stuff",
			"data": 3
          },
          "sizes": [ 8, 16, 24, 32 ],
          "chances": [ 100, 100, 100, 100 ]
        }
You might want to adjust the drop size and chance though.

## Client Information

* Modpack Version: 1.0.22r1
* Server/LAN/Single Player: SSP
* Optifine Installed: No
* Shaders Enabled: No

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
