### ISSUE TITLE
Cable Facade - Glas recipe not working

### ISSUE THREAD

**Issue by TheSim14** [Sunekaer/stoneBlock#389]
Hey the recipe for Cable Facade - Glas doesn't working
http://puu.sh/BM3Ln/3391d900c8.png
http://puu.sh/BMshf/a93770feba.png

i cant find normaly glas facade in JEI
http://puu.sh/BMseN/80715bbe05.png

## Client Information

* Modpack Version: 1.0.22r1
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
