### ISSUE TITLE
Bringing up recipe menu crashes game

### ISSUE THREAD

**Issue by Ferny133** [Sunekaer/stoneBlock#39]
## Bug Report
When right clicking on blocks in the recipe page or pressing 'U' in inventory, game crashes.  It has happened the most with blocks of Redstone, but it happens with other objects as well

## Steps to Reproduce (for bugs)
1. When I press 'U' while hovering mouse on blocks of Redstone, in inventory or chests, to see which recipes they are used for, the game crashes. Also happens when right clicking on items in JEI to bring up "used for" recipes

## Logs
* Client/Server Log: https://gist.github.com/Ferny133/6461bf1cd610ef019d24e38832da65fa
* Crash Log: https://pastebin.com/eJihD2zN

## Client Information

* Modpack Version: Stoneblock 1.0.8 (Release)
* Server/LAN/Single Player: SP
* Optifine Installed: NO
* Shaders Enabled: NO

**Comment by knoxhack** [comment]
hey, I know how to fix this

**Comment by BaalSalmon** [comment]
I actually put up an issue about this right below this one, it has to do with JEI's uses of blocks being falsely rendered (i think) and the EnderIO panting mechanic.
How do you fix it knox?

**Comment by knoxhack** [comment]
Fixed in 1.0.9!
