### ISSUE TITLE
EMC values from Dye - to easy - Change it pls

### ISSUE THREAD

**Issue by xILikepuddingx** [Sunekaer/stoneBlock#391]
## Bug Report
Optimize EMC values from Dye. Because with the Atomic Reconstructor and a Lens of Color you can quite easily erupt EMC.

Suggestion: Change all to 16 or an other value

## Steps to Reproduce (for bugs)

1. Drop Cactus Green
2. Change it with Atomic Reconstructor and Lens of Color to Cocoa Beans or Lapis Lazuli
3. collect up
4. Repeat process

too easy to automate

EMC Values of dye:
Ink Sac: 16
Rose Red: 16
Cactus Green: 8
Cocoa Beans: 128
Lapis Lazuli: 864
Purple Dye: 440
Cyan Dye: 436
Light Gray Dye: 16
Gray Dey: 32
Pink Dye: 16
Lime Dye: 28
Dandelion Dye: 16
Light Blue Dye: 16
Magenta Dye: 16
Orange Dye: 16
Bone Meal: 48

If u need help i can help

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
