### ISSUE TITLE
Jetpack Hud Position

### ISSUE THREAD

**Issue by Coirt** [Sunekaer/stoneBlock#392]
Jetpack hud position is set to Default 0 and In Game Info XML blocks the HUD. I'd Recommend setting the config to 5 (bottom left). FYI requires a restart, does not set in the Mod Options.

**Comment by knoxhack** [comment]
What Jetpack are we talking about here? from what mod?

**Comment by TheSnowyChickens** [comment]
Simply Jetpacks maybe`?

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)

**Comment by Coirt** [comment]
Hmm seems to be still set to 0!

@knoxhack

**Comment by Sunekaer** [comment]
https://github.com/Sunekaer/stoneBlock/blob/d4cb96b5f6dc8a18b9027843a98ad59a016d5b4c/config/simplyjetpacks-client.cfg line 48

**Comment by Coirt** [comment]
This still has not been implemented. Its no problem changing it myself but it gets tiring changing it after each update! Its the principle though @knoxhack said it was implemented, slightly annoying when it is not the case.
