### ISSUE TITLE
Aluminum and Nickel ore and ore chunks

### ISSUE THREAD

**Issue by FeistyPancake** [Sunekaer/stoneBlock#394]
I would strongly suggest that both Aluminum and Nickel chunks be added to Mekanism's higher tier machines like the Purification Chamber, Chemical Injection Chamber and Chemical Dissolution Chamber as automation isn't possible with these yet.

**Comment by Sunekaer** [comment]
There is no Clump version of these metals in Mekanism, so thats why you can use those machines for those metals
