### ISSUE TITLE
Moving wand dupes Flux Networks Flux Storage

### ISSUE THREAD

**Issue by PlacidK** [Sunekaer/stoneBlock#395]
## Bug Report
https://github.com/romelo333/notenoughwands1.8.8/issues/28

## Steps to Reproduce (for bugs)
1. Place a Flux storage in your world
2. Grab it with a moving wand
3. See 1 (unconfigured) flux storage drop on the ground and 1 (configured) in your wand.

## Logs

* Crash Log:no crash

## Client Information
* Modpack Version: 1.0.22r1
* Server/LAN/Single Player: single player
* Optifine Installed: yes
* Shaders Enabled: no

**Comment by knoxhack** [comment]
Thanks for reporting it to mod author 👍

**Comment by Sunekaer** [comment]
blacklisting all flux items from wand

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
