### ISSUE TITLE
Item translocator, extra utilities 2 crusher problem

### ISSUE THREAD

**Issue by Jerkis** [Sunekaer/stoneBlock#397]
## Bug Report

I have a cobblestone generator teir 5 that makes 1 cobblestone every tick. Using the translocator to move the cobblestone to be crushed into gravel. Unfortunatly it isn't stacking rather anything I put in the crusher automatically deletes cobblestone in there if there is more than 1 cobblestone. 
Video: https://youtu.be/jQVPDpusbHA
## Steps to Reproduce (for bugs)

1. Have a teir 5 cobble gen, extra utilites 2 crusher, 2 item translocators
2. place translocators on the right and left side (blocks left and right, not your left and right) of the cobble gen and crusher (depending on how you place them)
3. Have the translocator that is on the crusher have it only look for cobblestone (if needed)
4. Push the translocator button on the trans locator and should be going really fast and stacking (as it should)

## Logs

* Client/Server Log: https://pastebin.com/AsGWgW7z Don't have unlimited space so I don't know if this helps.
* Crash Log: 

## Client Information

* Modpack Version: StoneBlock-1.022r1
* Server/LAN/Single Player: SIngle Player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by knoxhack** [comment]
Might be a Translocator bug, reported to mod author
https://github.com/TheCBProject/Translocators/issues/48

**Comment by imsomeguy** [comment]
Currently most Extra Utilities 2 blocks that accept any transfer/itemduct/other item movement (including shift click) do the same thing. It is a mod issue, not a modpack issue.

**Comment by Sunekaer** [comment]
#387
