### ISSUE TITLE
@server owners

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [Sunekaer/stoneBlock#398]
Just a quick question. When resetting your servers, how did you reset the island data, my players seem to spawn back where their old island was. Deleting the world, deleting and readding the mod/config don't seem to do anything. 
Many thanks.

**Comment by Sunekaer** [comment]
Deleting world folder is enough for me

**Comment by Sunekaer** [comment]
https://discord.gg/bMtYsGy 
this is the discord for the dev of the island mod
