### ISSUE TITLE
Roost and Chicken Breeder minus % values

### ISSUE THREAD

**Issue by DesmondTaylor** [Sunekaer/stoneBlock#399]
## Bug Report
Roost and Chicken Breeder from the Roost mod not behaving correctly, showing minus percentage values and randomly not giving output items.

## Steps to Reproduce (for bugs)
Place chickens in the Roost or Chicken breeder and watch the values randomly go into minus

Screenshot can be seen here -> [https://imgur.com/a/KsltGMF](https://imgur.com/a/KsltGMF)

## Logs
This does not crash or produce anything in the log so I didn't include this.

## Client Information
* Modpack Version: 21
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by BSchneppe** [comment]
duplicates: https://github.com/Sunekaer/stoneBlock/issues/216

**Comment by DesmondTaylor** [comment]
I didn't see that one but thanks I'll keep an eye out on there

**Comment by Sunekaer** [comment]
Roost wont be updated unless you want to loss them, because that will havent if you update
