### ISSUE TITLE
Making clay?

### ISSUE THREAD

**Issue by aequasi** [Sunekaer/stoneBlock#4]
ex nihilo defaults making clay to putting dust in a barrel. Is that changed in this pack? Can't seem to find a recipe

**Comment by aequasi** [comment]
This doesn't work in 1.0.2

**Comment by Sunekaer** [comment]
Quick fix go to Instances\StoneBlock\config\exnihilocreatio and delete FluidBlockTransformerRegistry.json and restart the game 
ill have this fixed in the next update

**Comment by Sunekaer** [comment]
https://minecraft.curseforge.com/projects/stoneblock/files/2580687

**Comment by MaxAstro** [comment]
This is still happening for me in 1.0.4.
