### ISSUE TITLE
Is There a Way to download a server for the pack? sorry new to github i dont know where to ask questions.

### ISSUE THREAD

**Issue by Chetttttt** [Sunekaer/stoneBlock#40]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: Version 1.0.9
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled:No

**Comment by DoXiOfficial** [comment]
I have the same problem.. i'm downloading the server files from the website, but when i try to open the server it doesn't start like i was supposed to do. Any fix?

**Comment by knoxhack** [comment]
Will look into this

**Comment by knoxhack** [comment]
Fixed in 1.0.9!
