### ISSUE TITLE
Lootbag Bug

### ISSUE THREAD

**Issue by wendictive** [Sunekaer/stoneBlock#400]
Server
only detected on server 1.0.20

Automatic opening of lootbags via the lootbag opener or mechanical User results in a crash from the block that opens. my server admin told me that it creates a -number for the choosing of the random content for the specific lootbag wich causes the crash
doin this by hand on a chest dos not crash server

**Comment by DesmondTaylor** [comment]
It's an issue with something that is in one of the loot bags. Updating to v1.0.21 has a fixed config file for it. Hope this helps.

**Comment by wendictive** [comment]
ty very much il tell my admin
