### ISSUE TITLE
Extra Utilities 2: Resonator with lots of polished stone give 1 stoneburnt

### ISSUE THREAD

**Issue by Provocatore9090** [Sunekaer/stoneBlock#403]
## Bug Report

ExU2 Resonator problem with polished stone
## Steps to Reproduce (for bugs)

1. I insert more than one piece of Polished Stone into the Resonator
2. I use the Manual Mill to make it work
3. When the process is completed, I receive only one piece of Stoneburnt

## Logs

No Logs, sorry :(

## Client Information

* Modpack Version: 1.0.21
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by mskoczen** [comment]
Duplicate of issue https://github.com/Sunekaer/stoneBlock/issues/368
