### ISSUE TITLE
World breaking bug with Shear Madness

### ISSUE THREAD

**Issue by AtomicBlom** [Sunekaer/stoneBlock#404]
## Bug Report

It had come to my attention that my mod Shear Madness had a bug that will crash servers and clients and render the world unloadable due to an API change in Chisel/CTMLib.

I've just released a version of the mod (1.7.2.4) to CurseForge which addresses this issue, fixed by https://github.com/AtomicBlom/ShearMadness/pull/43

## Steps to Reproduce (for bugs)

1. Insert a block from the Chisel mod into the chisel
2. Right click on a sheep
3. Observe that the world crashes
4. Observe that the world cannot be loaded.

## Logs

* Crash Log: https://pastebin.com/JPDxTdge

## Client Information

* Modpack Version: 1.0.22
* Server/LAN/Single Player: All
* Optifine Installed: No
* Shaders Enabled: No

**Comment by knoxhack** [comment]
Thanks a lot for the fix, will be added to next update

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
