### ISSUE TITLE
aroma1997sdimension_gen.json is in need of an update

### ISSUE THREAD

**Issue by doppelhelix** [Sunekaer/stoneBlock#405]
This is an error reported to aroma1997 at [https://versioned.temporary.solutions/AromasMods/MiningWorld/issues/179](https://versioned.temporary.solutions/AromasMods/MiningWorld/issues/179)

The **clay_ore identifier** is duplicated as the first and fourth oreGen section

The sticky_ore identifier reads

    "ore": "minecraft:emerald_ore"
but it should read
 
    "ore": "aroma1997sdimension:miningore:0"

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
