### ISSUE TITLE
World breaking - Industrial Foregoing Potion Brewer

### ISSUE THREAD

**Issue by dbridle** [Sunekaer/stoneBlock#406]
Version : 
Pastebin of error loading world: https://pastebin.com/kBhjV6vg
1.0.22r1

Description of the issue:
Recently upgraded to 1.0.22r1.

Seting up automation for the Potion Brewer to create Crystal Growth blocks.  I had Awkward potions automatically being pumped in.  As soon as one of the potions hit the brewer, the pack crashed, since then the world has been unable to be opened.

Steps to Recreate:
1. Add a potion brewer
2. Use some fluiduct's and a signalum servo, pulling water from a sink, into the potion brewer
3. Add a stack of nether wart and glass bottles
4. Awkward potions are made, extract using itemducts and a signalum servo into a chest
5. Extract from chest using itemducts and a signalum servo back into the brewer
6. Open the brewer... crash.

**Comment by dbridle** [comment]
Reported error with mod author:

https://github.com/Buuz135/Industrial-Foregoing/issues/445

**Comment by Sunekaer** [comment]
remove the block in 1.0.25, will be enable again once its fixed

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
