### ISSUE TITLE
Bad FPS in the Mining World, because particles.

### ISSUE THREAD

**Issue by TheSnowyChickens** [Sunekaer/stoneBlock#408]
## Bug Report
Far too many particles in the underground in the mining world. (=-> decreased FPS)

If I turn the particle option to "minimal", the performance is better/okay.
(the potion effect particles are away, but the "dust" particles not)

Its diffucult to see in the pictures, but 75% from the underground is full with particles.
![2018-10-19_21 17 52](https://user-images.githubusercontent.com/29357962/47239164-ce2f2300-d3e4-11e8-9e7e-91e77a76e519.png)

![2018-10-19_21 17 56](https://user-images.githubusercontent.com/29357962/47239169-d0917d00-d3e4-11e8-8341-afef1add647c.png)

## Steps to Reproduce (for bugs)
1. go in a mining world

## Logs
My lastest:
[2018-10-19-5.log.gz](https://github.com/Sunekaer/stoneBlock/files/2497086/2018-10-19-5.log.gz)

## Client Information
* Modpack Version: 1.0.22r
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Scratchman** [comment]
too many bee hives. edit the config/aroma1977/aroma1997sdimension_gen.json and change the amount of beehives in each entry ... "amount": 3, to "amount": 1, also regenerate the mining dim or get away from old terrain.

**Comment by TheSnowyChickens** [comment]
Ah okay, thx.

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
