### ISSUE TITLE
Refined Storage (Mod Issue)

### ISSUE THREAD

**Issue by Evansj306** [Sunekaer/stoneBlock#409]
Please feel free to contact me if you need any additional 
information and thanks for making my dream mod pack! :)
## Bug Report

Refined Storage causes a crash when a crafter attempts to export to an inventory with not enough space.
## Steps to Reproduce (for bugs)

1. Setup a pattern in Refined Storage Crafter for two different types of items (Ie. Stone and Stone Bricks create log).
2. Place pattern in a crafter targeting a mini chest.
3. Attempt to use the recipe.
4. Crash occurs.

## Logs

* Client/Server Log:
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2497777/latest.log)
Crash Log: 
[Crash.txt](https://github.com/Sunekaer/stoneBlock/files/2497778/Crash.txt)

## Client Information

* Modpack Version: "1.0.22r1"
* Server/LAN/Single Player: Singler Player (I hope this doesn't crash Multiplayer servers)
* Optifine Installed: Default (If it is in the default pack)
* Shaders Enabled: Default (If they are enabled by the pack)

**Comment by Sunekaer** [comment]
Please report it to refined storage
