### ISSUE TITLE
Missing EMC for Blaze Powder

### ISSUE THREAD

**Issue by nrllewellyn** [Sunekaer/stoneBlock#410]
## Bug Report
There is currently no EMC value for blaze powder, which prevents a number of other items that use it as a component from having EMC values. (tier 6 solar panels, anything based on ender eyes, pyrotheum, dislocators, etc.)

## Steps to Reproduce (for bugs)
N/A

## Logs
N/A

## Client Information
* Modpack Version: 1.0.22r1
* Server/LAN/Single Player: Any
* Optifine Installed: No
* Shaders Enabled: None

**Comment by nrllewellyn** [comment]
This also applies to draconium, although that may be intentional.

**Comment by knoxhack** [comment]
Implemented in StoneBlock-1.0.23 [(https://minecraft.curseforge.com/projects/stoneblock/files/2629767)](https://minecraft.curseforge.com/projects/stoneblock/files/2629767)
