### ISSUE TITLE
Moving Wand deletes items from Refined Storage

### ISSUE THREAD

**Issue by Ladysarajane** [Sunekaer/stoneBlock#413]
## Bug Report
Moving the disk drive from Refined storage deletes the drives that in the Disk drive and it's items

## Steps to Reproduce (for bugs)

1.Have a Refined Storage disk drive filled with drives and those drives filled with some items.
2.Have a Moving Wand
3.Move Disk drive with moving wand to new place
4. Cry when you see that your Drives in you disk drive are missing along with your items

## Logs

* Client/Server Log: No crash Log
* Crash Log:

## Client Information

* Modpack Version: 1.0.22r1
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Ladysarajane** [comment]
I also moved a crafter with the moving wand and my patterns that were in there disappeared.

**Comment by Sunekaer** [comment]
Duplicate

**Comment by perlguy** [comment]
This IS a partial duplicate of the other RS moving wand bug report, but you haven't blacklisted the crafters from the move wand (as of modpack version 1.0.25) and they still delete contents when picked up with moving wand.
