### ISSUE TITLE
Lootbag opener causes crash

### ISSUE THREAD

**Issue by Dee-Fuse** [Sunekaer/stoneBlock#414]
## Bug Report

Game crashes randomly when opening lootbags in the lootbag opener. 
To reopen the world, the lootbag opener has to be removed with MCEdit.

## Steps to Reproduce (for bugs)

1. Craft Lootbag opener
2. insert Lootbags

## Logs

* Client/Server Log: https://pastebin.com/AVm46hj6
* Crash Log:

## Client Information

* Modpack Version: 1.0.21
* Server/LAN/Single Player: LAN
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Update the pack
