### ISSUE TITLE
Spectre coils not working

### ISSUE THREAD

**Issue by JayJay1989** [Sunekaer/stoneBlock#416]
## Bug Report
Spectre coils not working except for the coils from lootbags

green (from lootbag): http://prntscr.com/l8c3z6
blue: http://prntscr.com/l8c4sd
red [redstone]: http://prntscr.com/l8c515
purple[ender]: http://prntscr.com/l8c5co

## Client Information

* Modpack Version: v1.0.22r1
* Server/LAN/Single Player: server, client & lan
* Optifine Installed: no
* Shaders Enabled: no

**Comment by knoxhack** [comment]
Could you try 1.0.23?

**Comment by Sunekaer** [comment]
Only the green one generates power, the other transfers read the tooltip on them for more info
