### ISSUE TITLE
game crash while start 

### ISSUE THREAD

**Issue by liormalol** [Sunekaer/stoneBlock#419]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by Sunekaer** [comment]
No information given

**Comment by liormalol** [comment]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)

that what it say to me
