### ISSUE TITLE
Mod Rejection when making the server.

### ISSUE THREAD

**Issue by Sir2Medis** [Sunekaer/stoneBlock#42]
## Steps to Reproduce (for bugs)

1.Start the modpack on version 1.0.9
2.Log into server
3.this error: https://gyazo.com/ddb6cdd0dda15a944306d32b5f6d667c

## Logs

Not a crash, it's a file Bug so no crashlog

## Client Information

* Modpack Version: 1.0.9
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Sir_MedisToday at 1:09 PM
on the previous version of the pack i had to same issue but then i was able to fix it by manually adding toomanybackups version 1.0.0 but now in this version adding toomanybackups version 1.0.2 does not fix the mod rejection.
@Sunekaer  sorry for the ping but i kind of wanna fix it cuz i wanna play haha
SunekaerToday at 1:18 PM
when you add a mod server side it also need to be on client side
Sir_MedisToday at 1:18 PM
i didnt add a mod server side that is the issue
i just installed instance from twitch desktop and exported that instance and added that on my server
Creeperhost server
SunekaerToday at 1:20 PM
log on to your host and check your server files
check the mod folder to be sure that the mod isnt there
Sir_MedisToday at 1:21 PM
https://gyazo.com/d88e08d45500f6e1c6b78f699c4c6add
Gyazo
Gyazo
​

its not there
its really just a clean instance on my server that i exported from twitch desktop
SunekaerToday at 1:24 PM
the thing is
you have to contact creeperhost
looks like they automatically add that mod to there servers
you have a mod in the list called toomanytarvii-1.12.2
did you add that?
Sir_MedisToday at 1:26 PM
no i did not add that
i didnt change anything
SunekaerToday at 1:26 PM
thats not default in the pack
remove that
Sir_MedisToday at 1:26 PM
ill try thanks
:smile:
i will let you know if that worked
SunekaerToday at 1:27 PM
thanks
Sir_MedisToday at 1:33 PM
@Sunekaer  that fixed it, thanks man!
SunekaerToday at 1:33 PM
np
