### ISSUE TITLE
Gold chickens produce gold nuggets instead of ingots

### ISSUE THREAD

**Issue by ixanza** [Sunekaer/stoneBlock#427]
## Bug Report
Gold chickens from Roost produce gold nuggets instead of gold ingots like other chickens

## Steps to Reproduce (for bugs)
1. Get Gold Chicken
2. Place Gold Chicken in Roost
3. Get Gold Nuggets instead of Ingots

## Logs
![image](https://user-images.githubusercontent.com/5535758/47265691-8b915600-d55e-11e8-9e9c-462b7e633b2e.png)

## Client Information

* Modpack Version: 1.0.23
* Server/LAN/Single Player: Private Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
intended

**Comment by CharCharthemonkey** [comment]
umm just saying but i talked with the mod dev and he said that was a bug in 1.10.2 that should of been fixed cause it was intended to drop ingots not nuggets as of the 1.10.2 version lol
