### ISSUE TITLE
Items placed into Transumation table turn into default ones

### ISSUE THREAD

**Issue by JackRuby1** [Sunekaer/stoneBlock#429]
So I've just recently crafted the Transumation table and have throwing things in, I noticed that a lot of items are going to their basic forms when placed inside of the it or changing types. Namely the Mekanism cables that have EMC, they are all changing back to their basic forms and not the ultimate versions of themselves I placed into the table. Another problem I found was that I put in Spruce drawers/trim into the Transumation table and it's only showing me Oak, and I've never taught it the Oak variant of them.
The Thermal Expansion Magmetic Dynamo fully reinforced has dropped down to it's basic form as well when placed inside of it.

**Comment by xILikepuddingx** [comment]
its because of the nbtt data. the table cant read it

**Comment by Sunekaer** [comment]
Like pudding said the table and tablet doesn’t support nbt data
