### ISSUE TITLE
Crashing when searching for "Sp...."

### ISSUE THREAD

**Issue by swinhufvud** [Sunekaer/stoneBlock#432]
## Bug Report
Game crashes when i NEI get the search word "Sp". for example, if i gonna try search for Spoon or Spectra the game freezes just after the P. To keep playing again i need to delete search in NEI config. 

## Steps to Reproduce (for bugs)
1. starting the game
2. playing whit no problems
3. searching for Spectra coil
4. crash,.

## Logs
latest.log --> https://gist.github.com/swinhufvud/24bf6588c14682787dbdf5db2246973d
debug.log --> https://gist.github.com/swinhufvud/7d50e3d15430a9361e4033ad235dfbf0

## Client Information
* Modpack Version: 1.0.23
* Server/LAN/Single Player: sp
* Optifine Installed: not by me
* Shaders Enabled: not by me

**Comment by Sunekaer** [comment]
Crash log?

**Comment by swinhufvud** [comment]
> Crash log?

Game freezes so the server dont output any crashlog =/ i tried leave it on for 18h for the game to realize it crashed so i could get a crashlog, but no success. Thought it was RAM related at first. Had runt on 6gb at first. Incressed to 8, 10, 12... even decreesed to 4 but same result.

**Comment by Sunekaer** [comment]
i cant recreate this problem :S i use 8gb

**Comment by Grovert11** [comment]
I have this exact same issue!
If I restart my client after a freeze like this, I can't open any GUI without it crashing again. Overwriting all the config files with the ones from the override folder, fixes it, so I can play again, until I accidentally search for this combination again.

**Comment by mlpcoder** [comment]
Same thing happens for me if I: 1) type too quickly, 2) Type @

**Comment by neogia** [comment]
Just reporting in that I have the same issue recently when typing '@' to search by mod. It works *okay* but very very laggy in JEI and in a Refined Storage grid search bar, it actually freezes the entire client. No crash log since it seems to just soft lock.

**Comment by knoxhack** [comment]
@swinhufvud This seems like a JourneyMap bug, can your try to replicate with JourneyMap unistalled?

**Comment by iDarper** [comment]
> 
> 
> Just reporting in that I have the same issue recently when typing '@' to search by mod. It works _okay_ but very very laggy in JEI and in a Refined Storage grid search bar, it actually freezes the entire client. No crash log since it seems to just soft lock.

I also get this crash, and updating jei didn't help.

**Comment by griseouslight** [comment]
> @swinhufvud This seems like a JourneyMap bug, can your try to replicate with JourneyMap unistalled?    

Having exactly the same issues as @swinhufvud, removing JourneyMap had no effect.

For me, I don't need to delete the search, and I can even still do the search if I don't type the characters exactly like that. An example would be typing "s p" and then deleting the space.

**Comment by griseouslight** [comment]
setting `B:"attemptRecoveryOnItemRenderException"` in codechickenlib.cfg from false to true seems to prevent this from happening to me. I don't believe this is an effective permanent solution, however.

I turned it on due to the warning `[JM-task-4/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.` being the only error I'd have anywhere near the time before the game freezes.
Here's the [debug.log](https://puu.sh/BX8PT/fe73a5991a.log). It didn't crash, but it doesn't crash even when the issue happens, you have to force exit...

**Comment by Sunekaer** [comment]
Sorry about the delay, but it sounds like a low RAM issue and if assigning more doesnt help its something that JEI needs to look at 
https://github.com/mezz/JustEnoughItems/issues?q=is%3Aissue
