### ISSUE TITLE
Hemp Seeds?

### ISSUE THREAD

**Issue by BrockDierksen** [Sunekaer/stoneBlock#433]
Idk if there is a way to get hemp seeds for Immersive Engineering.

**Comment by TheSim14** [comment]
> Industrial Hemp Seeds are seeds added by Immersive Engineering. They are obtained by breaking Grass. Planting them on tilled soil plants Industrial Hemp. 

Just place dirt and use Grass Seeds u get them by siev dirt and then use bonemeal :)
or if you already have access for the miningdimension (Aroma) and use bonemeal their :3

**Comment by Sunekaer** [comment]
Like TheSim14 said
