### ISSUE TITLE
1fps throughout half of my base

### ISSUE THREAD

**Issue by Jerkis** [Sunekaer/stoneBlock#434]
## Bug Report

When I walk in a certain part of my base it lags really badly no matter what I do. I restarted my computer and Minecraft many times and still have a problem. 
## Steps to Reproduce (for bugs)

1.  https://youtu.be/wcaWprx5-fA 
2.

## Logs

* Client/Server Log:
* Crash Log: 
https://gist.githubusercontent.com/Jerkis/25878c186806e55395afe79d66572d00/raw/22f4e2e70e0641411f37bd9010de08a2a5ef645c/2018-10-21-7.log (Couldn't able to get it to work with the unraw version)
## Client Information

* Modpack Version: latest version
* Server/LAN/Single Player: SIngle player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Jdreioe** [comment]
Do you have a mob farm? If so, the items could be lagging the server out. This happent to me

**Comment by nzminecraftDOTcom** [comment]
Crystal chests etc entities and animals/mobs try adding the threshold mod to your game it may help clear any ground drops

**Comment by Jerkis** [comment]
Apparently, my extreme vector plates were to fast for the absorption hopper to pick up. I got it sorted out. Thanks guys!

**Comment by Jerkis** [comment]
Also having Void upgrades doesn't delete the items as it should. The interaction between absorption hopper and void upgrade is that it will count it as full and won't go into it.
