### ISSUE TITLE
game keeps crashing

### ISSUE THREAD

**Issue by AlwaysStijn** [Sunekaer/stoneBlock#436]
## Bug Report

the game keeps randomly crashing, sometimes it crashes the moment it loads the world, sometimes when i'm doing stuff, sometimes even when i'm afk
## Steps to Reproduce (for bugs)

1. just doing stuff, for instance sometimes when i open my refined storage, sometimes just flying around
2.

## Logs

* Client/Server Log: https://gist.github.com/AlwaysStijn/c14288eeb2003956d3ff23a0699bcd7a
* Crash Log:

## Client Information

* Modpack Version: 1.0.20
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
Crash log?

**Comment by AlwaysStijn** [comment]
I'll send it this evening, at school atm

Op di 23 okt. 2018 08:37 schreef Sunekaer <notifications@github.com:

**Comment by AlwaysStijn** [comment]
this is the crashlog, the only thing i understand about it is that it's something about lootbags.
https://gist.github.com/AlwaysStijn/fcbed356b7783feb15e37def111aced0

**Comment by Sunekaer** [comment]
update your pack version
