### ISSUE TITLE
Crash upon world launch

### ISSUE THREAD

**Issue by Jdreioe** [Sunekaer/stoneBlock#437]
## Bug Report
Game crashes upon world launch
I tried updating the modpack for a fix, but didn't fix the issue.
## Steps to Reproduce (for bugs)
1. I tried brewing a potion with the brewer from Industrial Foregoing after being unable to brew with the brewing stand.
2. The game crashes.
## Logs
* Client/Server Log: https://gist.github.com/Jdreioe/001e5e82ac3b72a6be8e24c0e3cd2b13
* Crash Log: https://pastebin.com/LGTHWes3

## Client Information

* Modpack Version: 1.0.23
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No
* 6 gb ram
* GTX 1060
I've provided my world as a zip.
World: https://drive.google.com/file/d/10Xk0JbGy9r4q5St2WcEmUNq1x5nVgcXX/view?usp=sharing

**Comment by Sunekaer** [comment]
Duplicate #406
