### ISSUE TITLE
Mod Compact Machines 3

### ISSUE THREAD

**Issue by ViZualEco** [Sunekaer/stoneBlock#440]
## Bug Report
Can not put the item tunnel on the compact machine maximum size block. Was able to place the tunnel on the inside of the compact block but not on the outside. Whenever I use the tunnel on the outside the block it just shows the enderman inside the block. I haven't place anything inside the block. I have tried to place it in a single player world. It also didn't work. 

## Steps to Reproduce (for bugs)

1. Just place down the maximum compact block and try to place a tunnel on it. It will just a preview of the block. 

## Client Information

* Modpack Version: The 1.0.22r1
* Server/LAN/Single Player: Sever (host scalacube)
* Optifine Installed: No
* Shaders Enabled: No

**Comment by P4t0r1kku** [comment]
Becouse you just need the Tunnel Inside. Place it wherever you want, klick on it to choose the Outside-Side. Done. I'm using it fpr Applied Energistics and allll the Chickens :D

**Comment by Sunekaer** [comment]
Please test the answer above
