### ISSUE TITLE
Game takes 40 minutes to launch and make a world, which is just lava.

### ISSUE THREAD

**Issue by Vnummela1** [Sunekaer/stoneBlock#441]
Ok so I'm having an issue with my Stoneblock. I installed 64-bit java and installed the minecraft mod through the twitch-app. Started the game through twitch and set the java argument in the settings menu in the launcher to allocate 16 of my 32 Gb of ram to the game, like I usually do.
After I waited for the game to load and lag out for around 40 minutes I finally got into the main menu and just started a regular minecraft survival world on Void? world type.

It took my i7-6700k pc atleast another 30 minutes to generate and launch the minecraft world. I waited and watched as the program went in-and-out of "not respoding" status in task manager and when it finally presented me the minecraft world, I was on fire in a world made of just lava, holding the quest-log item. The game gave me around 1-2 FPS and making any adjustment to the camera or pressing any button (sadly even F3) would crash the game and return me to the launcher with no error code. 

I tried this a few times, also changed the ram between 16gb, 8gb and 12gb, good thing is that now loading the world only takes around 20 minutes instead of the initial 30.

Im going to keep fiddling around with the settings/reinstalling stuff while I wait...

I suspect that this is a known issue, I just didnt find it on here...

Steps to Reproduce
1. Fresh java-64 bit (as of 23-10-2018)
2. Install modpack through Twitch-app
3. Launch and play the modpack.
4. Fresh world I guess...
5. Swim in lava :) (not a joke, read the description above)
## Logs
 Crash Log: 
part 1 https://pastebin.com/ybVfF9nQ
part 2 https://pastebin.com/XQQr46fz

* Modpack Version: 1.0.22r1
* Server/LAN/Single Player: Solo
* Optifine Installed: nope
* Shaders Enabled: nah

**Comment by ArbitraryHubris** [comment]
2 things:
1) You don't need 16gb of ram for java for any modpack in existence.  Java is really weird in that if you give it a ton of RAM, it will fill it up with variables, functions, etc., which are no longer referenced and wait longer to collect the garbage.  This make it perform worse than if you just gave you java launcher 6gb.  Give it 6-8gb for any pack and you'll be happier.  I don't think this is your problem, though.
2) have you tried just using the default world settings?  If you're setting up a server, you need the void_world world type, but in single player, you can just use default.  I'll also be surprised if this is your issue, but it's something quick to try.

good luck - it's a fun pack.

**Comment by Sunekaer** [comment]
could you try with default arguments and between 6 and 8 gb of ram

**Comment by Vnummela1** [comment]
With default argument (1gb) even "historical" versions of minecraft crash before a world can even load for me. But with 16gb setting everything runs best and works flawlessly on vanilla.

I did try generating a whole bunch of worlds, but usually its just falling out of the map at 1-2fps or death by lava at 2-3fps.
I used a roll-back version of java by manually setting the launcher to use it, I also tried it with the newest 64bit java ive installed a few times over now... 
After any kind of "repair game" kind of options or just reinstalling the pack or twitch app, Im still getting the same crap or loading in for an hour and then giving me just the same: 
lag and go "not-responding" while loading for 30 minutes -> slide-show of lava or fall out of the world -death -> crash if anything is pressed or mouse moved.

**Comment by Vnummela1** [comment]
> Make sure that
> 
> 1. you dont have to much back ground stuff going on
> 2. I have a 3.5 CPU so make sure that you pc setting on on high are better the low setting
> 3. you might want to change your RAM
> 
> the only other thing i can tell you is just hold one day someone will post a video on how to fix it

1. Checked that Im not running anything that would interfere at the same time yes.
2. and 3. The settings dont matter at all when the whole game doesnt run correctly. Also my 6700k is 4.5GHz overclocked and very powerful processor, so the hardware isnt the issue. Ive been playing on this system for almost 3 years now and I dont think that a minecraft mod is enough to make my system choke down to 1-3 fps ON MINECRAFT.

**Comment by Smario9000** [comment]
did you also check to make sure everything is up-to-date

**Comment by grandrolf** [comment]
This is from your log:
-Xmx16G -Xmx3072m

You have conflicting parameters.

How and where are you changing the java parameters?

Instructions for doing this via the Twitch app:
https://imgur.com/a/R9eKA
(remove everything else and try again)

Also, if you installed the latest java 8 64-bit on your system, make sure to set the launcher to use that as well.
https://imgur.com/a/0wVhh

Then do a repair of the pack, and **if you still have issues, post new logs.**

**Comment by Smario9000** [comment]
-Xmx13072m -Xms1256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C\...\StoneBlock" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

This is what i used
... = the path to the mod folder

**Comment by Smario9000** [comment]
> This is from your log:
> -Xmx16G -Xmx3072m
> 
> You have conflicting parameters.
> 
> How and where are you changing the java parameters?
> 
> Instructions for doing this via the Twitch app:
> https://imgur.com/a/R9eKA
> (remove everything else and try again)
> 
> Also, if you installed the latest java 8 64-bit on your system, make sure to set the launcher to use that as well.
> https://imgur.com/a/0wVhh
> 
> Then do a repair of the pack, and **if you still have issues, post new logs.**

That might by why

**Comment by nzminecraftDOTcom** [comment]
The Twitch launcher tells the game how much memory to use, not the Minecraft launcher, do as mentioned above.
