### ISSUE TITLE
Crash with Liquids from chancecubes

### ISSUE THREAD

**Issue by HomeFunk** [Sunekaer/stoneBlock#442]
## Bug Report

Placed out a chancecube, got all the diffrent liquids, stepped into one and CTD - cant log onto server again - CTD as soon as it starts to load into the server.
## Steps to Reproduce (for bugs)

1. Place a chancecube, hope it is one with diffrent liquids
2.step into one(didnt see what it was) and CTD

## Logs

* Client/Server Log:
* Crash Log:[2018-10-23-3.log](https://github.com/Sunekaer/stoneBlock/files/2507942/2018-10-23-3.log)

## Client Information

* Modpack Version:1.0.23
* Server/LAN/Single Player: Server (server did not crash)
* Optifine Installed:no
* Shaders Enabled:no

**Comment by Sunekaer** [comment]
1.0.25
