### ISSUE TITLE
Immersive Engineering Gun Turret keeps firing after mob is killed

### ISSUE THREAD

**Issue by vegeta-nc** [Sunekaer/stoneBlock#445]
## Bug Report
Immersive Engineering Gun Turret keeps firing after mob is killed.
I've done a complete fresh install with no additional mods and without changing anything.

## Steps to Reproduce (for bugs)

1. Setup gun turret with power and ammo.
2. Spawn a mob if needed.

## Logs

* Client/Server Log: No logs
* Crash Log: No logs

## Client Information

* Modpack Version: 1.0.24
* Server/LAN/Single Player: Both Single and LAN
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
please report to Immersive Engineering

**Comment by vegeta-nc** [comment]
I figured you would say that.

I went ahead and installed only forge, immersive engineering, jei. Same versions as the Stone Block pack 1.0.24 uses and it works fine.
forge-1.12.2-14.23.5.2768-universal.jar
ImmersiveEngineering-0.12-86.jar
jei_1.12.2-4.13.1.220.jar
