### ISSUE TITLE
Enderio Silicone

### ISSUE THREAD

**Issue by Smario9000** [Sunekaer/stoneBlock#446]
## Bug Report
the Recipe in Thermal Expansion Industrial Smelter doesn't allow me make Electric Steel in it with EnderIo Silicone but it will allow me to use AE2 Silicone

Is there any why either you can fix this or can you tell me how to add the recipe to fix this
I really don't want to used any Items form AE2

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: None
* Crash Log: None

## Client Information

* Modpack Version: 1.0.23 (Beta)
* Server/LAN/Single Player:
* Optifine Installed: No
* Shaders Enabled: No

Thank you

**Comment by Sunekaer** [comment]
1.0.25
