### ISSUE TITLE
Black Hole Dupe/Bug (Bees)

### ISSUE THREAD

**Issue by kaiand1** [Sunekaer/stoneBlock#448]
## Bug Report
Black Hole Controller + Black Hole Unit Duplicate/Change Bees Typs
(Spawn Rate in Mining World is little High, I have over 2,4 Mio Bees with 1 RFBuilder Quarry 512x512 size)

INFO
! Same Problem with Enchanted Books !

## Steps to Reproduce (for bugs)
1. Build Black Hole Controller +Black Hole Unit and Insert 1 or more different Bees
2. Place other Bees in your Inventory
3. Insert Bees from Inventory to Black Hole Controller and all other Bees change to the First Insert Bee in the Black Unit.
(Bees from Forestry)
Export from Refined Storage use the First Bee Slot and Change all other Bees...

(Tropical Drone and Wintry Drone)
![2018-10-24 19_34_03-minecraft 1 12 2](https://user-images.githubusercontent.com/44444152/47449830-eaa3d480-d7c3-11e8-9c91-1e853023b38b.png)
![2018-10-24 19_34_25-minecraft 1 12 2](https://user-images.githubusercontent.com/44444152/47449847-f4c5d300-d7c3-11e8-84e6-2940d2e936ca.png)
![2018-10-24 19_34_35-minecraft 1 12 2](https://user-images.githubusercontent.com/44444152/47449855-f7282d00-d7c3-11e8-9096-8db01a81682b.png)
![2018-10-24 19_34_41-minecraft 1 12 2](https://user-images.githubusercontent.com/44444152/47449859-f8f1f080-d7c3-11e8-9a23-a2f9dfb62f5f.png)

## Client Information
* Modpack Version: 1.0.22r1
* Server/LAN/Single Player: Single Player

**Comment by Sunekaer** [comment]
https://github.com/Buuz135/Industrial-Foregoing/issues/449

**Comment by kaiand1** [comment]
INFO
Same Problem with Enchanted Books.....

**Comment by Sunekaer** [comment]
StoneBlock-1.0.28
