### ISSUE TITLE
Textures/Sounds Not Working Properly

### ISSUE THREAD

**Issue by mcjacob** [Sunekaer/stoneBlock#449]
**Bug Report**

So I've been playing Stoneblock for a bit, and I think that the resources (sound, textures, etc.) are loading incorrectly for some reason. When I launch the game, it runs normally for a few minutes, then the sound suddenly stops working. All of the game sounds are not playing. After this, I reload the resources using F3+T, and then I end up with all sorts of texture issues from all sorts of different mods. Screenshots of these texture issues are attached.

**Steps to Reproduce (for bugs)**
1. Open Stoneblock, and run it for about 5-10 minutes
2. Game sounds are not playing
3. Press F3+T to reload resources
4. Wait a few minutes for resources to reload
5. Textures look all sorts of weird

**Logs**
Client/Server Log: N/A
Crash Log: N/A
**Client Information**
Modpack Version: 1.0.22r1
Server/LAN/Single Player: Single Player
Optifine Installed: No
Shaders Enabled: No

![2018-10-24_16 03 58](https://user-images.githubusercontent.com/7944752/47458082-c08fe980-d7a6-11e8-824b-a991b1d1ec23.png)
![2018-10-24_16 04 08](https://user-images.githubusercontent.com/7944752/47458083-c1288000-d7a6-11e8-8fc4-9ec35dd692f6.png)
![2018-10-24_16 04 21](https://user-images.githubusercontent.com/7944752/47458084-c1288000-d7a6-11e8-81fa-505e2e48ca8f.png)
![2018-10-24_16 04 33](https://user-images.githubusercontent.com/7944752/47458085-c1288000-d7a6-11e8-8fc3-cdeb37a7f37b.png)
![2018-10-24_16 04 41](https://user-images.githubusercontent.com/7944752/47458086-c1288000-d7a6-11e8-937e-0eae46f2c575.png)
![2018-10-24_16 05 15](https://user-images.githubusercontent.com/7944752/47458088-c1288000-d7a6-11e8-9c64-6684c3d2471c.png)

**Comment by Sunekaer** [comment]
In 1.12 modded it’s not advised to reload resources in-game, even if you have 6GBs of ram assigned it maxes usually in large packs..
When you reload all resources with the game open it maxes the ram
And when you run out of ram the first thing to go is texture sheets loading
