### ISSUE TITLE
Spawn Eggs from Pam's Harvestcraft Market are broken.

### ISSUE THREAD

**Issue by CaithSidhe** [Sunekaer/stoneBlock#45]
Alright, I can't really post logs for this but the Market from Pam's Harvestcraft gives the option to buy Spawn Eggs for emeralds, but when purchased you instead get a blank Spawn egg that doesn't work. From the bit of looking that I have done, this seems to be a known multiplayer issue with Pam's Harvestcraft and I couldn't find anything about a fix.

The Steps to Reproduce the bug:
Make a Pam's Harvestcraft Market
Buy any Spawn Egg.

**Comment by Sunekaer** [comment]
https://github.com/MatrexsVigil/harvestcraft/issues/168
