### ISSUE TITLE
Server scripts do not match client scripts - 1.0.24

### ISSUE THREAD

**Issue by Sabster** [Sunekaer/stoneBlock#452]
It looks like it was only shapedrecipes.zs (one of the wheat recipes)

Just for clarification:  I got stopped at log in to my server - got the message about scripts not matching (it mentioned wheat) and I copied all of them from the client to the server so they matched.

**Comment by Sabster** [comment]
Close this - I had 1.0.24 server - 1.0.25 client...  (there is no 1.0.25 server yet?)

**Comment by Sunekaer** [comment]
They are uploaded and waiting approval
