### ISSUE TITLE
Fluid Terminal from ExtraCells isnt craftable due to depreciation so the Universal Wireless Crafting terminal can not be "completed"

### ISSUE THREAD

**Issue by Algester** [Sunekaer/stoneBlock#454]
## Bug Report
Applied Energistics 2 has it's own Fluid Terminal now but the Universal Wireless Crafting Terminal Requires Extra Cell's variant of it which can no longer be crafted

## Client Information

* Modpack Version: 1.0.25
* Server/LAN/Single Player: Single Player
* Optifine Installed:
* Shaders Enabled:

**Comment by Algester** [comment]
fix is simple make the recipe for the Universal Wireless Crafting Terminal Require the use of Applied Energistics's 2 Fluid Terminal rather than Extra Cell's version of it

**Comment by Sunekaer** [comment]
https://github.com/ExtraCells/ExtraCells2/issues/612

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
