### ISSUE TITLE
Item's not being sent into Drawers even though there is space/void upgrades

### ISSUE THREAD

**Issue by Basilicum** [Sunekaer/stoneBlock#455]
So, this is an odd Bug. 
This is also a Random Bug, which happens with all the pipes.
I Had a Pipe running from the Mobfarm to my Drawer Storage, which are right next to eachother. Items would sometimes get stuck in the Absorbtion Hopper or Input Chest, since the Connected Pipes did not pull out certain items from the Inventory, to place them into the Drawers. 
It doesn't matter whether it's the Drawer Controller, or the Drawers Themselves. It might have to to do with the size though aka A Problem of the Pipe finding a Valid Spot to send the Item to.
The Drawers aren't full or even have Void Upgrades inside, and yet Items simply refuse to move. 
I tried to see if this was a Distance Problem, if the pipes were too long. But even after shortening the Distance with Ender Chests, and only having 1 Pipe Distance, it doesn't want to extract Items from the Inventory, and place them into the Drawers. 
IT WILL Place them into any Chest I attach to the Pipe. There is no Problem with that. 
It is strictly with Drawers.
For a while I thought I was the only one, or perhaps have screwed up, but after watching some Let's Plays, and asking friends, it seems to happen to more than just me. 

I hope this Problem gets addressed, as this is a big problem due to the clogging of input.

Since there is no Error Log, or anything, I can't really attach any files to this report, but I hope it still suffices. 

Thanks for your Time!
-Basil

**Comment by Ladysarajane** [comment]
What version of the pack are you using and which pipes have you used? I have noticed this,  on Version 1.0.22r1 all pipes worked to storage drawers including item translocators, but as soon as I put void upgrades on the drawers the translocators quit sending those items (ones with void upgrades ) to the drawers. The one I used was item conduits from ender io from the crate to the controller and it worked fine. With the new version, I restarted a world for testing and I haven't gotten that far yet in testing yet. 
I know this is a known bug with item translocators, but as I found out Ender IO item conduits fixed that problem, however those were slower.

**Comment by Basilicum** [comment]
I am using the most recent version of the Pack, as I just Updated, but this Problem existed in the previous version. I used Thermal Expansion Pipes, Open Blocks Transfer Pipes, and EnderIO Pipes. All of which seem to have the same problem. 
Also that problem existed with and without Void Upgrades.

**Comment by Algester** [comment]
I saw no issue with the use of Itemducts from Thermal Expansion but of the item transfering methods TE is actually the "slowest" that could actually prose a problem if you have a faster item intake <_<

**Comment by deadterran** [comment]
Its a known issue with item ducts, I remember Direwolf20 mentioning it a few months ago. The duct only sees the drawer as having one open slot so it gets confused. If I remember right it can be fixed by using a filter set to "allow over sending".

**Comment by Sunekaer** [comment]
As Deadterran said set the filter to "allow over-sending"
