### ISSUE TITLE
Can't force Refined Storage auto-crafting of Mystic Agriculture essence tiers

### ISSUE THREAD

**Issue by jivebiscuit** [Sunekaer/stoneBlock#457]
## Bug Report

After a clean update to 1.0.25, I can no longer Ctrl+Shift+Click to force auto-crafting of higher Mystical Agriculture tiers. This worked before the update. Example - crafting Supremium essence when only Inferium is in storage. I'm using a master infusion crystal which has unlimited uses.
## Steps to Reproduce (for bugs)

1. Make a pattern for a higher tier essence and try to auto-craft.
2. Ctrl+Shift+Click is not an option in the crafting summary dialog.

## Logs

* Client/Server Log: https://gist.github.com/jivebiscuit/adb78f99fec0dcf6de0590a93ff0c17e
* Crash Log: no crash.

## Client Information

* Modpack Version: 1.0.25
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
updated from what version

**Comment by Sunekaer** [comment]
Refined storage had alot of changes in the update

> 
> - Added new Crafter modes: ignore redstone signal, redstone signal unlocks autocrafting, redstone signal locks autocrafting and redstone pulse inserts next set (replacement for blocking mode) (raoulvdberge)
> - Added a config option to configure the autocrafting calculation timeout in milliseconds (raoulvdberge)
> - Added throttling for network devices that can request autocrafting (raoulvdberge)
> - Renamed Cut Processors to Raw Processors and those are now made with Processor Binding instead of a Cutting Tool (raoulvdberge)
> - Fixed an autocrafting bug where it crashed when external inventories couldn't be filled (raoulvdberge)
> - Fixed a duplication bug with a disconnected Crafting Grid (raoulvdberge)
> - Fixed oredict autocrafting sometimes reporting that a craftable item is missing (raoulvdberge)
> - Fixed fluid autocrafting without item inputs locking when there's not enough space for the fluids (raoulvdberge)
> - Fixed Grid "last changed" date not changing when using clear button or JEI transfer (raoulvdberge)
> - Fixed a duplication bug when pressing clear on a Wireless Crafting Grid from Refined Storage Addons (raoulvdberge)
> - Fixed a duplication bug with autocrafting and External Storages (raoulvdberge)
> - Fixed Crafting Manager displaying wrong name for chained crafters connected to some blocks (raoulvdberge)
> - Fixed crafting task losing internal buffer when network runs out of energy (raoulvdberge)
> - Removed handling of reusable items in autocrafting, to avoid problems (raoulvdberge)
> - You can no longer start a crafting task if it has missing items or fluids (raoulvdberge)
> - The Security Manager now supports Security Cards that have no player assigned to them. It is the default security card for players that aren't configured (raoulvdberge)
> - If no default Security Card is configured in the Security Manager, an unconfigured player is allowed to do everything in the network. Create a default Security Card (craft a Security Craft and don't assign it to a player, it acts as a fallback) to handle unconfigured players (raoulvdberge)

**Comment by jivebiscuit** [comment]
"Removed handling of reusable items in autocrafting, to avoid problems (raoulvdberge)"

Guess that would do it.
