### ISSUE TITLE
Cannot create Fluix Crystals.

### ISSUE THREAD

**Issue by WhyNotCthulhu** [Sunekaer/stoneBlock#458]
## Bug Report

With the current version of Realistic Item Drops it's impossible to create Fluix Crystals.

## Steps to Reproduce (for bugs)

1. Throw Redstone, Nether Quartz, and Charged Certus Quartz into a water source block.
2. The Charged Certus and Nether Quartz float on top and do not trigger the creation of Fluix Crystals.

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.23
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by WhyNotCthulhu** [comment]
That's how most players are getting by but that's not really a solution since it's based on RNG with only a set number of rewards.

**Comment by Algester** [comment]
edit I tried the recipe it works you need to give it some actual time <_<

**Comment by WhyNotCthulhu** [comment]
Yes, we've tried that. We've let the mats sit until they despawned and nothing happened. We've tried completely encasing the water in glass to prevent the items from moving.

**Comment by knoxhack** [comment]
Since this is on a sponge server, this might be a spongeForge bug.

**Comment by knoxhack** [comment]
@WhyNotCthulhu Can you test if this works in your client single player world?

**Comment by WhyNotCthulhu** [comment]
Yes I will test it tonight. It may very well be a server only issue as the only reason I opened the issue were the large amount of players asking me why it was not working on the public servers.

**Comment by WhyNotCthulhu** [comment]
Works fine in my test world. Gonna test a few times on the public and private servers as well.

**Comment by SolSavvy** [comment]
I have the same problem, no solution was ever specified. Playing singleplayer btw

**Comment by Landermark** [comment]
you should make sure that it is Charged Certus and not just Certus the texter looks vary similar
