### ISSUE TITLE
Wheat recipe error when updating from 1.0.23 to 1.0.25

### ISSUE THREAD

**Issue by Kerellian** [Sunekaer/stoneBlock#459]
## Bug Report
Getting the following error when trying to log into a server after being updated from 1.0.23 to 1.0.25

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe minecraft:wheat (net.minecraft.item.crafting.ShapedRecipes@49bc71b4) produces unregistered item minecraft:wheat (net.minecraft.item.Item@67ecf7ed)

## Steps to Reproduce (for bugs)
update server from 1.0.23 to 1.0.25
try logging into server and get the a registry error then the error about wheat

## Logs

* Client/Server Log:
* Crash Log: https://gist.github.com/Kerellian/70e11008b78b038d55e8439ee4e221b7

## Client Information
downloaded by the twitch app. no errors during install. 
* Modpack Version: 1.0.25
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
make sure that the script folder on the server has been updated

**Comment by Kerellian** [comment]
Just waiting on the server team to let me know

**Comment by Sunekaer** [comment]
reopen when you have more information
