### ISSUE TITLE
StoneBlock Server not working

### ISSUE THREAD

**Issue by Allexandru1** [Sunekaer/stoneBlock#463]
## Bug Report

Server don't start
## Steps to Reproduce (for bugs)

1. https://i.imgur.com/pjr9adB.png

## Client Information

* Modpack Version: StoneBlock 1.0.25 Server
* Server/LAN/Single Player: Server

**Comment by Sunekaer** [comment]
read the file called "Instructions"

**Comment by Allexandru1** [comment]
> read the file called "Instructions"

https://youtu.be/EmuR97nUiDA
