### ISSUE TITLE
Emeradic Chickens get unloaded inside the Roost Breeder when transfering Dimensions

### ISSUE THREAD

**Issue by Algester** [Sunekaer/stoneBlock#465]
## Bug Report
Going through Dimensions using the Advance Dislocator makes the Breeder Block to unload it's inventory.

## Steps to Reproduce (for bugs)
1. Use Advance Dislocator while the Breeder has items inside
2. Go to and fro dimensions
3. Check the Breeder Block if the Items are unloaded

## Client Information

* Modpack Version: 1.0.25
* Server/LAN/Single Player: Single Player
* Optifine Installed: None
* Shaders Enabled: None

**Comment by Sunekaer** [comment]
unloaded? like the items has stopped/paused the breeding process?

**Comment by Sunekaer** [comment]
okay if you break the block or relog do they then appear again?

**Comment by Algester** [comment]
nope and nope
so it wasnt an inventory sync issue either

**Comment by Sunekaer** [comment]
Just tested this in my world and i cant recreate this issue

**Comment by Algester** [comment]
yeah thought so it maybe a freak accident on my part as I never chunk loaded the areas being long gone from playing modded MC does that which might be the culprit but I really don't know it could also be my fault so ehh...

**Comment by Sunekaer** [comment]
can you recreate the problem?

**Comment by Algester** [comment]
For now not yet I have to fix my tick issue first but that requires me to world edit before I can attempt at recreating the problem and I’m currently away from my computer

**Comment by Sunekaer** [comment]
Okay cool, please report this issue once you have tested and can recreate the problem

**Comment by Algester** [comment]
ok it seems to be a one off bug that happened to my side as I can't recreate it so yeah
