### ISSUE TITLE
cursed earth broken

### ISSUE THREAD

**Issue by joosthoi1** [Sunekaer/stoneBlock#466]
## Bug Report

cursed earth not working
## Steps to Reproduce (for bugs)

since the new version cursed earth doesnt seem to be spawning any more mobs

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.25
* Server/LAN/Single Player: singleplayer (didnt test LAN or multiplayer)
* Optifine Installed: yes
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
works fine in my single player world

**Comment by Sunekaer** [comment]
is the light level low enough?

**Comment by Scratchman** [comment]
My cursed earth grinder wasn't working until I removed the actually additions lamps I was using for light when i wanted to work on the grinder. Even when they weren't on they prevented spawning on cursed earth.

**Comment by joosthoi1** [comment]
@Sunekaer the light level was low enough, but i put dark glas down, ill try it without

**Comment by joosthoi1** [comment]
even in a dark room made of cobble they dont spawn, i tried moving away 25+ blocks aswell, with no result

i would like to add that normal non cursed earth (the black mobs) ARE spawning at a slow rate when im 25+ blocks away

**Comment by Sunekaer** [comment]
Do you have any Feral Flare Lanterns around?
