### ISSUE TITLE
Potion recipe mix up, Gravity potion not correct, converts other potions to gravity with redstone

### ISSUE THREAD

**Issue by WRFleete** [Sunekaer/stoneBlock#467]
## Bug Report

adding redstone to any potion in a brewing stand including awkward and even ones that dont apply normally eg instant health turns to "gravity 8:00" and keeps using redstone in the brewing stand
the proper recipe in JEI for gravity uses obsidian. that recipe instead brews resistance for 3 minutes

## Steps to Reproduce (for bugs)

1. take a potion that normally wouldnt take (more) redstone (awkward instant health, damage or already upgraded effect potions)
2. apply redstone, the result should be gravity for 8 minutes and if multiple redstone is placed in ingredient slot, should attempt to use more 

additionally 
1. take awkward potion
2. add obsidian
3. result will be resistance for 3 minutes instead of gravity as mentioned in JEI

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.25
* Server/LAN/Single Player: SP
* Optifine Installed:
* Shaders Enabled:
* java 1.8.0_191
*Extra utilities (where the potion comes from) 1.9.7

**Comment by Sunekaer** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/issues/221

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue

**Comment by black-wolfy** [comment]
it's been 2 years, we getting a fix yet?
