### ISSUE TITLE
bad spawn points and malfunctioning commands

### ISSUE THREAD

**Issue by Master-Jynx** [Sunekaer/stoneBlock#47]
## Bug Report
Playing version 1.0.11 on the official server, another player that I know from o0ther games
used the /island invite [name] command to get me to his island and I used the accept command.

I tp'd 4 or 5 below his cave level in solid stone and suffocated until he dug me out.
Later i tried to use /island home but i got an error message saying i had to be atleast 500 blocks away
to use that command.
Confused, i then used /spawn to goto the world's spawn point, and I appeared several blocks below
the spawn cave in solid stone and died.
Upon dying i was tp'd to what appeared to be a lava lake where i caught on fire, and was then moved, before i could type or do anything, i was moved again , back to my friend's base....
Yes, 4 or 5 blocks below cave level, where he dug me out.
I stayed on fire, taking no damage, until i logged out.
I logged back in , i was still at his base, so i tried all of the commands again, and got the same results
mentioned above.

The 3rd time I stood on a crafting table and used /spawn and safely appeared at spawn
i then used /island spawn and appeared 4 or 5 blocks below cave level at my friends base, again.

I tried it all one more time to be sure of my conclusions and then tried the /island reset command
and was teleported to the world spawn, 4 or 5 blocks below cave level in solid stone, where i died.
upon death i was temporarily moved to what looked like a large lava lake, where i caught on fire
I logged out...

It looks like the following need fixing
1> Try setting the world spawn 1 block higher with empty air below it.
2> The initial Island spawn place you in water 1 block below the caves floor level.
      Move it away from the water and 1 block above the caves ground level.
3) Find out if invite is supposed to merge 2 players caves, like it did to me
    I would normally think itsw just supposed to give the invited player permission to enter another 
   players area.
   If it does merge, then change the commands description to say so.

There are other skyblock control mods which uses Invite/Uninvite, Join, TPA and other commands
better.
You might want to look into using them, instead

## Steps to Reproduce (for bugs)
I don't know but you could try this.
1> Have someone invite you to their island, (/island invite[name])
2> Then "accidentally" use /island home , upon getting an error say "oops" and use /island spawn,
     then try /spawn, thats all it took me.

## Logs
no crash occured. No logs.
* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.11
* Server/LAN/Single Player: The official server at 195.201.245.60:25573
* Optifine Installed: No
* Shaders Enabled: whatever the default is

**Comment by Sunekaer** [comment]
1.0.12

**Comment by Master-Jynx** [comment]
Thank You.
I curious, if you don't mind, how do you handle setting the player spawn point when structure blocks place players on the top most block, which in this modpack would be in lava?
