### ISSUE TITLE
Duplication issue (Probably more of a mod bug)d

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [Sunekaer/stoneBlock#471]
## Bug Report

15 approx cactus from 1 growth stage when using acceleration wand.
## Steps to Reproduce (for bugs)

1. Set up an auto cactus farm (where there is a block to the side of where the next cactus layer will grow)
2. Use acceleration wand on cactus
3. ????
4. Profit

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.22r1
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
https://github.com/romelo333/notenoughwands/issues/85

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
