### ISSUE TITLE
Game crashes immediately after clicking play

### ISSUE THREAD

**Issue by mynameispig123** [Sunekaer/stoneBlock#472]
## Bug Report
After clicking PLAY, the game just exits with a code: -1073741819

## Steps to Reproduce (for bugs)

1. Just launch the game after a few days or so and the issue may happen

## Logs

* Debug Log: https://pastebin.com/dVhZ7i5f
* Latest Log: https://pastebin.com/K09VyL9h

## Client Information

* Modpack Version: Rolled-back to 1.0.22r1 (As this issue seemed to appear after the update, but after roll-back, its still appearing)
* Server/LAN/Single Player: Single Player
* Optifine Installed: NIL
* Shaders Enabled: NIL

**Comment by Sunekaer** [comment]
https://bugs.mojang.com/browse/MC-112780

Looks like a faulty driver
