### ISSUE TITLE
Quest not working

### ISSUE THREAD

**Issue by LeafSalt** [Sunekaer/stoneBlock#473]
## Bug Report

Quest books are empty
I have tried both command
many times
I have tried making a new world but nothing has happened

## Steps to Reproduce (for bugs)

1. make a new world
2. then look in the quest book
3. then goto quests
4. nothing is there

## Logs

* Client/Server Log: https://gist.github.com/LeafSalt/d1537cf8062cd0f5782aad73ff6a7a8b
* Crash Log: No Crash

## Client Information

* Modpack Version:  1.0.1
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
First why are you using that old version??
Second use the newest version

**Comment by Wheezywookiee** [comment]
So in regards to why he's probably using older version is because anything newer than 1.0.25 will crash when trying to join Lan, and there's a server but it's only on version 1.0.25, it's not up to current date.
