### ISSUE TITLE
1.0.25 Item deletion bug on middle click in compactor

### ISSUE THREAD

**Issue by matjojo** [Sunekaer/stoneBlock#475]
## Bug Report

Middle clicking in compactor (to sort) deletes all items inside.

## Steps to Reproduce (for bugs)

1. Fill compactor with items that can be compacted (I had it in only 2X2 recipes mode)
2. Middle click

## Logs

* Client/Server Log: Didn't crash so no log
* Crash Log:

## Client Information

* Modpack Version: 1.0.25
* Server/LAN/Single Player: single player
* Optifine Installed: default modpack settings and mods, don't know
* Shaders Enabled: default modpack settings and mods, don't know

**Comment by P4t0r1kku** [comment]
had that bug in the 1.0.22r1 too, so: never tried to sort stuff with middle mause klick there again :D

**Comment by Sunekaer** [comment]
Which compacter/compactor are you talking about?

**Comment by matjojo** [comment]
The one compacter block in your pack, from the mod compacter.

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
