### ISSUE TITLE
BHU not accepting Draconium Nuggets

### ISSUE THREAD

**Issue by vertex101** [Sunekaer/stoneBlock#477]
## Bug Report

Black Hole Units not accepting draconium nuggets

## Steps to Reproduce (for bugs)

1. try to place draconium nuggets into a black hole unit
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: latest 1.0.25
* Server/LAN/Single Player: Server
* Optifine Installed: nope
* Shaders Enabled: nope

**Comment by P4t0r1kku** [comment]
i had no problem to put draconium nuggets in, but it seems to lock inventory, when put something in (doesn#t matter if i lock it or not), so have to pick up the BHU and place it new to put something else in.

**Comment by vertex101** [comment]
> i had no problem to put draconium nuggets in, but it seems to lock inventory, when put something in (doesn#t matter if i lock it or not), so have to pick up the BHU and place it new to put something else in.

it was a newly placed BHU i just put down and it wouldnt let me

**Comment by Sunekaer** [comment]
I just tested with both Draconium and awakened Draconium nuggets, ingot and blocks and it works fine
