### ISSUE TITLE
[Suggestion|Add some creative items

### ISSUE THREAD

**Issue by xILikepuddingx** [Sunekaer/stoneBlock#478]
maybe have a little suggestion to delay the endgame bit. Just add some small creative items that make life a little better.

I thought of it like this:
energy cell
everlast mana pool
tank

Energy itself should be considered basic. tank should build on the energy cell and everlast mana pool on the tank.

I made you a template:
https://screen.ilikepudding.de/b84bydfu2k.png

here's the script:
https://paste.myftb.de/gikurimohe.xml

if you want to do it, i would suggest that you either set the emc value of the book significantly higher or remove the value.
24 million is not exactly high when we look at the value of the catalysts

why ae2 energy cell? quite simply, because you can break it down again without switching to creative mode. the others can usually be broken only by gamemode. endo io would be the other variant.

If you like I can do for the other 2 or maybe even more the scripts.

**Comment by Sunekaer** [comment]
there wont be added anymore stuff to this pack
