### ISSUE TITLE
Flux Network not working properly

### ISSUE THREAD

**Issue by CodeMastr3** [Sunekaer/stoneBlock#479]
Flux Plugs and Flux Points aren't chunk loading as they are supposed to anymore since updating server and game.
Server
Version 1.0.25
No optifine or shaders

**Comment by Sunekaer** [comment]
"chunk loading as they are supposed" you are not giving me much info to work with here? 
What happens? 
What was supposed to happen?
Does the server you play on have Chunkloading enabled?

**Comment by CodeMastr3** [comment]
As of version 1.0.22r1 the flux plugs and points were chunk loading on my personal server that I run with friends and when I updated to 1.0.25 they no longer chunk load. But we found a workaround with claim territory chunk loading. So I don't know what happened but they just aren't chunk loading anymore

**Comment by Sunekaer** [comment]
Hmm, i dont know if Flux network normally chunk loads it own blocks, i dont think it do, but the mod hasnt been update and the settings for it hasnt been changed

**Comment by bogointeractive** [comment]
I just tried Flux Networks here in 1.0.28 and it does not load from one dimension to another. I have my Mekanism Reactor in Mining Dimension and they are not going back into the "over world". They just sit there and show nothing.
