### ISSUE TITLE
Huge lag because of mod function.

### ISSUE THREAD

**Issue by demethan** [Sunekaer/stoneBlock#48]
## Bug Report
if we have more then 2 or 3 people on the server, tps drops drastically because of mod fonction. 

## Steps to Reproduce (for bugs)

1. more people = bad tps
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

https://github.com/DoctorFTB/Stone-Block-Utilities/issues/5

Suggestion: disable custom spawn function.

**Comment by Sunekaer** [comment]
we are aware

**Comment by Sunekaer** [comment]
1.0.12
