### ISSUE TITLE
Game not responding after pressing save and quit to title

### ISSUE THREAD

**Issue by matjojo** [Sunekaer/stoneBlock#480]
## Bug Report

Game not responding after pressing save and quit to title

## Steps to Reproduce (for bugs)

1. Play game
2. Save and quit
3. Game doesn't reply and windows needs to kill it.

## Logs

* Client/Server Log: https://gist.github.com/matjojo/bba1eda4a13e90ba15defd72aac0bf09
* Crash Log: 

## Client Information

* Modpack Version: 1.0.25 MC 1.12.2 forge-14.23.5.2768
* Server/LAN/Single Player: Single player (but somewhere in the middle I used open to LAN to give myself gamemode C since I lost a lot of stuff in a bug that I filed some hours earlier.)
* Optifine Installed: Default modpack settings
* Shaders Enabled: Default modpack settings

**Comment by matjojo** [comment]
I have 6 gigs assigned (6,144MB in twitch launcher) I have 12 gigs in this machine. I just played some more and it seems like the world did indeed save, since I could just restart from where it stopped replying. It didn't do it again when I closed the game today, so I assume this was just 1/0 magic I do kinda want to know how I can increase the backup frequency for the saves now.

**Comment by nzminecraftDOTcom** [comment]
If single player you need to open the forge config file and set the backup part up to how you want it to run. If it's a server it's up to the host to set that up

**Comment by Sunekaer** [comment]
closing with issue fixed it self and nzmine has answered the other question
