### ISSUE TITLE
Marble (raw) not attainable

### ISSUE THREAD

**Issue by netmc** [Sunekaer/stoneBlock#482]
I was looking to build with marble, but there doesn't seem to be a way of obtaining it in the pack.  The only way I found to make it is with marble essence from magical crops, but it requires 4 marble to get the first seed.

Would it be possible to add in a crafting recipe/loot bag or add it to the igneous extruder machine like andesite, granite and diorite are?

**Comment by P4t0r1kku** [comment]
I don't looked for it, but got some from the Quantum Quarry from Extra Utilities. And maybe there some in the Mining Dimension, but not sure, i don't digged there.

**Comment by Sunekaer** [comment]
mining dim or quarry
