### ISSUE TITLE
Dupe glitch

### ISSUE THREAD

**Issue by Every-one1** [Sunekaer/stoneBlock#484]
## Bug Report
Dupe glitch

## Steps to Reproduce (for bugs)
1.place a workbench (from tinkers construct) Beside an lootbag opener
2.to dupe now just pull the craft recipe out of jei make sure there is one extra block [if you want to dupe cobblestone place 2 cobble on top of 2 sticks (shovel recipe) make sure there is no cobble in your inv and pull the recipe out of jei]

**Comment by Sunekaer** [comment]
#228

**Comment by Every-one1** [comment]
its not that
