### ISSUE TITLE
Server Tick Loop Error with Thermal Dynamics servos/retrievers I already posted the Issue to the CoFH team

### ISSUE THREAD

**Issue by Algester** [Sunekaer/stoneBlock#485]
## Bug Report
tinkering with the servo from the sink from the Cooking for Blockheads for the ender tank produced the error which was already glitching out

## Steps to Reproduce (for bugs)

1.  have a glitchy water pipe
2. check the servo with a glitchy water pipe

## Logs
* Client/Server Log: 
* Crash Log: https://pastebin.com/PqxMCT7j

## Client Information

* Modpack Version: 1.0.25
* Server/LAN/Single Player: Single Player
* Optifine Installed: None
* Shaders Enabled: None

**Comment by Sunekaer** [comment]
https://github.com/CoFH/Feedback/issues/1342 issue closed so closing this

**Comment by Algester** [comment]
ok just an update it seems the Ender Tanks were giving me issues I will probably have to post this issue to them
