### ISSUE TITLE
Crashing on Launch

### ISSUE THREAD

**Issue by LeafSalt** [Sunekaer/stoneBlock#487]
## Bug Report

When it gets to a certain mod, it crashes

## Steps to Reproduce (for bugs)

1. Just Launch the game from the launcher
2. then wait and it will crash

## Logs

* Client/Server Log: https://gist.github.com/LeafSalt/5d1d9722690c7d3427b8e89992b6bc9d
* Crash Log: https://gist.github.com/LeafSalt/3d2baba13ea762e89755fce969c17af3

## Client Information

* Modpack Version: 1.0.25
* Server/LAN/Single Player: SinglePlayer
* Optifine Installed: N/A
* Shaders Enabled: N/A

**Comment by knoxhack** [comment]
Looks like your rftoolsdim.jar is corrupted, try reinstalling the modpack

**Comment by LeafSalt** [comment]
I created a copy of the modpack on the twitch launcher and that works, but my save from the other one wont show
