### ISSUE TITLE
fps 0

### ISSUE THREAD

**Issue by drago555** [Sunekaer/stoneBlock#492]
## Client Information

* Modpack Version: 1.0.25/1.0.24/1.0.22r1
* Server/LAN/Single Player:Single Player
* Optifine Installed:
* Shaders Enabled:

**Comment by nzminecraftDOTcom** [comment]
Fill out the form so people know what you are using or trying to do on what version of the pack you are using

**Comment by nzminecraftDOTcom** [comment]
Are you able to post a log file (Not a crash report assuming it has not crashed, if it has, post that too) of the last time you tried and it wouldn't run right? I suspect you've allocated memory in the Minecraft launcher, not through the Twitch launcher, where you are meant to. The twitch launcher args overrule the Minecraft launchers args

**Comment by drago555** [comment]
this is the last logs and I do not understand the rest.
[2018-10-29-2.log.gz](https://github.com/Sunekaer/stoneBlock/files/2529767/2018-10-29-2.log.gz)

**Comment by Sunekaer** [comment]
Did you change ANY settings?

**Comment by Sunekaer** [comment]
Please upload the crash log from Minecraft\Instances\StoneBlock\crash-reports\ to gist.github.com and link it here

**Comment by nzminecraftDOTcom** [comment]
You need to allocate the pack more Memory.
To do this: Go to the twitch launcher's settings menu (The 3 dashes at the very top left of the window) - click file --> options
On the left side, locate Minecraft and open those settings. Scroll down till you see Java Settings. Slide the bar across till you are able to give it around 6GB of memory, more is better if you can.
Click the done button and try re-launch the pack.
