### ISSUE TITLE
World Spawn in Lava

### ISSUE THREAD

**Issue by GriefingAssassin** [Sunekaer/stoneBlock#493]
Whenever I try to create a new world I always spawn on the surface in the lava. How can I fix this?

**Comment by nzminecraftDOTcom** [comment]
Type /island home or create. See if that fixes it. Most of the time Minecraft will try spawn you at the highest point to avoid spawning you in caves etc. Kinda annoying for this pack

**Comment by Sunekaer** [comment]
It rarely happens butt sadly i cant do anything about it, youll have to do /island home or /island spawn to get away from there
