### ISSUE TITLE
Refined Storage: Solar Generator not Craftable

### ISSUE THREAD

**Issue by Kratzwurst** [Sunekaer/stoneBlock#494]
## Bug Report
Recipes with the energy tablet from mekanism can't be craftable automatically.
On the cafting preview locks the tablet at as full storage with energy.
I figured out with oredict and without, same problem

https://imgur.com/a/cgUnvF4

## Client Information

* Modpack Version: 1.0.25
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled:

**Comment by bobrob2004** [comment]
Several recipes that use an item that stores energy has this problem. Try manually putting the recipe in instead of using JEI.

**Comment by Kratzwurst** [comment]
yeah i try it to manually, but not works.

**Comment by PlacidK** [comment]
Try disabling wireless charging and put the energy tablet in manually

**Comment by Kratzwurst** [comment]
Okay that is a Problem by Refined Storage. I turn  off my Draconic Flux Capacitor than the Controller from Flux Networks.  

1. I ceate a recipe with JEI and no work
2. I create a recipe manually don't work
3. I create a recipe with oredict that's be also don't work.

**Comment by Sunekaer** [comment]
Refined storage had an update there they disabled/removed some stuff example "Removed handling of reusable items in autocrafting" and a lot of other stuff that might be why
https://minecraft.curseforge.com/projects/refined-storage/files/2629187
youll have to report this to refined storage
