### ISSUE TITLE
Can't Craft Philosophers Stone on my Server

### ISSUE THREAD

**Issue by KillerzGodZ** [Sunekaer/stoneBlock#495]
## Bug Report

Could not make the Philosophers Stone on my server, however, I could make it on my SinglePlayer Save
(I will upload both Server and Client logs Along with Crafttweaker Log both on Server and Client)
## Steps to Reproduce (for bugs)

1. Make 2 Blocks of Diamond, Block of Emerald, 3 Redstone Blocks, 2 glowstone and 1 Ender Star from Actually Additions
2. Use Crafting Table and put Resources in Table as shown -> https://imgur.com/dgN2oQM
3. Didn't get the end result which is Philosophers Stone

## Logs

* Client/Server Log: 
Server: https://pastebin.com/8ehQCLbS
Client:  N/A Tried to upload Client Log but I get NGINX error after finishing upload of log sorry.
* Crash Log: N/A
* Craftweaker Log:
Server: https://pastebin.com/055Pdras
Client: https://pastebin.com/5rTpkmMj

## Client Information

* Client: MultiMC
* Modpack Version: 1.0.25
* Server/LAN/Single Player: Server and SinglePlayer (Tested the recipe to see if it works which it did)
* Optifine Installed: no
* Shaders Enabled: no

**Comment by nzminecraftDOTcom** [comment]
You haven't got different script files for the client and server have you? They need to match otherwise the recipes won't show as expected. (They may vary from version to version etc)

**Comment by KillerzGodZ** [comment]
> You haven't got different script files for the client and server have you? They need to match otherwise the recipes won't show as expected. (They may vary from version to version etc)

no, I copied Client Scripts to Server I've also deleted config/scripts etc and copied them from client to server

**Comment by nzminecraftDOTcom** [comment]
As of 1.0.22r1 this is what I see https://i.imgur.com/mGUfrIt.png
It may have changed for your version perhaps.

**Comment by KillerzGodZ** [comment]
Oh okay, that works on your server?
If it does I may roll back to that version, however it's happening to other recipes also

**Comment by nzminecraftDOTcom** [comment]
Yep, works fine on my server, tried using the auto-fill thing the pack includes, by clicking the + to put the items in the crafting table?

**Comment by KillerzGodZ** [comment]
yes, I tried manual and + still doesn't work.

**Comment by KillerzGodZ** [comment]
> yes, I tried manual and + still doesn't work.



> Yep, works fine on my server, tried using the auto-fill thing the pack includes, by clicking the + to put the items in the crafting table?
> 
> And I've never heard any issues of recipes not working from my players, so presume all to be well

So I've tested locally the server for the crafting recipes and apparently something to do with the server. So I'm going to total wipe of everything (Except for the world) and I'm just gonna upload them to Server, If it fails then I will let my Hoster know what's wrong. So sorry for this post I honestly thought it would be the server in general but nope It's my hoster again so sorry.

I'll close this Bug/Issue that I had, I'll re-open it again if I run into trouble.
