### ISSUE TITLE
suspected update issue

### ISSUE THREAD

**Issue by slarzyer** [Sunekaer/stoneBlock#497]
## Steps to Reproduce (for bugs)

1. update sever
2. log on

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by slarzyer** [comment]
the starting "center chunk" at 1000 1000 seem to be messed up...check out the latest sytstem collapse utube he had same issue

**Comment by slarzyer** [comment]
it seem to be more ftb related issue cause his center wasnt the orginal center of world i believe

**Comment by nzminecraftDOTcom** [comment]
You need to fill out the form. Nobody can or will help you otherwise, they have nothing to go off "Updated server - logged on" is not an issue.

**Comment by Sunekaer** [comment]
World spawn is 0.0 but when an player logs in it auto create an island for them and there is 1000 blocks between each island
