### ISSUE TITLE
Crash when open inventory

### ISSUE THREAD

**Issue by mcfox23** [Sunekaer/stoneBlock#499]
Hello
## Bug Report

My client always crash when i open my inventory.
At the start of the modpack he didn't crash i played like 3hours.I tried to kill myself for cleaning my inventory but nothing change.
## Steps to Reproduce (for bugs)

1. open inventory
2. open crafting table

## Logs

* Client/Server Log: https://gist.github.com/mcfox23/219176310053ba9ab3a55c60a4f785d6
* Crash Log:	"monitor	Process Monitor	fatal	Process crashed with exit code -805306369"

## Client Information

* Modpack Version:1.0.25
* Server/LAN/Single Player:Single Player
* Optifine Installed:No
* Shaders Enabled:NO
+/- 8Go allowed

Thanks, felix.

**Comment by Sunekaer** [comment]
try updating your graphic drivers

**Comment by mcfox23** [comment]
All the drivers updated, that did not fix the problem.

**Comment by Sunekaer** [comment]
Okay, could you try and remove journey map and see what happens?

**Comment by mcfox23** [comment]
I removed journey map and that works well ! Nice thanks you :)

**Comment by mcfox23** [comment]
Ok no, that fixed it for 1hours, and now the game not responding like before, when i open inventory.

**Comment by Sunekaer** [comment]
new crash log?
