### ISSUE TITLE
Transmutation don`t work (Oil Bucket)

### ISSUE THREAD

**Issue by kaiand1** [Sunekaer/stoneBlock#500]
## Bug Report
Oil Bucket don`t work with Transmutation (EMC) and give Empty Bucket.
Same with Canola Oil

## Steps to Reproduce (for bugs)
1. Fill Bucket with Oil (Mining Dimension)
2. Put/Learn Oil Bucket in Transmuation Table
3. Try get Oil Bucket from Transmutation Table (Oil Bucket not Found, search Bucket)
After adding Oil Bucket another Empty Bucket appear.

![2018-10-30 16_38_12-minecraft 1 12 2](https://user-images.githubusercontent.com/44444152/47731145-d187a180-dc63-11e8-8541-5cf511f1379c.png)
![2018-10-30 16_38_23-minecraft 1 12 2](https://user-images.githubusercontent.com/44444152/47731148-d3e9fb80-dc63-11e8-8225-cecb381e9b59.png)
![2018-10-30 16_38_41-minecraft 1 12 2](https://user-images.githubusercontent.com/44444152/47731150-d64c5580-dc63-11e8-84f4-415dcd5ebb25.png)

## Client Information
* Modpack Version: V1.0.25
* Server/LAN/Single Player: Single Player

**Comment by Sunekaer** [comment]
ProjectE doesn't support NBT data on items, and there for the mod thinks its a normal bucket your giving it

**Comment by kaiand1** [comment]
Old Version work Oil Buckets...
