### ISSUE TITLE
Unable to play the game.

### ISSUE THREAD

**Issue by Estejer** [Sunekaer/stoneBlock#501]
## Bug Report
Unable to play the game (singleplayer). It crashes as soon as i create a world.

## Steps to Reproduce (for bugs)
1. Deleted and reinstalled
2. Tried other versions, they wont work either

## Logs
* Client/Server Log:
* Crash Log: [https://pastebin.com/igZwrw8J](https://pastebin.com/igZwrw8J)

## Client Information

* Modpack Version: 1.0.25 and earlier
* Server/LAN/Single Player: singleplayer
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
Could try with pack version 1.0.26, and if that also crashes please upload latest and crash log

**Comment by Estejer** [comment]
Still crashes. Crash-Log: https://pastebin.com/e7AUDhvw
latest.log was to big to upload on pastebin so i uploaded it here.

[latest.log](https://github.com/Sunekaer/stoneBlock/files/2536657/latest.log)

**Comment by Kratzwurst** [comment]
How much Memory have you? This Pack needs minimum 5-6 GB Ram to run. Please Check your launcher settings

**Comment by nzminecraftDOTcom** [comment]
It looks as if you've modified java args. You have done it incorrectly in this case. You can only modify java args though the twitch launcher, hence you may be running the game with only the default 1gb of ram allocated.

**Comment by Estejer** [comment]
> How much Memory have you? This Pack needs minimum 5-6 GB Ram to run. Please Check your launcher settings

I allocated 6-8GB of ram, im fine playing other packs with the same settings. It's just stoneblock.

**Comment by Estejer** [comment]
> It looks as if you've modified java args. You have done it incorrectly in this case. You can only modify java args though the twitch launcher, hence you may be running the game with only the default 1gb of ram allocated.
> 
> Top left 3 dashed lines --> File --> Settings --> Minecraft -> Scroll down -> Ensure that is set up correctly.

God damn, thank you! I deleted the java arguments and it works now. Kinda weird because they work with all other modpacks i played before. It is working now.
