### ISSUE TITLE
Crashes when loading into game

### ISSUE THREAD

**Issue by kenshin2666** [Sunekaer/stoneBlock#503]
## Bug Report

After selecting me world, when I load into the game my FPS tanks and the game freezes before crashing.
## Steps to Reproduce (for bugs)

1. Select game world
2. Allow to load
3. Attempt to move
4. Crash

## Logs

* Client/Server Log: https://gist.github.com/kenshin2666/a470d6c247c7a0db22f088be79151399
* Crash Log: 

## Client Information

* Modpack Version: 1.0.25.
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by knoxhack** [comment]
You allocating enough RAM to Minecraft?

**Comment by knoxhack** [comment]
Nvm, that's a bugged refined storage system

**Comment by knoxhack** [comment]
Since this is a mod issue, could you report this to the mod author?

**Comment by knoxhack** [comment]
Refined Storage that is

**Comment by kenshin2666** [comment]
I can find out where to and give them a ping about it. What exactly is happening with the mod that its messing up my game? This was my first time getting into Refined Storage.

**Comment by xILikepuddingx** [comment]
nobody likes refined storage =( vote for remove <.<

**Comment by raoulvdberge** [comment]
And I don't like you, @xILikepuddingx! Nor do I like pudding!

**Comment by xILikepuddingx** [comment]
we can gladly continue where we left off. but has nothing to look for here. Just go back to your little kids modding

**Comment by raoulvdberge** [comment]
Oh, I remember you now, I had blocked you because of your shitty issue.

https://github.com/raoulvdberge/refinedstorage/issues/2048

**Comment by xILikepuddingx** [comment]
shitty issue? so it's not stupid that you can easily dupe in an offline grid? it is not a fact that the mod is totally unsuitable for servers? the controller itself is partially 20-40 ms. autocrafting tops that even with 100 ms per crafter. and now this bug.

I also said that the mod has potential. but not with these mistakes. where I have to say that it has improved in comparison to the 1.10.2.

**Comment by Sunekaer** [comment]
please take that discussion another place

**Comment by nzminecraftDOTcom** [comment]
If you've got an NBT editor, it's simple to fix. You just need to load up the region .mca file that contains the block @  -1000 90 -995 and delete it (you will lose [assuming this is an RS controller] that block)

Or if you want, you can upload region file r.-2.-2.mca here and I can sort it out and then send it back if you don't know what to do.

**Comment by kenshin2666** [comment]
> 
> 
> If you've got an NBT editor, it's simple to fix. You just need to load up the region .mca file that contains the block @ -1000 90 -995 and delete it (you will lose [assuming this is an RS controller] that block)
> 
> Or if you want, you can upload region file r.-2.-2.mca here and I can sort it out and then send it back if you don't know what to do.
> 
> I suspect this is an auto-crafting setup and these are very well known to cause game issues.

Hey there nzminecraft,I don't trust myself for fixing it properly as I have no experience doing so, so I'd feel safer with someone else doing so. I had to just zip the file to attach it. Much appreciated. I dont mind losing whatever block is causing the issue, everything can be regained with some afk and such.
[r.-2.-2.zip](https://github.com/Sunekaer/stoneBlock/files/2536241/r.-2.-2.zip)

**Comment by nzminecraftDOTcom** [comment]
I don't think that region file is from the right world, can you check again that you have copied from the right game save?

**Comment by RehabOholic** [comment]
I was trying to remove the controller with NBTExplorer since I know of no other to use. My crash report also says -2-2, but have not found it after messing around for over an hour. Tried to mcedit out, but it removes everything because of block ids or something.  I even tried going back 3 pack versions one at a time and get the crash for discord something on one and the auto crafting on the other 2.

**Comment by raoulvdberge** [comment]
You can just use MCedit. It won't remove your blocks nor change the block ids. You just need to locate the RS controller and remove it.

**Comment by nzminecraftDOTcom** [comment]
I've just had a second look at the region file, chance cubes shouldn't be generating in a 100% stone world. I've just had a look at some random regions on my sever and none of them show chance cubes being generated, so as above please make sure you have sent the correct world file through.

**Comment by kenshin2666** [comment]
My apologies! I searched up just the "r.-2.-2.mca" and i didnt know there were multiple ones in the different folders and just clicked on the only thing that popped up for me >< I followed the directory path you said and this is the (i believe, hopefully) proper file. 
[r.-2.-2.zip](https://github.com/Sunekaer/stoneBlock/files/2540481/r.-2.-2.zip)

I did mess around with mcedit for my first time and popped in my level and like, deleted the entity or something at the block location, then updated to the new version of StoneBlock and it allowed me to get into the game for more than a few seconds but I caught this and am not sure what's going on: 
![rs](https://user-images.githubusercontent.com/44624535/47886289-890ce700-de0f-11e8-9f71-cdcaeea499f3.png)

**Comment by nzminecraftDOTcom** [comment]
Sweet I'll take a look for you when I get home from work.

**Comment by raoulvdberge** [comment]
That is optifine.

**Comment by raoulvdberge** [comment]
That is Optifine.

**Comment by nzminecraftDOTcom** [comment]
[r.-2.-2.zip](https://github.com/Sunekaer/stoneBlock/files/2540961/r.-2.-2.zip)
There you go, try replacing the existing r.-2.-2.mca file with that one.

**Comment by kenshin2666** [comment]
Hey there! I dropped in and replaced the file and I was able to load in with what seems like no problem. No crash. Although I still get the 5 fatals in the console as I did before, not sure if that has anything to do with this issue or its something else?
![capture](https://user-images.githubusercontent.com/44624535/47941717-aac8a580-dec5-11e8-91c9-e842943254f5.PNG)

**Comment by nzminecraftDOTcom** [comment]
That's a  different issue to the one you have here, if the game runs fine then i wouldn't worry about them

**Comment by kenshin2666** [comment]
It seems my delight to play StoneBlock again was short lived. Any time I access my RS system, I crash still X_X

**Comment by nzminecraftDOTcom** [comment]
Break the lot and try re placing it all. If that fails move to ae2

**Comment by kenshin2666** [comment]
This is the best setup I've been able to figure out how to move my items from RS to AE2. I feel bad i had to just cheat in items but it seems the only way to progress at this point. Hopefully whatever RS is doing to cause this issue gets fixed as I'm very fond of how easy the mod was to learn and versatile it was. Don't know if there's a faster way of moving 2m items?

![untitled](https://user-images.githubusercontent.com/44624535/47944741-e4081200-ded3-11e8-88f2-2aceebf5468c.png)

**Comment by raoulvdberge** [comment]
Were you having the same crash?? Why aren't you sending me that crash?

**Comment by nzminecraftDOTcom** [comment]
If you're using import busses put acceleration cards in them. It will pull items in stacks.

**Comment by kenshin2666** [comment]
I have the speed upgrades in the disk manipulators and the ME import bus. the import bus isnt having any trouble but the manipulators are only exporting like 10 items a second while seems to be the speed limitation I'm at.

For the crashes it seems like I have nothing in my crash logs folder :/ and when I took the screenshot overwrote the copy of the console copy. So I got nothing other than stuff in the logs folder if that's any help @raoulvdberge  :(

**Comment by Smario9000** [comment]
What it seems like to me is that two different mods conflicting with each other

Whatever you got connected to the RS system is what's causing it

What all did you have hooked up because even with the stuff I have hooked up I've never had this problem

So I'm actually kind of curious on what you have hooked up that was causing this issue

**Comment by kenshin2666** [comment]
Ummm I had the standard setup with all the RS monitors and such all together, and that was connected to a couple external storages a few chunks away for my mob farm drop drawers as well as my chickens. to the rear was my room with things like the alloy smelter and such. I had an importer on each of 2 ender chests bringing in items from the mining dimension and quantum quarry. And there was the multi-block pattern storage connected as well, was a fairly small one only like a 8x8x8 or something of the sort. Other than that there really wasnt too much else. From what I've seen in youtube videos the amount of stuff I had going on was quite minimal? I dont know. Its unfortunate this has happened as I havent gotten to play in 2 weeks and it was my first time using the RS system and really like it.

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue

**Comment by Smario9000** [comment]
Do you still have the save file

**Comment by kenshin2666** [comment]
> 
> 
> Do you still have the save file

I do, sorta. My laptop fan was going a little wonky and making some unpleasant noises so I had to send it in for servicing. I wont have the laptop back for about 2-4 weeks (estimated). Will have to wait till then.
