### ISSUE TITLE
Chunk load and Steves Cart

### ISSUE THREAD

**Issue by Narinja1** [Sunekaer/stoneBlock#504]
The chunk loading upgrade to use whit Steves cart is missing. If this is deliberetly done its okay. But the chunk loading by claiming chunks do not work to run the cart. I try to use it in the mining dimension to mine whit but becous of the inabilety to load shunks its not working to well. I dont know if this is a bug or if its just note the meaning to load chunks in this pack.

**Comment by Sunekaer** [comment]
Yes i removed steves carts own chunkloader, please report the issue to steves cards or FTB, as its those two mods not working together
