### ISSUE TITLE
Flux-infused Jetplate

### ISSUE THREAD

**Issue by Etheria137** [Sunekaer/stoneBlock#507]
## Bug Report
When I was trying to craft the flux-infused Jetplate It didn't allow me to craft it and I tried charged and fully uncharged and there was no difference. 

## Steps to Reproduce (for bugs)
1.https://imgur.com/a/dHcw174

## Logs
* Client/Server Log: 
* Crash Log:

## Client Information
* Modpack Version: 1.0.26
* Server/LAN/Single Player: single
* Optifine Installed: no
* Shaders Enabled: no

**Comment by psycheau** [comment]
Can't tell which crafting table you're using but did you try a  different crafting table? Perhaps try a standard table. Some things don't work in the refined storage crafting table for example I've found.

**Comment by Etheria137** [comment]
I tried using the wood crafting table, stone crafting table, and the refined storage crafting table and none of them worked.

**Comment by P4t0r1kku** [comment]
hmm.. i'm on 1.0.26 SinglePlayer and had no problem to craft it. Annoying part was the Wireless antenna which kept charging the items, so always had to manually place the charged parts into the crafting grid ^^
![2018-11-01_15 12 39](https://user-images.githubusercontent.com/44398409/47857095-15f07a00-dde9-11e8-939e-9ae2eca7f4f6.png)

**Comment by Etheria137** [comment]
found the problem, when I was reading the recipe I didn't see the armored flux pack I thought it was a normal one. Sorry for wasting your time.
