### ISSUE TITLE
Ore Excavation on Stone not working?

### ISSUE THREAD

**Issue by Munchiest** [Sunekaer/stoneBlock#509]
I don't know if it's intentional or not but it doesn't work on stone blocks.

**Comment by P4t0r1kku** [comment]
I think it's intensional, becouse the Whole World is Stone. There is no Layer of Bedrock below it. So, if you Excavate all the Stone below. you could fall into the Void over and over and over... 😄

**Comment by Mordaii** [comment]
This definitely is intentional.  Stone is in the ore excavation blacklist.

**Comment by Munchiest** [comment]
Yeah I thought it might be intentional :D thanks guys
