### ISSUE TITLE
Steel Ingot from Tiny Progressions is craftable?

### ISSUE THREAD

**Issue by Munchiest** [Sunekaer/stoneBlock#514]
I see all steel ingots except thermal foundation's are blocked or converted to it's. (only this steel ingot can be seen in JEI). You can't see Steel Ingot recipe of Tiny Progressions in JEI directly but you can still craft it. I thought that might be unintentional because it makes getting steel so easy and fast?

**Comment by Sunekaer** [comment]
Recipe showing under Thermals steeling ingot

**Comment by Sunekaer** [comment]
1.0.27
