### ISSUE TITLE
can't auto-craft certain items using Refined Storage

### ISSUE THREAD

**Issue by KillerzGodZ** [Sunekaer/stoneBlock#516]
Hello I'm putting this here so you know (I won't be able to reply till 7-8am in the morning for me, and won't be able to reply after 9:00 am my timezone is GMT+13 If you wanted to know) 
## Bug Report

So I use Refined Storage quite a lot for auto crafting (the issue the task) but some items can't be crafted in Refined Storage, for Example, this https://imgur.com/a/DiEQjZ6 and it happens with other Mekanisms Smeltery and if this is the case then this needs to be addressed.
## Steps to Reproduce (for bugs)

1. make patterns for Basic Smelting Factory along with pre-requisites to craft/smelt items required
2.  Issue task to make basic Smelting Factory 
3. Don't get end result as shown -> https://imgur.com/a/DiEQjZ6

## Logs

* Client/Server Log:
Server: https://gist.github.com/KillerzGodZ/64a09c3e6c72917378d094b8d1a27beb
* Crash Log: N/A

## Client Information

* Client: MultiMC
* Modpack Version: 1.0.25
* Server/LAN/Single Player: Server (haven't tested in Singleplayer Yet)
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Etheria137** [comment]
The problem is you need a recipe for the energized smelter because it is part of the recipe for the basic smelter.

**Comment by Sunekaer** [comment]
answered by Etheria137
