### ISSUE TITLE
Crashing at Startup

### ISSUE THREAD

**Issue by RezaSmith** [Sunekaer/stoneBlock#517]
## Bug Report
So from my understanding , after some investigation , i found out that the mod CraftPresence requires internet while in loading , so its all fine until here but idk if its dns issue or what but me and my friends always crash if we dont use vpn while loading the game . now this is just not needed , i hope you can remove this mod or find a way around it

## Steps to Reproduce (for bugs)
1. launch the game
2. wait for loading step 4
3. that's it

## Logs

* Crash Log: https://paste.ee/p/ZMutw

## Client Information
* Modpack Version: 1.0.26
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

**Comment by KiteXBlack** [comment]
Go to your Stoneblock installation folder search for the folder mods and find the craftpresence.jar and just delete it or disable it we had the same problem and this fixed it.

**Comment by Sunekaer** [comment]
That Error could be due to a partial/corrupted DiscordRPC dll file, so can you try removing (if it exists) the CraftPresence folder from your instance's .minecraft?

**Comment by RezaSmith** [comment]
the thing is it load OK while i change my ip or use some kind of VPN , but anyway since it's a Client-side mod i just removed it , thanks
