### ISSUE TITLE
AE Facade not craftable.

### ISSUE THREAD

**Issue by demethan** [Sunekaer/stoneBlock#52]
## Bug Report
4 anchor and one red wool. that usually works for me in the other packs.  I color code the P2P with facades to not mix them up.  

## Steps to Reproduce (for bugs)

1.place recipe in crafting grid. No output.
2.

![image](https://user-images.githubusercontent.com/5810363/44039691-9966ecf2-9ee7-11e8-843f-c416f8397da3.png)

![image](https://user-images.githubusercontent.com/5810363/44039610-7348dddc-9ee7-11e8-9fa4-85a23339c526.png)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:1.0.11
* Server/LAN/Single Player:Server
* Optifine Installed:No
* Shaders Enabled:No

**Comment by Sunekaer** [comment]
Not a bug. they are currently disabled.
You can enable them in /config/AppliedEnergistics2/AppliedEnergistics2.cfg line 215

**Comment by demethan** [comment]
Any particular reason. Will enabling crash the server?
