### ISSUE TITLE
Update Better Questing - LAN Party doesn't work with old versions

### ISSUE THREAD

**Issue by MokahTGS** [Sunekaer/stoneBlock#520]
please update the modpack to use the newest version of Better Questing (273+).  There is a fixed bug that prevents people on LAN from joining parties.

**Comment by DaWeegee** [comment]
If the inviting player has admin mode enabled it should work. At least it did for us.

**Comment by MokahTGS** [comment]
Inviting player is the host and op.  Update the mod and it works.

**Comment by KiteXBlack** [comment]
What he meant was the host has to give himself admin for better questing via bq_admin

**Comment by Sunekaer** [comment]
1.0.27
