### ISSUE TITLE
Can`t  play. Some help?

### ISSUE THREAD

**Issue by Honcharuk** [Sunekaer/stoneBlock#521]
Cant start the game. Reinstall Java, forge, StoneBlock

## Bug Report
Cant load game

## Steps to Reproduce (for bugs)
1. Start game
2. Crash

## Logs
https://pastebin.com/bvfK5CDG

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: single
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
try deleting scala-reflect in minecraft/install/libraries/org/scala-lang/scala-reflect/2.11.1

**Comment by Honcharuk** [comment]
Thank you, it helped, do not know why this happened?

**Comment by Honcharuk** [comment]
helped on one run, again the same error.

**Comment by Sunekaer** [comment]
youll have to contact twitch as its an problem with their launcher, the fix i gave you normal fixes it for good
