### ISSUE TITLE
Bug with an oven from "Cooking for Blockheads" mod

### ISSUE THREAD

**Issue by xkatsuro** [Sunekaer/stoneBlock#522]
## Bug Report
Wireless Heating Coil from EU2 is consumed in the oven (Cooking for Blockheads)

## Steps to Reproduce (for bugs)

1. Use a wireless heating coil in the CfBH oven 
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: SP
* Optifine Installed: yes
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
