### ISSUE TITLE
Server won't generate voidworld level

### ISSUE THREAD

**Issue by Hellboen** [Sunekaer/stoneBlock#529]
## Bug Report
No matter what I do, my server(latest stoneblock server.zip from the download tab) won't generate the voidworld required to play stoneblock. I've tried everything within my knowledge.

## Client Information

* Modpack Version: 1.0.26, latest version as of 11/03/2018
* Server/LAN/Single Player: Server
* Optifine Installed: False
* Shaders Enabled: False

**Comment by Sunekaer** [comment]
stop server, delete world folder, change level-type to voidworld, start server

**Comment by Hellboen** [comment]
how can you close this, when you don't know if it worked lol.
it didn't work
