### ISSUE TITLE
Unable to Launch Server, Missing Essential Libraries

### ISSUE THREAD

**Issue by AeZ0** [Sunekaer/stoneBlock#530]
## Bug Report
Cannot launch server. When I run the Install.bat file, it installs all the necessary files(As far as I can see), but it doesn't install the forge file and the necessary libraries. Initially I got an error where the LaunchServer.bat file could not access the universal forge jar so I extracted the jar from the installer into my server directory. Afterwords, I kept getting the error that I was missing essential libraries. I tried to install the client and server files from the forge installer, but they didn't help.

## Steps to Reproduce (for bugs)

1. Run Install.bat
2. Extract Forge from installer into Server Directory
3. Run LaunchServer.bat
4. Install Client from installer into Server Directory
5. Install Server from installer into Server Directory

## Logs

* Client/Server Log:
https://pastebin.com/pUmV4ia7
https://pastebin.com/iL3f6aXv

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Honcharuk** [comment]
Forge broke, you need to wait for repair.

**Comment by Sunekaer** [comment]
The Forge Download server is currently having issues. 

http://www.minecraftforge.net/forum/

**Comment by Hellboen** [comment]
you have to change the name of the Minecraft_Server.jar to forge-1.12.2-14.23.5.2768-universal.jar, after running the install.bat. that worked for me.
