### ISSUE TITLE
Tectonic Initiator in Pulveriser doesn't produce Tectonic Petrotheum?

### ISSUE THREAD

**Issue by Ann-MarieR** [Sunekaer/stoneBlock#532]
## Bug Report
Despite various ores being shown to process in the TE Pulveriser with Tectonic Initiator augment, producing a larger yield, plus liquid Tectonic Petrotheum, it just sits there doing nothing  - no power usage, no processing, no yield.

Tested so far on Destabilized Redstone Ore, Resonant End Stone, and Oil Shale (will update as I can try more ores)

## Steps to Reproduce (for bugs)
1. Set up Pulveriser with connection to suitable power.
2. Upgrade Pulveriser (took mine to Resonant)
3. Add Augment: Tectonic Initiator.
Try inserting Destabilised Redstone Ore, Resonant End Stone, or Oil Shale (all ores gathered by Tier 1 Void Ore Miner) - note that all 3 have a Tectonic  Initiator JEI entry.
4. See that the items go in (so the machine accepts them), but nothing happens.

## Logs
N/A

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Augment doesnt make Tectonic Petrotheum, is uses Tectonic Petrotheum to increase yield from ores

**Comment by Ann-MarieR** [comment]
Oops... my bad, I misread JEI the first time, and assumed it might be a way to get supplementary power for my processing setup.
