### ISSUE TITLE
Extreme Reactor's won't oredict

### ISSUE THREAD

**Issue by MrTestificate1** [Sunekaer/stoneBlock#533]
## Bug Report

Extreme Reactor's won't oredict refined uranium and yellorium ingots for crafting recipes
Scripts show removing yellorium from the oredict however the recipes user the oredict.
Not seeing a direct recipe to convert back and forth
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.27
* Server/LAN/Single Player: SSP
* Optifine Installed: Yes
* Shaders Enabled:

**Comment by Etheria137** [comment]
It’s becuase the recipe for refined uranium is from the ore not dust

**Comment by MrTestificate1** [comment]
However with the yellorium crops and chickens it produces actual yellorium and not the refined uranium

**Comment by Sunekaer** [comment]
first of theres not version 1.0.27
second there an crafting recipe to convert yellorium and uranium
