### ISSUE TITLE
[1.0.26] Crash Report

### ISSUE THREAD

**Issue by TheMingo888** [Sunekaer/stoneBlock#535]
## Bug Report

My client crashed while trying to connect to a localhost server.

## Steps to Reproduce (for bugs)

Unknown

## Logs

* Client/Server Log: https://gist.github.com/TheMingo888/89607ca23413590729725a1a64d76edb
* Crash Log: https://pastebin.com/fEFt1AUM

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: Localhost Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
510

**Comment by Sunekaer** [comment]
#510
