### ISSUE TITLE
Compacting Drawer thinks Compressed Bone Block recipe is Bone Meal (duplication bug)

### ISSUE THREAD

**Issue by griseouslight** [Sunekaer/stoneBlock#536]
## Bug Report

Placing Tiny Progression's "Compressed Bone Block" in a compacting drawer incorrectly sets it as bonemeal, allowing you to effectively triple your bonemeal.

![javaw_2018-11-03_21-18-32](https://user-images.githubusercontent.com/9774133/47959015-30745000-dfaf-11e8-9927-955833a5784c.png)

## Steps to Reproduce (for bugs)

1. Place Compressed Bone Block in a compacting drawer

That's it for the bug, but this allows you to:
1. Put in 9 Bone Meal
2. Remove the Compressed Bone Block
3. Decompress the Bone Block into 9 Bones
4. Craft that into 27 total Bone Meal
5. Repeat

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Etheria137** [comment]
When I put 9 bone meal in a got a bone block which equals 9 bone meal.

**Comment by griseouslight** [comment]
> When I put 9 bone meal in a got a bone block which equals 9 bone meal.

Unless there is something wrong with my pack, the bone block crafts into 9 bones, not 9 bone meal.

**Comment by Sunekaer** [comment]
1.0.27
