### ISSUE TITLE
Request: ArchitectureCraft or other aesthetic block shape mod

### ISSUE THREAD

**Issue by Nonsanity** [Sunekaer/stoneBlock#537]
Missing Pieces mod adds wedges and columns, but only for a very restricted set of vanilla textures, not even including the concrete colors. Stoneblock makes for a wonderful kitchen sink environment, but beyond chisels and bits, there's a dearth of aesthetic block shapes—slope varieties in particular. Adding a mod like ArchitectureCraft or BlockCraftery would allow for much more photogenic builds.

**Comment by Sunekaer** [comment]
i wont be adding anymore mods
