### ISSUE TITLE
Server connection issue

### ISSUE THREAD

**Issue by Warrriorrr** [Sunekaer/stoneBlock#538]
## Bug Report
Crash upon joining my own server, yet single player works and other players can connect to mine

## Steps to Reproduce (for bugs)
1. Freshly up to date StoneBlock modpack downloaded via Twitch launcher
2. Freshly up to date StoneBlock server files downloaded, installed, launched, and running (Friend can connect to it)
3. Launch StoneBlock via Twitch launcher
4. Go into single player world, creates and loads up fine, exit.
5. Attempt to connect to my server via ip:port
6. Server says I timeout, client says I am running a modified and unsupported version of the game

## Logs
* Client/Server Log: https://gist.github.com/Warrriorrr/53e5fcd6c1ed903ce729f6c4e0420390
* Crash Log: https://gist.github.com/Warrriorrr/3576be8abaa50201259fba554265e221

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: Self-hosted server and Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
#510
