### ISSUE TITLE
Game Crash when joining server

### ISSUE THREAD

**Issue by MattyyyG** [Sunekaer/stoneBlock#539]
Bug Report
I can join the server fine, my friend however crashes with a Nullpointerexeption error whenever he joins.

Steps to Reproduce (for bugs)
1. Opens modpack
2. Joins server
3. Crashes after loading terrain

Logs
Client/Server Log: https://pastebin.com/sREJQSSU

Client Information
Modpack Version: 1.0.26
Server/LAN/Single Player: Server
Optifine Installed: Nope
Shaders Enabled: Nope

**Comment by MattyyyG** [comment]
Worth noting that i did disable CraftPresence on the server before this particular crash because it was a fix in an earlier thread

**Comment by Sunekaer** [comment]
#510
