### ISSUE TITLE
game crash 

### ISSUE THREAD

**Issue by dityareborn** [Sunekaer/stoneBlock#540]
when Im trying to join my friends server game crashes after +-30 sec and in multiplayer chat writes that I leaved from server without joining but some times it writes that I joined and after disconnected but game keep crushing https://media.discordapp.net/attachments/399295188113293332/508366410569744405/unknown.png?width=1202&height=677
![unknown](https://user-images.githubusercontent.com/44749687/47965878-5bb57880-e05d-11e8-807c-93ed73e3bb37.png)

[crash-2018-11-03_22.48.08-client.txt](https://github.com/Sunekaer/stoneBlock/files/2545949/crash-2018-11-03_22.48.08-client.txt)

**Comment by Sunekaer** [comment]
use the template when creating an issue
