### ISSUE TITLE
Very Important Bug

### ISSUE THREAD

**Issue by P0ru** [Sunekaer/stoneBlock#544]
I have a Rx580 and a ryzen 1700x working at stock clocks.

The problem is that when ur playing full screen u need optifinehd to make it at 60 fps stable with no drops.
You add optifine in the mods folder and all ok, the problem is when u interact witch the crafting table from tinker`s construct, it makes u graphics card to stop wotking at max mhz and the game starts to drop fps and sutter because of that.
I am sure there are more interactions that does that.

**Comment by Sunekaer** [comment]
use the template when creating an issue

**Comment by P0ru** [comment]
sry first time using git hub
