### ISSUE TITLE
Itemducts won't pull

### ISSUE THREAD

**Issue by McSassyK** [Sunekaer/stoneBlock#545]
Ever since the most recent update to the pack, Thermal Dynamics itemducts randomly stop working or don't work at all. 

1) I have two identical farms set up with cloches. I have itemducts attached to the output. No servo since cloches auto output (though I did try servos to see if that would matter). The left farm works fine, extracts everything. The right farm randomly stops extracting, or only extracts some of the items. For example, it will extract the wheat, but not the seeds.

2) I have a Cyclic harvester set up, with itemducts and signalum servo. It was working fine. When I swapped out the signalum servo for a resonant, the itemduct stopped working. I put the signalum server back, and it still didn't work.

I did some other testing, to see if I could just cycle objects between two basic chests. No luck. I tried with a redstone signal and without.

**Comment by Sunekaer** [comment]
what do they insert to?

**Comment by netmc** [comment]
Out of curiosity, are either of these on the chunk boundary where the machine is in one chunk and the duct in the other?  This shouldn't cause problems, but I've seen cases where stuff just doesn't work right when on the boundary.

Also, ducts will generally only accept items when they're is a valid destination for them to go to.    If the duct is back-stuffed, the back-stuff will have to be cleared out before normal functionality returns.  Have you tried connecting a regular chest to the output line and see if you get all the items in it?

**Comment by McSassyK** [comment]
They’re not on a chunk boundary. The items are being piped into my refined storage, which has room for another half million items. I have the same result when I try to pipe into chests.

**Comment by PlacidK** [comment]
I had a similar problem with cloche and thermal pipes. Try wrenching the cloche a couple times.

**Comment by McSassyK** [comment]
Thanks. Sadly, I wrenched like my life depended on it, and no luck. I went through the entire line to make sure everything was configured correctly, that everything had somewhere to export to, that there were no blockages or backlogs anywhere. I moved machines around, checked chunk boundaries, made sure chunks were loaded. Nothing works. I even just took two chests and tried to pipe items between them. Just used vanilla items. Couldn’t get the pipes to extract consistently. 

Before the last update, no issues at all. (Btw, still a GREAT pack even with these little glitches).

**Comment by netmc** [comment]
I did run into a similar issue with the cloche.  I just set up my farm, and the item ducts connected to the output on some farms, but not others.  Wrenching them didn't work.  I had to break the farm and replace it for the ducts to connect to the cloche.  I'm thinking that this is an IE bug.

**Comment by Sunekaer** [comment]
Please report this to IE

**Comment by McSassyK** [comment]
Will do. For now, I replaced the ducts with Mekanism pipes and everthing’s up and running perfectly! Thanks for looking into it.
