### ISSUE TITLE
Ore unification issue with aluminum

### ISSUE THREAD

**Issue by netmc** [Sunekaer/stoneBlock#546]
If you smelt the aluminum chunks in a TC smeltery, you get thermal foundation's aluminum ingot.  If you use a thermal expansion induction smelter, you get mekanism aluminum.

The other ores seem to be the same output for both setups with unification to thermal foundation's ingots.

**Comment by Sunekaer** [comment]
I get Thermals aluminum ingots in the induction smelter, what is it your smelting when you get that mekanism alu

**Comment by netmc** [comment]
I am smelting the ore chunks you get from sifting.  I am using the ore chunk + sand recipe in the induction smelter.

**Comment by Sunekaer** [comment]
1.0.27
