### ISSUE TITLE
Treated Planks/Immersive Engineering

### ISSUE THREAD

**Issue by xkatsuro** [Sunekaer/stoneBlock#547]
## Bug Report
Missing recipe for treated wood.
## Steps to Reproduce (for bugs)

1. Search for "treated wood planks" in Jei
2. Look through the recipes

I don't know if that is intentional and the recipe had been changed to "world interaction" one, if yes, there should be an "info tab" explaining how to get the treated wood. Creosote oil is unavailable too, perhaps for the reason I described above.
## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: SP
* Optifine Installed: yes
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/47999904-329bf300-e104-11e8-9dda-625d0523f71b.png)
![image](https://user-images.githubusercontent.com/18720460/47999913-3e87b500-e104-11e8-8f3e-68289f662230.png)
