### ISSUE TITLE
game crashes connecting trough evolve

### ISSUE THREAD

**Issue by dityareborn** [Sunekaer/stoneBlock#548]
## Bug Report
game crashes connecting trough evolve

## Steps to Reproduce (for bugs)
1. Go to Multiplayer
2. Start connection with direct connect
3. Type in the evolve and the server port of the LAN server
4. Connect
5. on the server that u left game without joining
## Logs

[crash-2018-11-03_22.48.08-client.txt](https://github.com/Sunekaer/stoneBlock/files/2548345/crash-2018-11-03_22.48.08-c
![unknown](https://user-images.githubusercontent.com/44749687/47998217-9a0b7000-e10f-11e8-8810-2be138748562.png)
lient.txt)

## Client Information

* Modpack Version:1.0.26
* Server/LAN/Single Player:lan
* Optifine Installed: no
* Shaders Enabled:no

**Comment by Sunekaer** [comment]
#510
