### ISSUE TITLE
crashing after restart it crashes soon as world opens

### ISSUE THREAD

**Issue by desiredstoner69** [Sunekaer/stoneBlock#55]
[crash-2018-08-13_21.37.46-server.txt](https://github.com/Sunekaer/stoneBlock/files/2285240/crash-2018-08-13_21.37.46-server.txt)

## Bug Report

game crashed soon as i connected table to storage system
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: latest release
* Server/LAN/Single Player:  single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
Please upload log to pastebin.com or gist.github.com

**Comment by SynexWolf** [comment]
From the crash log, it appears to be an interaction issue with project E and Refined storage. As far as I know, refined storage integration with project e isn't supported anymore. There are mods that allow the integration, but refined storage itself is no longer supporting it.
https://refinedstorage.raoulvdberge.com/wiki/project-e-integration/a685e913183263f9d3b4a15d523ec144 (Link to where project E integration *should be* but no longer exists.)

**Comment by Sunekaer** [comment]
Well I haven't read the log yet, still waiting for him to upload it as gist or Pastebin before I open it

**Comment by Sunekaer** [comment]
Closed do to logs haven't been posted in pastebin.com or gist.github.com yet
