### ISSUE TITLE
Immersive Engineering Missing

### ISSUE THREAD

**Issue by bogointeractive** [Sunekaer/stoneBlock#550]
As I have played through the pack I have all of this oil and nothing to either pump or refine it for use. This has been missing since the start. Also I have yet to get dimlets or anything to allow me to create RF Tools Dimensions. Also I have noticed with certain Ender IO that it causes my single player world to just stop working. In that my ender chest which is used to import everything into my AE2 system is constantly full. So when I go to run a builder quarry it stops because it is full. 

Also, I have noticed the wireless crafting terminal constantly loses power or connection. I used to be able to just insert one booster card but now I have to use the creative ones. Even those have issues.

**Comment by Sunekaer** [comment]
Use the template when creating an issue

**Comment by bogointeractive** [comment]
I changed it, sorry
