### ISSUE TITLE
[1.0.26] Steel Block Conflict

### ISSUE THREAD

**Issue by TheMingo888** [Sunekaer/stoneBlock#551]
## Bug Report

There are two recipes to craft a block of steel, resulting in a recipe conflict. One involves creating the Mekanism block, while the other (likely intended) recipe involves creating the Thermal Foundation block.

## Steps to Reproduce (for bugs)

1. Try to craft a block of Thermal Foundation Steel
2. End up with a block of Mekanism Steel.

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
1.0.27
