### ISSUE TITLE
Shift clicking too much coal into the furnace generator crashes the game

### ISSUE THREAD

**Issue by id0001** [Sunekaer/stoneBlock#553]
---
name: Bug report
about: Create a report to help us improve

---

## Bug Report
When I shift click coal into the furnace generator and the total amount would be over 64, the game hangs until I force close it.

## Steps to Reproduce (for bugs)
1. Have a furnace generator running
2. Shift click a stack of coal into the input slot making the total amount of coal in the machine over 64
3. crash

## Logs

* Client/Server Log: https://gist.github.com/id0001/80a7fb741c96606356b983e9a9025158
* Crash Log: No crash log

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/issues/226

**Comment by Heyo13579** [comment]
im getting the same issue but with me its anytime i try to but any large amount into the generator

**Comment by redwolf41** [comment]
I'm having this issue as well, but its happening when I try to shift click coal into my bag of holding.

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
