### ISSUE TITLE
i have a couple of questions?

### ISSUE THREAD

**Issue by joshuasuperboy** [Sunekaer/stoneBlock#554]
I wanted to ask is it possible to find a molten infinity dimlet in the RFTools dim dimlet buildings or did you disable it? If you did, i would like to enable it where can i enable it at in the configs if you did disable it. The reason why is because i been searching for almost 2 days for it. I have found every other op molten liquid dimlets except for a dimlet for molten infinity from avaritia. Is it just super bad luck or is it disabled?

**Comment by Sunekaer** [comment]
No dims has been disabled

**Comment by joshuasuperboy** [comment]
never mind i figured it out

**Comment by joshuasuperboy** [comment]
so im just very unlucky on finding it

**Comment by joshuasuperboy** [comment]
I FOUND IT

**Comment by joshuasuperboy** [comment]
finally

**Comment by joshuasuperboy** [comment]
oh yea infinite infinity ingots

**Comment by joshuasuperboy** [comment]
im skipping on getting compressed single larities
