### ISSUE TITLE
Veinmine Hopping Bonsai

### ISSUE THREAD

**Issue by DracoClaw** [Sunekaer/stoneBlock#556]
## Bug Report
Veinmining a hopping bonsai pot with trees in them, at the time Pam's Harvestcraft, caused my world to stop responding.

## Steps to Reproduce (for bugs)
1. I had a row of three hopping bonsai pots on top of 2x2 oak storage drawers
2. Inside the pots were Pam's Harvestcraft trees, Paperbark, Spiderweb, and Apple
3. I didn't like the placement so I went to remove them
4. Used Veinminer for it to go faster, because I'm lazy
5. The screen froze and the game stopped responding.

## Logs
* Client Log: https://pastebin.com/dyn4jZ4S
* Crash Log: https://pastebin.com/7Av0ecF9

## Client Information
* Modpack Version: 1.0.26
* Server/LAN/Single Player: Single Player
* Optifine Installed: Nope
* Shaders Enabled: Nope

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue

**Comment by Godvil** [comment]
@DracoClaw @Sunekaer 

There is a workaround in oreexcavation config. I'm using this on my server.

    # Blocks blacklisted from being excavated [default: ]
    S:"Block Blacklist" <
        bonsaitrees:bonsaipot
        bonsaitrees:bonsaipot_hopping
     >
