### ISSUE TITLE
Fluxbore enchanted with Silk Touch issues

### ISSUE THREAD

**Issue by Algester** [Sunekaer/stoneBlock#558]
## Bug Report
There are some blocks which when broken by the fluxbore thats been enchanted with Silk Touch will infact destroy the item. Personally I havent reported this to the CoFH team yet I'll probably do some more digging if it could be a inventory sync issue again but this has been the second time that has happened to me

## Steps to Reproduce (for bugs)
1. Enchant a Fluxbore with Silk Touch
2. destroy some of these blocks Flux Storage from Flux Networks, Ultimate Fluid Tank (with some fluids inside) from Mekanism

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: SP
* Optifine Installed: None
* Shaders Enabled: None

**Comment by Sunekaer** [comment]
i just tested in my world it doesnt happen, which fluxbore and what mode did you have it in?

**Comment by Algester** [comment]
single block mode

**Comment by Sunekaer** [comment]
i can not recreate your problem, can you give some more details about when it happens and whats connected what other enchants you have

**Comment by Algester** [comment]
Soulbound
Efficiency
Holding
Silk Touch
IIRC

**Comment by Algester** [comment]
for now I havent experienced the same thing

**Comment by Algester** [comment]
ok now there's something different I used the Omniwrench and remove the portable tank and the Alchemical Imbuer and they just "fly" off the world I think realistic drops might be the issue?

**Comment by Sunekaer** [comment]
Hm okay because i havent been able to recreate it with any of these enchants

**Comment by Sunekaer** [comment]
Let me know if it happens again, with what tools and enchants and on what block, and what the block is connected to
