### ISSUE TITLE
Something giving me 0fps

### ISSUE THREAD

**Issue by Tabish3304** [Sunekaer/stoneBlock#559]
Not sure if this is a bug or something of my own fault but would appreciate you helping me out.

## Bug Report
Something in the central part of my base is causing massive amount of lag, giving me 0fps.

## Steps to Reproduce (for bugs)

1. Walk into the central part of my base. world link attached.
2. World link: https://drive.google.com/open?id=1q_TXLeZDZoHWw61yU282Wg9V3tSlvOvs

## Logs
* Client/Server Log: https://pastebin.com/16wBugdj

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: Singe player
* Optifine Installed: No
* Shaders Enabled: No

Please let me know what is causing that and if i can fix it somehow.

**Comment by nzminecraftDOTcom** [comment]
A whole lot of items on the ground perhaps?

**Comment by Sunekaer** [comment]
Your log doesn’t say what’s coursing it the lag, what do you have in that room?

**Comment by Tabish3304** [comment]
A lot of stuff so not sure whats causing that. it was fine till a day ago.
And no there arent any dropped items

**Comment by joshuasuperboy** [comment]
im debugging it now for you

**Comment by joshuasuperboy** [comment]
when i opened up your world it made it start over the reason why is because i need your coords

**Comment by joshuasuperboy** [comment]
yep

**Comment by joshuasuperboy** [comment]
your enderman farm had like over 5000 items on the ground

**Comment by joshuasuperboy** [comment]
that will do it

**Comment by joshuasuperboy** [comment]
your enderman farm was not collecting the items

**Comment by joshuasuperboy** [comment]
fixed it though just had to kill all those entities

**Comment by joshuasuperboy** [comment]
when you go in your world this will take a while though but when you get in your world copy this command here /kill @e[type=!player] then paste it in your mincraft chat just open up the chat the press ctrl v after you copied that command what it will do it will kill all items on the ground and it will fix your issue then after its fixed hurry and stop your enderman farm then put void upgrades in the drawers at your enderman spawner then it should not happen again

**Comment by joshuasuperboy** [comment]
just open up your chat dont press / to do it press what every button you have set to open your chat my button is set on t to open up chat i do not know what you have yours is set on but when you open up your chat then paste the command by pressing ctrl v to paste in in your chat it will take a while to appear after you pressed that because the fps will be so low then after it appears press enter then it will fix it how every i had like 39 fps because my computer is a beast so it took a little while to find it

**Comment by joshuasuperboy** [comment]
i have like a amd 8 core cpu over clocked to 5.2ghz and the new Nvidia rtx 2080ti graphics card also over clocked so 5000 items on the ground was nothing for my computer

**Comment by joshuasuperboy** [comment]
also when you do fix it make drawers for the enderman souls and enderman trophies

**Comment by joshuasuperboy** [comment]
or do you want me to put a link down for the fixed world

**Comment by joshuasuperboy** [comment]
if you dont want to do that here is the link to download the fixed world https://drive.google.com/file/d/1q_TXLeZDZoHWw61yU282Wg9V3tSlvOvs/view?usp=sharing

**Comment by joshuasuperboy** [comment]
did it fix your problem? and also did you read that
