### ISSUE TITLE
SolarFluxReborn issue

### ISSUE THREAD

**Issue by Bass2style** [Sunekaer/stoneBlock#56]
## Bug Report
latest update breaks SolarFluxReborn questline.

## Steps to Reproduce (for bugs)
latest update from SolarFluxReborn seems breaking some things.
BQ quest for solars panels are broken : http://prntscr.com/kikukh
Draconic Evolution compatibility seems also no more available, so we lost two tiers of panels, and need to be removed from the questbook (draconic and chaotic panels) : http://prntscr.com/kikv43

## Logs

* Client/Server Log: no logs
* Crash Log: no logs

## Client Information

* Modpack Version: 1.0.12
* Server/LAN/Single Player: single player
* Optifine Installed: nope
* Shaders Enabled: no optifine, so nope.

**Comment by Sunekaer** [comment]
we are aware

**Comment by Sunekaer** [comment]
1.0.13
