### ISSUE TITLE
Occupied Roost breeders disappear after most recent update

### ISSUE THREAD

**Issue by catkin63** [Sunekaer/stoneBlock#560]
## Bug Report

After the most recent update, the roost breeders that had chickens in them all disappeared. I was in the mining dimension and when I returned to the overworld, my breeder that was unoccupied was normal. The other 9 appeared to be shadows on the wall. Logged out and back in and they were completely gone. Restored from back-up, repeated steps and they were still gone. No crash, no error messages. Am going to try an older version where I was in the overworld to see if this still happens. And it does.
## Steps to Reproduce (for bugs)

1. Saved game while in mining dimension.
2. Updated modpack and started game. Received message about 3 blocks missing.
3. Changed from mining dimension to overworld. (Not a dimension shifting problem)
4. All occupied roosts missing. Unoccupied roosts are just fine.

## Logs

* Client/Server Log: 1 of 3: <script src="https://pastebin.com/embed_js/wT6KyAkb"></script>
2 of 3: <script src="https://pastebin.com/embed_js/PuT59BHZ"></script>
3 of 3: <script src="https://pastebin.com/embed_js/7mqVaXcP"></script>
* Crash Log:

## Client Information

* Modpack Version: 1.0.27
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
https://minecraft.curseforge.com/projects/stoneblock/files/2636272
