### ISSUE TITLE
Hello There - Help with Tinker's Smeltery and Other Heat Source

### ISSUE THREAD

**Issue by Smario9000** [Sunekaer/stoneBlock#564]
## Bug Report

I can't get Blazing Pyrotheum to work
 - Do i need to report this to you are do i need to report this to the mod Dev's for Tinker's 
   Construct
## Steps to Reproduce (for bugs)

1. make and put Blazing pyrotheum in to tank
2. see if it does 1400 instead of 1300
3. use  Block Of Platinum

![help 1](https://user-images.githubusercontent.com/12405567/48232886-be1dba00-e378-11e8-9e68-1a03c5f5b73f.png)

## Logs

* Client/Server Log: None
* Crash Log: None

## Client Information

* Modpack Version:1.0.27
* Server/LAN/Single Player: Single
* Optifine Installed: n/a
* Shaders Enabled: n/a

Thank you

**Comment by Etheria137** [comment]
You have to break the controller and place it down when the tank is placed and has blazin pyrotheum in it. But still needs to be fixed by the dev.

**Comment by Smario9000** [comment]
Thanks
