### ISSUE TITLE
Quest Book Blank (LAN)

### ISSUE THREAD

**Issue by Wheezywookiee** [Sunekaer/stoneBlock#565]
## Bug Report
Quest book is blank when playing on LAN

## Steps to Reproduce (for bugs)
1. Join room-mate on LAN
2. Open up quest book
3. Click on Quests tab
4. Nothing there

## Logs
* Client/Server Log: N/A as this is not a crash and not sure how this would help as I am not the host
* Crash Log: N/A as this is not a crash and not sure how this would help as I am not the host

## Client Information
* Modpack Version: 1.0.25 (and before you ask why I'm playing an older version, I've had issues with newer versions, 1.0.26 crashed and would say, "it looks like you are using an unsupported modified version of the game", 1.0.27 we tried once, I clicked to join him on LAN and he crashed instead of me but no error message, it just exited)
* Server/LAN/Single Player: LAN
* Optifine Installed: Not sure?
* Shaders Enabled: Not sure?

**Comment by Sunekaer** [comment]
please update to the newest version as the Betterquesting mod has been updated.

**Comment by Wheezywookiee** [comment]
That's cool. Can you guarantee that the newest version won't have any problems with LAN?
