### ISSUE TITLE
Aluminum chunk recipe now makes steel.

### ISSUE THREAD

**Issue by netmc** [Sunekaer/stoneBlock#566]
## Bug Report
The aluminum chunk recipe in the thermal induction smelter now makes steel instead of mekanism aluminum.  I'm thinking that this was a copy/paste bug when working with modtweaker.

## Client Information

* Modpack Version: 1.0.27r1
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
StoneBlock-1.0.27r2.
