### ISSUE TITLE
Chaos Guardian bugged in Woot

### ISSUE THREAD

**Issue by dev0ur** [Sunekaer/stoneBlock#567]
## Bug Report
Chaos Guardian in Woot factory is not dropping anything or showing any ingredients.

## Steps to Reproduce (for bugs)

1. Capture Chaos Guardian
2. Create Tier 3 Chaos Guardian Woot Factory
3. https://i.imgur.com/plh2z3t.png

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Algester** [comment]
https://github.com/Ipsis/Woot/issues/236
because to get the Chaos Shard you need to break the block (Chaos Crystal) itself

**Comment by Sunekaer** [comment]
what algester said and linked, but i wont be changing the drop table
