### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by huet87** [Sunekaer/stoneBlock#568]
## Bug Report
Can't start server after updating to 1.0.27r

## Steps to Reproduce (for bugs)

1.Follow the steps like i did before.
2. crash immediately

## Logs

* Client/Server Log: none
* Crash Log: none

## Client Information

* Modpack Version: 1.0.27r
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2565713/latest.log)

**Comment by Sunekaer** [comment]
please paste the log in gist.github.com and link it here.

**Comment by Sunekaer** [comment]
You must use the installer. You are missing libraries.
