### ISSUE TITLE
Draconic Evolution Helmet allows Heart container consumption to pass the preset limit

### ISSUE THREAD

**Issue by braingkk** [Sunekaer/stoneBlock#569]
## Bug Report
Draconic Evolution Helmet allows Heart container consumption to pass the preset limit

## Steps to Reproduce (for bugs)
https://youtu.be/gipwYC56paE
1) Eat Cyclic Heart containers until it does not let you eat more
2) Equip Draconic evolution Helmet, and enable auto feed.
3) Place several Cyclic Heart Containers in your Inventory
4) Cause your food to drop, so the helmet feeds you
5) Enjoy unlimited hearts

## Logs
N/A

## Client Information
* Modpack Version: 1.0.27r1
* Server/LAN/Single Player: SMP
* Optifine Installed: Neg
* Shaders Enabled: Neg

opened a ticket on cyclics page, no clue if i should be opening one on Draconic Evolutions as well 
https://github.com/PrinceOfAmber/Cyclic/issues/976

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
