### ISSUE TITLE
Silicon Chickens drop the disabled AE2 silicon

### ISSUE THREAD

**Issue by mindreave** [Sunekaer/stoneBlock#57]
## Bug Report

The Silicon Chicken creates the AE2 silicon, which shows as "This Item Is Disabled"
This drop can also be observed in JEI: https://i.imgur.com/fWRq1nz.png

## Steps to Reproduce (for bugs)

1. Breed a Silicon Chicken
2. Wait for Silicon Chicken to drop Silicon
3. Pick up disabled item and cry. 

## Logs

* Client/Server Log: No relevant log entries, but here you go: 
https://gist.github.com/mindreave/1772e5f68539a4a9b4d41f94e0c60414
* Crash Log: No relevant crash

## Client Information

* Modpack Version: 1.0.9
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by RandomLibrarian** [comment]
I recommend EnderIO:itemMaterial since it seems to work better interchangeably with other mods specifically RS. Possibly refinedstorage:silicon though as an alternative.

**Comment by RandomLibrarian** [comment]
Within the exact same config.

  "morechickens:terrasteelchicken": {
    "Name": "terrasteelchicken",
    "Is Enabled": true,
    "Lay Coefficient": 2.0,
    "Lay Item": "botania:manaresource:4",
    "Drop Item": "botania:manaresource:4",
    "Spawn Type": "NONE",
    "Parent 1": "",
    "Parent 2": ""

I recommend:
"Parent 1": "chickens:enderchicken",
"Parent 2": "chickens:pcrystalchicken"



  "morechickens:redstonecrystalchicken": {
    "Name": "redstonecrystalchicken",
    "Is Enabled": true,
    "Lay Coefficient": 1.0,
    "Lay Item": "extrautils2:ingredients",
    "Drop Item": "extrautils2:ingredients",
    "Spawn Type": "NONE",
    "Parent 1": "",
    "Parent 2": ""

I recommend:
"Parent 1": "chickens:redstonechicken",
"Parent 2": "chickens:pcrystalchicken"

Both of those parent recommends were from a git issue posted in the MoreCHickens Git.
https://github.com/GenDeathrow/MoreChickens/issues/38

**Comment by Sunekaer** [comment]
1.0.13
