### ISSUE TITLE
Can't update?

### ISSUE THREAD

**Issue by Jacob-Suldaan** [Sunekaer/stoneBlock#570]
## Steps to Reproduce (for bugs)

1. simply just try to update...
2.

## Logs

* Client/Server Log: https://gyazo.com/4b3124b772f0cecc029f2b003cb1d1c8
* Crash Log: Isnt a crash.

## Client Information

* Modpack Version: trying to get 1.0.27
* Server/LAN/Single Player: singe player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
restart your pc

**Comment by Jacob-Suldaan** [comment]
I've just turned my pc on

**Comment by Jacob-Suldaan** [comment]
did as you said and as soon as twitch opened i clicked to update same thing happened

**Comment by Jacob-Suldaan** [comment]
what normally stops it is deleting and reinstalling...

**Comment by Sunekaer** [comment]
Well theres nothing i can do about this, all it says is that the files is in use, youll have to contact twitch

**Comment by Jacob-Suldaan** [comment]
it only happens with your modpack though?
