### ISSUE TITLE
stoneBlock 1.0.27 Server crashing at random

### ISSUE THREAD

**Issue by itz-deprestion** [Sunekaer/stoneBlock#572]
## Bug Report
server crashing randomly 

## Steps to Reproduce (for bugs)
1.start server
2. wait about a min or so

## Logs
* Client/Server Log:
[2018-11-09-1.log.gz](https://github.com/Sunekaer/stoneBlock/files/2566941/2018-11-09-1.log.gz)

##debug.log:
[debug.log](https://github.com/Sunekaer/stoneBlock/files/2566964/debug.log)

* Crash Log:

## Client Information

* Modpack Version: StoneBlock-1.0.27 Server and client
* Server/LAN/Single Player: server
* Optifine Installed: nope
* Shaders Enabled:  nope

**Comment by Sunekaer** [comment]
upload the latest and crash log to gist.github.com and link it here

**Comment by itz-deprestion** [comment]
https://gist.github.com/itz-deprestion/4fdcd3ec72a8f032707d4889fd093134

**Comment by nzminecraftDOTcom** [comment]
Whole bunch of items on the ground, entities wandering around, is this a multiplayer server where others other than you play?

**Comment by itz-deprestion** [comment]
just me i moved my single player world over so i can have it always loaded 
world works fine in single player but on server it crashes

**Comment by 0-x-2-2** [comment]
Yeah this happens a lot.

**Comment by nzminecraftDOTcom** [comment]
Are you running the server on the same PC as playing the game? Has it got enough memory to actually do both those tasks?

**Comment by 0-x-2-2** [comment]
My server is on another machine and memory should not be a issue at all.

**Comment by djbenbe** [comment]
my server crashes too.
I'm going to give the traffic jam with a porridge.
[crash-2018-11-10_19.15.38-server.txt](https://github.com/Sunekaer/stoneBlock/files/2568692/crash-2018-11-10_19.15.38-server.txt)

**Comment by itz-deprestion** [comment]
server is on a diffrent pc and has 10gb of ram dedicated to it 
client has 8gb dedicated to it

**Comment by djbenbe** [comment]
thank you

**Comment by itz-deprestion** [comment]
dont think its RS coz the world works fine when it loded in the client

**Comment by djbenbe** [comment]
thank you we have to disable a mod

**Comment by itz-deprestion** [comment]
@nzminecraftDOTcom them cords have nothing at them but stone

**Comment by nzminecraftDOTcom** [comment]
Those coords weren't @'d at you though? So yes, there probably will be stone there.

**Comment by 0-x-2-2** [comment]
Yeah I still issues with refined storage but I did fix the 0 tps thing.

**Comment by Sunekaer** [comment]
Did you get it fixed itz-de?

**Comment by CyanSlinky** [comment]
1.0.27 server also crashes for me 100% of the time when a client joins, tried open to lan on both computers and tried running a dedicated server, always crashes. i then tried different versions, i started with 1.0.27r2(crashes) and then went down to 1.0.27(crashes) and then finally 1.0.26 which doesn't crash when a client joins but clients have empty quest books. I have no idea if this is only happening for me but it renders the modpack unplayable in multiplayer.

**Comment by Sunekaer** [comment]
Not the same issue cyan... make an new issue for your problem

**Comment by itz-deprestion** [comment]
no still crashing

**Comment by Sunekaer** [comment]
seems to be loaded with a lot of chance cubes floating around according to log.  Your options are to profile the world to find the lag and clean it up or start a fresh world. nothing i can do
