### ISSUE TITLE
Mekanism VoiceServer kills bluetooth headset

### ISSUE THREAD

**Issue by DrJKL** [Sunekaer/stoneBlock#574]
## Bug Report
Mekanism VoiceServer kills my bluetooth headset on init.

## Steps to Reproduce (for bugs)

1. Connect bluetooth headphones (Windows 10)
2. Start listening to another application with sound
3. Start StoneBlock, wait several minutes (longer than usual) for client initialization because I forgot to tweak the memory allocation.
4. Open world, wait for mods to start up
5. Realize you can't hear the other application, or any applications anymore
6. Change the mod config to disable VoiceServer
7. Exit and Re-enter the world
8. No issues

Log; https://gist.github.com/DrJKL/bafc71cb2fa70bce21e99638fb84b037

## Client Information

* Modpack Version: Tested in 1.0.27r1, observed in several previous versions.
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
i do not have this problem, and please report it to mekanism
