### ISSUE TITLE
PSA: Don't use any builder's wand to build Mekanism's Induction Matrix with advance or up Cells or Providers

### ISSUE THREAD

**Issue by Algester** [Sunekaer/stoneBlock#577]
## Bug Report
Using any Builder's wands from the Better Builder's wand mod when placing Advance or Up Cells or Providers reset's the Block's NBT data turning it back into a Basic Cell or Provider

## Steps to Reproduce (for bugs)
1. have any advance blocks for the induction matrix
2. use the Builder's Wand to place them into the world
3. enjoy your Resource and Time sink (especially once you decided to go big and use 36 of each)

## Client Information
* Modpack Version: 1.0.26
* Server/LAN/Single Player: Single Player
* Optifine Installed: None
* Shaders Enabled: None

I will check Extra Utilities 2's Builder's wand if the same thing happens and maybe Psi's version of it maybe they handle block data better

**Comment by Sunekaer** [comment]
seems to be only better builders wand could you report it them?

**Comment by Algester** [comment]
sure no problem

**Comment by Algester** [comment]
https://github.com/portablejim/BetterBuildersWands/issues/85

I have linked the issue to them

**Comment by Sunekaer** [comment]
Thanks ill close this ticket and keep an eye out for updates on these mods
