### ISSUE TITLE
ME Crafting Terminal not Crafting Full Stacks

### ISSUE THREAD

**Issue by quanald** [Sunekaer/stoneBlock#580]
## Bug Report

So I set up an ME system from applied energistics and the crafting isn't working correctly (in the regular crafting terminal, not auto). For example, if I try to craft a stack of iron blocks by setting up the recipe for 1 block and then shift-clicking, it does not make a full stack. I end up with 21 blocks and the crafting terminal has 5 ingots left in it. Now, this happens specifically like that, with those numbers, every time with any type of block (gold, diamond, compressed cobble, etc.). It acting like there isn't enough of the material, even though there are thousands. Similar thing happens with 2*2 crafting recipes (quartz blocks, crafting tables, ore chunks) but it makes 47 and then leaves 1 in the crafting terminal. I don't think it does it with normal recipes that contains different kinds of items, but I'm not 100% sure. I really just want to be able to craft and shift-click stacks out of the ME system without having to replace the recipe every time, so thanks for the help!

## Steps to Reproduce (for bugs)

1. Set up an ME system
2. Put enough iron ingots (for example) into it to make a stack of iron blocks
3. Click an one ingot into each spot in the crafting terminal 
4. Shift-click the iron block like you're trying to craft a stack
5. Get mildly annoyed because it didn't make the whole stack :(

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.27r2
* Server/LAN/Single Player: Single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by quanald** [comment]
I just tried to replicate in a new world and everything worked fine, so i guess the issue is specifically in that world.

**Comment by Sunekaer** [comment]
Could you report this to the AE2 mod Author as they might be able to help you

**Comment by quanald** [comment]
Well I figured out what it was after some trial and error. Turns out the Ender IO power bank I was using was the issue. I noticed this after I saw the system go dark once after crafting for a split second. I switched to a power cell from AE and it works fine now. Either way, its still an issue with the integration.
