### ISSUE TITLE
Refined Storage Override does not work anymore

### ISSUE THREAD

**Issue by Almandor** [Sunekaer/stoneBlock#581]
## Bug Report
If you open refined storage autocrafting for example with a ProjectE receipe for coal the game shows it needs 3 philosophers stones and greys out the start button. Normally you can override this by pressing both shift and control. This does no longer work

## Steps to Reproduce (for bugs)

1. Set up receipe for Aerternalis fuel with all prior receipe in different crafters
2. Order a couple of fuel from crafter
3. Confirm the crafter demands more then the provided Philosophers Stones
4. Press the overrride combination

## Client Information

* Modpack Version: 1.0.27r2
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: Not manually added
* Shaders Enabled: Not manually added

**Comment by Sunekaer** [comment]
in version 1.6.6 of refined storage they change some stuff som of it being this:

> Removed handling of reusable items in autocrafting, to avoid problems
> You can no longer start a crafting task if it has missing items or fluids
