### ISSUE TITLE
Aroma Dimension Items Disappearing 

### ISSUE THREAD

**Issue by DracoClaw** [Sunekaer/stoneBlock#583]
## Steps to Reproduce (for bugs)
1. I'm in the mining dimension.
2. I opened a chance cube.
3. The result was an Inventory Bomb
4. All my items went onto the ground
5. They immediately disappeared.

## Logs
* Client/Server Log: https://pastebin.com/nexm1Rbb
* Crash Log: no crash report, because it didnt crash

## Client Information

* Modpack Version: 1.0.27
* Server/LAN/Single Player: single player
* Optifine Installed: nope
* Shaders Enabled: nope

also i was wondering if there would be a way to get my items back? the last server backup was an hour before this happened. is there a log of what the bomb throws out? or what my inventory was in that dimensions, or even when i switched dimensions?

**Comment by Sunekaer** [comment]
this might help you 
https://www.reddit.com/r/feedthebeast/comments/4c69se/recover_items_after_death/

**Comment by DracoClaw** [comment]
idk why you closed this. my issue wasn't fixed. what you linked me to talks about restoring from a grave file, but since i didnt die there isnt a grave file

**Comment by Sunekaer** [comment]
theres nothing i can do about this

**Comment by DracoClaw** [comment]
theres no way to know what items i lost? anyway to know what this bug is?

**Comment by Algester** [comment]
another way of going about this is just to cheat in the items you lost

**Comment by DracoClaw** [comment]
i mean. i did, but i probably missed some stuff. really think this bug needs to be squashed though. might have something to do with the ender flowers from enderman evolution, i was standing next to one when it happened
