### ISSUE TITLE
Translocator mod Is acting extremely weird.

### ISSUE THREAD

**Issue by imfeared** [Sunekaer/stoneBlock#584]
## Bug Report

Extremely weird but Item translocators, they stop sending some items and only 2 types of items 
will be extracted from the enderchest.

## Steps to Reproduce (for bugs)

1. Have loads of Roost chickens 
2. roost collectors to collect the items
3. translocators going out of the collectors and into a enderchest
4, huge drawer system for items
5. controller slaves with enderchest with item translocators 
6, output all items from enderchest into drawer system
7. Wait..... Its random I believe and i dont entirely know how to reproduce it.

## Logs

Logs: http://www.mediafire.com/folder/0zln905h2j2iu/Logs

## Client Information

* Modpack Version: 1.0.27r2
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by elijah-thomas774** [comment]
It has a hard time communicating with the drawer if it has good upgrades. I don’t know why but I found that in other packs too

**Comment by Etheria137** [comment]
When I have a void upgrade on a drawer and have a translocator on to a cobble generator it doesn't input until I take the void upgrade out.

**Comment by Sunekaer** [comment]
Nothing i can do about this, as the guys above stated It has a hard time communicating with the drawer, all you can do is report it to the translocator author
