### ISSUE TITLE
Caught Exception from MPUtils

### ISSUE THREAD

**Issue by Cuyoya** [Sunekaer/stoneBlock#586]
## Bug Report
ModPack crashes during mod loading due to, from what I can tell, and error with MPUtils.
Can't seem to get the client to launch at all.

## Logs

Crash Log: https://pastebin.com/ge9FgmU6

## Client Information

* Modpack Version: 1.0.27r2, same exact crash happens on v1.0.26
* Server/LAN/Single Player: Singleplayer Client
* Optifine Installed: No
* Shaders Enabled: No
* RAM Allocated: 6G
* Reinstalled: Yes, several times with different versions, all ending the same
* Believing in the Heart of the Cards: Yes

**Comment by Sunekaer** [comment]
can you launch the part of you remove MPUtils?

**Comment by OfficialStamper** [comment]
Crash log shows not enough RAM allocated.....
```    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 666812664 bytes (635 MB) / 3001548800 bytes (2862 MB) up to 3001548800 bytes (2862 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m```

**Comment by Sunekaer** [comment]
Ah ty was on mobile so didnt read the log

**Comment by Sunekaer** [comment]
allocate more ram

**Comment by Cuyoya** [comment]
I did, same thing happens. You want to see it with more RAM allocated? I allocated 8 gigs and the same thing happens.

It's not the RAM, thanks.
