### ISSUE TITLE
Fluix seed visual glitch

### ISSUE THREAD

**Issue by Etheria137** [Sunekaer/stoneBlock#587]
## Bug Report
When I put a fluix seed into the energy condenser (the first one) and set it to make more seeds it makes pure certus quartz seeds but when grown produces fluix seeds

## Steps to Reproduce (for bugs)
1. Get a fluix seed
2. place into slot in energy condenser to make more
3. put emc into energy condenser
4. Grab the "seed" 
5. Grow seed

## Logs
https://imgur.com/a/agFnzqf

## Client Information
* Modpack Version: 1.0.27r2
* Server/LAN/Single Player: Single
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
ProjectE doesnt support items with NBT Tags, ill remove EMC value from these

**Comment by Etheria137** [comment]
Cool

**Comment by Sunekaer** [comment]
StoneBlock-1.0.28
