### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by Smario9000** [Sunekaer/stoneBlock#588]
## Bug Report

Sorry again for bugging you but i have another problem

![help_1](https://user-images.githubusercontent.com/12405567/48322182-e3662e80-e5eb-11e8-86e0-a09355076251.png)

![help_2](https://user-images.githubusercontent.com/12405567/48322201-f973ef00-e5eb-11e8-96ea-7c50448103cb.png)

so does this not work inside a compact M. Block inside a compact M. Block form the outside of a compact block or am I doing something wrong
## Steps to Reproduce (for bugs)

1. take a compact M. block and place it
2. then take a draw and hook it up to the compact draw with a conduit
3. go inside it and place another Comapact M. Block
4. hook it both together
5. go inside that compact M. Block
6. try to get the item to go into reactor
7. tell me if you figure out how to get this to work 

it will work with the steam from reactor to Turbine inside a CMB inside a CMB

![help_5](https://user-images.githubusercontent.com/12405567/48322854-368db080-e5ef-11e8-9e5f-a02a46f41069.png)

![help_3](https://user-images.githubusercontent.com/12405567/48322636-39d46c80-e5ee-11e8-8219-5b2a1e8d5399.png)

![help_4](https://user-images.githubusercontent.com/12405567/48322639-3d67f380-e5ee-11e8-8884-0e54267855ee.png)

so why cant i pull items for RS to Draw to CMB to CMB to Reactor

## Logs

* Client/Server Log: n/a
* Crash Log: N/a

## Client Information

* Modpack Version: 1.0.27R2
* Server/LAN/Single Player: Single
* Optifine Installed: N/a
* Shaders Enabled: N/a

Thank you

**Comment by Smario9000** [comment]
Just Connect from Refined Storage to CM Block using RS Conduit
go into first CM block then wire up form input Conduit to CM Block using RS Conduits
then go into Second CM Block then wire form input Conduit to Reactor input Port with RS conduits
then add Filters to all Export side
this means like this
RS System Conduit and one Filter to Export with item
in first CM Block where ever you are importing it form add a Filter to the export with item
then in second CM block add a filter to where ever you are importing it form with item and to the Conduit your Reactor with item
then do it backwards for the other item to get the blue one out of the Reactor

This is one way to do it
but not the way i wanted to do it

**Comment by Sunekaer** [comment]
is all of this loaded?

**Comment by Smario9000** [comment]
I am doing a on chuck challenge so yes
And by default CM block are chuck loaded

Plus if it wasn't then none of my setup would work not just this one time

**Comment by Sunekaer** [comment]
i havent used these mods much and specially not combined, so i dont really know what to tell you to do. 
Have you check that it isnt the conduit doing it? right now im just guessing

**Comment by Smario9000** [comment]
I am not sure what is causing it not to work but like I reply the Rs Condiuts work so I am just going to used it but it doesn't work with item condiuts and I tried all different ways but I don't know

**Comment by nzminecraftDOTcom** [comment]
Using Enderchests as a transport method between dimensions is also a very good way of doing things if you haven't tried already (Can't remember if they're in the pack)

**Comment by Smario9000** [comment]
Yes they are and it's okay I've already figured out around about anyway so it's cool

I was just bringing it to your attention that item condiments might not work

**Comment by Sunekaer** [comment]
Could you report it to ender io as you know a lot more about all the details in this issue
