### ISSUE TITLE
StoneBlock World resetting using another MC account

### ISSUE THREAD

**Issue by Areallyfatsum** [Sunekaer/stoneBlock#590]
## Bug Report
When I log into another account from the MInecraft launcher and open a stoneblock map it resets the whole world, starting from the beginning but with the same xp as before resetting. 

## Steps to Reproduce (for bugs)
1. Sign into an account and produce stoneblock world - works without bugs in other world types besides voidworld -
2. Play on the map or take noticeable action - break a block per se. 
3. Save the world, and quit the game
4. Load launcher and sign into another account. 
5. Open the map and it will be completely reset - but only xp will remain the same.

## Client Information

* Modpack Version: 1.0.27r2 and 1.0.26
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by P4t0r1kku** [comment]
Are you at the same Coordinates as on the previous Account?

**Comment by Areallyfatsum** [comment]
It was not! But I have still lost my entire inventory on hand. Any help with that one?

**Comment by Sunekaer** [comment]
inventory is bassed on account, so if you log back in with your old account youll have your inv, same with the island

**Comment by Areallyfatsum** [comment]
I have tried that - my fault for not disclosing that. Still doesn't give me the same inventory.

**Comment by Areallyfatsum** [comment]
Moreover, I have tried opening the level.dat file and I haven't been able to find where my player inventory is? I know inventory is kept in Data/Player/Inventory so I checked it and its got the inventory of my second account only.

**Comment by Sncnwsky** [comment]
@Sunekaer Is There Any Guide About How To Set Them On The New Account?
