### ISSUE TITLE
MPUtils Causes Loading Crash- NOT THE RAM

### ISSUE THREAD

**Issue by Cuyoya** [Sunekaer/stoneBlock#592]
## Bug Report
Cool cool. So I opened an issue last night with #586 and got it closed before I could reply this morning, with the answer being "allocate more RAM" 💢 
Surprise, surprise, it isn't an issue with RAM!
It's almost like I stated in the Client Information I allocated 6 gigs... Weird!
Sorry I posted only the third-to-most-recent log of the same exact crash, I suppose.

ModPack crashes during mod loading due to, from what I can tell, and error with MPUtils. Can't seem to get the client to launch at all UNLESS I disable MPUtils entirely.

## Logs

Crash Log WITH UPDATED RAM NUMBERS: https://pastebin.com/q16ue1w7

## Client Information

* Modpack Version: 1.0.27r2, same exact crash happens on v1.0.26
* Server/LAN/Single Player: Singleplayer Client
* Optifine Installed: No
* Shaders Enabled: No
* RAM Allocated: 6 ENTIRE GIGABYTES
* Reinstalled: Yes, several times with different versions, all ending the same
* Annoyed: Slightly yes, sorry

**Comment by Sunekaer** [comment]
and if you remove MPUtils does it then load fine?

**Comment by Cuyoya** [comment]
Yes, as I stated in the Report, it does.

**Comment by Sunekaer** [comment]
log of crash with MPUtils removed

**Comment by Cuyoya** [comment]
...but there's no crash when MpUtils is removed?

**Comment by Sunekaer** [comment]
ill remove MPUtils next update as it isnt being used atm

**Comment by Sunekaer** [comment]
StoneBlock-1.0.28
