### ISSUE TITLE
Game crash upon autocrafting.

### ISSUE THREAD

**Issue by Dournbrood** [Sunekaer/stoneBlock#593]
When attempting to autocraft the Cyclic garden scythe using AE2, the game will crash. OreDict is disabled in all patterns necessary to craft it. Putting a crafting card on an export bus with the scythe as the export caused a world corruption for obvious reasons. Upon the crash, the game simply closes producing seemingly no error log.

**Comment by Sunekaer** [comment]
Template not used and no logs
