### ISSUE TITLE
World not generating correctly

### ISSUE THREAD

**Issue by DrWheelbarrow** [Sunekaer/stoneBlock#595]
When hosting a server, the world keeps generating as a default vanilla minecraft world. I did follow the instructions. The level type was "voidworld" by default. I tried creating a world in single player and placing it in the server folder with a name equivalent to the world name set in server.properties which resulted in creating a completely empty world. I also tried reinstalling the server and restarting it as suggested in other posts. 
No matter what ive tried i still cant get the stoneblock cave to generate. What am I doing wrong?

**Comment by Algester** [comment]
another way is let the server generate a world but replace all those files with the ones generated with stoneblock no more renaming required

**Comment by DrWheelbarrow** [comment]
Logically this results in exactly the same outcome as replacing the world folder and renaming it in server.properties. Nevertheless I tried it, and ofcourse i was placed in a completely empty world and forced to fall indefinitely. I thought this might be due to chunks not being loaded so i gave it some time, but nothing changed. 

PS: It cannot be an issue of not enough RAM/CPU. I am on a powerful system and have allocated more than enough.

**Comment by Sunekaer** [comment]
Stop the server, check the `server.properties ` has `level-type` set to `level-type=voidworld`, delete the world, and boot the server
