### ISSUE TITLE
Two problems with Void (not "Void?") world preset.

### ISSUE THREAD

**Issue by booblebobble** [Sunekaer/stoneBlock#596]
Trying the pack in skyblock form (with infinite creative stone and lava sources) because the whole 'living underground forever' thing makes me claustrophobic. :p

## Bug Report
Problem 1) No mobs spawn in the overworld ever.  Doesn't matter the location or time of day or whether it's on regular stone vs. cursed earth or in a box or open to air...no monsters ever spawn.  Animal bait and wither spawning works.  Other dimensions seems to spawn mobs as normal.

Problem 2) No matter where or in what dimension I logged off or what my spawnpoint is, whenever I open a world it puts me back on the original glass block at 0,17,0.  If I try to obstruct the block so it spawns me higher, it just dumps me into the void.  Dying sends me back to my bed as expected.

I'm not sure if these are actually bugs or if there are config options I need to change or what.

## Steps to Reproduce (for bugs)
1) Make a new world with the Void world preset, make a spawn platform out of cursed earth (or anything else) and set it to night, and watch as nothing happens.

2) Make a new world with Void preset, go anywhere other than the original glass block, then close world and reopen it.

## Client Information
* Modpack Version: 1.0.27r2
* Server/LAN/Single Player: Single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
I dont really support this... but which void world preset are you using? there is like 3
