### ISSUE TITLE
Veinmining Mekanism's Industrial Turbine Motors will produce an NPE (Null Pointer Exception)

### ISSUE THREAD

**Issue by Algester** [Sunekaer/stoneBlock#597]
## Bug Report
it will crash the world but nothing game breaking?

## Steps to Reproduce (for bugs)
1. place rotor blocks complete with blades on them
2. veinmine

## Logs
* Crash Log: https://pastebin.com/Ns3xwBiz

## Client Information
* Modpack Version: 1.0.26
* Server/LAN/Single Player: Single Player
* Optifine Installed: None
* Shaders Enabled: None

**Comment by Sunekaer** [comment]
Please report to mekanism
