### ISSUE TITLE
Tiny Progressions : Infinity Water Bucket [Uncraftable]

### ISSUE THREAD

**Issue by Kithio** [Sunekaer/stoneBlock#598]
Was craftable in previous versions of the pack as you were able to get Tiny  Progressions Steel using the (Stone Hammer + 2 Iron + 6 Coal) Recipe, Now that recipe has been changed to give Thermal Steel instead making the Infinity Water Bucket impossible to get as it will only accept Tiny Progressions Steel Ingots.

(Tested Versions, 1.0.27r2, 1.0.28)

**Comment by Algester** [comment]
I wonder if thermal expansion’s oredict works

**Comment by Sunekaer** [comment]
StoneBlock-1.0.29
