### ISSUE TITLE
Issue Making Pink Slime ingots

### ISSUE THREAD

**Issue by FixerEternal** [Sunekaer/stoneBlock#599]
Iron ingots sit in the Fluid Sieving Machine when filled with pink slime and powered. Can we get a workaround recipe until this gets addressed?

**Comment by Algester** [comment]
Pink slime can only be made in a tinker’s smelter....

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/48567526-81fcd300-e8fd-11e8-9a2f-da4cdb6c885e.png)

Works fine for me

**Comment by Sunekaer** [comment]
Make sure you have your redstone settings correct and that the block isnt paused

**Comment by ghatus0** [comment]
I ran into this issue last night and figured I would comment for posterity.

This is caused by [https://github.com/Buuz135/Industrial-Foregoing/issues/454](url) and updating to IF 1.11.10-223 fixed it.

**Comment by piwod** [comment]
How do I make reinforced pink slime?
