### ISSUE TITLE
Quests in the wrong order? 

### ISSUE THREAD

**Issue by gaminggirl** [Sunekaer/stoneBlock#6]
StoneBlock Version 1.0.1

In the Refined Storage Quest tree the Disk Drive is before the Controller. But since the Disk Drive takes an Advanced Processor you have to make a Controller that feeds the Solderer with energy before you make the disk drive. Might be good to swap the Controller and Disk Drive quests.

**Comment by Sunekaer** [comment]
https://minecraft.curseforge.com/projects/stoneblock/files/2580687
