### ISSUE TITLE
Extra Util Bug....I cannot launch the pack

### ISSUE THREAD

**Issue by HairyDragonBeck** [Sunekaer/stoneBlock#60]
## Bug Report

I launch the game and it crashes
## Steps to Reproduce (for bugs)

1. Just launch it and it crashes itself
2. On Stage 4 once it get's to Extra Utilities it just crashes

## Logs

* Client/Server Log: https://pastebin.com/12QuBz2R
* Crash Log: https://pastebin.com/LFXAX5M8

## Client Information

* Modpack Version: 1.0.12
* Server/LAN/Single Player: LAN (Sort of, just launching it, but I play on LAN)
* Optifine Installed: False
* Shaders Enabled: False
* Added Mods: [Custom Lan Ports](https://minecraft.curseforge.com/projects/custom-ports)

**Comment by Sunekaer** [comment]
Mod bug not pack bug
temp fix:
In your twitch client go to settings>minecraft> launch method change from native to jar

**Comment by HairyDragonBeck** [comment]
The temp fix worked.

**Comment by Sunekaer** [comment]
1.0.13
