### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by lavaglijder** [Sunekaer/stoneBlock#600]
## Bug Report
When starting the server it just crashed.

## Steps to Reproduce (for bugs)
1. Startup server

## Logs
* Client/Server Log: 
Server: https://pastebin.com/VMV8UkEc
Client: n/a due no client involved
* Crash Log:
https://pastebin.com/iZ1eXbbW

## Client Information

* Modpack Version: 1.0.28
* Server/LAN/Single Player: Server
* Optifine Installed: n/a
* Shaders Enabled: n/a

**Comment by Sunekaer** [comment]
assigned at least 4gb of ram
