### ISSUE TITLE
Can Not Upgrade to tier 8 Draconic Energy ball

### ISSUE THREAD

**Issue by bogointeractive** [Sunekaer/stoneBlock#602]
## Bug Report

In trying to do a t5 to t8 Draconic Energy Ball it keeps saying that I need advanced stabilizers. I have tried with the 9 in a bunch which become the circle ones and it says error. I have tried many many times to get this and I am stuck at t4 which fills fast. I will try to get screen captures to help.

## Steps to Reproduce (for bugs)

1. placed the energy core 10 blocks high. 
2. then went 10 blocks off each of the 4 sides to place the stabilizers. 
3. I clicked in the GUI provided t8 template. I then built the core as stated. Then went to activate in the GUI
4. GUI said advanced stabilizers required.
5. Placed extra stabilizers to create the circles and only core said it was valid. The stabilizers were not
https://i.postimg.cc/14hJsGfV/Untitled.png

## Logs

* Client/Server Log: Not using Twitch Launcher. Using MMC
* Crash Log:

## Client Information

* Modpack Version: StoneBlock-1.0.27r2
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
It literally says on the image with red text that you have a wrong block at that x z y
