### ISSUE TITLE
Server Thread/Warning

### ISSUE THREAD

**Issue by bogointeractive** [Sunekaer/stoneBlock#603]
## Bug Report

Currently having issues with my mob farm. The Attractior Obelisk is acting like it does not know what to do even with full mob souls.
## Steps to Reproduce (for bugs)

1. https://pastebin.com/wdYxaCjf
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.27r2
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Please report to enderio
