### ISSUE TITLE
Unsupported

### ISSUE THREAD

**Issue by BlakeKM** [Sunekaer/stoneBlock#604]
The game crashes right when I launch it. It says, "It looks like you are using an unsupported modified version of the game" sorry if it is simple to solve, I had this problem for a while. Can you just take a look and just tell me what I can, thanks.- Blake

https://pastebin.com/UZ5J4Du7

* Modpack Version:1.0.28
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
First you need to assign between 4 and 6 of ram then try and see what it says

**Comment by BlakeKM** [comment]
It still does the same thing. Maybe I did it wrong, do you know how I can change the amount of ram?

**Comment by BlakeKM** [comment]
Oh, this is for all modpacks from twitch.

**Comment by BlakeKM** [comment]
https://pastebin.com/dBq6KmBr new  crash report

**Comment by BlakeKM** [comment]
Ok, I figured how to add ram but it still not working. Still 58 errors. Updated Crash Log ->https://pastebin.com/sPyr24Gm

**Comment by BlakeKM** [comment]
Strange, it's for all TWITCH modpacks. I tried to load a copy of it on Technic Launcher and it worked. Maybe twitch is taking an older version of java.

**Comment by Sunekaer** [comment]
First dont download those from Technic they are not mine... and will be removed
Seconded you can change what java you used in the setting under Minecraft in the twitch launcer

**Comment by BlakeKM** [comment]
Ok, I'll check it out.

**Comment by Sunekaer** [comment]
If that doesnt help you need to contact Twitch, as its an issue with the launcher
