### ISSUE TITLE
Stoneblock: Cant create or open world.

### ISSUE THREAD

**Issue by TomChelsea08** [Sunekaer/stoneBlock#606]
Bug Report

So i cant open or create a world, when i do the game just freezes at 0 fps. i dedicated 8gb of ram and idk what to do. i have also removed foamfix and hats mods.

Steps to Reproduce (for bugs)
1. Launch game
2. Open/Create world
Logs
Client/Server Log:
[2018-11-15-7.log.gz](https://github.com/Sunekaer/stoneBlock/files/2585593/2018-11-15-7.log.gz)

Crash Log: No crash log
Client Information
Modpack Version: 1.0.28
Server/LAN/Single Player: Singleplayer
Optifine Installed: no
Shaders Enabled: no

**Comment by Sunekaer** [comment]
upload log to gist.github.com and link it
