### ISSUE TITLE
Server 1.0.28 crashing on launch after update

### ISSUE THREAD

**Issue by Kegulf** [Sunekaer/stoneBlock#607]
## Bug Report

I updated my StoneBlock server to v1.0.28 and now it crashes when I start the launchServer.bat.
I have followed steps in the instructions.txt.

## Steps to Reproduce (for bugs)

1. Upgrade server from 1.0.16
2. Execute steps in instructions.txt
3. Run launchserver.bat

## Logs

* Latest.log:  https://pastebin.com/27qT6F4D
* Debug.log: https://pastebin.com/pZHyaGzA

## Client Information

* Modpack Version: 1.0.28
* Server/LAN/Single Player: Server issue
* Optifine Installed: No idea
* Shaders Enabled: No idea

**Comment by Sunekaer** [comment]
Java isnt the issue, please upload the full log to gist.github.com and link it
