### ISSUE TITLE
Coal and Oil Shale genned in Overworld (1.0.28)

### ISSUE THREAD

**Issue by grannymc** [Sunekaer/stoneBlock#608]
Found around level 67. [Image](https://drive.google.com/file/d/1f2zmZMUbrnKG6YRi-3aHEqDnaAPUwHIw/view).

**Comment by Sunekaer** [comment]
Dont know how that has spawned for you as i blacklisted overworld and it only spawned for you, but ill try and change some stuff to block it more

**Comment by mskoczen** [comment]
I had some spawn in my world also. I don't remember what version my world started in.

**Comment by Sunekaer** [comment]
StoneBlock-1.0.29
