### ISSUE TITLE
Crash to desktop checking Uses of Glowstone block in JEI

### ISSUE THREAD

**Issue by ATexanPlaysGames** [Sunekaer/stoneBlock#61]
## Bug Report

As above, when checking U (Uses) in JEI of Glowstone Block, client will Crash to desktop.
Independently tested and reproducible by at least two different people.

## Steps to Reproduce (for bugs)

1. Open inventory
2. Search for glowstone block in search bar
3. Mouseover glowstone block and press U to see item uses
4. Crash to desktop.

## Logs

* Client/Server Log:
* Crash Log:
https://pastebin.com/2zu6zYfi

## Client Information

* Modpack Version: Stoneblock 1.0.12
* Server/LAN/Single Player: Official Server2
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/4755
https://github.com/SleepyTrousers/EnderIO/issues/4744
