### ISSUE TITLE
Items disappearing from a 20x20 Colossal 

### ISSUE THREAD

**Issue by Furious1964** [Sunekaer/stoneBlock#616]
## Bug Report
I put items into the chest via an Ender pouch/chest and the items show up but when I finished adding more, I lost 70% of everything I had.

## Steps to Reproduce (for bugs)

1. Added items.
2. Added more items and look into the AE2 System.
3. Logged of and then on again and I lost stuff again.

## Logs

* Client/Server Log: 
* Crash Log:

## Client Information

* Modpack Version: 1.0.27r2
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes, HD U E2
* Shaders Enabled: No
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2591291/latest.log)

**Comment by Sunekaer** [comment]
Please report it to AE2, so they can have an look at it, theres nothing can do about it

**Comment by Furious1964** [comment]
I would suggest removing Colossal Chests and installing Ender Rift instead. You can modify the recipe to make the items to make it a Mid to Ed Game device. It retains its inventory and is a lot better than having gigantic chests in your base. Just warn those on the server that CC will be removed so as not to lose items.
