### ISSUE TITLE
Ender IO Redstone Conduits do not work properly

### ISSUE THREAD

**Issue by Rainee4563** [Sunekaer/stoneBlock#619]
## Bug Report

When sending a Redstone Signal through the conduit from either a ComputerCraft Computer to a Garden Cloche it doesn't seem to register the fact that there is a signal at all
## Steps to Reproduce (for bugs)

1. Place a Garden Cloche down and pipe in water to the back and RF at the top
2. Place Dirt and a Mystical Agriculture seed inside e.g. Gold Seed
3. Place a Redstone Conduit to the left of the Cloche have a Computer output a Redstone signal into that conduit (I will be able to provide a video if needed)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.28
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Please report to Immersive Engineering or EnderIO, dont know which one of them that need to fix this
