### ISSUE TITLE
Broken Transmutation Table Crafting

### ISSUE THREAD

**Issue by FUCKINGALREADYTAKENNAMES** [Sunekaer/stoneBlock#62]
## Bug Report

Transmutation table wont craft

## Steps to Reproduce (for bugs)

1. https://youtu.be/LJiIr0wGNe8

## Logs

* Client/Server Log: no relevant logs
* Crash Log: no relevant logs
 
## Client Information

* Modpack Version: 1.0.12
* Server/LAN/Single Player: official server 1
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
Ill have a look at that

**Comment by FUCKINGALREADYTAKENNAMES** [comment]
it seem physically crafting the all four klein star spheres instead of making on a using EMC to "Dupe" more fixed the crafting recipe

**Comment by Sunekaer** [comment]
1.0.13
