### ISSUE TITLE
AE2 and Tinker's Compatibilities with the molecular assembler crafting

### ISSUE THREAD

**Issue by Algester** [Sunekaer/stoneBlock#621]
## Bug Report
this is a freak bug and it seems both the Tinker's Teams and AE2 team know about it but crafting a molecular assembler using the default recipe may provide some hickups (IE the main culprit is the vanilla crafting table) I'll check if using the stone crafting doesnt provide the same issues

## Steps to Reproduce (for bugs)
1. attempt to craft a molecular assembler through AE2
2. you can't proceed when clicking start
if step 1 fails craft a vanilla crafting table through AE2

## Client Information
* Modpack Version: 1.0.28
* Server/LAN/Single Player: SP
* Optifine Installed: None
* Shaders Enabled: None

Mirror to the same issue
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3575

**Comment by Sunekaer** [comment]
Looks to be this:
https://github.com/SlimeKnights/TinkersConstruct/issues/3546
Closing the issue as i cant do anything about and the devs knows about it
