### ISSUE TITLE
RS AutoCrafting Processors

### ISSUE THREAD

**Issue by PsyberMind** [Sunekaer/stoneBlock#622]
I'm running into an issue with Refined Storage and Autocrafting it's own Raw Processors. Specifically, the Silicon requirements will not accept anything other than AE2 Silicon

Steps to Reproduce:

1. Create a Recipe in the Pattern Terminal for say, a Raw Advanced Processor - (1x Silicon, 1x Diamond, 1x Binder, 1x Redstone

2. Encode Pattern, place into crafter

3. Request Raw Advanced Processor from Crafting Grid

4. Crafting Requirements Show Missing AE2 Silicon

5. Tear Hair out.

Currently I am using the RS Silicon Method (Smelt Quartz) to produce Silicon. 

I have tried a couple of workarounds to no avail:

Oredicted the Recipe
Synced the JEI Recipe at the exact time the RS Silicon shows in the grid
Hand-Replaced the Silicon with the RS Silicon from my inventory in the pattern

Nothing seems to work.

As a Stop-Gap measure, I am going to run all my silicon into a drawer with a conversion upgrade, but that's a band-aid solution. 

Here's what I mean in Pictures..

Edit - When taking the screenshots I noticed that the pattern for the Raw Processor was in the Crafter attatched to the furnace, so I moved it to a standalone crafter, same result. 

![2018-11-16_13 11 35](https://user-images.githubusercontent.com/425975/48665682-a0d3a480-ea78-11e8-94f1-ef46e7fad606.png)

![2018-11-16_13 09 52](https://user-images.githubusercontent.com/425975/48665684-a630ef00-ea78-11e8-8fdb-5c1058b97e52.png)

![2018-11-17_14 55 44](https://user-images.githubusercontent.com/425975/48665705-ed1ee480-ea78-11e8-9369-b02bbb562879.png)

![2018-11-17_14 55 55](https://user-images.githubusercontent.com/425975/48665706-f14b0200-ea78-11e8-8ed5-760fa0604ae7.png)

**Comment by Algester** [comment]
can RS have anything with a fuzzy oredict like how AE2 does with the patterns?

**Comment by PsyberMind** [comment]
Sadly No - There is an Option to OreDict, but I tried that and it doesn't work - No Fuzzy Logic available that I can see

**Comment by raoulvdberge** [comment]
Fixed

**Comment by Sunekaer** [comment]
@raoulvdberge 
Do you have an ETA for when the next RS update will be out?

**Comment by raoulvdberge** [comment]
Sometime next week hopefully.

**Comment by Sunekaer** [comment]
Thanks

**Comment by Sunekaer** [comment]
StoneBlock-1.0.29
