### ISSUE TITLE
Cover creating not working on Stone Table (1.0.28 from Twitch)

### ISSUE THREAD

**Issue by sandokanski** [Sunekaer/stoneBlock#623]
## Bug Report
Some cover recipes are not working properly

## Steps to Reproduce (for bugs)
1. Have Stone, Cutting Tool (Refined Storage), Iron Saw (Forge Microblocks), Structuralduct (Thermal Dynamics) and Stone Crafting Table (StoneBlockUtilities)
2. Iron Saw not working with Stone. No combination will produce any output nor there is a recipe. (maybe intentional)

3. Use JEI. Write "stone cover" in search field. Select Cover/Stone (Refined Storage). It is 2nd in my JEI.
4. There should be recipe displayed that uses the Cutting Tool. Use that recipe on the Stone Crafting Table.
5. No output is available regardless the recipe is in JEI.

6. Use JEI. Write "stone cover @th" in search field. Select Stone Cover (Thermal Dynamics). Should be only 1 choice.
7. There is recipe for it. Use it on the Stone Crafting Table manually.
8. You can create Invalid Cover (Thermal Dynamics).

It seems these are problems with the Stone Crafting Table. 

## Logs
* Client/Server Log: https://gist.github.com/sandokanski/aa91a8d4b46788dfeb5c3e3c9c9e0fc5
* Crash Log: none, game does not crash.

## Client Information

* Modpack Version: 1.0.28
* Server/LAN/Single Player: single player
* Optifine Installed: no changes. Downloaded and played using Twitch.
* Shaders Enabled: no changes. Downloaded and played using Twitch.
* Twitch Minecraft settings: Only changed maximum memory to 7,168 MB.

**Comment by Sunekaer** [comment]
2. ![image](https://user-images.githubusercontent.com/18720460/48675884-511bd880-eb5f-11e8-91f9-accc45f082da.png)
3 - 5.  I dont see any recipe for an stone crafting table cover?
8. cant recreate this problem if i try to combine an Structuralduct and Stone crafting table i dont get any result at all

**Comment by sandokanski** [comment]
2.
![problem1](https://user-images.githubusercontent.com/45141897/48678547-6dcf0500-eb8d-11e8-8693-d596dc0e1611.png)
![prblem2](https://user-images.githubusercontent.com/45141897/48678550-78899a00-eb8d-11e8-8b06-bbadf4bb0385.png)

It does not work on Stone Crafting Table, It works on other tables.
3-5. 
![image](https://user-images.githubusercontent.com/45141897/48678584-ee8e0100-eb8d-11e8-8132-43dec449a4c5.png)
![image](https://user-images.githubusercontent.com/45141897/48678611-272dda80-eb8e-11e8-88b3-5dd3589a3bc8.png)
This is the recipe you should use. (Again, on Stone Crafting Table. Perhaps it works on others.)
6-8.
![image](https://user-images.githubusercontent.com/45141897/48678639-77a53800-eb8e-11e8-93a4-b772c31ae8b9.png)
This is the bad recipe.
