### ISSUE TITLE
Balance suggestion: Quantum Battery

### ISSUE THREAD

**Issue by PsyberMind** [Sunekaer/stoneBlock#624]
I'm wondering if this is intended, or a recipe that was overlooked, but the Quantum Battery from Quantum Storage is a little OP.. It only costs a little iron and redstone, and it holds 2 BILLION RF. I'm just getting into Draconic, and crafted the Wyvern Bow, and was looking for a decent battery to keep it charged. I was going to go with the Wyvern Flux Capacitor, however a viewer on my stream mentioned this one, and I just don't think that kind of portable power storage should be so cheap to craft.

I mean, in a server environment, someone could easily load 3-4 of these things into a couple of chargers, go to bed and have portable power forever, because they don't use their power while not online..

![2018-11-18_09 50 37](https://user-images.githubusercontent.com/425975/48674922-7f75c580-eb17-11e8-966f-b1177b95fe59.png)

**Comment by Sunekaer** [comment]
I have deliberately not changed the recipe
