### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by duts0n** [Sunekaer/stoneBlock#625]
## Bug Report

the server will randomly crash 
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:https://pastebin.com/QdsAM4uZ

## Client Information

* Modpack Version:1.0.27.r2
* Server/LAN/Single Player:server
* Optifine Installed:no
* Shaders Enabled:no

**Comment by Sunekaer** [comment]
TimeWatch is lagging out your server
