### ISSUE TITLE
Unable to connect to one specific stoneblock server

### ISSUE THREAD

**Issue by 34Besim** [Sunekaer/stoneBlock#626]
## Bug Report
<When I attempt to login to the Stoneblock server I am a moderator of, I have been receiving the same error message for about a week and a half. (see screenshot)
![minecraft 1 12 2 2018-11-18 13_13_23](https://user-images.githubusercontent.com/45149852/48676567-7811e480-eb36-11e8-8f66-60d6a9778906.png)
I've tried logging into other stoneblock servers, no problem there. I've tried logging into other servers on different modpacks, no issues there. Every other game I run on my PC, no issues there. I've tried maximizing performance through my settings to no avail. I've tried maxing my RAM dedication to stoneblock to no avail. I've reinstalled the twitch launcher 4 or 5 times at this point, reinstalled stoneblock at least that many times, upgraded then downgraded my stoneblock version, downgraded the upgraded, all to no avail.>

## Steps to Reproduce (for bugs)

1.
2.
<I'll post a screenshot of my PC specs, not sure if that's gonna help at all in this case but anything I can throw at yall the better I'm assuming.
![system 2018-11-18 13_41_01](https://user-images.githubusercontent.com/45149852/48676649-9b895f00-eb37-11e8-8ed5-363c83fac863.png)
>

## Logs

* Client/Server Log: Latest Stoneblock Logs <script src="https://gist.github.com/34Besim/0f78abd9e75a7915d45068019ccf18db.js"></script>
* Crash Log:

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: Server
* Optifine Installed: No (attempted with optifine installed to no avail)
* Shaders Enabled: No

**Comment by 34Besim** [comment]
My apologies on the link to the logs, first time doing this and wasn't sure how to get the direct link on here. Copy and pasting the link works, but if anyone could let me know an easy way of getting a clickable link on here I'd appreciate it! (used gist)

**Comment by Sunekaer** [comment]
you linking a javascript not a log file

**Comment by 34Besim** [comment]
> you linking a javascript not a log file

My apologies, followed the steps the guide said to finding the logs, where would I find them? What I did was open my folder, opened logs and pasted latest

**Comment by 0-x-2-2** [comment]
This is a vanilla issue with giant nbt data in the inventory you prob picked up tons of disk drives or something.

**Comment by nzminecraftDOTcom** [comment]
I second @0-x-2-2's comment. You may need your inventory reset, or the items taken out that have the large NBT tag. Most likely a portable inventory of sorts, like one of those enderbags full of items or a shulker box.

**Comment by Sunekaer** [comment]
I see the issue has been answered, ill close the issue please report if problem persists
