### ISSUE TITLE
1.0.28 error (IO Exception)

### ISSUE THREAD

**Issue by MonfGeiger** [Sunekaer/stoneBlock#628]
## Bug Report (Maybe?)
Last wednsday, im playing stoneblock 1.0.28 on twitch just fine, and for no reason at all, I get timed out of my world, sent to hub, then booted from the server entirely because of the following

Internal Exception: java.io.Exception: An existing connection was forcibly closed by the remote host

any attempt at joining the stoneblock server below, or even the server hub itself (play.mc-complex.com) will always result in getting booted because of that java error; I made doubly sure all minecraft related ports were forwarded, firewall exceptions for everything minecraft and java were made/adjusted in mcafee, uninstalled my java 8u192 and reinstalled it, updated my Windows 10 1803 with the most current Cumulative Update hoping it would fix it, even turned off the built-in windows firewall to allow everything and anything to connect/receive. No dice on anything

And I tried this on a spare gaming laptop I had after doing a fresh install of windows 10 on it, updates installed, java installed, twitch launcher installed and the stoneblock modpack installed, once again, nothing

I can say before this happened, I was trying to power a basic induction smelter and an ender IO simple alloy smelter with a heated redstone generator. I put it down, put the 2 smelters on the front and right sides of it, put two buckets of lava in it, and tried putting redstone in it like the older thermal expansion ones did, but it didn't work; shortly after, before i logged out it booted me ouyt because java error

## Steps to Reproduce (for bugs)
As much as I want to detail how to re-create this bug, I don't exactly know HOW to do so; this hit me out of nowhere and its left me at a loss; I did switch over to MultiMC due to recommendations from the discord channel, but this bug happens even there

## Logs
I tried copy/pasting the logs to paste.feed-the.beast.com, but the website froze when I tried uploading, then went to black then white in the browser, then my browser crashed all together, here's a zippylink, please don't close my issue because of it

https://www47.zippyshare.com/v/qmb0OYBZ/file.html

## Client Information
* Modpack Version: 1.0.28
* Server/LAN/Single Player: sb.mc-complex.com
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
I do not download files, please use the feed the beast pastebin
Does it work in single player

**Comment by MonfGeiger** [comment]
All modpacks I try (stoneblock, sky factory 3, etc....) work on single player, its the multiplayer aspect of it that cant't seem to connect to any server, no matter which internet or OS I use (I tried my neighbor's internet after asking, still happens); I can't even do vanilla multiplayer, and that has no mods (yes, done on the java minecraft launcher from mojang/microsoft)

ill try uploading the logs to the feed the beast pastebin again; just to be sure, its trhe 2 text files in the stoneblock's logs folder, correct?

**Comment by Sunekaer** [comment]
I have to direct you to mojang/forge/twitch support theres nothing i can do about this and i dont know whats causing
