### ISSUE TITLE
Apple Tree cant harvest

### ISSUE THREAD

**Issue by xGarren** [Sunekaer/stoneBlock#630]
## Bug Report
When I right click the apple on the apple tree nothing happens. When I go to the keybinds and hit set to default nothing changes. I can't even view the keybinds because all the text is cut off on the left side as it pushed off screen to the left.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by Sunekaer** [comment]
You just need to right click on them and they will pop off if they are 100% grown.
What text? try changing the GUI Scale in settings
