### ISSUE TITLE
Chrome/Windows/Firefox download issues

### ISSUE THREAD

**Issue by Munkeywaxx** [Sunekaer/stoneBlock#632]
Evening/Afternoon/Morning wherever you may be.

Over the last few days, I've been hosting a "Server" VIA "Open-To-Lan" in single player.
The reason for this is something related to windows, but how? Firewall is turned off and Defender is disabled for the time being, but the download from ALL Browsers won't actually download.

https://gyazo.com/8b384bc71f3b1db3382aa07853e8c4fe
Sure, in my "Downloads" Folder it says it's complete, but when I drag it into a dedicated folder on my desktop and "Unzip", there is no ETA or any information on folder relocation or unpacking.

There is no issue here for previous versions as you can see in the above picture. x.0.24 Works fine, am unable to move/relocate the .zip to a folder and have done for testing purposes, but the latest version isn't doing anything.

Any information on this would be great!

Thanks,
Munkeywaxx

**Comment by Sunekaer** [comment]
Youll have to contact twitch/curseforge, nothing i can do, other then say i dont have this problem

**Comment by Munkeywaxx** [comment]
No worries, cheers for the reply.
