### ISSUE TITLE
ExtraUtills crash

### ISSUE THREAD

**Issue by SpiritGate** [Sunekaer/stoneBlock#633]
In version 1.0.28 in single player, when trying to shift+r click a stack of items in extrautills machines/nodes my game crashes. it happened 3 times in total. 1st - when i tried to shift+r click a stack of cobble in a item transfer node to fill it . 2nd - shift+r click a stack of obsidian again to fill a item transfer node. and the 3rd time when I shift+r clicked a stack of coal in a Furnace Generator to fill it. If it even matters, the node/machine already had some of said item in it.

**Comment by Sunekaer** [comment]
use the template and link log....
