### ISSUE TITLE
Flux Networks Not Allowing Power Through Multi Dimensions

### ISSUE THREAD

**Issue by bogointeractive** [Sunekaer/stoneBlock#634]
## Bug Report
In the current version of Stone Block 1.0.28 I have my mekanism reactors setup in the mining dimension as it just works there. Recently I moved my draconic power ball to the overworld. In doing so I needed to find a power network that will go through the multi dimension. So I went to Flux Networks as it is the only one that will allow for unlimited transfer. I setup the plugs and it said 99.9M power coming into the network.

I then went back to the overworld and none of the points on any of the the machines, AE2 system, and draconic power ball were not sending or reviving any power. So I setup the RFTools power cells as they are the only thing that will send the power.

## Steps to Reproduce (for bugs)

1. I have setup points and plugs and deleted them. Then tried them connected to other machines or power cells and plugs showed power but the points on Ender IO, Draconic Ev, etc in their points were losing power. So I tried to reset the networks with a delete in the Flux Networks Control panel. Still nothing coming in. So I tried to do some other machines but still no power.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.28
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by bogointeractive** [comment]
![untitled](https://user-images.githubusercontent.com/28167934/48810381-ae925f80-ecee-11e8-8490-843683ea08ba.png)
![untitled1](https://user-images.githubusercontent.com/28167934/48810400-c9fd6a80-ecee-11e8-8d8d-23d6cd9808e0.png)
![untitled2](https://user-images.githubusercontent.com/28167934/48810419-e5687580-ecee-11e8-809e-9c0750c23ae8.png)
![untitled3](https://user-images.githubusercontent.com/28167934/48810438-029d4400-ecef-11e8-834e-2c6504dec47f.png)
![untitled4](https://user-images.githubusercontent.com/28167934/48810477-324c4c00-ecef-11e8-83d3-098b2aeadb60.png)


Here are a few screen shots. As you can see in some of the points and also the plugs are working. However, some of them say they are pushing or pulling power but are not working at all. Also the flux storage should auto fill once the network is selected, which it does not. I have gone into my claimed chunks and nothing works to improve the power issues.

**Comment by Sunekaer** [comment]
I have seen many people use them across dims, have you chunk loaded them?

**Comment by bogointeractive** [comment]
@Sunekaer Yes they are all chunk loaded as I have went to check them all. I use them across dims as well. I am not sure what else to use for power. I have also tried to setup the reactor in the overworld and it will not power up for some reason.

**Comment by bogointeractive** [comment]
![untitled5](https://user-images.githubusercontent.com/28167934/48823424-655e0200-ed26-11e8-9e19-bd79d07d4f1e.png) As you can see that the storage is not filling

**Comment by bogointeractive** [comment]
![untitled6](https://user-images.githubusercontent.com/28167934/48824362-aacffe80-ed29-11e8-9cf2-be0e67408d08.png)
this is the view from the controller and you can see there is nothing that is not chunk loaded. You can also see there is no power going through either.

**Comment by bogointeractive** [comment]
[https://pastebin.com/dmYEQeq7](url) Noticed this as well.

**Comment by Sunekaer** [comment]
You’ll have to contact flux network on their issue page, because I don’t know what your doing wrong, as I personally haven’t used that mod much, and I know it works for others
