### ISSUE TITLE
Extra Utilities

### ISSUE THREAD

**Issue by stardrifter21** [Sunekaer/stoneBlock#635]
## Bug Report
Extra Utilities causing a game crash

## Steps to Reproduce (for bugs)

1. Place down Enchanter
2. Provide a full set of book shelves or other block to provide the 30 level enchanting needed
3. Provide Power
4. Insert a few items into both inputs, in my case I did apples and lapis
5. Shift + r click a full stack of apples into the machine
6. Game will shut down internal server and then crash
7. I have tested this on the resonator, crusher, and enchanter.

I presume this also then works with the rest of the machines in the mod.
## Logs

* Client/Server Log:
* Crash Log: https://paste.feed-the-beast.com/view/d842ed19

## Client Information

* Modpack Version:1.0.28
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled:No

**Comment by stardrifter21** [comment]
It also happens when shift + r click 2 stack upgrades into a fluid transfer node, may be more that are affected

**Comment by Sunekaer** [comment]
Please report to extra utilities, as there is nothing I can do about this
