### ISSUE TITLE
World Problems.

### ISSUE THREAD

**Issue by Deadlypain96** [Sunekaer/stoneBlock#637]
Hello.

I've been running into problem where every time i close twitch program and re open stone block my world has been restarted it starts me in same cube i started with and my chests broken and every item dropped on ground. After i dig around some i find my spaces i have digged but. Still its kind of annoying every time to re dig and re do all my chests.

**Comment by Sunekaer** [comment]
Template not used, and no logs

**Comment by Deadlypain96** [comment]
kk.... ill find new modpack with better owner
