### ISSUE TITLE
CPU Usage at 100 Percent

### ISSUE THREAD

**Issue by King0fCookies** [Sunekaer/stoneBlock#64]
## Bug Report
After a short period of time i get randomly freezes , cpu usage jumps up to 100 percent after recent update (Version : StoneBlock-1.0.13)

## Client Information

* Modpack Version: StoneBlock -1.0.13
* Server/LAN/Single Player: LAN
* Optifine Installed: No
* Shaders Enabled: NO

**Comment by hmforall** [comment]
Also happeneds to us on our little server. We had to restart the server to fix the problem. Could play hours without freeze, or within 10 minutes.

**Comment by Sunekaer** [comment]
Knoxhack is working on finding out what makes the servers lag so much and what there can be done about it

**Comment by Sunekaer** [comment]
@King0fCookies and @hmforall 
Please add something like https://minecraft.curseforge.com/projects/tickprofiler (this one is server side only)
and run it when the lag is crazy, to see what makes your worlds lag

**Comment by Nicocraft05** [comment]
no problem on my server version 1.0.12
