### ISSUE TITLE
Mobs are dropping less items than they should

### ISSUE THREAD

**Issue by NLBlacky** [Sunekaer/stoneBlock#640]
## Bug Report
We've opened a Stoneblock server 2 weeks ago. We've had alot of reports from players that the loot dropped by mobs were alot less than they expected. After testing the Mob Crusher, Spikes and a few other mob killing tools, we came to the conclusion that the drops from mobs (aggressive and passive) were indeed alot less. When testing this on spawners, we noticed that we got like 1 item every ~7 mobs. It took 6 zombies before rotten flesh was dropped. We've been talking with some other developers and players about it, and we were sadly not able to find any setting to adjust drop chances. We expect that drop chances are lowered for spawners (by checking the amount of mob kills in a chunk?). Since we still haven't been able to figure out why or where we can chance it, we decided to bring the question to this Github.

## Steps to Reproduce (for bugs)
I think that making a mob spawner on any server should recreate the environment. Since it is happenening on our server, feel free to join our server for testing or recreating. Permissions will be granted to make sure we can recreate it. Just contact NLBlacky on discord. The discord link is https://discordapp.com/invite/J2gHy4c (This is not ment as advertisement. Feel free to delete it if it is considered advertising).

## Logs
No logs are added because no crash happened or console error was given. I can still upload logs if requested.

## Client Information
* Modpack Version: StoneBlock-1.0.28
* Server/LAN/Single Player: Server
* Optifine Installed: Depend per player
* Shaders Enabled: Depend per player

**Comment by Sunekaer** [comment]
I havent changed anything regarding mob drops, are your server running sponge or anything like that?

**Comment by NLBlacky** [comment]
Yes, our server is running on Spongeforge. I never had this in any of my other servers so it must be something in the modpack. Maybe lootcrates or something that is effecting it then ?

**Comment by Sunekaer** [comment]
Loots crates has nothing to do with mobs, Sponge has been seen to mess with stuff like this before. but as said drops hasnt been changed and never been a problem
