### ISSUE TITLE
Overfilling containers crashes to desktop

### ISSUE THREAD

**Issue by YukiMurakumo** [Sunekaer/stoneBlock#641]
## Bug Report

When shift-clicking to fill a non-vanilla container (Generator, etc), the game crashes. Server and world stay intact, including other players nearby. Container doesn't accept the items at all.

Does not seem to happen with Storage Crates (possibly just inconsistent), happens especially consistently with EU2 Generators.
## Steps to Reproduce (for bugs)

1. Spawn generator or other non-vanilla chest/container
2. Fill container minus a few items in the last space 
3. Attempt to quickly fill past limit with shift-click (eg. leave 60 items in the corner of a chest, then shift click 5 items into said chest, example in attached picture)
![image](https://user-images.githubusercontent.com/45274309/48924158-445ef380-ee83-11e8-9e70-80c8a2bd618b.png)

## Logs

* Client/Server Log:  
Server cmd log: https://paste.feed-the-beast.com/view/9ed39a7d
latest.log: https://paste.feed-the-beast.com/view/1920230c

Note: Server log is noticeably small, simply the only error the server shows, as it doesn't crash. Able to rejoin afterwards, and no other players online are affected - simply a temporary setback for the user who produces the issue.

* Crash Log (Launcher Log): https://paste.feed-the-beast.com/view/a1a39c75

**If any logs are missing, let me know. I'll update as necessary. These are all the logs I was able to find surrounding the matter.**

## Client Information

* Modpack Version: 1.0.28
* Server/LAN/Single Player: Server, hosted on same machine. May happen in SP as well, as it only affects the user, and the server leaves near-zero report.
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
#553
