### ISSUE TITLE
This is not a bug I just don't know where to discuss this, a problem with a tool I just wanna sort out.

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Sunekaer/stoneBlock#642]
Anyone know what  items the acceleration wand works on I tried a few machines and stuff it really didn't work specifically any that produce benefits in the roost breeders and magical crops  would be appreciated but if you go the extra mile and give me an extensive list of things I'd really appreciate it, thanks for your time reading this, have a nice day 😄

**Comment by Sunekaer** [comment]
Don’t have an list
