### ISSUE TITLE
Roost chickens

### ISSUE THREAD

**Issue by CharCharthemonkey** [Sunekaer/stoneBlock#643]
on the list it shows the "funwaychick" as obtainable but nothing works to get it even trying to feed a chicken fireworks (which is odd) doesnt work so how to get it? please and thank you also pack version 1.0.27r2 if that helps

**Comment by mskoczen** [comment]
Pleease use the provided form for bug reports.
To get the "funwaychick" you feed a chicken TNT.

**Comment by Sunekaer** [comment]
answered by mskoczen
