### ISSUE TITLE
Errors and DC when logging in my server 

### ISSUE THREAD

**Issue by kakanos** [Sunekaer/stoneBlock#644]
The latest version btw  I need to log in like 6 times after a time out to finally log in to my server  even my host company tryed to install it 4 times even did a clean server IP so what's with it I can send the logs when I am at home my friends are complaining -_-  ps it's a clean server files setup nothing changed

**Comment by Sunekaer** [comment]
There is nothing i can do about this, some servers i can log straight in to others i also get dced sometimes before i get in.
Next time use the template or you issue will be ignored
