### ISSUE TITLE
Woot Mob Factory Drops?

### ISSUE THREAD

**Issue by ShadowDrakken** [Sunekaer/stoneBlock#645]
## Bug Report
Woot mob factories don't appear to drop all non-player drops correctly. Example: cow mob factory does not drop leather, rabbit mob factory does not drop rabbit hide, etc.

I can't find anything on Woot's or the modpack referencing any changes to the factory's mob drops. This may be a wholly Woot issue??

## Steps to Reproduce (for bugs)
No special steps, standard Woot mob factory as described above.

## Logs
Not this kind of bug, there's no errors involved. Purely behavioral.

## Client Information
* Modpack Version: 1.0.28
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
I havent changed the drops from woot, ill regenerate the config for next update, and if that doesnt fix it for report to woot
