### ISSUE TITLE
stoneblock crash error after 3 days of play

### ISSUE THREAD

**Issue by nogoodgamers** [Sunekaer/stoneBlock#646]
## Bug Report
game crashes after trying to join the world on single player, lan, and server based games

## Steps to Reproduce (for bugs)

1.https://vimeo.com/user92067302/review/302527784/8e65a0111e
2.

## Logs

* Client/Server Log: cant upload cause file too large but same thing as server
* Crash Log: https://pastebin.com/1T6Es0qF

## Client Information

* Modpack Version: 1.0.28
* Server/LAN/Single Player: all options
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
Try and reinstall the pack

**Comment by nogoodgamers** [comment]
after running the server even the server crashes, like when i launch the server it goes just fine but then when someone tries to connect, the server just dies

**Comment by nzminecraftDOTcom** [comment]
Are all crash reports similar, do some mention the Server tick watchdog - server has run too many ticks in x time and is behind etc etc.

**Comment by Sunekaer** [comment]
Now your saying server, but in your report you say "single player, lan, and server based games" so which is it?

**Comment by nogoodgamers** [comment]
neither will load after that crash unless I start a new world but haven't done anything wrong to cause it

**Comment by Sunekaer** [comment]
make an new world, and give me the crash log for it

**Comment by nogoodgamers** [comment]
https://pastebin.com/kBb2rBv5
updated crash report
reinstalled modpack

**Comment by Sunekaer** [comment]
Did you try making an new world?

**Comment by nogoodgamers** [comment]
yes i have and it works on a new world but i want my old world back cause all the work i did

**Comment by Sunekaer** [comment]
Your world is corrupted and there nothing I can do about that, you have to roll back to and backup if you have any or start on a new world
