### ISSUE TITLE
Refined Storage Controller Breaking other RS Blocks around it

### ISSUE THREAD

**Issue by VenomNaols** [Sunekaer/stoneBlock#647]
## Bug Report
After leaving the mining dimension I found found that my RS disk drive, crafter, and monitor had been broken. After rearranging the RS block around and traveling back and forth between the overworld and mining dimension, I found that the controller is breaking any RS block or cable that is directly touching it. Chunkloading the area seemed to fix the issue. It happens when traveling to the nether as well, but not the end.

## Steps to Reproduce (for bugs)

1. https://vimeo.com/302552441
2.

## Logs

* Client/Server Log: https://paste.feed-the-beast.com/view/fdbc3f6d
* Crash Log: No Logs

## Client Information

* Modpack Version:1.0.29
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
does it happen when coming from other dims?

**Comment by FluxcapGaming** [comment]
I thought I would chime in here and confirm that I also have this issue after traveling to the Nether.  I also had the stone workbench and growth crystal break as well in a separate trip.

**Comment by VenomNaols** [comment]
It also happens when traveling to the Nether, But it doesn't seem to happen when traveling to the End dimension. I haven't tried any other dims yet.

**Comment by Sunekaer** [comment]
I cant recreate this in my world, does it happen everytime? what do you have connected?

**Comment by Sunekaer** [comment]
reported to RS

**Comment by FluxcapGaming** [comment]
Could it be the mod that drops items on the ground instead of normally?  I had this happen once prior to the recent update.

**Comment by Nbenito** [comment]
I know this is being told to the mod dev, but I'm also having this issue and it happens to me every other time I travel out of the overworld, be it the nether, mining, compact machine, Etc. 
So it is happening not just the nether and end Dims.

**Comment by Sunekaer** [comment]
1.0.30
