### ISSUE TITLE
Minecraft-Stoneblock Crash while starting

### ISSUE THREAD

**Issue by Dustin2004** [Sunekaer/stoneBlock#648]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by nzminecraftDOTcom** [comment]
To fix this bug, you need to do:

1:
2:
3:
4:???
5: profit
