### ISSUE TITLE
Environmental Tech Machines are ownerless after 1.0.13 update

### ISSUE THREAD

**Issue by kosherbacon79** [Sunekaer/stoneBlock#65]
## Bug Report
After updating to version 1.0.13, Environmental Tech machines that were constructed are considered ownerless, and are therefore unbreakable.

## Steps to Reproduce (for bugs)

1. Create a world in 1.0.12 or earlier. 
2. Create a valid Void Ore Miner, or other Environmental Tech Machine.
3. Test the machine's ownership by right clicking. It should say Owner: (Player Name)
4. Update to 1.0.13
5. Right click your 1.0.12 machine.
6. Note how the chat says Owner: (blank).
7. Attempt to break any part of the multiblock. It should immediately reappear, without dropping.

Note I have only tested this with a Void Ore Miner. Other machines may not be bugged, but it stands to reason that they would be.

## Client Information

* Version 1.0.13:
* Single Player, on a local machine. no servers involved.
* Optifine Installed: No.
* Shaders Enabled: No.

The only changes from a default installation are as follows:

Evilcraft mobs have been configured to only spawn at y=200+.
Ore Excavation mining limit raised to 10000.

**Comment by Sunekaer** [comment]
https://github.com/ValkyrieofNight/EnvironmentalTech/issues/147

Fix update EnvironmentalTech

**Comment by Sunekaer** [comment]
1.0.14

**Comment by kosherbacon79** [comment]
Tested in 1.0.14:

The machines built in 1.0.13 have proper ownership, but the machines built in 1.0.12 are still ownerless.

**Comment by Sunekaer** [comment]
They need to be rebuilt not much I can do about that
