### ISSUE TITLE
Mesh duping in industrial foregoing enchantment extractor

### ISSUE THREAD

**Issue by SnappierSoap318** [Sunekaer/stoneBlock#650]
## Bug Report

it is an issue when you put multiple sieve mesh's into the industrial foregoing enchantment extractor, only one of the mesh will be sent to the output( all will get dis-enchanted) and the rest will stay in the input of the machine.

## Steps to Reproduce (for bugs)
1.insert multiple enchanted meshes having same enchantment's and let the machine dis-enchant the mesh.
## Client Information
* Modpack Version:1.0.28
* Server/LAN/Single Player:Single Player
* Optifine Installed:Not installed  
* Shaders Enabled:No

**Comment by Sunekaer** [comment]
reported to industrial-Foregoing
https://github.com/Buuz135/Industrial-Foregoing/issues/460
