### ISSUE TITLE
Refined storage blocks have broken textures

### ISSUE THREAD

**Issue by CasperTheG** [Sunekaer/stoneBlock#653]
## Bug Report

When coming back from the mining age all refined storage textures and some other block textures like bonsai tree textures are broken. 

## Steps to Reproduce (for bugs)

1.Go to mining world
2.Come back through mining world portal 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.29
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
does it happen when coming from other dims?

**Comment by CasperTheG** [comment]
> I wasnt able to recreate this in my world, does it happen eveytime?

I happend one time. I relaunched and reloaded my chunks in the over-world and the mining world and I have not gotten the issue again. I'm not sure what it was. I have not tried other dims yet. Also I sometimes get invisible skeletons and enderman I can not kill in my base. I don't know if its a mob farm issue or what. I have no no-torched areas where they would be able to spawn, so i'm not sure how they are getting in and why I can't see them.

**Comment by Sunekaer** [comment]
Okay sounds to be this problem #160 still waiting for dev to fix it
