### ISSUE TITLE
Tier 6 Mystical Aggriculture seeds won't drop extras when broken regardless of anything.

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Sunekaer/stoneBlock#654]
## Bug Report
I've tried countless times and I don't know if it's impossible but I think they aren't really reproducing.

## Steps to Reproduce (for bugs)
It's in general always happening no matter what, just use tier 6 magical crops and you'll see.

## Logs
Logs wouldn't really be required as its' not a crash or something 

## Client Information

* Modpack Version: 1.0.28
* Server/LAN/Single Player: Single Player.
* Optifine Installed: No.
* Shaders Enabled: No.

**Comment by AnimeNerdDJBROS** [comment]
Also slightly related to this issue but not 100% related, do you guys know if any hoe or mattock gives chances or better chances of getting more seeds?

**Comment by VenomNaols** [comment]
In response to AnimeNerdDBROS, I haven't gotten any tool to work very well, but the actually additions farmer seems to duplicate seeds pretty quickly if you use an acceleration wand

**Comment by VenomNaols** [comment]
And tier 6 seeds are programmed to not reproduce by the mystical agriculture mod author. He didn't even add an option in the configs because he thought it would be way too OP.

**Comment by Sunekaer** [comment]
answered by VenomNaols

**Comment by Algester** [comment]
if you want the tier 6 to spread you need to add agricraft <_< but that kinda destroys the balance

**Comment by AnimeNerdDJBROS** [comment]
k.
