### ISSUE TITLE
A suggestion about buildings

### ISSUE THREAD

**Issue by Explosivee** [Sunekaer/stoneBlock#655]
Hello, the modpack itself is really fun and amazing but it's kinda limited about buildings i think you guys should add Blockcraftery, Bibliocraft and ArchitectureCraft into the mod pack, especially Blockcraftery would be really awesome, thanks!

**Comment by Sunekaer** [comment]
not adding anymore mods

**Comment by Explosivee** [comment]
Blockcraftery is really small mod, i don't think it'd make any problems
