### ISSUE TITLE
Server crash due to iron hoe ore dictionary

### ISSUE THREAD

**Issue by jc2xs** [Sunekaer/stoneBlock#657]
## Bug Report
Using AE2's autocrafting to craft the Industrial Foregoing plant gatherer will crash the server when it goes to use the vanilla iron hoe in the template.  There is a template in the system for crafting the other ingredients and the hoe.

## Steps to Reproduce (for bugs)
See this report at the AE2 Github:  https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3768 and https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3835

## Logs
* Crash Log:  https://pastebin.com/sUHDMdsd

## Client Information
* Modpack Version: v1.0.29
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Solution
* Remove the oredict entries for hoe (specifically toolHoe oredict).  See the links for AE2's Github above.

**Comment by Sunekaer** [comment]
removed minecraft hoes from oredict

**Comment by Sunekaer** [comment]
1.0.31
