### ISSUE TITLE
Stoneblock crashes entire PC

### ISSUE THREAD

**Issue by AtlasSouth** [Sunekaer/stoneBlock#663]
## Bug Report
Whenever I try to launch Stoneblock, the game loads normally until it gets to the main menu. After about 10-15 seconds, regardless of what I do, my entire PC locks up and I have to hard reboot. Ive tested several other modpacks, and two seperate launchers to play the pack. On both Twitch and MultiMC, Stoneblock crashes my PC. However, no other modpack seems to do this, even after hours of play. 

## Steps to Reproduce (for bugs)
1. Launch Stoneblock through Twitch or MultiMC
2. Wait for pack to load
4. Crash after about 10 seconds. 

## Logs

* Client/Server Log: None
* Crash Log: None

## Client Information
* Modpack Version: 1.0.28 - 1.0.30
* Server/LAN/Single Player: Unable to get this far
* Optifine Installed: None
* Shaders Enabled: None

**Comment by Sunekaer** [comment]
How much does your pc have and how much have you assigned to Minecraft?
Latest log?

**Comment by nzminecraftDOTcom** [comment]
Did you allocate through the twitch launcher, or through the Mojang Minecraft launcher via editing the Java Args?

**Comment by Gunner76th** [comment]
@AtlasSouth One thing you can do to help the staff is please include your crash report and or log files. both are found in the install folder for your modpack.

**Comment by Sunekaer** [comment]
Okay so its not because you allocating to much ram, now i need some logs as Gunner also said

**Comment by AtlasSouth** [comment]
@Gunner76th @Sunekaer Ive only got one log, but it isnt a crash log. 
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2622261/latest.log)

**Comment by AtlasSouth** [comment]
I have stress tested, and Ive had no problems. I play far more intensive games such as Fallout 76 on a daily basis without any issues

**Comment by Sunekaer** [comment]
I’m not downloading files, please use paste.feed-the-beast.com and link it here

**Comment by joshuasuperboy** [comment]
Have you messed with any of your nvidia driver settings? Also your nvidia drivers are outdated. Make sure all your drivers are updated in device manager. Then it will maybe fix your problem.
