### ISSUE TITLE
Cannot fill glass bottles with potions in the fluid transposer

### ISSUE THREAD

**Issue by llhilton** [Sunekaer/stoneBlock#665]
## Bug Report
I'm trying to get Lingering Potion of Invisibility into bottles for the potion generator. If I start out with the potion in the fluid transposer and then put the bottles in, they will fill up as expected. But if I start out with the bottles, one moves into the "processing" slot, but it will never fill up. I have to manually remove it, and then the remaining bottles start to fill. This doesn't happen with buckets, but buckets don't go into the potion generator. It doesn't happen with just water, either. My super-slick potion-making set-up isn't working! :( 

## Steps to Reproduce (for bugs)
1. Create a bucket of awkward potion in an alchemical infuser.
2. Place and power a fluid transposer.
3. Insert a stack of glass bottles into the transposer.
4. Right-click the fluid transposer with the bucket of awkward potion. 

Expected result: 
The bottle will fill with the awkward potion.

Actual result: 
The fluid stays in the "tank" until the bottle in the processing slot is removed manually. Then the next bottle will fill.

## Logs
* Client/Server Log: https://pastebin.com/DEDpN51n

## Client Information
* Modpack Version: 1.0.28
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by nzminecraftDOTcom** [comment]
Do you get the same result on the latest version of the pack? 1.0.30?

**Comment by llhilton** [comment]
Yep, same behavior.

**Comment by Sunekaer** [comment]
Could you please report it to Thermal Expansion, as they have to look at the problem
