### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Sketchycoyote** [Sunekaer/stoneBlock#666]
## Bug Report

Game crashes whenever you try shift-clicking BLOCK of coal into furnace generator.
## Steps to Reproduce (for bugs)

1. shiftclick  block of coal into furnace generator
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by nzminecraftDOTcom** [comment]
Fill out the form so we know what version, post a crash log please.

**Comment by Sunekaer** [comment]
#553
