### ISSUE TITLE
Dragon scales have no emc

### ISSUE THREAD

**Issue by FallenCasshern** [Sunekaer/stoneBlock#667]
## Bug Report

In the patch notes on the twitch launcher it says that emc was added to dragon scales, though neither scale have emc. 
## Steps to Reproduce (for bugs)

![5b2dd9f95de67452a92538c881e91981](https://user-images.githubusercontent.com/41969146/49101658-c153e980-f244-11e8-8244-40a07b16ab90.png)
![852011f447d1995f6a5184f83a9d6ff1](https://user-images.githubusercontent.com/41969146/49101665-c6b13400-f244-11e8-822a-85588a412bb3.png)
![00d45be0c17749bcdf2084ef879be970](https://user-images.githubusercontent.com/41969146/49101674-c9138e00-f244-11e8-81b1-7572f4dc7b0f.png)

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.30
* Server/LAN/Single Player: Both
* Optifine Installed: N/A
* Shaders Enabled: N/A

**Comment by Sunekaer** [comment]
Hmm weird I’ll add it again then..

**Comment by Sunekaer** [comment]
1.0.31
