### ISSUE TITLE
World

### ISSUE THREAD

**Issue by SMASH-DIAMOND** [Sunekaer/stoneBlock#668]
## Bug Report

World will never stop Loading in.
## Steps to Reproduce (for bugs)

1.load up minecraft with the mods
2.tell it to create a world or join one

## Client Information

* Modpack Version:lastest version
* Server/LAN/Single Player:Singe Play> This doesnt concuren you but i cant get my server to start. im using Aternos i have giving them my problom
* Optifine Installed: no unless its in the pack
* Shaders Enabled:no

**Comment by Sunekaer** [comment]
No logs.. can’t help

**Comment by SMASH-DIAMOND** [comment]
the logs?
