### ISSUE TITLE
Server crashes when I log in

### ISSUE THREAD

**Issue by Chaoticator** [Sunekaer/stoneBlock#669]
## Bug Report
When I try to log on to a multiplayer server I've been playing on, the server crashes.  It doesn't happen for any of the other players, and it doesn't happen to me in singleplayer.  
The first crash happened just after I placed an item translocator on a roost and clicked it to tell it which way to send items.  I didn't have an empty hand, so that click would have done nothing, and I was about to empty my hand and try again.  Not even sure that was related.  After that, all it took to crash the server was me trying to log in.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log: https://paste.feed-the-beast.com/view/7265e89d

## Client Information

* Modpack Version: 1.0.30
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Translocator at your base that’s crashing the server, they need to remove it

**Comment by Chaoticator** [comment]
The server owner says that when they try to remove that block remotely, the game says it's out of the world, and when he tried to send himself there it crashed the server.  Could you tell us how to resolve/remove it?

**Comment by Tommsy64** [comment]
@Chaoticator I'm sure there are better ways of fixing this crash, but removing the translocator seems like a safe bet. Besides manual NBT-editing of the world file, you can try downloading [MCEdit](http://www.mcedit.net/) and going to the position of the trans-locator and deleting it. Note that MCEdit does not support mods, so all the modded blocks won't have textures; however, the last time I tried doing this for a similar reason, it worked.
