### ISSUE TITLE
Emerald paxel recipe conflict

### ISSUE THREAD

**Issue by Chaoticator** [Sunekaer/stoneBlock#672]
## Bug Report
I am unable to craft the emerald paxel from tiny progressions, because when I try to craft the axe, shovel, and pick needed for the recipe it will only let me make the ones from actually additions, which won't work in the recipe.

## Steps to Reproduce (for bugs)

1. Click the recipe for the tiny progressions emerald pick, axe, or shovel from JEI into the crafting grid
2. Get offered the actually additions emerald pick, axe, or shovel as a crafting result instead

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.30
* Server/LAN/Single Player: Both server and single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
1.0.31
