### ISSUE TITLE
Translocators crash game when clicked with iron ingot

### ISSUE THREAD

**Issue by Chaoticator** [Sunekaer/stoneBlock#673]
## Bug Report
Game (or server, on a server) crashes when item translocator is right-clicked with an iron ingot.  Server crashes whenever the chunk that translocator is in is loaded from then on.
Trying to fix the server, apparently we need the chunk to be loaded to run the setblock command to remove the translocator in question, but once it loads, it causes the server to crash.  Any way of getting around that?

## Steps to Reproduce (for bugs)

1. place two chests with one block of air between them.
2. place pair of item translocators between the chests
3. right click on the centre of one of them as if to set which direction the items should flow, only instead of an empty hand, do it while holding an iron ingot

## Logs

* Client/Server Log:
* Crash Log: https://paste.feed-the-beast.com/view/8f4f8940

## Client Information

* Modpack Version: 1.0.30
* Server/LAN/Single Player: Server and single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by jc2xs** [comment]
Make sure to take a backup of your game then edit the forge.cfg in the config file.  There are a couple of lines about removing erroring entities.  Change both of them to true and load the world and see if the removes the translocator.  If that doesn't work, then use mcedit on the world to remove the block located at (-1001,90,-999).

**Comment by Chaoticator** [comment]
Thanks, jc2xs.  We've got it fixed now.
