### ISSUE TITLE
Massive Meteors in Mining Dimension

### ISSUE THREAD

**Issue by RyanEHenderson** [Sunekaer/stoneBlock#674]
## Bug Report

Upon spawning in the mining dimension, when the world is loaded in the spawn point is bombarded by meteors. Last time I did it it spawned 17 meteors all very close to the spawn location. This wouldn't be a problem, but A) It's really excessive and annoying to have to deal with all of the meteors, and B) The meteor generation breaks the portal, so I have to turn on cheats to get back.

I took a screenshot of an example of this: https://imgur.com/d5yggz5
The portal was right in the middle, in that lava area. It was overwritten by the meteor.
This has happened multiple times, I have deleted & re-generated the world a minimum of 5 times.

## Steps to Reproduce (for bugs)

1. Generate new mining dimension world (DIM-6 folder)
2. Enter mining dimension

## Logs

* Client/Server Log: https://paste.feed-the-beast.com/view/147456a4
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.30
* Server/LAN/Single Player: Single Player (LAN enabled to turn on cheats to escape bug)
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
I have never seen this happen, you must have been really lucky/unlucky depending on how you see it,but theres not really anything i can do about it sorry
