### ISSUE TITLE
Install on Linux (without Twitch app)

### ISSUE THREAD

**Issue by piousminion** [Sunekaer/stoneBlock#675]
How do I get the actual modpack and not the twitch app config stuff?
I run linux on my desktop and the cancerous Twitch app doesn't run on linux.

Are non-windows and/or non-twitch app users SOL ?

**Comment by Sunekaer** [comment]
You could download the server files, and take the mods, scripts, config and resources folder from there to build you files

**Comment by Tommsy64** [comment]
@piousminion [MultiMC](https://multimc.org/) is amazing and does exactly this!

Download the latest StoneBlock client from [CurseForge page](https://minecraft.curseforge.com/projects/stoneblock/files) and import it as an instance into MultiMC.
![Import from Zip](https://user-images.githubusercontent.com/3900951/49195778-6e6a5700-f356-11e8-9a62-f088b2cf98b4.png)
