### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity (xu2:tilemachineprovider // com.rwtema.extrautils2.machine.TileMachineProvider)

### ISSUE THREAD

**Issue by Godvil** [Sunekaer/stoneBlock#677]
Infos:
Our server crashed tonight, and crashes now directly on startup.
Looks like some blocks doing not well with each other...
Is there any way, we can remove them from our world without starting a server?

Bug Report
Steps to Reproduce (for bugs)

Logs

Client/Server Log: https://gist.github.com/Godvil/490fd33dbe9ae47fcb34b3553ceaeccd
Crash Log: https://gist.github.com/Godvil/c1e57e7a1778ba2177700ccc85544ca9

Client Information

    Modpack Version: 1.0.30
    Server/LAN/Single Player: Server
    Optifine Installed:
    Shaders Enabled:

**Comment by Godvil** [comment]
I was able to fix corrupted region file using NBTExplorer. Crash caused extra utilities 2 lava generator block.

**Comment by Sunekaer** [comment]
Make sure to take a backup of your game then edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. If that doesn't work, then use mcedit on the world to remove the block located at (-1004,93,-1990)

**Comment by Godvil** [comment]
> 
> 
> Make sure to take a backup of your game then edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. If that doesn't work, then use mcedit on the world to remove the block located at (-1004,93,-1990)

thank you. this information is very helpful too!
