### ISSUE TITLE
Quit closing my issue. Maybe if you actually helped.

### ISSUE THREAD

**Issue by ThePuffingMoose** [Sunekaer/stoneBlock#681]
Maybe if you actually read the last one it says i want to join the server but in order to do so i have to downgrade the modpack to version 26. Maybe if you told me how to do so or kept it opened i wouldnt be creating so many.

**Comment by netmc** [comment]
This isn't a stoneblock issue.  The pack maintainer is properly closing the issue as it's your issue for not knowing how to use the twitch launcher to change the version.  It's not up to the pack author to tell you how to use twitch.

There is a version button on the twitch launcher.  click the button, change your version.
