### ISSUE TITLE
Void Miners from Environmental Tech can't be accelerated in the stoneblock modpack

### ISSUE THREAD

**Issue by joshuasuperboy** [Sunekaer/stoneBlock#682]
## Bug Report
All void miners from Environmental Tech will not let me accelerate them with a acceleration wand and the watch of lowing time. It only happens in the stoneblock modpack.
## Steps to Reproduce (for bugs)
1. Download any version of the stoneblock modpack.
2. Open up a world and get any void miner from Environmental Tech.
3. Put together the void miner and make it start running.
4. Get a chest and put it next to it.
5. Get the acceleration wand and the watch of flowing time.
6. Try to accelerate the miner with the wand of acceleration and you will see it not work.
7. Try to accelerate the miner with the watch of flowing time and you will see it not work also.
## Client Information
* Modpack Version: StoneBlock-1.0.31
* Server/LAN/Single Player: Single player
* Optifine Installed: yes
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
https://github.com/ValkyrieofNight/EnvironmentalTech/issues/166

**Comment by KonchokDhondrub** [comment]
> https://github.com/ValkyrieofNight/EnvironmentalTech/issues/166

404 Page not found.
