### ISSUE TITLE
RE:  Server crash due to iron hoe ore dictionary #657

### ISSUE THREAD

**Issue by Gunner76th** [Sunekaer/stoneBlock#684]
## Bug Report

This is to inform that the above referenced bug report is still an issue in 1.0.31 I had one of my admins just attempt to craft the plant gatherer and the server crashes still with the same error. The updates from AE (if any were released) as well as removing the hoe from the OreDict has not been successful in preventing this issue. 

## Steps to Reproduce (for bugs)

1. Setup AE to autocraft the IF Plant Gatherer
2. Watch server crash when job is called. 

## Logs

* Client/Server Log: https://pastebin.com/aLx8vDKf
* Related Bug Report: https://github.com/Sunekaer/stoneBlock/issues/657

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Server Multiplayer
* Optifine Installed: No-N/A
* Shaders Enabled: No-N/A

**Comment by Sunekaer** [comment]
ill see what i can do about, but it will first be some time next week

**Comment by Sunekaer** [comment]
1.0.32
