### ISSUE TITLE
Bag of Holding

### ISSUE THREAD

**Issue by MayMeMiMoMu** [Sunekaer/stoneBlock#685]
Hi there.

For some reason, when trying to pull items out of the bag of holding, it freezes the game. There is no crash report, unfortunately, at least none I can see, but this has happened a few times now over the last few version updates. 

I can easily enough use a different method of extra inventory storage, but I just thought you'd like to know. 

Thanks.

**Comment by Sunekaer** [comment]
i cant recreate this problem, i would recommend creating an issue on Extra Utilities tracker as they might beable to tell you why this happens to you

**Comment by Tommsy64** [comment]
@MayMeMiMoMu I've had a similar issue with the Bag of Holding except when trying to shift+click items into it when the bag is already full. See https://github.com/Sunekaer/stoneBlock/issues/641
