### ISSUE TITLE
After joining server I crash instantly

### ISSUE THREAD

**Issue by Dustin2004** [Sunekaer/stoneBlock#687]
## Bug Report

After joining a server I´m crashing
## Steps to Reproduce (for bugs)

1./
2./

## Logs

* Client/Server Log:  / cant even join
* Crash Log:https://paste.feed-the-beast.com/view/e2a7d25a

## Client Information

* Modpack Version: 1.0.30
* Server/LAN/Single Player: /
* Optifine Installed: No
* Shaders Enabled: No /

**Comment by Dustin2004** [comment]
#562

**Comment by Dustin2004** [comment]
#1

**Comment by nzminecraftDOTcom** [comment]
Give a go re-installing the modpack, looks like it's missing a texture or two and crashes when loading it.

**Comment by Sunekaer** [comment]
Why you linking reports there has nothing to do with this and did you try what nzminecraft suggested?
