### ISSUE TITLE
Game crashes on starting sp or mp

### ISSUE THREAD

**Issue by Ribcage52** [Sunekaer/stoneBlock#69]
## Bug Report
whenever i try to load up a single player world or a multiplayer world, it crashes.
I downloaded the pack through the twitch app.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

https://pastebin.com/XikPTCVB

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by Sunekaer** [comment]
Could you try updating your java?

**Comment by Ribcage52** [comment]
okay thanks! I'll try that out. most mod packs I have played haven't had issues but its been a few months now.
