### ISSUE TITLE
I have a couple of suggestions?

### ISSUE THREAD

**Issue by joshuasuperboy** [Sunekaer/stoneBlock#690]
I would like to see more draconic quests and more avaritia quests. A quest of like get every tool and weapon and the armor from avaritia. New draconic quests like get every type of tool and weapon from that mod. Also another few draconic quests of get the draconic reactor core, reactor stabilizer frame, flux gate, entity detector, advanced entity detector, and other things from draconic evolution. Those suggestions is just some of the quests i would like to see. I would like to see a lot more quests in this modpack. It will make the modpack more fun to try and complete the quests. Im thinking that you had this idea already. I just wanted to suggest some good things that can be added. Like more invironmental tech quests.

**Comment by Sunekaer** [comment]
I’m not changing anything in this pack only bug fixes
