### ISSUE TITLE
Client hang when overfilling inventories (Bag of Holding, Generators)

### ISSUE THREAD

**Issue by Tommsy64** [Sunekaer/stoneBlock#691]
## Bug Report
The client will hang when certain inventories such as the Bag of Holding or Extra Utilities generators are overfilled via shift-clicking an itemstack.

## Possible Solution
This issue has been reported several times before (#685, #641, #553) and even reported to Extra Utilities (rwtema/Extra-Utilities-2-Source#226). Although an official bugfix has not been released, it appears that downgrading Extra Utilities from its current version, 1.9.8, to 1.9.7 prevents this bug from happening.

The only line in the [change-log](https://minecraft.curseforge.com/projects/extra-utilities/files/2632255) for 1.9.8 is `Fix items being voided when shift-click-transfering them in the GUI`.  This bug was probably introduced during that change.

## Steps to Reproduce (for bugs)

1. Fill a Bag of Holding completely with cobblestone.
2. Shift click a piece of cobblestone while the filled Bag of Holding is open.

## Logs

* Client/Server Log: Client and server logs throw no exceptions as the game simply hangs.
* Crash Log: No crash log.

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Happens both Server and Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Tommsy64** [comment]
@pseudoenigma I completely agree (including the part you edited out :p). Furthermore, the change between 1.9.8 and 1.9.7 is so small that even if a server is running 1.9.8, a 1.9.7 client should be able to connect without any major issues, The only thing preventing this from happening is the lack of an `acceptableRemoteVersions` parameter in the Extra Utilities 2 mod annotation. By default, the only accepted remote version is the one that matches exactly. Something like `1.9.*` would allow any Extra Utilities 2 versions starting with `1.9` to connect.

**Comment by Sunekaer** [comment]
Downgrading would cause other bugs to come

**Comment by 20Attila03** [comment]
Still happens on 1.0.33 :/
