### ISSUE TITLE
Add blacklists for Facades or Covers

### ISSUE THREAD

**Issue by Xevion** [Sunekaer/stoneBlock#692]
_yes how do I craft the ztones slightly limegreen faded white cable facade?_
_surely the recipe is different from the ztones slightly more limegreen faded white cable facade_
**oh thank god JEI has it**

Yeah. I know you can do it manually, but really, are most people concerned with it?
Perhaps you can whitelist Stone Facades or Covers as a "Blanket Example" for every other block.
And in the end, wouldn't this be a performance optimization, reducing our 79 JEI pages to maybe 20-40...

**Comment by Xevion** [comment]
Edit: Just checked the main page and noted the notice about you closing issues without templates...
There is no template for a suggestion type. Do you want me to change this and format or what?

**Comment by Sunekaer** [comment]
I’m only doing bug fixes now.
