### ISSUE TITLE
Tinkers Construct Arrows not stacking

### ISSUE THREAD

**Issue by ItzPnwd115** [Sunekaer/stoneBlock#693]
---
name: Bug report
about: Create a report to help us improve

---

## Bug Report
Tinkers construct arrows are not stacking. I do not know if it has to deal with the mod pack itself or a bug just thought it should be reported.

## Steps to Reproduce (for bugs)
Create any type of tinkers construct arrow

## Logs
No logs or crash logs

## Client Information

* Modpack Version:Current
* Server/LAN/Single Player:Single Player
* Optifine Installed: Yes
* Shaders Enabled:No

**Comment by EastArctica** [comment]
this is normal i think
each arrow has like 400 in it

**Comment by Sunekaer** [comment]
you only need one they have multiple shots in them, you need to repair them and upgrade them like any other tools
