### ISSUE TITLE
Refined Storage "External Storage" Bus Stops Working After 1.0.31 Update

### ISSUE THREAD

**Issue by naptimeshadows** [Sunekaer/stoneBlock#696]
## Bug Report
After a server restarts, the external storage that connects my drawer controller to my refined storage network no longer works. This was not happening in 1.0.28. I have to break and replace the bus in order for things to reconnect.

## Steps to Reproduce (for bugs)
I have a 7gb consumer/rented server that I use. After the regular 8-hour restart, the bus needs to be replaced. I doubt the memory or restart frequency matters, but there it is.

## Logs
No errors, bugs, or crashes.

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Server
* Optifine Installed: No mod files added to the pack
* Shaders Enabled: No

**Comment by DemonGyro** [comment]
I experienced the above issue and I have also encountered crashes when using external storage with IO Port. This is happening on v1.0.31 on Single Player for me.

**Comment by DemonGyro** [comment]
UPDATE: The issue I encountered is SAVE BREAKING and will cause a crash on load. 

**DO NOT ATTACH AN EXTERNAL STORAGE TO YOUR REBORN STORAGE IO PORT**

**Comment by Sunekaer** [comment]
Refined storage updated in 1.0.32
