### ISSUE TITLE
Client has to run two versions behind server to match server mod versions

### ISSUE THREAD

**Issue by toolongtospell** [Sunekaer/stoneBlock#697]
## Bug Report
This morning I updated my server to version 1.0.31, and then used the Twitch client to update to the same version. When I loaded the server and then my client and tried to connect I received a list of mods that my client had that had versions with revisions higher than the server.

In an effort to get my server back up and running I downgraded my server back to the version 1.0.27r2, I then changed the version of my client in the Twitch app to the matching version. I still received the mod mismatch list.

So next, I started rolling back my client version by version and for my client to connect to my server running 1.0.27r2 my client has to be running 1.0.25.

Server Files obtained from: https://minecraft.curseforge.com/projects/stoneblock

## Steps to Reproduce (for bugs)
1. Server running 1.0.27r2 
2. Client has to be running 1.0.25 to connect

## Logs
Can provide logs if needed

## Client Information
* Modpack Version: 1.0.25
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by toolongtospell** [comment]
Well, I'm still not able to run the client using version 1.0.25 due to a crafting recipe conflict but I am not longer getting the long list of mods that have incorrect versions.

**Comment by Sunekaer** [comment]
you must be doing something wrong because no one else has this problem, make sure you download the right files
