### ISSUE TITLE
FluxNetworks Chunkloading

### ISSUE THREAD

**Issue by DirtyDerv** [Sunekaer/stoneBlock#699]
## Bug Report
Fluxnetworks always loaded

## Steps to Reproduce (for bugs)
Place flux netorks plugs or points in a claim and leave, the claim will unload then reload straight away (found using /ae Chunklogger

Updated to latest fluxnewtowrks and sonarcore 17 and all is well no more chunks loaded.

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player:Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
I'm aware

**Comment by Sunekaer** [comment]
1.0.32
