### ISSUE TITLE
Spawn coommand Bug

### ISSUE THREAD

**Issue by prototype-saber** [Sunekaer/stoneBlock#70]
## Bug Report

When tp out form the room,the spawn command won`t turn you back to your own room.A new room  will be created and you will be there.

## Steps to Reproduce (for bugs)

1.Open a new world
2./tp 0 ~1000 0
3./spawn
4. spawn at a new room

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:1.0.13
* Server/LAN/Single Player:SSP
* Optifine Installed:no
* Shaders Enabled:no

**Comment by prototype-saber** [comment]
/island home is usable,just a small bug

**Comment by Sunekaer** [comment]
Not a bug

**Comment by Sunekaer** [comment]
Island home and spawn is two different places on the map
