### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Chaoticator** [Sunekaer/stoneBlock#700]
## Bug Report

Server crashed when I turned on the last few generators required to start the rainbow generator, and crashed again when I tried to log back in.  Too many things happening at that moment to narrow things down properly, though looking at the crash log, it might have been a problem with the froster I was using to make ice for the frosty generator.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log: https://paste.feed-the-beast.com/view/1676dee2

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
`Name: industrialforegoing:froster_tile // com.buuz135.industrial.tile.misc.FrosterTile`

Make sure to take a backup of your game then edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. If that doesn't work, then use mcedit on the world to remove the block located at (-990,29,1005)
