### ISSUE TITLE
Problems when start StoneBlock modpack with SpongeForge

### ISSUE THREAD

**Issue by SlappySlap** [Sunekaer/stoneBlock#701]
## Bug Report
Hello,
I buy a server but when i start StoneBlock with SpongeForge i get no access to my plugins or /sponge

I try to change config of FoamFix and remove them but not work
tanks for your help

## Steps to Reproduce (for bugs)

1. install modpack on sponge server
2. install plugins
3. lunch server

## Logs

* Client/Server Log: ttps://paste.feed-the-beast.com/view/11311403
* Crash Log:

## Client Information
* Modpack Version: 1.0.31
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders no
* SpongeForge version : 1.12.2-2768-7.1.4 AND 1.12.2-2768-7.1.5-RC3508
* Forge version : 14.23.5.2768

**Comment by Sunekaer** [comment]
#461
#453
#113

See if any of those helps you
