### ISSUE TITLE
Shiftclicking stack into EU2 crashes the game.

### ISSUE THREAD

**Issue by Cucumbear** [Sunekaer/stoneBlock#702]
## Bug Report

Shift clicking stack into EU2 inventory crashes the game
## Steps to Reproduce (for bugs)

1.In the bug report
2.

## Logs

* Client/Server Log: https://paste.feed-the-beast.com/view/6a45a7fc
* Crash Log: crash report: https://paste.feed-the-beast.com/view/39bc3844
latest.log : https://paste.feed-the-beast.com/view/ae132a4e

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player : SP
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
#553
