### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by hayhurst** [Sunekaer/stoneBlock#704]
## Bug Report

Updated my stoneblock pack to the latest version, now getting a crash every time I load my world. Any help would be great.

## Steps to Reproduce (for bugs)

1. Open my world
2. It crashes

## Logs

* Client/Server Log: https://pastebin.com/Yzmn8PR6
* Crash Log: Not entirely sure where to find this

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by hayhurst** [comment]
Does some more testing - happens when trying to create a new world for me as well :/

**Comment by hayhurst** [comment]
![image](https://user-images.githubusercontent.com/15649917/49481113-3f098d80-f821-11e8-91b4-1839367f8933.png)
This may also be important - happens when I load the world

**Comment by Sunekaer** [comment]
Full log?
Crash log in the folder crash-reports

**Comment by hayhurst** [comment]
[crash-2018-12-04_23.10.22-server.txt](https://github.com/Sunekaer/stoneBlock/files/2656961/crash-2018-12-04_23.10.22-server.txt)
Sorry about the delay - here you go
