### ISSUE TITLE
XNet Controller may cause crash on servers.

### ISSUE THREAD

**Issue by Vonr** [Sunekaer/stoneBlock#706]
## Bug Report

Interacting with a XNet Controller may cause a crash on some clients (discovered in server)
Produces a fatal connection error. Only happens on some clients, no clue why.

## Steps to Reproduce (for bugs)

1.Place a XNet Controller
2.Interact with it
3.Probably induce a crash

## Logs

* Client/Server Log: Nothing related found.
* Crash Log: -

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Server
* Optifine Installed: Unless Mod Pack has it, no
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Please report with log to XNet so they can fix the issue
