### ISSUE TITLE
GP isn't Generating

### ISSUE THREAD

**Issue by TheWolf531** [Sunekaer/stoneBlock#708]
## Bug Report

None of the GP generators are working. 
## Steps to Reproduce (for bugs)

1. I try to generate any kind of GP in ExtraUtilities2, and nothing works. I've tried creative gens as well. 
2.

## Logs

* Client/Server Log: Doesn't really help with this kind of bug.
* Crash Log: Doesn't crash.

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Any
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
i cant recreate you problem? which blocks have you been trying to use and how? Server, Single Player?

**Comment by TheWolf531** [comment]
I have been trying to use the manual mill, water mill, lava mill, and creative mill. No GP generates. I don't really know what's going on, I installed this on my server a while ago and no one has been able to generate any GP.

**Comment by Sunekaer** [comment]
could you show this? Installed what on your server? the pack?
I have not been able to create this problem in SP or server

**Comment by TheWolf531** [comment]
I installed the pack on the server. I have even updated it, and yet I still haven't been able to generate any GP. I'll post a video in a second.

**Comment by TheWolf531** [comment]
https://youtu.be/U1pqUrqm_Qg

**Comment by Sunekaer** [comment]
It is working? your using 0 out of 15

**Comment by TheWolf531** [comment]
It isn't working, All the time that I've had this pack, whenever I try to use GP, it says like 15 GP generated, and 0/15 GP total. I have no GP machines going.
