### ISSUE TITLE
World Loading error

### ISSUE THREAD

**Issue by davmaster10234** [Sunekaer/stoneBlock#709]
## Bug Report
Whenever I load into a world my game fully crashes and gives me this 

The game crashed whilst updating screen events
Error: java.lang.IllegalStateException: failed to create a child event loop

## Steps to Reproduce (for bugs)

1. play world 
2. crash

## Logs

* Client/Server Log:
* Crash Log: https://paste.feed-the-beast.com/view/60da287b

## Client Information

* Modpack Version: Forge- 14.23.5.2768, 1.0.31
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Tommsy64** [comment]
This is a strange socket error. According to Mojang [bug reports](https://bugs.mojang.com/browse/MC-34749),

> * This issue is most commonly caused by a broken installation of Avast! free edition Anti-virus software. A reinstallation of **Avast!** and a reboot usually fixes it.
>     * **McAfee** anti-virus software (and derivatives) are also know to cause this issue, and currently the only known solution is to uninstall this software to correct the problem.
>     * Also **Outpost security** may cause that issue.
> * This error also occurs when Java tries to open a socket on the IPv6 stack, but could't get a connection to the outside world. Try forcing the use of the IPv4 stack by adding `-Djava.net.preferIPv4Stack=true` to the launch options.

To add the preferIPv4Stack flag to the JVM arguments, go to Minecraft under twitch settings:

![image](https://user-images.githubusercontent.com/3900951/49626566-76567680-f9a8-11e8-9bcf-f875043cd492.png)

**Comment by Sunekaer** [comment]
Answered by Tommsy
