### ISSUE TITLE
tablet not crafting sigh

### ISSUE THREAD

**Issue by Verbalvolley** [Sunekaer/stoneBlock#71]
any help on this if possible stopping us from finishing this pack 

![tablet](https://user-images.githubusercontent.com/35580151/44491726-18508e00-a65a-11e8-99f2-ade653e6b261.png)

**Comment by Sunekaer** [comment]
hmm worked in my test world

**Comment by Verbalvolley** [comment]
welcome to come to island and try, sometimes if I hover over the omega's and get the little bars showing I can take out the transmutation table, place back in and the tablet appears I click it and then it disappears. weird.

**Comment by C0LiSii0N** [comment]
you have to put the klein in a relay to get the "damage" bar permanently so the craft work, just find this out ^^'
