### ISSUE TITLE
Repeated Crashing

### ISSUE THREAD

**Issue by YuBh8Tn** [Sunekaer/stoneBlock#710]
server keeps crashing and i cant figure it out help
its crashed multiple times and this is the most latest one,
i tred figuring it out but i just couldnt
[crash-2018-12-06_16.01.25-server.txt](https://github.com/Sunekaer/stoneBlock/files/2655375/crash-2018-12-06_16.01.25-server.txt)

sorry for the shameful englishi wrote before.
The server keeps crashing after a few hours of runtime, and it just crashed a couple minutes ago right after opening a grave. Can anyone decipher the crash log? It doesn't make sense to me.

**Comment by Tommsy64** [comment]
It appears that a Forestry butterfly entity is crashing the server while interacting with Aroma core somehow.

A possible solution:
1. Make a **backup** of the world and necessary files (IMPORTANT).
2. Go to `forge.cfg` and set the following line to true:
```
# Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
B:removeErroringTileEntities=true
```
3. Launch the server and do whatever caused it to crash. This should remove the erroring entity.
4. Turn off the server and set `B:removeErroringTileEntities` back to **false**. Do not leave this option indefinitely set to true.

Go back to the backup if your save becomes corrupted or damaged somehow.

**Comment by CastielAngelow** [comment]
It is honestly related to Aroma Dimensional World and Portal code rather then Forestry.
