### ISSUE TITLE
Single Player Crash

### ISSUE THREAD

**Issue by bogointeractive** [Sunekaer/stoneBlock#711]
## Bug Report

Single Player Instance crashed when going to an RFTools dimension. I have it stored on my Draconic Evolution dislocate charm
## Steps to Reproduce (for bugs)

1. selected the dimension I wanted to load into and instance crashed.
2.

## Logs

* Client/Server Log: https://pastebin.com/dfGMyHPg
* Crash Log: https://pastebin.com/6XzF0RbC

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by nzminecraftDOTcom** [comment]
Got a mob farm running in that world that's all jammed up? Too many mobs by the looks of the crash report

**Comment by bogointeractive** [comment]
I have zero mob farms per say. I do have wither kill chambers in a compact machine but those should not be causing an issue

**Comment by Lighter97** [comment]
Could you try enable the Peaceful difficluty? this should helps you with despawning all entities, if they are present

**Comment by bogointeractive** [comment]
I have tried that. The only mobs I have now are 3 sheep for power and that is it. Otherwise everything is off

**Comment by nzminecraftDOTcom** [comment]
Can you prove the either farms are not the cause? They most likely have jammed up and are spawning hundreds of Withers. I've seen it happen before.

**Comment by bogointeractive** [comment]
There is no way they can be spawning hundreds. The wither builder and the mob grinder are at full speed so there is maybe 10 in the kill area at a time

**Comment by nzminecraftDOTcom** [comment]
Unless you have checked it and confirmed it is not the problem then we can't offer more advice

**Comment by nzminecraftDOTcom** [comment]
When you mention compact machines then please be more precise with your explanation. The overworld and compact machine dimension are different.

**Comment by bogointeractive** [comment]
@nzminecraftDOTcom I have said that a few times already. I have said my wither farms are in Compact Machines. 

>           I have zero mob farms per say. I do have wither kill chambers in a compact machine but those should not be causing an issue

**Comment by bogointeractive** [comment]
>           There is no way they can be spawning hundreds. The wither builder and the mob grinder are at full speed so there is maybe 10 in the kill area at a time. Plus they are not in the overworld. If they were it would an issue. But since they are a compact machine world there is no way for them to be the cause.

**Comment by Sunekaer** [comment]
Hey

So its only when going to that one RF dim? the dim might corrupted, and then you have to recreate it

**Comment by bogointeractive** [comment]
I have done that a few times. I was also thinking it was losing power as well. Neither has helped. it is still very buggy

**Comment by Sunekaer** [comment]
hmm then i dont know, ill have to said try make a issue on the RF dims site and they might be able to help you with what's wrong with you dim

**Comment by bogointeractive** [comment]
OK Cool
