### ISSUE TITLE
Server crashes ~30 Seconds After Being Open

### ISSUE THREAD

**Issue by Quxzcover** [Sunekaer/stoneBlock#712]
## Bug Report

After opening the server, the world will open and people will be able to join. after about 30 seconds regardless of if people have joined or not, the server will crash creating a crash report listed below. 
## Steps to Reproduce (for bugs)

1. Open "LaunchServer.bat"
2. Wait around 30 seconds of the server being open (after the server has fully loaded)
3. It crashes

## Logs

* Server Crash Report: https://paste.feed-the-beast.com/view/5b80ceb6

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Server
* Optifine Installed: Nope
* Shaders Enabled: Nope
* 12 Gb of ram enabled. Usually only takes half of my system resources.
* Game is being run on a seperate computer from where the server is run.

**Comment by Sunekaer** [comment]
Seems like a corrupted world, idk if we can do anything to fix it :/ could you try making a backup of the world and making a new one? just for testing

**Comment by 0-x-2-2** [comment]
Something is probably modifying the world async
