### ISSUE TITLE
Game crashes when loading up mods

### ISSUE THREAD

**Issue by Alex7692** [Sunekaer/stoneBlock#716]
## Bug Report

The game begins to crash during the mod-loading procedure (6/7 of loading completion, when trying to load JEI mod). Fails in multiple attempts of restarting the launcher.
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: - 
* Crash Log:  https://paste.feed-the-beast.com/view/552b11c

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Alex7692** [comment]
System: Mac Mojave
Launcher Version: 1.6.91
Forge Version: 14.23.5.2768

**Comment by Sunekaer** [comment]
log not working try uploading it again
