### ISSUE TITLE
Crops not growing with growth crystals

### ISSUE THREAD

**Issue by WaterPasta** [Sunekaer/stoneBlock#717]
## Bug Report

Some block spaces are inhibited from growing when being affected by growth crystals.

![2018-12-09_17 27 38](https://user-images.githubusercontent.com/45742920/49703902-10046a80-fbd9-11e8-8114-33aadfc8a370.png)

The farm consists of a vacuum hopper from Mob Grinding Utils, farmland (vanilla) or fertilized dirt (random things) (they seem to yield the same result), crops from Mystical Agriculture with mechanical users (Extra Utilities 2) above them, and about 64 growth crystal tier 3s (Tiny Progressions) in a 3x3 column in the middle. This also affects other crops.

When I tried recreating the bug in another world it did not appear to happen.

## Steps to Reproduce (for bugs)

1. Build the farm as described.
2. See if the bug occurs

## Logs

* Client/Server Log: [latest.log](https://github.com/Sunekaer/stoneBlock/files/2661092/latest.log)
* Crash Log: No crash occured

## Client Information

* Modpack Version: 1.0.30 and 1.0.31
* Server/LAN/Single Player: Single Player and LAN
* Optifine Installed: No
* Shaders Enabled: No

**Comment by SirioIlBe** [comment]
control the light level

**Comment by Sunekaer** [comment]
As sirioll said check your light levels

**Comment by Sunekaer** [comment]
If you have a acceleration wand you can use that on the growth block and see if they all growth up
