### ISSUE TITLE
Cannot complete Reactor task.

### ISSUE THREAD

**Issue by Tronif** [Sunekaer/stoneBlock#718]
## Bug Report
I created  all blocks required by Reactor task, but Reactor Task cannot complete.

## Steps to Reproduce (for bugs)
1.
2.

## Logs
* Client/Server Log: -
* Crash Log: -

## Client Information
* Modpack Version: 1.0.31
* Server/LAN/Single Player: Single Player
* Optifine Installed: -
* Shaders Enabled: -

**Comment by bogointeractive** [comment]
OK you might want to include information that the report asks for. Just saying it cannot complete is like saying I don't fart in church.

**Comment by Sunekaer** [comment]
Could you show us what items you have made?

**Comment by lurchj** [comment]
I also had this problem last night. I will post a picture of everything crafted tonight after work.

**Comment by lurchj** [comment]
Well got home and remade everything and it worked... Thanks anyways!
