### ISSUE TITLE
Server Crash while exploring RFTools Dimension

### ISSUE THREAD

**Issue by RuinPrime** [Sunekaer/stoneBlock#720]
Putting the crash report below.

Multiplayer server crashed while exploring an RFTools Dimension. The Dimension was 100% randomly generated so I can't supply info on dimlets used, but am willing to provide any extra info I do have that is not in the crash report. 

[crash-2018-12-11_04.21.23-server.txt](https://github.com/Sunekaer/stoneBlock/files/2667790/crash-2018-12-11_04.21.23-server.txt)

**Comment by Sunekaer** [comment]
Templated not used, log not linked via paste.feed-the-beast.com
