### ISSUE TITLE
Multiplayer Server Crash while exploring RFTools Dimension

### ISSUE THREAD

**Issue by RuinPrime** [Sunekaer/stoneBlock#721]
## Bug Report

Multiplayer server crashed while exploring an RFTools Dimension. The Dimension was 100% randomly generated so I can't supply info on dimlets used, but am willing to provide any extra info I do have that is not in the crash report.

## Steps to Reproduce (for bugs)

1. Generate a random RF Tools dimension
2. Travel/explore through it

## Logs

* Client/Server Log: https://paste.feed-the-beast.com/view/ba02a6d1 
* Crash Log: https://paste.feed-the-beast.com/view/ba02a6d1 

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Tommsy64** [comment]
Seems to be something interacting badly with the Sponge asynchronous lighting. Try disabling it. See https://github.com/SpongePowered/SpongeForge/issues/2405
