### ISSUE TITLE
Chunks reverting

### ISSUE THREAD

**Issue by llhilton** [Sunekaer/stoneBlock#722]
I am currently trying to dig out a massive, circular hole (around 99px radius). I've replaced the lava on top with clear glass, and I've started digging out the stone. There are two chunks that keep reverting back to stone with lava on top. I even cleared out one of them down to y=90, but it's shown back up again, complete with the lava on top. Is there anything I can do to stop this from reverting?

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Single Player
* Optifine Installed: Nope
* Shaders Enabled: Nope

ETA: there's no crash that happens, so I don't have any logs. It happens even within the same play session of having taken out the lava/stone.

**Comment by Tommsy64** [comment]
There is nothing we can really do without *some* logs. At the very least attach a log of a game during which the chunks revert.

The chunks that are reverting may be corrupted somehow, either in memory or on disk, preventing them from being saved or loaded properly. If it is the latter, than the chunk is simply regenerated as if it was never created in the first place.

(I recently saw a [youtuber](https://youtu.be/M_klBRhDj3U?t=12) experience a similar chunk-reverting issue)

**Comment by llhilton** [comment]
This is me logging in, digging out a few blocks and placing some clear glass in each of the troublesome chunks.
https://pastebin.com/Q4viPNQj

This is me logging back in, with the changes reverted.
https://pastebin.com/witjF4jt

Couldn't catch it reverting while I was logged in last time. It definitely's happening when I relog. Never dealt with a corrupted chunk before. But this is probably only the second or maybe third modpack I've ever actually completed the quest book for!

**Comment by Sunekaer** [comment]
i know there is a way to delete and regen chunks but how its done, i have to said i dont know
