### ISSUE TITLE
NPE strikes yet again this time with the Entangled Chalice

### ISSUE THREAD

**Issue by Algester** [Sunekaer/stoneBlock#723]
## Bug Report
Random NPE crash when transferring fluids in a "wireless" manner

## Steps to Reproduce (for bugs)
1. Set up an Entangled Chalice (Blood or XP as its a mob farm)
2. and just wait for it to happen

## Logs
* Client/Server Log: None
* Crash Log: https://pastebin.com/a2whVAKX

## Client Information
* Modpack Version: 1.0.31
* Server/LAN/Single Player: SP
* Optifine Installed: None
* Shaders Enabled: None

Mirrored Issue if needed for updates:
https://github.com/CyclopsMC/EvilCraft/issues/744#issuecomment-446515658

**Comment by Sunekaer** [comment]
Okay thank you
