### ISSUE TITLE
Translocators needs update to latest version.

### ISSUE THREAD

**Issue by Pherex44** [Sunekaer/stoneBlock#724]
## Bug Report
https://github.com/TheCBProject/Translocators/pull/52

## Steps to Reproduce (for bugs)
In current version,  Translocators v2.5.1.77
adding redstone to a fluid translocator will generate an array out of bounds exception.
this will crash the world and any future attempt to load it.

**This has been fixed by the mod creator! See bug report.**

**Comment by Pherex44** [comment]
the latest version also addresses the iron ingot causing crash.

**Comment by Sunekaer** [comment]
v2.5.1.77 is the newest

**Comment by Pherex44** [comment]
http://chickenbones.net/Pages/links.html

v2.5.1.77 is the latest "recommended"
And has the bugs

v2.5.1.79 is the latest "development"
and has the bug fixes.

**Comment by Sunekaer** [comment]
It has to be out on curse before i can update to it
