### ISSUE TITLE
autosifter fed with humanoid flesh

### ISSUE THREAD

**Issue by iopredman** [Sunekaer/stoneBlock#725]
---
name: Autosifter fed with humanoid flesh
about: Autosifter locked at 2.0 speed, can't be sped up further, never runs out.

---

## Bug Report
Right-clicking the autosifter with humanoid flesh locks it at 2.0 speed.

## Steps to Reproduce (for bugs)

1. Place autosifter with diamond mesh
2. Right click with humanoid flesh

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: Most recent
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
please report to ex nihilo creatio
