### ISSUE TITLE
Gravestones mod - TMG (To many graves)

### ISSUE THREAD

**Issue by 0Chameleon0** [Sunekaer/stoneBlock#727]
## Bug Report
We have stoneblock as a community server, we have had a couple of instances now where players have either teleported into the lava on the roof instead of returning to a portal, or suffocated in a wall (stone) from teleportation from a chance cube) and even falling through the void due to no bedrock, and the grave ended up in lava on the roof or no grave appeared. As a moderator I cant see moderator tools for the gravestone Mod, and wonder if it may be an option to switch this out with the TMG (to many graves) mod, that has OP tools for restoration and rollback for the player.

## Steps to Reproduce (for bugs)
Examples are teleportation from a chance cube into the stone, digging throught the floor (no bedroack) and falling into the void. Returning from another dimension via the portal and being placed in the lava on the roof instead of back to the original portal.

## Logs

* Client/Server Log: Due to the nature I dont have a log
* Crash Log: Due to the nature I dont have a log

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
im not changing any mods sorry
