### ISSUE TITLE
Cannot recharge Cyclic Charms - Recipe issue

### ISSUE THREAD

**Issue by Gunner76th** [Sunekaer/stoneBlock#728]
## Bug Report

In the modpack Cyclic adds a few charms to the game such as Air and Fire. In JEI it shows that you can insert the charms into the Fluid Tank from Ender IO, and using the Solidified Experience you can recharge the Charms. However the problem is that for some reason the Tank does not let you insert the charms into it. ***Note*** After looking at the recipe, it appears that the custom recipe is instead of using Fuzzy crafting, it is set to only allow you to recharge the charm if it has a durability of 4/16 and Mending enchantment applied to it. After looking at the other charm recipes, I am seeing that each of them also has Mending applied in the recipe. 

![image](https://user-images.githubusercontent.com/5566872/49918336-b61dd200-fe70-11e8-91cf-732e2a7e64d7.png)

## Steps to Reproduce (for bugs)

1. Acquire any charm from Cyclic (I have tested this with both Air and Fire so far as those are the only ones i have). 
![image](https://user-images.githubusercontent.com/5566872/49918304-8ec70500-fe70-11e8-8e2d-4f9c196329c7.png)

2. Craft the Fluid Tank from Ender IO
![image](https://user-images.githubusercontent.com/5566872/49918313-9686a980-fe70-11e8-9b56-ba983ac44b5e.png)

3. Take Solidified Experience from Actually Additions and insert it into Fluid Tank to create Liquid XP
![image](https://user-images.githubusercontent.com/5566872/49918323-a0101180-fe70-11e8-8430-bf7b204bd15c.png)

4. Attempt to insert the Cyclic Charm from Step 1 into Fluid Tank to recharge it. 
![image](https://user-images.githubusercontent.com/5566872/49918327-a7cfb600-fe70-11e8-879b-d2de30a6b3ef.png)

## Logs

* Client/Server Log: N/A as this is not a logged bug
* Crash Log: N/A as this is not a crash report

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Server MP
* Optifine Installed: N/A
* Shaders Enabled: N/A

**Comment by Sunekaer** [comment]
You need mending on it for it to work

**Comment by Gunner76th** [comment]
So this is an intentional crafting change from the default,  and not a
recipe goof.  Gotcha
