### ISSUE TITLE
This app can't run on your PC.

### ISSUE THREAD

**Issue by CoryJS** [Sunekaer/stoneBlock#730]
## Bug Report

When I try to load the modpack using the Twitch app, it pops up with the message shown in the screenshot. The "this app can't run on your PC." However, I'd really, really, really like to play so as much help as possible would be appreciated.

## Steps to Reproduce (for bugs)

1. https://gyazo.com/90698db16c1599689e09b6df259bbe6c
2. 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.12.2
* Server/LAN/Single Player: N/A
* Optifine Installed: N/A
* Shaders Enabled: N/A

**Comment by Sunekaer** [comment]
twitch launcher problem, contact twitch
