### ISSUE TITLE
you can't craft Arrow of Withering from EnderIO due to lacking Ender Zoo and therefore can't craft the withering enchant

### ISSUE THREAD

**Issue by Algester** [Sunekaer/stoneBlock#733]
## Bug Report
well its more of a "missing recipe" than anything as since you cant craft the arrows you cant craft the withering enchant from EnderIO.

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Single Player
* Optifine Installed: None
* Shaders Enabled: None

**Comment by Sunekaer** [comment]
i dont see the arrow your talking about

**Comment by Algester** [comment]
the withering enchant from EIO is available on JEI so I think there's something there but its "uncraftable"
