### ISSUE TITLE
End not rendering and then crashing.

### ISSUE THREAD

**Issue by DracoClaw** [Sunekaer/stoneBlock#734]
## Crash Report
So um... I was in the end, doing the fight, and like everything was darker than usual, but i thought whatever. but then, the ground disappeared, and there were cubes of fence posts, ans also saplings?!?! I'm playing Stoneblock version 1.0.31 and I've added Universal Remote mod by orbwoi. https://pastebin.com/AVf6Qytd

**Comment by nzminecraftDOTcom** [comment]
Try running the mod pack as it was sent out by the creator, and report back to see how it works. A fresh install will probably be needed.

**Comment by Sunekaer** [comment]
most be the mod you added, because that have neverhappen to anyone else with this pack that i know off

**Comment by DracoClaw** [comment]
how could a mod that adds one item be the issue?
