### ISSUE TITLE
Actually Additions issue. phantom breakers

### ISSUE THREAD

**Issue by versedplays** [Sunekaer/stoneBlock#735]
## Steps to Reproduce (for bugs)

1. no steps required broken by default
2.

## Logs

* Client/Server Log:
* Crash Log:n/a

## Client Information

* Modpack Version: latest
* Server/LAN/Single Player: single player
* Optifine Installed:no
* Shaders Enabled:no

**Comment by alpal01** [comment]
not very detailed

**Comment by Sunekaer** [comment]
not enough info
