### ISSUE TITLE
HashMap HashIterator crash

### ISSUE THREAD

**Issue by UldisAlksnis** [Sunekaer/stoneBlock#736]
## Bug Report

Server starts, can play on it for some time, then crashes.
Crashes became more often with more players on the server.
(Note this happened BEFORE spongeforge was added to it, i only added it just now and it does not affect the issue)

EDIT:
RAM never reaches its limit(Max bein 6) Used about 2-3gb, after longer time 4-4.5
CPU is 3.8GHZ
## Logs

* Client/Server Log: https://pastebin.com/80epfcwv  (couldnt copy whole log due to pastebin limits)
* Crash Log: https://pastebin.com/n9bFaC5F

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Server
* Optifine Installed: Default
* Shaders Enabled: Default

**Comment by Sunekaer** [comment]
answered by nz
