### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by zeebo30** [Sunekaer/stoneBlock#737]
## Bug Report

Game is crashing due to the Mob Masher from Mob Grinding Utilities

## Steps to Reproduce (for bugs)

Not sure how to reliably reproduce as I've not seen others have the issue. Game runs fine without Mob Masher in world, but if I put the mob masher down and put looting upgrades in it and have it kill a mob that game crashes to desktop. Attempting to reload the world causes the game to crash again. Only fix has been to remove the Mob Masher from outside the game and reload the world.

Edit: I did more thorough testing and it seems the mob masher works completely fine all the way up to 10 looting upgrades. At 9 it works fine, at 10 it crashes as soon as the mob dies

**Comment by Sunekaer** [comment]
no crash log
