### ISSUE TITLE
refined storage

### ISSUE THREAD

**Issue by Dalurion** [Sunekaer/stoneBlock#739]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by Sunekaer** [comment]
no info given

**Comment by Dalurion** [comment]
Refined storage and ProjectE
when trying to dupliccate a 64K storage disk within an energy condenser you cant use the produced disk within a disk drive

step 1: have an energy condenser MK1/2
step 2:  have the wanted item ( 64K storage disk ) in the "to duplicate slot"
step 3: fill some EMC in the energy condenser
step 4: try to insert produced storage disks in a disk drive from refined storage

modpack version: 1.0.31
single player
no optifine
no shaders

**Comment by Sunekaer** [comment]
you cant dupe items with items in

**Comment by Dalurion** [comment]
was done with empty disks
