### ISSUE TITLE
Crashs on Load

### ISSUE THREAD

**Issue by bogointeractive** [Sunekaer/stoneBlock#744]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log: https://paste.ee/p/bt9TR

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Is this still a problem?

**Comment by bogointeractive** [comment]
Yes. I think it is one of the mods. I am thinking it might be Flux Networks but not 100%

**Comment by Sunekaer** [comment]
try 1.0.32 i update flux in that one

**Comment by bogointeractive** [comment]
OK did you update the latest mods all the way around?

**Comment by Sunekaer** [comment]
No because i havent had time to see how much that would break

**Comment by bogointeractive** [comment]
OK I have updated and some is still there.

**Comment by bogointeractive** [comment]
I will see if I can get it to Copy and Paste

**Comment by bogointeractive** [comment]
OK it is not crashing the instance but I have the flux plugs setup correctly and it acts like there is something gulping up the power to where nothing else is getting power. I think it is more Flux problem but again I am not sure

**Comment by bogointeractive** [comment]
OK I am still running into the problem that AE2 is not working with power. My nano bot is not keeping power. Nothing is holding power.

**Comment by bogointeractive** [comment]
OK I have a few updates, and things are not looking correctly
![2018-12-28_13 42 26](https://user-images.githubusercontent.com/28167934/50526269-99a3ab80-0aa6-11e9-98a1-575bc1326aba.png)
![2018-12-28_13 39 35](https://user-images.githubusercontent.com/28167934/50526270-99a3ab80-0aa6-11e9-918e-1cfa9dcda142.png)
![2018-12-28_13 39 58](https://user-images.githubusercontent.com/28167934/50526271-99a3ab80-0aa6-11e9-8c6c-a5d3ab715857.png)
![2018-12-28_13 40 23](https://user-images.githubusercontent.com/28167934/50526272-99a3ab80-0aa6-11e9-86f7-86535b14bc33.png)
![2018-12-28_13 40 58](https://user-images.githubusercontent.com/28167934/50526273-99a3ab80-0aa6-11e9-8f45-a64f531da2cf.png)
![2018-12-28_13 41 44](https://user-images.githubusercontent.com/28167934/50526275-99a3ab80-0aa6-11e9-8dd5-f3282cc1cd9b.png)

the energy ball is showing correctly. The point is off I believe.  The plug is not correct I believe.  The plug on the reactor is showing correctly. The point on my nano beacon is correct. The controller is not working correctly. I think there has to be a bug someplace. Having 4.39 Billion RF/t cant be right at all.

**Comment by Sunekaer** [comment]
Could you try a look on th Flux network issue tracker if anyone else has this issue, and maybe ask for help there, because i dont know whats going on there

**Comment by bogointeractive** [comment]
I dont either. It has to be the latest mod but again I dont know.
