### ISSUE TITLE
Server crashes due to tickspeed

### ISSUE THREAD

**Issue by TheLastLaugh** [Sunekaer/stoneBlock#745]
## Bug Report

It's a little hard to explain, but the server has been running fine for the last week or so, however recently it's started to slow down. It's gotten to a point where the server finishes loading, then after some time (say a minute or two) the server says that it took over a minute to do 1 tick and is treating it like a crash. I'm not too sure if I explained it well, but you'll see in the log

## Steps to Reproduce (for bugs)

1. Uhhhh.... I guess have the server and game running on a single pc
2. Play stoneblock for a while... Not sure what else

## Logs

* Client/Server Log: At the time of posting this, paste.feed-the-beast.com isn't working. I'll try tomorrow
* Crash Log: "    "

## Client Information

* Modpack Version: Stoneblock version 1.0.31
* Server/LAN/Single Player: Server
* Optifine Installed: False
* Shaders Enabled: False

**Comment by Sunekaer** [comment]
no log, use gist.github.com if paste.feed-the-beast.com isn't working
