### ISSUE TITLE
Tier 3 Growth Crystal from Tiny Progressions Crash

### ISSUE THREAD

**Issue by HawkEyeZ99** [Sunekaer/stoneBlock#746]
## Bug Report

When you place a tier 3 growth crystal from Tiny Progressions, your client crashes.

## Steps to Reproduce (for bugs)

1. Place tier 3 growth crystal

## Logs

* Client/Server Log: https://drive.google.com/file/d/1-_2GJgMvhUgcrTSI_fXQE-yxTYXSnDDB/view?usp=sharing
* Crash Log: https://drive.google.com/file/d/1W6Q3OYfJVGkPxDxm4nLWDMTjFlLBwZyc/view?usp=sharing

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
I can not recreate this problem, could you try placing it another place, or try in a new world

**Comment by HawkEyeZ99** [comment]
> I can not recreate this problem, could you try placing it another place, or try in a new world

Okay well I went to try it again after the recent update and it hasn't happened again either in the over world or mining dimension (first encounter). So either it was fixed in the update or I don't know what happened. I tried in my current world and a new one. I guess if I find it again I'll let you know.

**Comment by Sunekaer** [comment]
Thanks
