### ISSUE TITLE
Backup Error

### ISSUE THREAD

**Issue by AmmiraglioKrell** [Sunekaer/stoneBlock#747]
Hi Sunekaer,
I encountered a problem about Stoneblock. I don't know if it's the right place to contact you but I have not found anything else. In practice, whenever the modpack makes a backup, through a normal world (not a server), it displays a message about "Java Backup Failed - Java Null - Java.io". I thought it was a temporary problem, maybe of my pc or java, but the problem persists for a while. I know very well that without backups in the worlds it doesn't go on. Maybe for a Blackout or for a Chunk Discountinuity, which I'm forced to take an old backup but there isn't for this problem.
For the rest, the Modpack is really well done. I've not installed other mods like optifine, shaders or change version. I hope you can give an answer as soon as possible, before the irreparable happens.
Dear Regards,
Ammiraglio_Krell

**Comment by Sunekaer** [comment]
Might be a FTB Util bug we are running a older version

**Comment by Sunekaer** [comment]
try 1.0.32 if that doesnt fix it try https://github.com/LatvianModder/FTBUtilities/issues

**Comment by AmmiraglioKrell** [comment]
Thank you so much. Now backups works.
