### ISSUE TITLE
Can't craft Obsidian OIOT because there is no recipe for AA Obsidian Sword.

### ISSUE THREAD

**Issue by IMarvinTPA** [Sunekaer/stoneBlock#748]
## Bug Report
Crafting an Obsidian Sword makes a sword that won't work in the Actually Addition recipe for the Obsidian All-In-One-Tool.

1.  Craft one of each Obsidian tool and Obsidian Sword.
2.  Try to use them to make the Obsidian AIOT.
3.  Feel sad.

I was able to do it in 1.0.28 but not in 1.0.31. It seems the overlapping recipe was fixed by removing the Actually Additions one.

* Modpack Version:  1.0.31
* Server/LAN/Single Player:  SP
* Optifine Installed:  No
* Shaders Enabled:  No

**Comment by Sunekaer** [comment]
1.0.32
