### ISSUE TITLE
Array out of bounds Error

### ISSUE THREAD

**Issue by LunarChimera** [Sunekaer/stoneBlock#749]
## Bug Report
I crash after trying to put (via shift click) apples into a culinary generator... The apple is in the 5th toolbar slot.

## Steps to Reproduce (for bugs)
1. Put apples form 5th toolbar slot into culinary generator

## Logs
Report on paste bin because the provided link was giving a 522 connection timed out error
* Client/Server Log:
Can't send full log file from twitch ...paste bin limit...I have the file if it is needed and there is a better way to provide it
* Crash Log:
https://pastebin.com/3hw1PX3s
Report on paste bin because the provided link was giving a 522 connection timed out error

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Sunekaer** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/issues/226
