### ISSUE TITLE
Hatchery Eggs Unable to be converted into Mineraft eggs

### ISSUE THREAD

**Issue by jsliu013** [Sunekaer/stoneBlock#751]
## Bug Report

Available recipe for converting Hatchery mod eggs to Minecraft eggs does not work. (no output)

## Steps to Reproduce (for bugs)

1. Place Hatchery Egg in Crafting Screen. 

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Single Player
* Optifine Installed: False
* Shaders Enabled: False

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/50490671-9d83ef00-0a0e-11e9-9c43-527d15ef7c43.png)
Works fine for me

**Comment by jsliu013** [comment]
I still can't. Is it a config menu thing or perhaps it was fixed in dev?

**Comment by Sunekaer** [comment]
I changed nothing, i just loaded the pack, and created a new world and took an egg and put it in my crafting grid

**Comment by AWDoBaun** [comment]
Perhaps it is a mod interaction, or somehow a pack setting. I see this issue in the Stoneblock packs. The recipe shows up in JEI but doe not work in any crafting interface I have access to.
