### ISSUE TITLE
game freeze adding charcoal block to furnace generator.

### ISSUE THREAD

**Issue by Timnus** [Sunekaer/stoneBlock#752]
setup a tier1 cobblestone generator. set a simple drawer inventory on top of it. have a node transfer (items) go out of the side into a auto-hammer. add 2 diamond hammers inside it. have node transfer (items) go out another side into side of auto sieve with diamond sieve.  have item node transfer go out of side into a small crate.  create 2 furnace generators and place one on top of the auto hammer and one on top of the auto sieve.  create 20 charcoal blocks. place 10 in each furnace generator.  create 2 full stack of charcoal block. try to add to partial stack in furnace generator. game freezes.  reboot game.  try other generator to add block of charcoal.  it takes from inv and freezes game. force reboot. chance of charcoal block gone but not added to furnace.  only work around i have found is to use a vanilla hopper going into the side of the furnace generator to transfer into the furnace generator.. 

    Modpack Version: 1.0.31
    Server/LAN/Single Player: Single Player
    Optifine Installed: False
    Shaders Enabled: False

cannot make link for logs as website keeps giving 552 error for me
![ftbweberror](https://user-images.githubusercontent.com/27913772/50304410-7bf69680-0455-11e9-8767-adbab43d8405.JPG)
![ftbweberror](https://user-images.githubusercontent.com/27913772/50304422-80bb4a80-0455-11e9-9805-b85a2fad5716.JPG)

[2018-12-20-Logs.zip](https://github.com/Sunekaer/stoneBlock/files/2708375/2018-12-20-Logs.zip)

**Comment by Sunekaer** [comment]
Okay, i have informed FTB that the site doesnt work, please use gist.github.com instead in the mean time
