### ISSUE TITLE
Items on Floor are cleared/disappearing at random intervals

### ISSUE THREAD

**Issue by duck-mon** [Sunekaer/stoneBlock#754]
## Bug Report

Items will randomly disappear or clear regardless of item life timer of 5 mins
## Steps to Reproduce (for bugs)

1. Noticeable in the aroma dimension and after creeper explosions/chance blocks
2. It's as if something is doing /killentity at an interval

#583 is similar to what I am experiencing.
## Logs

* Client/Server Log: https://pastebin.com/b6VZd2by
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Single Player
* Optifine Installed:
* Shaders Enabled:

**Comment by Sunekaer** [comment]
Could you try quickly after the items "disappear" relog, because they might just be invisible

**Comment by Sunekaer** [comment]
do to this issue: https://github.com/iChun/iChunUtil/issues/178

**Comment by duck-mon** [comment]
Nope, the items just straight up delete themselves. I'm not sure if that's the functionality of the mining dimension but it clears w/o showing on logs.

**Comment by duck-mon** [comment]
[Desktop 2018.12.28 - 03.49.31.10.zip](https://github.com/Sunekaer/stoneBlock/files/2714784/Desktop.2018.12.28.-.03.49.31.10.zip)

**Comment by Sunekaer** [comment]
Please use gist.github.com or paste.feed-the-beast.com for the log and link it here

**Comment by amberstine** [comment]
Are there maybe too many items on the floor? I think that minecraft might have a limit on the number of dropped items that can appear at a time, so they may be deleting themselves in order to make room for other stuff. 
I have also noticed that sometimes dropped items can glitch through the floor, so that could also be what is happening.
