### ISSUE TITLE
Update reborn storage

### ISSUE THREAD

**Issue by djoey123** [Sunekaer/stoneBlock#757]
Hi,

Rebornstorage have already got 3 new updates 1 improves the crafting speed + lagg of the server a lot, maybe it is an good idea to update rebornstorage in the modpack

Logs

    Client/Server Log: Nope
    Crash Log: nope

Client Information

    Modpack Version: 1.0.31
    Server/LAN/Single Player: nope
    Optifine Installed: nope
    Shaders Enabled: nope

**Comment by Sunekaer** [comment]
1.0.33
