### ISSUE TITLE
Bug with /dank/null and Mekanism

### ISSUE THREAD

**Issue by elmasbv** [Sunekaer/stoneBlock#758]
## Bug Report
When I add the Wind Generators from Mekanism into the /dunk/null/ it crashes the game.

## Steps to Reproduce (for bugs)
Add some Wind Generators into the /dank/null/ MK VI
After you close the inventory of the /dank/null/ it freezes the game and crashes it.

## Logs
This is the crash-log after i just put the wind generator into the /dank/null/ - https://pastebin.com/0yS8zw12

And this is the crash log after i tried to start the client again, it's not letting me in the save anymore - https://pastebin.com/EtDFtqaz

* The paste ftb link what you gave me above it wasn't working, so i used pastebin.

## Client Information
* Modpack Version: 1.0.32
* Server/LAN/Single Player: Single Player (Sometimes playing in LAN with a friend)
* Optifine Installed: No
* Shaders Enabled: No

- P.S : I Added Inventory Tweaks because after i finish a stack of my hand it doesn't refill the slot with other stack of the same item and is a bit annoying, or I don't know how to figure out to enable this thing without Inventory Tweaks.

**Comment by elmasbv** [comment]
Another bug, i include it here , the Wind Generator's texture from Mekanism is not loading... i just reinstalled all the modpack and i can't solve it...

**Comment by Sunekaer** [comment]
Have you reported this to the mod author?
The texture issue i cant recreate, please reinstall your pack if its still happening
