### ISSUE TITLE
Disconnected from server when you try to "move items" from JEI to Refined Storage Crafting grid

### ISSUE THREAD

**Issue by xavizus** [Sunekaer/stoneBlock#762]
## Bug Report
When the player try use JEI to automatic fill Refined Storage Crafting grid for the specific recipe Greenhouse Glass. The player get disconnected with the following error message:
_**Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes**_

Edit:
It seems to only effect Refined Storage Crafting grid. Nothing happens if I use a crafting table with the ingredients in the inventory.

## Steps to Reproduce (for bugs)

1. Open Refined Storage Crafting grid
2. Search for Greenhouse Glass
3. Left click the Greenhouse Glass
4. Press the +-icon (Move Items)
5. Magic
6. You get disconnected and get the following error message:
Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

## Logs

* Server Log:
[17:22:41] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Xavizus lost connection: Disconnected
[17:22:41] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Xavizus left the game

*Client Logs
[Link to Client Logs @pastebin](https://pastebin.com/x20Z1a6M)
* Crash Log:

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Server (Have not tested this in singelplayer)
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Have you reported this to Refind storage?

**Comment by xavizus** [comment]
No, I've not.

Would you like me to do it?

**Comment by Sunekaer** [comment]
Yes, he cant fix it, if it doesnt get reported to him

**Comment by xavizus** [comment]
These seems to be already an issue for that problem raoulvdberge/refinedstorage#1790
