### ISSUE TITLE
Accidentally included CTMLib 1.7.10?

### ISSUE THREAD

**Issue by Xetaxheb** [Sunekaer/stoneBlock#763]
Oops, lol

https://minecraft.curseforge.com/projects/ctmlib
CTMLib-MC1.7.10-1.4.1.5.jar

**Comment by Sunekaer** [comment]
In server files?

**Comment by Xetaxheb** [comment]
No, in the main modpack. It shouldn't be able to load and therefore do no damage but pointless to include (it's a 1.7.10 library) 

 https://minecraft.curseforge.com/projects/stoneblock/relations/dependencies?page=3


CTMLib  by tterrag1098
538,663 Jan 3, 2016
Contains the core code Chisel 2 uses for CTM and other texture types. Shipped with Chisel 2.

**Comment by Xetaxheb** [comment]
Looking around a bit, this might be an issue with https://minecraft.curseforge.com/projects/shear-madness/files/2629244 shear madness listing it as a required dependency for the 1.12.x versions, which it couldn't possibly be.
