### ISSUE TITLE
Suggestion Adding More Quests

### ISSUE THREAD

**Issue by Prelart** [Sunekaer/stoneBlock#766]
Hi!

The modpack is absolutly amazing!! Really! Great Job!!!

I would like to make a suggestion!

**More Quests line! We need more quests!** 

Going trhu more mods!
Keep the good work! tbh is the greatest modpack i played since a while. Totally different of what i have played before!

I Enjoy the pack!

Cheers

**Comment by amberstine** [comment]
I think this is actually an amazing idea! I love stoneblock over skyfactory because it explores more of the mods. I think adding some of the cooking for blockheads, more of the botania, and some of the electronic stuff would be really cool.

**Comment by Sunekaer** [comment]
There wont be done anymore to this pack, if anything it would only bug fixes
