### ISSUE TITLE
io.netty.channel.abstractchannel$annotatedconnectexception connection refused no further information

### ISSUE THREAD

**Issue by rotellini9809** [Sunekaer/stoneBlock#768]
## Steps to Reproduce (for bugs)

1.set the server
2.try to connect

## Logs

* Client/Server Log:
* Crash Log:io.netty.channel.abstractchannel$annotatedconnectexception connection refused no further information

## Client Information

* Modpack Version:StoneBlock-1.0.33
* Server/LAN/Single Player:server
* Optifine Installed:no
* Shaders Enabled:no

hello guys i'm not a programmer so if i write something wrong forgive me,i'm trying to set up a server for server for this modpack but i always have the same problem,the server seem to work fine but when i try to connect i have this error: io.netty.channel.abstractchannel$annotatedconnectexception connection refused no further information. i try installing it different time on an other computer restarting the pc but nothing seem to work

**Comment by Gunner76th** [comment]
In order to be able to help, you will need to upload the entire server log file, not just a snippet that you think might be what people need. Second, also upload your client's log file as there might be information there as well. 

Is it doing this on every connection attempt? Have you tried to connect, gotten that message, and then immediately tried to connect again? On the server that I maintain for IHOC the first time players attempt to connect they get an instant DC, but when they try a second time it succeeds.

**Comment by rotellini9809** [comment]
ok so i will upload the log file of the server,but where are the client log?
I've just noticed to have the same issue whit a normal 1.12.2 server in my lan,i tried on an other computer whit an other wi-fi but same issue whit the stoneblock server in lan.
It do it on every connection attempt,and i try to connect for three times consecutively but nothing
[log server.txt](https://github.com/Sunekaer/stoneBlock/files/2725451/log.server.txt)
i know that this problem isn't really close related whit the pack but please help me i really wnat to play this pack and also my friend we are in five and we can't figure aut what to do,i try a lot of things write on internet about this error but nothing seem to work and some suggestion are too complicated and we don't understand them.

**Comment by Gunner76th** [comment]
Your log files are in a similar location for the client as they are for the server. Goto the directory where you tell Twitch (or whaterver loader you are using) to install modpacks, find the folder for the modpack in question and you will see a folder names "logs" 

![image](https://user-images.githubusercontent.com/5566872/50664587-94999d00-0f7b-11e9-9412-b9acf23ab51e.png)

In my example, I have it set to store modepacks in L:\Minecraft\Instances\  so the location for the modpack's log folder is L:\Minecraft\Instances\StoneBlock (1)\logs

If you are using Twitch, you can find out where your modpacks are stored from the Settings > Minecraft section 

![image](https://user-images.githubusercontent.com/5566872/50664657-dcb8bf80-0f7b-11e9-8478-b2b362a9addd.png)

**Comment by rotellini9809** [comment]
*is

**Comment by Sunekaer** [comment]
Make sure your firewall/Antivirus isnt blocking

**Comment by Opme19** [comment]
I was suffering from this issue too, here I found a [guide](https://winerrorfixer.com/io-netty-channel-abstractchannelannotatedconnectexception-connection-refused-no-further-information/) on the Internet.
