### ISSUE TITLE
started crashing at startup after first try

### ISSUE THREAD

**Issue by joshuailssml** [Sunekaer/stoneBlock#769]
Played it for few hours, after relaunching keeps crashing before even opening the game
Tried changing launch settings, repaired the modpack, still crashing

Here is the error: https://pastebin.com/mTgu1ZbN

**Comment by amberstine** [comment]
have you tried allotting more RAM to the loading of the modpack? I had it crashing while loading. I'm not sure what exactly is happening. Is it crashing before the loading screen even comes up, or is it during the loading screen, or does it crash after the loading screen? Have you tried deleting and redownloading?

**Comment by Gunner76th** [comment]
@joshuailssml please post your FULL client latest.log file as well as your crash report. The snippet you posted is not of any real use. You can either upload it as a txt file or use gist and paste it there.

**Comment by Sunekaer** [comment]
no full log
