### ISSUE TITLE
oreexcavation/extra utils crashed server

### ISSUE THREAD

**Issue by TacticalUniverse** [Sunekaer/stoneBlock#77]
## Bug Report
 When one of our players was playing on our stone block server, he did something with Ore excavation and it crashed the whole server.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: Just have a crash report
* Crash Log: https://gist.github.com/TacticalUniverse/cfda2001d758d996c992c4885441c718

## Client Information

* Modpack Version:
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by prototype-saber** [comment]
Your log said that a compressed block form extra utilities 2 mined by ore excavation will lead to crash.
You can put those compressed blocks into the black list of ore excavation.

Ps: this bug i had seen in other modpack but not in StoneBlock

**Comment by TacticalUniverse** [comment]
Thanks
