### ISSUE TITLE
Cyclic Building Scepter gui not showing up due to conflict with InGameInfo 

### ISSUE THREAD

**Issue by Reignofmagic** [Sunekaer/stoneBlock#771]
## Bug Report
This isn't a big thing, but it is vaguely annoying. 

Cyclic Builder wand mode switch gui doesn't show up due to a conflict with the following mod installed: InGameInfoXML-1.12.2-2.8.2.94-universal.jar

My guess this is due to various overlays conflicting with each other. 

How I identified this was remove half the modlist until I narrowed it down to the g-m mod starting letters. In the I's section of the modlist and read the name, popped that out and that stopped the issue. 

 
It has been just over 2 years since I used github frequently, so I forget how to ping other people (namely the ingame info and cyclic devs). 

## Steps to Reproduce (for bugs)
Have cyclic and InGameInfoXML installed at the same time. 

## Logs

* Client/Server Log: https://paste.feed-the-beast.com/view/6a95c723

## Client Information

* Modpack Version: StoneBlock 1.0.28 (According to server MOTD from when I downloaded the pack)
* Server/LAN/Single Player: Both
* Optifine Installed: Yes
* Shaders Enabled: No (unless it is on by default)

**Comment by Sunekaer** [comment]
Conflict how? are they overlapping?

**Comment by Reignofmagic** [comment]
In the video from the developer you can see what the gui looks like (Upper left hand corner in his video) https://www.youtube.com/watch?v=oA2niaFSMxw

And here is a screenshot showing my screen (It is in the lower left as that is its default). The weird part is that a portion of the gui is there (What block is currently selected by the wand), but the rest of the gui surrounding it is missing meaning you can still use it/switch to it, but you have to guess/experiment to see which mode you are currently in. 

![2019-01-16_21 56 11](https://user-images.githubusercontent.com/10967885/51294686-b95d2e00-19d9-11e9-836e-23ba1a2149bb.png)


If I reboot the modpack with the ingameinfo mod disabled the rest of the Cyclic Builder gui appears and functions like normal.

**Comment by Sunekaer** [comment]
i have no way of moving Cyclic Building Scepter gui
