### ISSUE TITLE
Nether Star Seed not growing

### ISSUE THREAD

**Issue by LuckyDarms** [Sunekaer/stoneBlock#772]
Title. And yes, there is a crux underneath. Seed on tilled dirt, crux underneath as stated. Worms for keeping dirt moist. Mystical fertilizer nor any other method of acceleration works either. I noticed the last person who opened a ticket for this didn't even get a chance to respond to statements of "it worked for me", hopefully that doesn't happen here.

**Comment by Jo-Mamma75** [comment]
I had issues with this as well.  Mine was due to light levels.
