### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Xorei** [Sunekaer/stoneBlock#776]
## Bug Report

I have a 6gb server and I put 7gb to run the client but even with that my game will still lag out and white screen making me have to force close the game and it goes to the launcher saying an unexpected error has occurred. Im not much of a programmer or anything like that so i don't know where to look for error reports. its crashed twice when I've gone to put in speed upgrades. I don't think its a server problem the people who run them have checked and said it wasn't. I don't think its my computer because its only stoneblock that crashes and lags. I put a screen shot of what it does before it crashes. I also don't know if its just cause how many items are spawning/de-spawning but I have watch lots of youtube and what mine is doing is nothing compared to some of their stuff.
## Steps to Reproduce (for bugs)

[1.]
![2019-01-08](https://user-images.githubusercontent.com/46503446/50859837-ab603b00-1351-11e9-8233-f89a59cd03fb.png)

[2.]

## Logs

* Client/Server Log: ?
* Crash Log: ?

## Client Information

* Modpack Version: 1.12.2
* Server/LAN/Single Player: 147.135.117.103:25565
* Optifine Installed: ?
* Shaders Enabled: ?

**Comment by Sunekaer** [comment]
Caused by same bug as https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/31
