### ISSUE TITLE
Modpack Fails to work every time it is updated, have to keeps restarting.

### ISSUE THREAD

**Issue by amberstine** [Sunekaer/stoneBlock#777]
## Bug Report

So I have only had this mod pack for a couple months, but I have had to start a new game 3 different times. Every time the pack updates, something breaks, and it will not load at all, I have tried waiting and the loading page does not come up. I have to reinstall it and start a new game, I cant make any progress like this! It is very frustrating. 
Redownloading always fixes it, but I do not want to restart for the 4th time. 

## Steps to Reproduce (for bugs)

1. Update game to newest version after update is released.
2. Press play in Twitch desktop app
3. when Minecraft launcher comes up, press play.
4. Wait 5-10 minutes for loading screen to com up (It doesn't.) 
5. Open task manager and manually close Minecraft under proprieties because it does not show up in running applications.

## Logs

* Client/Server Log:
* Crash Log: (No crash logs, it doesn't crash, it simply does not open or load)

## Client Information

* Modpack Version: 1.0.33 (Also happened with 1.0.32 and 1.0.31)
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: I don't think so. I don't have anything extra and I don't mess with any of the mods.

**Comment by Gunner76th** [comment]
Without any log files uploaded there is no support the author is able to give. Please upload your Latest/log file (you can copy it to gist and then link that here). Also check for possible PID files in the main folder of the modpack. PID files indicate JAVA issues preventing it from loading. 

Also how much RAM are you allocating to the modpack, how much RAM do you have installed, what OS are you using (Windows, Linux, MAC), what version of JAVA do you have installed? These are all questions that need answered in order for you to receive any sort of assistance. What you have posted is in short the same as going to a video store and asking "Do you have that movie by that guy?"

As a community admin and player of the modpack myself, just following your steps to reproduce above, I cannot personally reproduce your issue.

**Comment by Gunner76th** [comment]
Go to where that specific modpack is stored on your computer.  Look for a
folder called "logs" Inside that folder is a file called latest.log Copy
the contents of that file to gist and share the link here . I assure you if
you are clicking launch it is generating a log file.

**Comment by Gunner76th** [comment]
To find out which Java you have,  in windows click on the Cortana box and
enter the word command and launch the one with the icon that looks like a
black box with c: in it.  On the new screen that opens run the following:
java -version

**Comment by Gunner76th** [comment]
![image](https://user-images.githubusercontent.com/5566872/51086047-9c8dd580-170f-11e9-9bd0-0c39ae214487.png)
Please reference the image above to locate where your modpacks are stored. Then go to that folder, look for the folder names "instances" From there find the folder for Stoneblock, and then the "logs" and "crash--reports" folders. In the "logs" folder is where you will find latest.log, and in "crash-reports" you will find any crash reports for your pack.
