### ISSUE TITLE
Particle bug?

### ISSUE THREAD

**Issue by Zittla** [Sunekaer/stoneBlock#778]
## Bug Report
Spawned a Wither boss at my base he was unkillable and then first it was fine but after a while when i try login to the EMB server on stoneblock 2, i keep crashing the server every time and the wither now has particle effects for some wierd reason im not sure how this works but i think it was to do with the particles effects.
https://i.imgur.com/Uytavwc.png (this is what it looks like when i log in and then it just say waiting for server the entire time until crash).
One of the admins said that this happened to them earlyer aswell, and the only way to fix it was delete the player data just hope this is not the case i kinda dont wanna re start my entire base

## Steps to Reproduce (for bugs)
Not even sure how this happend but, this issue was on stoneblock 1 wich also caused the server to crash with those particle affects in some wierd way.
If i go to close to someone it spreads to them and they keep crashing the server if they login aswell

## Logs
https://paste.feed-the-beast.com/view/7f716ea1
client log not server log

## Client Information

* Modpack Version: 1.1.1-1.12.2.zip(beta)(current)
* Server EMB network
* Ram; 8 gig allocated to my pc client
* Cpu of my pc Client: AMD Ryzen 7 2700X Prosessor
Socket-AM4, 8-Core, 16-Thread, 4.35GHz, 20MB cache, 105W
* Optifine Installed: default i guess
* Shaders Enabled: dident change anything in settings so default i guess

**Comment by Sunekaer** [comment]
![5o9dnma7](https://user-images.githubusercontent.com/18720460/51086880-1f348600-174c-11e9-81f9-3c42b5db521a.png)
Works just fine for me
Most be something on the server your playing on

**Comment by Sunekaer** [comment]
And this git is for STONEBLOCK not FTB Presents Stoneblock 2

**Comment by Zittla** [comment]
wither spawning is not the issue its just that sometimes they carry particle effects idk could be server related but i cant log in on the server now without crashing it i dotn even have to be taht close to it just as long as i see the bar and sorry i had no idea there was a stoneblock 2 github this was the onlyone i did find
