### ISSUE TITLE
Cow stall

### ISSUE THREAD

**Issue by ChisleLP** [Sunekaer/stoneBlock#782]
I didn't found a github for Stoneblock 2. so im hope here is fine too.

## Bug Report
Cow stall in one chunk => fps drops

## Steps to Reproduce (for bugs)
We build a compact machine, and we planing to put every cow stall there. After we put 64 Cow into stall, it drop from 120fps to 8 fps. 

## Logs
* Client/Server Log: https://paste.feed-the-beast.com/view/83d8368a (at [10:18:23] happens)
* Crash Log: -

## Client Information
* Modpack Version: 1.2.0
* Server/LAN/Single Player: Lan
* Optifine Installed: -
* Shaders Enabled: -

**Comment by Sunekaer** [comment]
wrong tracker
