### ISSUE TITLE
Game crash when try to initialize

### ISSUE THREAD

**Issue by jatxada** [Sunekaer/stoneBlock#783]
## Bug Report
When i try to access to my saved world, suddenly the game crash and close as  "Error code: 1"

Attached you can finde the crass report.

Thanks in advance and best regards.
## Steps to Reproduce (for bugs)
When i try to initialize the game, suddenly the game crash and close as  "Error code: 1". See the link below for more details

![image](https://user-images.githubusercontent.com/46871219/51443355-0e55b880-1ce8-11e9-89b2-82cb964af103.png)

## Logs

* Client/Server Log: N/A
* Crash Log: https://paste.feed-the-beast.com/view/926151ac

## Client Information

* Modpack Version: Stoneblock version 1.0.33 by sunekaer
* Server/LAN/Single Player: Single player
* Optifine Installed: N/A
* Shaders Enabled: N/A

**Comment by jatxada** [comment]
I think that isn´t a problem with the version, because i try to copy the world to the previous version (1.0.31) and have the same problems. Thanks.

**Comment by jatxada** [comment]
Hello friend,
I can´t type any kind of command becausa i can´t join to the game. The problem is that the screen is freeze during 2 seconds and after that the game shut down. Do you know any command or modification in the stoneblock or minecraft folder that prevent to spawn the dragon? Or maybe can spawn directly in my world instead of nether...

Thanks in advance!

**Comment by jatxada** [comment]
Instead of end sorry :)

**Comment by nzminecraftDOTcom** [comment]
You can always delete the end dimension (From memory it's Dim-1) from your world folder if nothing is in there that you need.

**Comment by jatxada** [comment]
Hello!
I delete the Dim1 folder  and works! The end world was re-createad. 
Thanks you!
