### ISSUE TITLE
Contents of Quantum Storage deleted when broken with Red Morningstar on modes.

### ISSUE THREAD

**Issue by ROSSO-D** [Sunekaer/stoneBlock#785]
## Bug Report

Using a ProjectE Red Morningstar on any other mode than Standard deleted the entire contents of a Quantum Storage unit.

## Steps to Reproduce (for bugs)

Break a Quantum Storage Unit with items inside using a Red Morningstar on Wideshot, Longshot or Tallshot mode.

https://clips.twitch.tv/PoliteInterestingSamosaDoggo

## Logs

* Client/Server Log: Not applicable
* Crash Log: Not applicable

## Client Information

* Modpack Version: 1.0.33
* Server/LAN/Single Player: Single Player
* Optifine Installed:  No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
please report to Quantum Storage
