### ISSUE TITLE
Crashing when loading into world

### ISSUE THREAD

**Issue by iDemonz** [Sunekaer/stoneBlock#786]
## Bug Report
Every time I try to load into the world, my game crashes
Note: I've been playing on this world for over a 2 days, so it's not that I just can't play it :).
Also, I presume this is a save corruption issue. (More on this at the bottom)

## Steps to Reproduce (for bugs)
1. Open the modpack
2. Start loading into world
3. Crash before I load into world

## Logs
* Client/Server Log: https://paste.feed-the-beast.com/view/11a620b8
* Crash Log: https://paste.feed-the-beast.com/view/b2aebae3

## Client Information
Every so often my game crashes, usually it's fine, it stops responding, I close it and reopen it. The last time it did this, I reopened the game and It crashed.
Right before it crashed, I was troubleshooting something with a **creative power source.** 
(Creative power source into a flux point) (<-- not sure if that helps)

Note: I can open another world, and it will work normally, I presume there's some sort of corrupted block in the save, Idk what it is though... (I presume I'd have to use MC Edit to delete the block, if that's the issue)

* Modpack Version: 1.1.1
* Server/LAN/Single Player: Single player (LAN enabled, to stop the game from pausing)
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
wrong tracker
