### ISSUE TITLE
StoneBlock 2 - Load into world - complete freeze - Mac

### ISSUE THREAD

**Issue by raediancy** [Sunekaer/stoneBlock#787]
## Bug Report
when launching stoneblock 2 from the Twitch client, the minecraft launcher starts up correctly. 
Stoneblock 2 loads and the basic Login game menu appears.
The world loads and the ingame option menu appears.
at this point the game freezes and i can't even click on for example: "back to game", "save and quit to title" etc. 

I have tried: 
- increasing and decreasing RAM
- deleting all modpacks, and reinstall
- copy pasting the missing 1.7.10.json file (this made the game crash during loading) 

I have seen similar issues but never a solution. I have tried, with my limited knowledge, to apply solutions i thought might work from other problems that looked like similar errors but sadly to no result. 

I also looked through the related issues but did not find anything that could solve my problem

## Steps to Reproduce (for bugs)
1. i simply load the game
2. i can't do anything beyond that point

## Logs

Launcher log: https://paste.feed-the-beast.com/view/78f2b6a8
game output log: https://paste.feed-the-beast.com/view/537d1fff

## Client Information

* Modpack Version: 1,2,0
* Server/LAN/Single Player: SIngle Player
* Optifine Installed: No
* Shaders Enabled: no

**Comment by raediancy** [comment]
also deleted twitch app and reinstalled everything: the same bug appears. 
different logs: 
- launcher logs: https://paste.feed-the-beast.com/view/cdb8d50a
- https://paste.feed-the-beast.com/view/11ea7443

**Comment by Sunekaer** [comment]
wrong tracker
