### ISSUE TITLE
Zero Frames

### ISSUE THREAD

**Issue by DracoClaw** [Sunekaer/stoneBlock#789]
I start up the pack last night and Im running on 0-3 fps. Nothing has changed since the last time I played. Whats going on?

**Comment by LoganDungeon** [comment]
Aliens probably.

No seriously how is anyone supposed to help you without knowing anything about: operating system, java version, crash reports etc.

**Comment by DracoClaw** [comment]
Windows 10
java version 8 update 209
pack 1.0.33
no crash reports, the world starts up just fine, i just cant do anything as its zero frames.

**Comment by LoganDungeon** [comment]
What processor do you have and how much ram? Also which graphics card do you have?

**Comment by DracoClaw** [comment]
intel core i7, 12 gb ram, gforce gtx 1060 3gb

**Comment by DracoClaw** [comment]
now it wont even launch, "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience." just from clicking play in the launcher

**Comment by Sunekaer** [comment]
log file?

**Comment by DracoClaw** [comment]
https://pastebin.com/9TbDug9B

**Comment by DracoClaw** [comment]
anything?

**Comment by Sunekaer** [comment]
No clue, there is nothing in this log saying anything, have you tried installing the pack?

**Comment by DracoClaw** [comment]
I just updated the pack to the latest version and its all working again!
