### ISSUE TITLE
World Creation - Air and Glass?

### ISSUE THREAD

**Issue by RobertLSnead** [Sunekaer/stoneBlock#79]
## Bug Report

When creating a new world, you start out in the sky while standing on a glass block.
Expected to be surrounded by stone instead like intended mod description.

## Steps to Reproduce (for bugs)

1. Create New World
2. Leave Default Settings
3. Play

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.14
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by RobertLSnead** [comment]
The server files seem to have the right .nbt file for the void world setup!
Recommend taking a look!

**Comment by Sunekaer** [comment]
Works fine for me, did you leave the world type at default? (Void? World)

**Comment by Nicocraft05** [comment]
no problèm please report problem no created world other than part defaur please

**Comment by Sunekaer** [comment]
Hmm just did a refresh install of the pack still works for me, could you try installing a new instance of the pack and test, if it still happens upload the log to gist.github.com and link it here.
