### ISSUE TITLE
Crashes at Start up

### ISSUE THREAD

**Issue by beaufil** [Sunekaer/stoneBlock#792]
## Bug Report
Crashes right after tryna start up

## Logs

03:54:33 | launcher | Preparing to launch minecraft client for forge-14.23.5.2772
-- | -- | --
03:54:33 | launcher | Couldn't get hash for org/ow2/asm/asm-all/5.2/asm-all-5.2.jar from https://modloaders.forgecdn.net/647622546/maven/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for org/jline/jline/3.5.1/jline-3.5.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/jline/jline/3.5.1/jline-3.5.1.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar from https://modloaders.forgecdn.net/647622546/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for com/typesafe/config/1.2.1/config-1.2.1.jar from https://modloaders.forgecdn.net/647622546/maven/com/typesafe/config/1.2.1/config-1.2.1.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar from https://modloaders.forgecdn.net/647622546/maven/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Couldn't get hash for 1.12.2 jar from https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\versions\1.12.2/1.12.2.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/ow2/asm/asm-all/5.2/asm-all-5.2.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/jline/jline/3.5.1/jline-3.5.1.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\com/typesafe/config/1.2.1/config-1.2.1.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Couldn't get hash for net/minecraftforge/forge/1.12.2-14.23.5.2772/forge-1.12.2-14.23.5.2772.jar from https://modloaders.forgecdn.net/647622546/maven/net/minecraftforge/forge/1.12.2-14.23.5.2772/forge-1.12.2-14.23.5.2772.jar.sha1: HTTP 403: Forbidden
03:54:33 | launcher | Have local file C:/Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\libraries\net/minecraftforge/forge/1.12.2-14.23.5.2772/forge-1.12.2-14.23.5.2772.jar but don't know what size or hash it should be. Have to assume it's good.
03:54:33 | launcher | Checking installations.
03:54:33 | launcher | Minecraft client forge-14.23.5.2772 is ready to start.
03:54:33 | launcher | Starting!
03:54:34 | launcher | Using default game log configuration client-1.12.xml (outputs XML)
03:54:35 | LaunchWrapper | Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
03:54:35 | LaunchWrapper | Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
03:54:35 | LaunchWrapper | Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
03:54:35 | FML | Forge Mod Loader version 14.23.5.2772 for Minecraft 1.12.2 loading
03:54:35 | FML | Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\beauf\OneDrive\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_51
03:54:36 | FML | Searching C:\Users\beauf\OneDrive\Documents\Curse\Minecraft\Instances\StoneBlock\mods for mods
03:54:36 | FML | Searching C:\Users\beauf\OneDrive\Documents\Curse\Minecraft\Instances\StoneBlock\mods\1.12.2 for mods
03:54:36 | LaunchWrapper | Unable to launch java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\beauf\OneDrive\Documents\Curse\Minecraft\Instances\StoneBlock for Forge Mod Loader 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:139) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:386) 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:264) 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) 	... 5 more Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	... 8 more
20:54:36 | game | Exception in thread "main"   <log4j:Event logger="STDERR" timestamp="1550314476380" level="INFO" thread="main">     <log4j:Message><![CDATA[[java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException]]></log4j:Message>   </log4j:Event>
20:54:36 | monitor | expected <
03:54:36 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
03:54:36 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
03:54:36 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
03:54:36 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
03:54:36 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
03:54:36 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
03:54:36 | launcher | Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
20:54:36 | monitor | Process crashed with exit code 1

## Client Information

* Modpack Version: 1.0.33
* Server/LAN/Single Player: n/a
* Optifine Installed: no
* Shaders Enabled: no

Logs Linked:  https://paste.feed-the-beast.com/view/e3df83d8

**Comment by Sunekaer** [comment]
move your minecraft save out of OneDrive and try again

**Comment by beaufil** [comment]
where would i find my minecraft save in the onedrive
