### ISSUE TITLE
Duplication bug with TC crafting station.

### ISSUE THREAD

**Issue by winnetrie83** [Sunekaer/stoneBlock#794]
## Bug Report
While playing multiplayer, another player is able to take the result of a crafting recipe out of the Tinkers
Construct crafting station after the first player took it out, result in duping the item/block. 

## Steps to Reproduce (for bugs)
[https://youtu.be/b1-OFFwMuVk](url)

Very clear to see the bug here!

## Logs
* Client/Server Log: [https://paste.feed-the-beast.com/view/08c1a024](url)
* Crash Log: no crash

## Client Information

* Modpack Version: Version 1.0.34 for Minecraft 1.12.2
* Server/LAN/Single Player: Multiplayer LAN
* Optifine Installed: No
* Shaders Enabled: None

**Comment by Sunekaer** [comment]
I think this is fixed in .36
