### ISSUE TITLE
Refined Storage Controller Quest not recognized

### ISSUE THREAD

**Issue by JRSofty** [Sunekaer/stoneBlock#798]
## Bug Report
After creating a Controller for Refined Storage, the quest does not recognize it, even if clicking the "Submit and Claim" button in the quest book, while the block is in my inventory.

## Steps to Reproduce (for bugs)

1. Create a Refined Storage Controller
2. Quest will not complete which locks the entire tree.

It may have been that I placed it down too quickly after creating it but I don't think so. I've double checked that there is no power so that its state is not different. I was able to get the game to recognize the quest by using /give @p refinedstorage:controller and then it recognized it. I'm guessing it has something to do with the NBT when you put it down and power it before it identifes the quest.

## Client Information

* Modpack Version: 1.0.35
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Banana243** [comment]
Same problem here

**Comment by imreallyphat** [comment]
Had the same problem, you can manually complete it by typing: /bq_admin complete 94 (you'll need cheats enabled unfortunately)

**Comment by Sunekaer** [comment]
fix uploaded

**Comment by mulhollandaf** [comment]
I am playing 1.0.3.7 on multiplayer and it still isn't working. What version is it fixed on?

**Comment by ThatScar** [comment]
Same, doesn't work on Stoneblock modpack version 1.0.37
It probably doesn't complete because NBT tags don't match? (the quest has no NBT tags, crafted item has 1 tag). I didn't try imreallyphat's solution but this worked:
/give ThatScar refinedstorage:controller
(of course, replace with your name)

**Comment by DAV3Y06L3GO** [comment]
I'm still having this issue

also if I don't have cheats on can I turn them on through the files

**Comment by TheCodeInjection** [comment]
You can open to LAN and enable cheats
