### ISSUE TITLE
World stops giving information to players (I think)?

### ISSUE THREAD

**Issue by Divrann** [Sunekaer/stoneBlock#80]
## Bug Report

Game will start, open world and look to play as normal, but chests and machine blocks do nothing at all when right clicked. Blocks can be broken, and items in inventory can be moved and equipped but no item is dropped when breaking blocks or dropping items. Reloading world reverts back to before blocks were broken or items moved. This used to be a problem after a few hours of game play, then a few minutes, and now happens just after loading world. Happens on Singleplayer and when opening to LAN, (If you can open it quick enough at this point). Copied save to another PC, and problem still occurs. When was happening on LAN, would occur for both myself (Host) and my roommate on LAN. Animals/mobs stop moving as well. You are able to explore the World/Base with no problems or loading, but nothing can be interacted with. This can go in of as long as Ive been able to tell, with no 'Re-connection to world', and game will not freeze or crash, so unsure if logs will help, but Ill post them anyhow.  It is difficult to word this specific issue, so please contact if more detail is needed.

## Steps to Reproduce (for bugs)

1. Load our specific save game as a Singleplayer world, and try to interact with machine/Inventory, or try to break block
2. Should be all that is required, May work normally for up to 10 or 15 seconds, then no interaction. 

## Logs

* Client/Server Log: https://gist.github.com/Divrann/379922ac35e093a2712df9e40c8f76a9
* Crash Log: None made as game does not crash. (Until ESC > Quit, but Minecraft has always crashed when quitting for me in this way)

## Client Information

* Modpack Version:1.10.12 and 1.10.13, Have not yet tried 1.10.14 seeing no mention of this issue in notes
* Server/LAN/Single Player: LAN And Single Player. First noticed in LAN When happening hours in, but cannot open game to LAN with how soon problem happens. 8GB Ram Allocated in Twitch
* Optifine Installed:Not Currently, but Tried with Optifine installed as well in 1.10.12. No change
* Shaders Enabled:No

Extremely frustrating as my Roomate and I always seem to find a way to break Modpacks, and have never made it to the end of one. Also because nobody else seems to be having this problem that I can search, as it is difficult to phrase. World stops responding, but its not a case of the window saying (Not Responding), It doesnt freeze or crash, so those terms are out, it doesnt make a crash log, just the normal log as given above, and happens on 2 PCs when copying Save over. 
Will send Saved world upon request. Lurking on Discord Stoneblock category in 'Modpack-Support' channel as 'Divrann' without permission to send messages, so Private message if needed.

**Comment by Divrann** [comment]
I can try a few combinations by placing them in Creative, but Im not sure what machines are causing it. When it happened before, you could play for some time before it happened, then less and less until it happens as soon as you start the game, so it it is tough to pinpoint what machines or placement are the cause.
It feels like 'something' overloading, or going too fast for the world/player interaction part of the game to the point that it gives up, but I cant think of anything we would have built like that. We can always start over and try to see if we can better figure out exactly what did it, after a few more releases.

**Comment by RandomLibrarian** [comment]
Happens to me as well occasionally. Pretty sure it has something to do with extra utilities and a memory leak. Can’t be sure because you never remember to turn on garbage collection debugging. Do you use cursed earth, mechanical users, or speed upgrades?

**Comment by Sunekaer** [comment]
Could you try and go into the config folder. Locate the file "Forge.cfg" there is a line for removing erroring tile entities. turn this from false to true. Restart the server and load the chunks the crash is happening at. Afterwards turn the config back to false and restart the server.

**Comment by Divrann** [comment]
We definitely use Speed upgrades, but I dont think we've used cursed earth or mechanical users yet. Ill give the Forge.cfg line a shot. Am I correct in assuming this could delete the problem items? Just to know what to look for and report back with.

**Comment by Sunekaer** [comment]
Correct

**Comment by griseouslight** [comment]
I am having literally the same issue, The suggestion above did nothing to resolve it.

Log: https://puu.sh/BLYJp/8ffb760a00.txt
I wasn't sure whether or not to make this a new issue or not. I'm playing exclusively single player on 1.0.22r1 with 8GB ram.
