### ISSUE TITLE
cant install stoneblock from twitch

### ISSUE THREAD

**Issue by wackoamd1** [Sunekaer/stoneBlock#801]
Bug Report
Steps to Reproduce (for bugs)
it doesnt install  at all , when validating manifest it throws 
"Cannot find addon dependency 282415" in a popup and just doesnt install at all
Logs
Client/Server Log:
Crash Log:
Client Information
Modpack Version: 1.0.35
Server/LAN/Single Player: singleplayer
Optifine Installed: no
Shaders Enabled: no

**Comment by Sunekaer** [comment]
Please report to twitch, i cant do anything about this
