### ISSUE TITLE
Stoneblock 2 crashing

### ISSUE THREAD

**Issue by thealmghtyweeb** [Sunekaer/stoneBlock#802]
## Bug Report
I launch stoneblock 2 and then it just crashes.

## Steps to Reproduce (for bugs)

1. Launch stoneblock 2 from twitch launcher
2.after a while it crashes

## Logs

* Client/Server Log:
* Crash Log:https://paste.dimdev.org/adegecumud.mccrash

## Client Information

* Modpack Version: 1.12.2
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
Line 8 `Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded` assign more ram to minecraft
