### ISSUE TITLE
laggs problem

### ISSUE THREAD

**Issue by MegaShon123** [Sunekaer/stoneBlock#804]
i have a new pc but when i join stoneblock the game allmost crashes and the screen moving in delay maybe its something with the files of the modpack i dont know pls help

**Comment by jeffgillispie114** [comment]
Have you modified the amount of ram that you are starting with?

**Comment by MegaShon123** [comment]
LOL i dont play stoneblock a half year now

‫בתאריך יום א׳, 5 באפר׳ 2020 ב-19:46 מאת ‪Jeff Gillispie‬‏ <‪
notifications@github.com‬‏>:‬
