### ISSUE TITLE
Twitch

### ISSUE THREAD

**Issue by Cookielqnd** [Sunekaer/stoneBlock#807]
## Bug Report

Twitch will not load the game and says something about the manifest files not being able to work idk
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by Sunekaer** [comment]
Twitch issue, nothing i can do about it sadly, report it to twitch
