### ISSUE TITLE
Cant start game/stuck in the mc launcher

### ISSUE THREAD

**Issue by Minecraftuser04** [Sunekaer/stoneBlock#808]
(btw im german thats why the stuff down below is in german)
when i try to start the game with Stoneblock selected it at first does the normal things and seems to Download the required files. but at the point where it should close the launcher and start the actual game it shows me this:

Eine Datei konnte nicht heruntergeladen werden; der Dateiinhalt unterscheidet sich von dem, der erwartet wurde.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Dateiname: jna-4.4.0.jar
Pfad: C:\Users\HP\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Existiert: File

**Comment by Sunekaer** [comment]
Twitch issue, nothing i can do about it sadly, report it to twitch

**Comment by domocorn** [comment]
Try this! https://www.youtube.com/watch?v=DqRxVwsk0k8
