### ISSUE TITLE
Storage quest not accepting

### ISSUE THREAD

**Issue by kianj2005** [Sunekaer/stoneBlock#809]
Hi, so I’m working through the quest book on my stream and it won’t detect that I have the controller. I have tried restarting application and throwing it down and picking it up

**Comment by eawilhelm** [comment]
Same here, I even tried to go in creative mode and grab every controller and nothing updates the progress.

**Comment by jeffgillispie114** [comment]
Which Controller quest is it? There are 2 on the storage quest line. I got one to complete, but not the other as well.

**Comment by B14U2NV** [comment]
The refined storage controller didn't detect for me (The first quest in the refined storage questline). I just enabled edit mode in the better questing and manually completed it. Probably some .nbt data or something not registering with better questing.

**Comment by Sunekaer** [comment]
#798
