### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by prototype-saber** [Sunekaer/stoneBlock#81]
## Context

there are so many recipe conflict in StoneBlock,like ender dust and ender pearl ,seed and cow bait,5 
kinds of gear.I think this mod will help improve the probleme

Also projecte can be better by use Refined Exchange that allow RS to use emc in later.
Refined Exchange is a link between Refined Storage and ProjectE.The late game of StoneBlock will be better.

Hope these mods can be helpful!

## Mod Details
* Name:stimmedcow : NoMoreRecipeConflict
* CurseForge Link:https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict

* Name:Refined Exchange
* CurseForge Link:https://minecraft.curseforge.com/projects/refined-exchange

**Comment by Sunekaer** [comment]
what gears and what are they conflicting with?

**Comment by Sunekaer** [comment]
1.0.15
