### ISSUE TITLE
I downloaded it of twitch but i can't play it

### ISSUE THREAD

**Issue by theterrarianyoshi** [Sunekaer/stoneBlock#810]
here is what it says

![error report](https://user-images.githubusercontent.com/59356974/71573111-392bbd80-2ab0-11ea-9cfc-e073dab51f46.PNG)

**Comment by jeffgillispie114** [comment]
you are launching it through the Twitch app as well right?

**Comment by Sunekaer** [comment]
Issue with the twitch launcher, i dont have a fix for this
