### ISSUE TITLE
Loot Bags Won't Open

### ISSUE THREAD

**Issue by Lassalot0703** [Sunekaer/stoneBlock#812]
**Bug Report**
When I right-click on a loot bag it won't open. There is no error, everything looks normal, it just won't open. All other containers open fine but not loot bags dropped by mobs. 

**Steps to Reproduce (for bugs)**
- get loot bag
- put loot bag on hot bar
- select the loot bag
- right click from hot bar
- nothing happens

**Logs**
Client/Server Log: No logs
Crash Log: No logs

**Client Information**
Updated: 12/16/2019
Version: 1.0.35
Minecraft Version: 1.12.2
(modded) forge-14.23.5.2836

![Minecraft 1 12 2 2_8_2020 6_10_02 PM](https://user-images.githubusercontent.com/60832611/74095011-5e442080-4a9f-11ea-8e40-f27066fb218c.png)

**Comment by jeffgillispie114** [comment]
Try to not be pointing at the ground or any item, so like be pointed at empty air or down a long hallway.

**Comment by Sunekaer** [comment]
point in air when trying to open it
