### ISSUE TITLE
Bug to break the blocks

### ISSUE THREAD

**Issue by NoGaniX** [Sunekaer/stoneBlock#815]
I wanted to do a Stone Block 2 adventure but in a normal world.
When I tried to break blocks of grass, wood, ... I couldn't get them back except the stone. I would like to know if a mod does this or if it is a bug?
Sorry for my English, I'm French x) 
And thank you in advance!

**Comment by Sunekaer** [comment]
This tracker is for stoneblock 1 not 2 but i dont know
