### ISSUE TITLE
Modpack crashing after Loading step 7/7 and after Dirt Screen

### ISSUE THREAD

**Issue by xSaMpLe1** [Sunekaer/stoneBlock#817]
No idea what could be wrong reinstalled the modpack couple times aswell as java.

I tried to load 1.12.2 Vanila before I install the modpack but the crash did not disapear.

[crash-2020-04-01_18.23.26-client.txt](https://github.com/Sunekaer/stoneBlock/files/4416419/crash-2020-04-01_18.23.26-client.txt)

Thank you in advance.

**Comment by whytf** [comment]
Got the same crash error
[stoneblock crash.txt](https://github.com/Sunekaer/stoneBlock/files/4424041/stoneblock.crash.txt)

**Comment by AvgRedPanda** [comment]
Getting the same crash as of today.
[crash-2020-04-02_19.29.50-client.txt](https://github.com/Sunekaer/stoneBlock/files/4424324/crash-2020-04-02_19.29.50-client.txt)

**Comment by AustinTX1985** [comment]
Same issue.
[crash-2020-04-03_14.22.28-client.txt](https://github.com/Sunekaer/stoneBlock/files/4429281/crash-2020-04-03_14.22.28-client.txt)

**Comment by B14U2NV** [comment]
Same was happening to me, CraftPresence was the culprit. Disabled the CraftPresence.jar and the pack loads fine. There is an updated version of CraftPresence (v1.6.1) but I did not manually update and see if the issue is remedied. Hope this helps some of you get the pack to load and maybe the pack creator can look into this if the pack is still supported.

**Comment by xSaMpLe1** [comment]
How do you do that ?
A good thing to know is that I am on the Twitch App.

**Comment by AvgRedPanda** [comment]
> Same was happening to me, CraftPresence was the culprit. Disabled the CraftPresence.jar and the pack loads fine. There is an updated version of CraftPresence (v1.6.1) but I did not manually update and see if the issue is remedied. Hope this helps some of you get the pack to load and maybe the pack creator can look into this if the pack is still supported.

Can confirm this worked for me.

**Comment by xSaMpLe1** [comment]
How do you disable the .jar ?
Does it work for Stoneblock too ?

**Comment by AvgRedPanda** [comment]
> 
> 
> How do you disable the .jar ?
> Does it work for Stoneblock too ?

I'm using the Twitch launcher myself, you go to the stoneblock page and into settings (gear icon). From there you want to go to open folder which takes you to where the pack is installed. head into the mods folder and you should find craftpresence.jar which you can then delete. Well the other commenter said disable but I'm not sure exactly how to do that so I just deleted it. My game has been running fine since! Hope this helps.

**Comment by B14U2NV** [comment]
> > How do you disable the .jar ?
> > Does it work for Stoneblock too ?
> 
> I'm using the Twitch launcher myself, you go to the stoneblock page and into settings (gear icon). From there you want to go to open folder which takes you to where the pack is installed. head into the mods folder and you should find craftpresence.jar which you can then delete. Well the other commenter said disable but I'm not sure exactly how to do that so I just deleted it. My game has been running fine since! Hope this helps.

Just rename craftpresence.jar to craftpresence.jar.disable and click "OK" on the warning dialog box that appears. If you don't see the .jar extension on your files then you need to uncheck "Hide extensions for known file types" in "Windows folder and search options" settings.  It's just a quick way to enable/disable mods which may be causing issues without deleting them outright. Glad it worked out for you. Cheers

**Comment by xSaMpLe1** [comment]
> > > How do you disable the .jar ?
> > > Does it work for Stoneblock too ?
> > 
> > 
> > I'm using the Twitch launcher myself, you go to the stoneblock page and into settings (gear icon). From there you want to go to open folder which takes you to where the pack is installed. head into the mods folder and you should find craftpresence.jar which you can then delete. Well the other commenter said disable but I'm not sure exactly how to do that so I just deleted it. My game has been running fine since! Hope this helps.
> 
> Just rename craftpresence.jar to craftpresence.jar.disable and click "OK" on the warning dialog box that appears. If you don't see the .jar extension on your files then you need to uncheck "Hide extensions for known file types" in "Windows folder and search options" settings. It's just a quick way to enable/disable mods which may be causing issues without deleting them outright. Glad it worked out for you. Cheers

I really appreciate You guys to delete the craftpresence.jar has helped me out.
Thank You very much that You use hubs like this to help other people.

**Comment by TheSpicePhantom** [comment]
Updating fixes the issue!

**Comment by Datzu** [comment]
> Updating fixes the issue!

Last version is 1.0.35 and is not fixed, but removing the craftpresence.jar works fines!

**Comment by TheSpicePhantom** [comment]
> > Updating fixes the issue!
> 
> Last version is 1.0.35 and is not fixed, but removing the craftpresence.jar works fines!

I know that 1.0.35 is the latest version. I was replying to the comment above, that updating the mod itself (not the pack) also fixes the issue.

**Comment by brimstonecross** [comment]
im having the launch issue, and i cant seem to find the craftpresence.jar to delete/ mess with.

**Comment by SadMod** [comment]
Hey there! I found a solution, that worked for me. I didn't disable any mods and  **copied missing library** to **C:/windows/system32**. After that modpack loaded normally. I will leave a link from developer himself to download .dll [**here**](https://github.com/MinnDevelopment/discord-rpc-release/blob/master/src/main/resources/win32-x86-64/discord-rpc.dll) so you can play normally as well. 

Write some good words, if that helped you. 

edit1: i hope for @brimstonecross could see that he or she could try to take use of advice i wrote above...

**Comment by Mimicry4326** [comment]
> Hey there! I found a solution, that worked for me. I didn't disable any mods and **copied missing library** to **C:/windows/system32**. After that modpack loaded normally. I will leave a link from developer himself to download .dll [**here**](https://github.com/MinnDevelopment/discord-rpc-release/blob/master/src/main/resources/win32-x86-64/discord-rpc.dll) so you can play normally as well.
> 
> Write some good words, if that helped you.
> 
> edit1: i hope for @brimstonecross could see that he or she could try to take use of advice i wrote above...

honestly thought you were about to tell people to delete system32 but you seem like a nice person

**Comment by Mimicry4326** [comment]
> > > > How do you disable the .jar ?
> > > > Does it work for Stoneblock too ?
> > > 
> > > 
> > > I'm using the Twitch launcher myself, you go to the stoneblock page and into settings (gear icon). From there you want to go to open folder which takes you to where the pack is installed. head into the mods folder and you should find craftpresence.jar which you can then delete. Well the other commenter said disable but I'm not sure exactly how to do that so I just deleted it. My game has been running fine since! Hope this helps.
> > 
> > 
> > Just rename craftpresence.jar to craftpresence.jar.disable and click "OK" on the warning dialog box that appears. If you don't see the .jar extension on your files then you need to uncheck "Hide extensions for known file types" in "Windows folder and search options" settings. It's just a quick way to enable/disable mods which may be causing issues without deleting them outright. Glad it worked out for you. Cheers
> 
> I really appreciate You guys to delete the craftpresence.jar has helped me out.
> Thank You very much that You use hubs like this to help other people.

h o l y  s h i t  this was so helpful thank you for this

**Comment by Sunekaer** [comment]
fix uploaded
