### ISSUE TITLE
Wireless Crafting Missing Item

### ISSUE THREAD

**Issue by jeffgillispie114** [Sunekaer/stoneBlock#819]
## Steps to Reproduce (for bugs)

1. Complete all the steps prior to this quest
2. Open the Wireless Crafting

## Logs

* Client/Server Log: Doesn't cause any errors
* Crash Log: Doesn't crash the game

## Client Information

* Modpack Version: 1.0.35
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

![item placeholder](https://user-images.githubusercontent.com/53870118/78509310-d141de80-7752-11ea-9228-c75e0fd656af.png)
![placeholder item](https://user-images.githubusercontent.com/53870118/78509313-d141de80-7752-11ea-9fd4-b7e9f69df81d.png)
![storage](https://user-images.githubusercontent.com/53870118/78509314-d141de80-7752-11ea-9f7e-2cb474241e7d.png)

**Comment by Sunekaer** [comment]
fix uploaded
