### ISSUE TITLE
Game Crashes When Loading Main Menu

### ISSUE THREAD

**Issue by maxicode2** [Sunekaer/stoneBlock#823]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log: [Pastebin Crash Report](https://pastebin.com/5HW7gpsJ)

## Client Information

* Modpack Version: 1.0.35
* Server/LAN/Single Player: *Single Player*
* Optifine Installed: Yes?
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
update your pack
