### ISSUE TITLE
Game startup just crashes 

### ISSUE THREAD

**Issue by MgoMoar** [Sunekaer/stoneBlock#824]
## Bug Report

when game is loaded it just shows dirtbackground and then closes with crash report
## Steps to Reproduce (for bugs)

1.i tried reinstall it but same issue
2.tried reinstall twitch and minecraft and so again and didnt work

## Logs

* Client/Server Log:
[latest.log](https://github.com/Sunekaer/stoneBlock/files/4903893/latest.log)
[debug.log](https://github.com/Sunekaer/stoneBlock/files/4903894/debug.log)
[crash-2020-07-10_16.43.15-client.txt](https://github.com/Sunekaer/stoneBlock/files/4903895/crash-2020-07-10_16.43.15-client.txt)

* Crash Log:https://pastebin.com/13rxXqZB

## Client Information

* Modpack Version: latest
* Server/LAN/Single Player: single player
* Optifine Installed:
* Shaders Enabled:

**Comment by Sunekaer** [comment]
use version 36

**Comment by MgoMoar** [comment]
Oh okey great ill try that and thanks :)
