### ISSUE TITLE
Game crashes when open inventory

### ISSUE THREAD

**Issue by binou4256** [Sunekaer/stoneBlock#825]
## Bug Report
Crashes when open inventory

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log: [https://pastebin.com/U73ZWJ5C](url)

## Client Information

* Modpack Version: latest
* Server/LAN/Single Player: single player
* Optifine Installed:
* Shaders Enabled:

**Comment by Sunekaer** [comment]
I'm not able to reproduce this crash, try this:
Make sure to take a backup of your game then edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the mod that causes the crash
