### ISSUE TITLE
Redstone furnace sometimes outputting Yellorium and sometimes refined uranium from Yellorium Dust

### ISSUE THREAD

**Issue by Kuperus** [Sunekaer/stoneBlock#828]
## Bug Report
Redstone Furnace outputs either yellorium or refined uranium when smelting yellorium dust... but it keeps changing.

## Steps to Reproduce (for bugs)
No way to reproduce, other than smelting batches of dust., Note: once smelting begins to yellorium it will keep smelting to yellorium, until dust runs out... then tthe following batch can be something different.

## Logs
No crash log

## Client Information
* Modpack Version: 1.0.35
* Server/LAN/Single Player: Single PLayer
* Optifine Installed: no
* Shaders Enabled: no

Note: craft tweakers has been updated, otherwise pack would not start,

**Comment by Sunekaer** [comment]
Hmm, wasnt able to get it to do that for me, but ill add some scripts to make sure it shouldn't happen again
