### ISSUE TITLE
Enderman evolution mod crashing the game on world loadup

### ISSUE THREAD

**Issue by KrAzYGEEK32** [Sunekaer/stoneBlock#829]
Bug Report
enderman evolution mod crashing world on startup

Steps to Reproduce (for bugs)
dont know if it can be reproduced, im just looking for some solution, for now just removing the mod fixed it

Logs
crash report: https://pastebin.com/gkQEXSU2

Client Information
Modpack Version: 1.0.36
Server/LAN/Single Player: Single PLayer
Optifine Installed: no
Shaders Enabled: no

**Comment by NeilMunro44** [comment]
Same issue. 
[crash-2020-07-24_21.44.18-server.txt](https://github.com/Sunekaer/stoneBlock/files/4974182/crash-2020-07-24_21.44.18-server.txt)

Removed the mod also to continue playing.

**Comment by Sunekaer** [comment]
Hmm I'm not able to reproduce this crash, try this:
Make sure to take a backup of your game then edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the mod that causes the crash
