### ISSUE TITLE
Enderio not working on servers

### ISSUE THREAD

**Issue by Ed-Amb** [Sunekaer/stoneBlock#830]
The servers crash report says that ender io and other ender io related mods need forge 14.23.5.2854 not 14.23.5.2836 and it works when I remove enderio and enderio core

stoneblock version 1.0.37
once I put in the right version of forge and changed the .bat file the  server worked. I changed the .bat to java -jar forge-1.12.2-14.23.5.2854.jar --nogui

**Comment by Sunekaer** [comment]
https://www.curseforge.com/minecraft/modpacks/stoneblock/files/3014957
