### ISSUE TITLE
Wrong Forge for server files 

### ISSUE THREAD

**Issue by Itzm1llertime** [Sunekaer/stoneBlock#831]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b167.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 7/26/20 12:08 AM
Description: Exception in server tick loop

Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2836

Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2836

Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2836

Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2836

Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2836

Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2836

Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2836

Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2836

net.minecraftforge.fml.common.MultipleModsErrored
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:298)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)

* Crash Log:

## Client Information

* Modpack Version:1.0.37
* Server/LAN/Single Player:server
* Optifine Installed:nope
* Shaders Enabled:nope

**Comment by Sunekaer** [comment]
duplicate #830
