### ISSUE TITLE
Server Install Broken

### ISSUE THREAD

**Issue by YesImSevy** [Sunekaer/stoneBlock#832]
There is no install file for the forge and when ever I just get the same version of forge and use those libraries it just doesn't start at all.

**Comment by Sunekaer** [comment]
There is a installer?
![image](https://user-images.githubusercontent.com/18720460/88564191-3176cc00-d033-11ea-8b74-febc1f183456.png)

**Comment by YesImSevy** [comment]
That's not the latest download on the curse page

**Comment by Sunekaer** [comment]
Ah fucking curseforge download the archived version for me
uploading a new

**Comment by YesImSevy** [comment]
okay then lol.

**Comment by YesImSevy** [comment]
Also with the client you cant join the server due to the server having plustic but the client not having plustic. So it causing an error when joining servers.

**Comment by Sunekaer** [comment]
lets try again
https://www.curseforge.com/minecraft/modpacks/stoneblock/files/3016966
