### ISSUE TITLE
1.0.37 Download not Possible. Missing Addon ID: 297039

### ISSUE THREAD

**Issue by Dominicus1165** [Sunekaer/stoneBlock#834]
## Bug Report

Update to 1.0.37 not possible

## Steps to Reproduce (for bugs)

1. Update or freshly download pack via Twitch Launcher

## Logs

* Crash Log: This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 297039

**Comment by Sunekaer** [comment]
This is an issue with curseforge not the pack it-self..
Please report to curseforge if you continue to have issues
