### ISSUE TITLE
Bug in mod Better Questing 

### ISSUE THREAD

**Issue by RinLight18** [Sunekaer/stoneBlock#842]
## Bug Report

Bug in mod Better questing
task in category storage
task: craft controller from mod refined storage
even if I craft this item , mod better questing dont see item even if I hold it in inventory in hotbar.

## Steps to Reproduce (for bugs)

obtain controller
![image](https://user-images.githubusercontent.com/76453391/102822066-8f3bf400-43d8-11eb-9e9b-65d52ec1d225.png)

## Client Information

* Modpack Version: latest relase
* Server/LAN/Single Player: Single Player
* Optifine Installed: nope
* Shaders Enabled: nope

**Comment by Ladysarajane** [comment]
I too am experiencing this. Is there a quest I need to do before this is completed? It is a retrieval quest, but I did make it in a tinker's  crafting table. 

I tried to complete the quest using command line. I think the quest id is 9276 but I keep getting an error that it cannot complete.  Is that the quest id number?

**Comment by klaujesi** [comment]
Hey. Looks like Better Questing mod, don't recognize energized items.
- Remove any Capacitor from you inventory and baubble (Draconic Evolution, Thermal Expansion,..)
- Disable any wireless charging (Flux Networks and others)
When you craft the item, this mus have 0 charge to be detected
This bug could happend with: Controlers from AE2 and RS, Wireless Crafting Terminal, Draconic Flux Capacitor and others items with charge.

Hope this help

**Comment by Chefbarbie** [comment]
https://github.com/Sunekaer/stoneBlock/issues/798
