### ISSUE TITLE
Unable to use Bonsai Pots

### ISSUE THREAD

**Issue by AlleinSoldat** [Sunekaer/stoneBlock#85]
I saw there was a ticket open previously, so I tried that before this I opened this. Unfortunately, the solution for that ticket does not work with my current issue.

I am able to craft both the normal Bonsai Pot and the Hopping Bonsai Pot. But, I am not able to place any saplings in either pot variation. I attempted to use them both with and without dirt "placed" inside them. As previously stated, I did log completely out of Minecraft and logged back in. Which did not fix the issue.

**Comment by Sunekaer** [comment]
## Bug Report


## Steps to Reproduce (for bugs)

1.
2.


## Logs


* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by AlleinSoldat** [comment]
Whoops, I saw you had the format, but forgot to format it like so.

Bug Report
I am able to craft both the normal Bonsai Pot and the Hopping Bonsai Pot. But, I am not able to place any saplings in either pot variation. I attempted to use them both with and without dirt "placed" inside them. As previously stated, I did log completely out of Minecraft and logged back in. Which did not fix the issue.

Steps to Reproduce (for bugs)
1. Craft Bonsai Pot
2. Place any sapling in pot

Logs
Client/Server Log: None
Crash Log: None

Client Information
Modpack Version: 1.0.14
Server/LAN/Single Player: SSP
Optifine Installed: N/A
Shaders Enabled: N/A

**Comment by Ladysarajane** [comment]
I found I cannot place a sapling in a hopping bonsai pot if there is not a chest under it. I haven't even tried the regular bonsai pot yet. I go straight to the hopping bonsai pot.

**Comment by AlleinSoldat** [comment]
I've tried them both and have been unsuccessful. As I'm writing this, I'm actually booting up Minecraft to see if it magically started working again or not. I know it hasn't the last few times I've attempted to use them.

**Comment by oliverjanik** [comment]
I just started playing and hopping bonsai works OK.

**Comment by RobertLSnead** [comment]
Works fine on my end.
Check the user guide on the bonsai trees, if that does not work try deleting the config folder and try again!

**Comment by iDarper** [comment]
I can confirm, that both Bonsai pots and hopping bonsai pots DO work. you need to have an inventory (like a chest or a drawer) below them to work.

**Comment by RobertLSnead** [comment]
Here is a fun video to watch on the Bonsai Pots:
https://www.youtube.com/watch?v=jmlVz249QoQ
Also the regular pot you need to use an axe and right click, the hopper one you need some form of inventory below for it to work!

**Comment by Sunekaer** [comment]
Works for everyone but you idont know what your doing wrong on your end

**Comment by miguelcangueiro** [comment]
I know this is closed, but if someone finds this make sure to try and place the sapling without anything on your off hand.

**Comment by oliverjanik** [comment]
lots of mods have issues with off-hand.
