### ISSUE TITLE
Cannot download 

### ISSUE THREAD

**Issue by Heehoo1114** [Sunekaer/stoneBlock#852]
## Bug Report
Mod pack will not download from curse forge desktop application  because it "It cannot find child addon 229073"

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 1.12.2
* Server/LAN/Single Player: Single Player
* Optifine Installed: N/A
* Shaders Enabled: N/A

**Comment by Lofi-Artist** [comment]
Yeah same here, been like this for a couple days now

**Comment by Sunekaer** [comment]
This is an issue with curseforge not the pack it-self..
Please report to curseforge if you continue to have issues
