### ISSUE TITLE
Beginning of stoneblock

### ISSUE THREAD

**Issue by nesslynn** [Sunekaer/stoneBlock#865]
The main issue is that it says to make a stone hammer, I make stone hammer, then it says to mine and it will turn things to dirt, it does not. Just cobble stone, there is no progressing any further if i cannot even get dirt so In my opinion, this was a waste of time.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by Jordan-Nguy** [comment]
I was just swinging by the issues and this is...
Mine the cobble with the hammer to get dirt...

**Comment by Chefbarbie** [comment]
It's a progression
Cobble > Gravel > Dirt > Sand > Dust
