### ISSUE TITLE
Loot bag drop glitch

### ISSUE THREAD

**Issue by HairyDragonBeck** [Sunekaer/stoneBlock#88]
## Bug Report

You can spawn a mob using the Target Dummy Spawner (Cyclic) and when you kill them, it has the same chance to drop a loot bag, creating infinite free lootbags
## Steps to Reproduce (for bugs)

1. Right click with a Target Dummy Spawner (Cyclic)
2. Kill them

## Logs

* Client/Server Log: Not needed
* Crash Log: Not needed

## Client Information

* Modpack Version: 1.0.14
* Server/LAN/Single Player: Single Player
* Optifine Installed: False
* Shaders Enabled: False

**Comment by Sunekaer** [comment]
I’ll see what I can do about it

**Comment by Sunekaer** [comment]
1.0.15
