### ISSUE TITLE
Client crash with sprinkler and fluid tank

### ISSUE THREAD

**Issue by SirioIlBe** [Sunekaer/stoneBlock#89]
## Bug Report

If you place a sprinkler from openblocks on top of an enderio fluid tank and then click on the configure io option the client will crash.
## Steps to Reproduce (for bugs)

1.place sprinkler on the ender io fluid tank
2.open the tank and click configure io

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:1.0.14
* Server/LAN/Single Player:Single Player
* Optifine Installed:No
* Shaders Enabled:No

**Comment by Sunekaer** [comment]
No logs
