### ISSUE TITLE
Starting location is not the same as spawn

### ISSUE THREAD

**Issue by Kobting** [Sunekaer/stoneBlock#90]
## Bug Report

Starting position is not the location of spawn which makes it so if you've never looked at your coordinates and you use `Ender Wing` you are now lost forever in your world.
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.14
* Server/LAN/Single Player: Single
* Optifine Installed:
* Shaders Enabled:

**Comment by Sunekaer** [comment]
Not a bug, just use /island home to get back
