### ISSUE TITLE
Quests do not automatically mark as completed.

### ISSUE THREAD

**Issue by marcmohon** [Sunekaer/stoneBlock#91]
## Bug Report

Quests do not automatically mark themselves as completed / blue in Better Questing.

When completing quests and using the Better Questing book, every item has to be manually 'detect/submit'ed, instead of quests autocompleting upon existence of relevant items.

Playing with cheats off, edit mode for better questing does not appear to be on.

## Steps to Reproduce (for bugs)

1. Complete steps for a quest.
2. Look in quest book for applicable task, items are still marked as 'INCOMPLETE' even if book is closed / opened or if we just wait a few minutes.

## Logs

* Client/Server Log: https://gist.github.com/marcmohon/4ddefe26c8817997aeeb1311d5f1cb96
* Crash Log: Does not crash for this issue.

## Client Information

* Modpack Version: 1.0.14
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: None

**Comment by Sunekaer** [comment]
Not much I can do about it, if the quest completes after you click detect and exit the quest and it then completes I can’t do anything it’s how the mod is

**Comment by marcmohon** [comment]
This is my first time playing Stoneblock, but for most modpacks, the Detect/Submit option is only required if its a turn-in based quest, i.e. if you're giving up resources.  I don't know if it's a config option or what, but Betterquests will usually detect automatically.

**Comment by syntaxer** [comment]
I think it's because the qest book is in edit mode. It was for me when I first created my world. To toggle edit mode: /bq_admin edit

**Comment by marcmohon** [comment]
Hmm, I'm a glutton for punishment and I play with cheats off, so I get a permissions error message on that command.  After some quick googling though, modpack authors forgetting to turn off 'edit mode' does seem to match very well with what i'm seeing, so it looks like we're on the right track.

It seems like there's a line very close to the end of a few of the quest json files labeled '"editmode:1": 1,' that should be set to 0 to default it to off.  After manually changing that to 0 in the betterquesting config files and the betterquesting file attached to my save, this seems to work as it does in other modpacks.  We get the 'Quest Complete' popup, the quests in the questbook automatically turn blue, etc.

**Comment by iDarper** [comment]
marcmohon : If you are playing in single player, the easy fix, is setting the world to lan play, enable cheats, run the command, then exit the world. reloading the world will return you to having no cheats enabled and you can then keep playing. =)

**Comment by marcmohon** [comment]
I appreciate the response iDarper, but the actual permanent fix was in my last comment.

**Comment by Sunekaer** [comment]
Hmm weird, that is has editmode 1, when i turned off edit mode with command before pushing last update :S ill make sure its 0 on next update

**Comment by Sunekaer** [comment]
1.0.15
