### ISSUE TITLE
Applied Energistics / Extra Cells Recipe conflict prevents fluid crafting

### ISSUE THREAD

**Issue by InflamedSebi** [Sunekaer/stoneBlock#94]
You can not craft the "XXk ME Fluid Storage Component" via autocrafting in the ME System, since ExtraCells and AppliedEnergistics both add this item with the same recipe, but they are not part of the oreDictionary.
Applied Energistics recipe takes preference, which makes the fluid assembler and some other items uncraftable and prevents fluid crafting via AE completely.

I would suggest to add an oreDictonary entry for all XXk Fluid storage components to be interchangeable between AE and EC
if this is not possible at all, alternating the recipes for the 1k fluid storage component would solve it too.

**Comment by Sunekaer** [comment]
Have to downgrade AE2 from Rv6 to Rv5 so there wont be any fluid storage from AE

**Comment by Sunekaer** [comment]
1.0.15
