### ISSUE TITLE
Modded eggs only spawning vanilla chickens

### ISSUE THREAD

**Issue by anarth** [Sunekaer/stoneBlock#98]
## Bug Report
When using eggs from the Chickens mod and throwing them like usual to spawn said chicken, it ONLY spawns the vanilla chicken. Not the modded chicken. 

## Steps to Reproduce
1. Breed two chickens. (I was breeding for Redstone, I was using the breeder from Hatchery)
2. Place chicken in nest box from hatchery
3. Throw egg given by said chicken after they produce one 
4. Any chickens spawned from the egg spawn as vanilla chickens. 

http://prntscr.com/ksaijh (Screenshot of the eggs used) 
http://prntscr.com/ksakmc (Screenshot of the chicken produced)

## Client Information
* Modpack Version: 1.0.14
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No
* Tested with my extra mods and with a clean install thinking perhaps it was Quark but even on a clean install the bug persisted.

**Comment by Ladysarajane** [comment]
Hmm...I thought this was purposeful to encourage the use of the nests or breeders.

**Comment by anarth** [comment]
> Hmm...I thought this was purposeful to encourage the use of the nests or breeders.

Doesn't makes sense when All of the components have been in other packs but still allow you to throw the eggs. I literally sat and went through all the options too to see if something was disabling it and couldn't find anything.

**Comment by Sunekaer** [comment]
1.0.15
