### ISSUE TITLE
Recipe Conflict - Emerald Armor

### ISSUE THREAD

**Issue by RobertLSnead** [Sunekaer/stoneBlock#99]
## Bug Report

Unable to craft certain emerald armors.  There appears to be three sets made the same way, Actually Additions, Cyclic, and Tiny Progressions.  The recipe seems to only allow Actually Additions instead.
Not sure if this was intended or not?

## Steps to Reproduce (for bugs)

1. Create Tiny Progressions or Cyclic Emerald Armor
2. Receive Actually Additions Emerald Armor

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 1.0.14
* Server/LAN/Single Player: Server
* Optifine Installed: Yes 
* Shaders Enabled: No

**Comment by RobertLSnead** [comment]
Going to try No More Recipe Conflict Mod as I'd really like to create the Tiny Progressions Armor Sets :D

**Comment by RobertLSnead** [comment]
That does not seem to work, that's a bummer.

**Comment by mooretec** [comment]
Try the Forestry Worktable/Workbench something like that. It has a toggle to select another recipe.

**Comment by RobertLSnead** [comment]
Forestry Worktable works!!!
Thanks for the help.
